#lang racket/base

(require "../../../../parser/data-definitions/data-definitions.rkt"
         "../../../../parser/functions/file.rkt"
         "../../../../parser/functions/spine-parser.rkt"
         "../../../../parser/data-structures/humdrum-graph/data-definitions/data-definitions.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hgraph-to-hfile.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hfile-to-hgraph.rkt"
         "../../../../parser/data-structures/linked-spine/data-definitions/data-definitions.rkt"
         "../../../../parser/data-structures/linked-spine/functions/gspines-to-linked-spines.rkt"
         test-engine/racket-tests)

;; Node definitions
(define TERM-13-0 (terminator-node (token "*-" 'SpineTerminator 13 0)))
(define J-12-0 (token-node (token "*v" 'SpineJoin 12 0) (box-immutable TERM-13-0)))
(define J-12-1 (token-node (token "*v" 'SpineJoin 12 1) (box-immutable TERM-13-0)))
(define 4c-11-0 (token-node (token "4c" 'SpineData 11 0) (box-immutable J-12-0)))
(define 4c-11-1 (token-node (token "4c" 'SpineData 11 1) (box-immutable J-12-1)))
(define J-10-0 (token-node (token "*v" 'SpineJoin 10 0) (box-immutable 4c-11-0)))
(define J-10-1 (token-node (token "*v" 'SpineJoin 10 1) (box-immutable 4c-11-0)))
(define NULL-10-2 (token-node (token "*" 'NullInterpretation 10 2) (box-immutable 4c-11-1)))
(define 4c-9-0 (token-node (token "4c" 'SpineData 9 0) (box-immutable J-10-0)))
(define 4c-9-1 (token-node (token "4c" 'SpineData 9 1) (box-immutable J-10-1)))
(define 4c-9-2 (token-node (token "4c" 'SpineData 9 2) (box-immutable NULL-10-2)))
(define 4c-8-0 (token-node (token "4c" 'SpineData 8 0) (box-immutable 4c-9-0)))
(define 4c-8-1 (token-node (token "4c" 'SpineData 8 1) (box-immutable 4c-9-1)))
(define 4c-8-2 (token-node (token "4c" 'SpineData 8 2) (box-immutable 4c-9-2)))
(define J-7-0 (token-node (token "*v" 'SpineJoin 7 0) (box-immutable 4c-8-0)))
(define J-7-1 (token-node (token "*v" 'SpineJoin 7 1) (box-immutable 4c-8-0)))
(define NULL-7-2 (token-node (token "*" 'NullInterpretation 7 2) (box-immutable 4c-8-1)))
(define NULL-7-3 (token-node (token "*" 'NullInterpretation 7 3) (box-immutable 4c-8-2)))
(define 4c-6-0 (token-node (token "4c" 'SpineData 6 0) (box-immutable J-7-0)))
(define 4c-6-1 (token-node (token "4c" 'SpineData 6 1) (box-immutable J-7-1)))
(define 4c-6-2 (token-node (token "4c" 'SpineData 6 2) (box-immutable NULL-7-2)))
(define 4c-6-3 (token-node (token "4c" 'SpineData 6 3) (box-immutable NULL-7-3)))
(define 4c-5-0 (token-node (token "4c" 'SpineData 5 0) (box-immutable 4c-6-0)))
(define 4c-5-1 (token-node (token "4c" 'SpineData 5 1) (box-immutable 4c-6-1)))
(define 4c-5-2 (token-node (token "4c" 'SpineData 5 2) (box-immutable 4c-6-2)))
(define 4c-5-3 (token-node (token "4c" 'SpineData 5 3) (box-immutable 4c-6-3)))
(define 4c-4-0 (token-node (token "4c" 'SpineData 4 0) (box-immutable 4c-5-0)))
(define 4c-4-1 (token-node (token "4c" 'SpineData 4 1) (box-immutable 4c-5-1)))
(define 4c-4-2 (token-node (token "4c" 'SpineData 4 2) (box-immutable 4c-5-2)))
(define 4c-4-3 (token-node (token "4c" 'SpineData 4 3) (box-immutable 4c-5-3)))
(define NULL-3-0 (token-node (token "*" 'NullInterpretation 3 0) (box-immutable 4c-4-0)))
(define NULL-3-1 (token-node (token "*" 'NullInterpretation 3 1) (box-immutable 4c-4-1)))
(define S-3-2 (split-node (token "*^" 'SpineSplit 3 2)
                          (box-immutable 4c-4-2)
                          (box-immutable 4c-4-3)))
(define NULL-2-0 (token-node (token "*" 'NullInterpretation 2 0) (box-immutable NULL-3-0)))
(define S-2-1 (split-node (token "*^" 'SpineSplit 2 1)
                          (box-immutable NULL-3-1)
                          (box-immutable S-3-2)))
(define S-1-0 (split-node (token "*^" 'SpineSplit 1 0)
                          (box-immutable NULL-2-0)
                          (box-immutable S-2-1)))
(define KERN-0-0 (token-node (token "**kern" 'ExclusiveInterpretation 0 0) (box-immutable S-1-0)))

(check-expect (path->hfile "../../data/order/spine-splits-right-joins-left-c.krn")
              (hfile (list (record "**kern" TOKEN
                                   (list (token "**kern" 'ExclusiveInterpretation 0 0))
                                   0)
                           (record "*^" TOKEN
                                   (list (token "*^" 'SpineSplit 1 0))
                                   1)
                           (record "*\t*^" TOKEN
                                   (list (token "*" 'NullInterpretation 2 0)
                                         (token "*^" 'SpineSplit 2 1))
                                   2)
                           (record "*\t*\t*^" TOKEN
                                   (list (token "*" 'NullInterpretation 3 0)
                                         (token "*" 'NullInterpretation 3 1)
                                         (token "*^" 'SpineSplit 3 2))
                                   3)
                           (record "4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" 'SpineData 4 0)
                                         (token "4c" 'SpineData 4 1)
                                         (token "4c" 'SpineData 4 2)
                                         (token "4c" 'SpineData 4 3))
                                   4)
                           (record "4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" 'SpineData 5 0)
                                         (token "4c" 'SpineData 5 1)
                                         (token "4c" 'SpineData 5 2)
                                         (token "4c" 'SpineData 5 3))
                                   5)
                           (record "4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" 'SpineData 6 0)
                                         (token "4c" 'SpineData 6 1)
                                         (token "4c" 'SpineData 6 2)
                                         (token "4c" 'SpineData 6 3))
                                   6)
                           (record "*v\t*v\t*\t*" TOKEN
                                   (list (token "*v" 'SpineJoin 7 0)
                                         (token "*v" 'SpineJoin 7 1)
                                         (token "*" 'NullInterpretation 7 2)
                                         (token "*" 'NullInterpretation 7 3))
                                   7)
                           (record "4c\t4c\t4c" TOKEN
                                   (list (token "4c" 'SpineData 8 0)
                                         (token "4c" 'SpineData 8 1)
                                         (token "4c" 'SpineData 8 2))
                                   8)
                           (record "4c\t4c\t4c" TOKEN
                                   (list (token "4c" 'SpineData 9 0)
                                         (token "4c" 'SpineData 9 1)
                                         (token "4c" 'SpineData 9 2))
                                   9)
                           (record "*v\t*v\t*" TOKEN
                                   (list (token "*v" 'SpineJoin 10 0)
                                         (token "*v" 'SpineJoin 10 1)
                                         (token "*" 'NullInterpretation 10 2))
                                   10)
                           (record "4c\t4c" TOKEN
                                   (list (token "4c" 'SpineData 11 0)
                                         (token "4c" 'SpineData 11 1))
                                   11)
                           (record "*v\t*v" TOKEN
                                   (list (token "*v" 'SpineJoin 12 0)
                                         (token "*v" 'SpineJoin 12 1))
                                   12)
                           (record "*-" TOKEN
                                   (list (token "*-" 'SpineTerminator 13 0))
                                   13))))
(check-expect (spine-parser (path->hfile "../../data/order/spine-splits-right-joins-left-c.krn"))
              (list (global-spine KERN
                                  (list (list (token "**kern" 'ExclusiveInterpretation 0 0))
                                        (list (token "*^" 'SpineSplit 1 0))
                                        (list (token "*" 'NullInterpretation 2 0)
                                              (token "*^" 'SpineSplit 2 1))
                                        (list (token "*" 'NullInterpretation 3 0)
                                              (token "*" 'NullInterpretation 3 1)
                                              (token "*^" 'SpineSplit 3 2))
                                        (list (token "4c" 'SpineData 4 0)
                                              (token "4c" 'SpineData 4 1)
                                              (token "4c" 'SpineData 4 2)
                                              (token "4c" 'SpineData 4 3))
                                        (list (token "4c" 'SpineData 5 0)
                                              (token "4c" 'SpineData 5 1)
                                              (token "4c" 'SpineData 5 2)
                                              (token "4c" 'SpineData 5 3))
                                        (list (token "4c" 'SpineData 6 0)
                                              (token "4c" 'SpineData 6 1)
                                              (token "4c" 'SpineData 6 2)
                                              (token "4c" 'SpineData 6 3))
                                        (list (token "*v" 'SpineJoin 7 0)
                                              (token "*v" 'SpineJoin 7 1)
                                              (token "*" 'NullInterpretation 7 2)
                                              (token "*" 'NullInterpretation 7 3))
                                        (list (token "4c" 'SpineData 8 0)
                                              (token "4c" 'SpineData 8 1)
                                              (token "4c" 'SpineData 8 2))
                                        (list (token "4c" 'SpineData 9 0)
                                              (token "4c" 'SpineData 9 1)
                                              (token "4c" 'SpineData 9 2))
                                        (list (token "*v" 'SpineJoin 10 0)
                                              (token "*v" 'SpineJoin 10 1)
                                              (token "*" 'NullInterpretation 10 2))
                                        (list (token "4c" 'SpineData 11 0)
                                              (token "4c" 'SpineData 11 1))
                                        (list (token "*v" 'SpineJoin 12 0)
                                              (token "*v" 'SpineJoin 12 1))
                                        (list (token "*-" 'SpineTerminator 13 0)))
                                  0)))
(check-expect (hgraph->hfile (hgraph (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                                       (parent (token "*^" 'SpineSplit 1 0)
                                                               (list (leaf (token "*" 'NullInterpretation 2 0))
                                                                     (leaf (token "*" 'NullInterpretation 3 0))
                                                                     (leaf (token "4c" 'SpineData 4 0))
                                                                     (leaf (token "4c" 'SpineData 5 0))
                                                                     (leaf (token "4c" 'SpineData 6 0))
                                                                     (leaf (token "*v" 'SpineJoin 7 0)))
                                                               (list (parent (token "*^" 'SpineSplit 2 1)
                                                                             (list (leaf (token "*" 'NullInterpretation 3 1))
                                                                                   (leaf (token "4c" 'SpineData 4 1))
                                                                                   (leaf (token "4c" 'SpineData 5 1))
                                                                                   (leaf (token "4c" 'SpineData 6 1))
                                                                                   (leaf (token "*v" 'SpineJoin 7 1)))
                                                                             (list (parent (token "*^" 'SpineSplit 3 2)
                                                                                           (list (leaf (token "4c" 'SpineData 4 2))
                                                                                                 (leaf (token "4c" 'SpineData 5 2))
                                                                                                 (leaf (token "4c" 'SpineData 6 2))
                                                                                                 (leaf (token "*" 'NullInterpretation 7 2))
                                                                                                 (leaf (token "4c" 'SpineData 8 2))
                                                                                                 (leaf (token "4c" 'SpineData 9 2))
                                                                                                 (leaf (token "*v" 'SpineJoin 1 20)))
                                                                                           (list (leaf (token "4c" 'SpineData 4 3))
                                                                                                 (leaf (token "4c" 'SpineData 5 3))
                                                                                                 (leaf (token "4c" 'SpineData 6 3))
                                                                                                 (leaf (token "*" 'NullInterpretation 7 3))
                                                                                                 (leaf (token "4c" 'SpineData 8 3))
                                                                                                 (leaf (token "4c" 'SpineData 9 3))
                                                                                                 (leaf (token "*v" 'SpineJoin 10 3))))
                                                                                   (leaf (token "4c" 'SpineData 11 2))
                                                                                   (leaf (token "*v" 'SpineJoin 12 2))))
                                                                     (leaf (token "4c" 'SpineData 8 1))
                                                                     (leaf (token "4c" 'SpineData 9 1))
                                                                     (leaf (token "*" 'NullInterpretation 10 1))
                                                                     (leaf (token "4c" 'SpineData 11 1))
                                                                     (leaf (token "*v" 'SpineJoin 12 1))))
                                                       (leaf (token "*-" 'SpineTerminator 13 0)))))))
              (path->hfile "../../data/order/spine-splits-right-joins-left-c.krn"))
(check-expect (lolot->lor (list (list (token "**kern" 'ExclusiveInterpretation 0 0))
                                (list (token "*^" 'SpineSplit 1 0))
                                (list (token "*" 'NullInterpretation 2 0)
                                      (token "*^" 'SpineSplit 2 1))
                                (list (token "*" 'NullInterpretation 3 0)
                                      (token "*" 'NullInterpretation 3 1)
                                      (token "*^" 'SpineSplit 3 2))
                                (list (token "4c" 'SpineData 4 0)
                                      (token "4c" 'SpineData 4 1)
                                      (token "4c" 'SpineData 4 2)
                                      (token "4c" 'SpineData 4 3))
                                (list (token "4c" 'SpineData 5 0)
                                      (token "4c" 'SpineData 5 1)
                                      (token "4c" 'SpineData 5 2)
                                      (token "4c" 'SpineData 5 3))
                                (list (token "4c" 'SpineData 6 0)
                                      (token "4c" 'SpineData 6 1)
                                      (token "4c" 'SpineData 6 2)
                                      (token "4c" 'SpineData 6 3))
                                (list (token "*v" 'SpineJoin 7 0)
                                      (token "*v" 'SpineJoin 7 1)
                                      (token "*" 'NullInterpretation 7 2)
                                      (token "*" 'NullInterpretation 7 3))
                                (list (token "4c" 'SpineData 8 0)
                                      (token "4c" 'SpineData 8 1)
                                      (token "4c" 'SpineData 8 2))
                                (list (token "4c" 'SpineData 9 0)
                                      (token "4c" 'SpineData 9 1)
                                      (token "4c" 'SpineData 9 2))
                                (list (token "*v" 'SpineJoin 10 0)
                                      (token "*v" 'SpineJoin 10 1)
                                      (token "*" 'NullInterpretation 10 2))
                                (list (token "4c" 'SpineData 11 0)
                                      (token "4c" 'SpineData 11 1))
                                (list (token "*v" 'SpineJoin 12 0)
                                      (token "*v" 'SpineJoin 12 1))
                                (list (token "*-" 'SpineTerminator 13 0))))
              (list (record "**kern" TOKEN
                            (list (token "**kern" 'ExclusiveInterpretation 0 0))
                            0)
                    (record "*^" TOKEN
                            (list (token "*^" 'SpineSplit 1 0))
                            1)
                    (record "*\t*^" TOKEN
                            (list (token "*" 'NullInterpretation 2 0)
                                  (token "*^" 'SpineSplit 2 1))
                            2)
                    (record "*\t*\t*^" TOKEN
                            (list (token "*" 'NullInterpretation 3 0)
                                  (token "*" 'NullInterpretation 3 1)
                                  (token "*^" 'SpineSplit 3 2))
                            3)
                    (record "4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" 'SpineData 4 0)
                                  (token "4c" 'SpineData 4 1)
                                  (token "4c" 'SpineData 4 2)
                                  (token "4c" 'SpineData 4 3))
                            4)
                    (record "4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" 'SpineData 5 0)
                                  (token "4c" 'SpineData 5 1)
                                  (token "4c" 'SpineData 5 2)
                                  (token "4c" 'SpineData 5 3))
                            5)
                    (record "4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" 'SpineData 6 0)
                                  (token "4c" 'SpineData 6 1)
                                  (token "4c" 'SpineData 6 2)
                                  (token "4c" 'SpineData 6 3))
                            6)
                    (record "*v\t*v\t*\t*" TOKEN
                            (list (token "*v" 'SpineJoin 7 0)
                                  (token "*v" 'SpineJoin 7 1)
                                  (token "*" 'NullInterpretation 7 2)
                                  (token "*" 'NullInterpretation 7 3))
                            7)
                    (record "4c\t4c\t4c" TOKEN
                            (list (token "4c" 'SpineData 8 0)
                                  (token "4c" 'SpineData 8 1)
                                  (token "4c" 'SpineData 8 2))
                            8)
                    (record "4c\t4c\t4c" TOKEN
                            (list (token "4c" 'SpineData 9 0)
                                  (token "4c" 'SpineData 9 1)
                                  (token "4c" 'SpineData 9 2))
                            9)
                    (record "*v\t*v\t*" TOKEN
                            (list (token "*v" 'SpineJoin 10 0)
                                  (token "*v" 'SpineJoin 10 1)
                                  (token "*" 'NullInterpretation 10 2))
                            10)
                    (record "4c\t4c" TOKEN
                            (list (token "4c" 'SpineData 11 0)
                                  (token "4c" 'SpineData 11 1))
                            11)
                    (record "*v\t*v" TOKEN
                            (list (token "*v" 'SpineJoin 12 0)
                                  (token "*v" 'SpineJoin 12 1))
                            12)
                    (record "*-" TOKEN
                            (list (token "*-" 'SpineTerminator 13 0))
                            13)))
(check-expect (hgraph->lolot (hgraph (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                                       (parent (token "*^" 'SpineSplit 1 0)
                                                               (list (leaf (token "*" 'NullInterpretation 2 0))
                                                                     (leaf (token "*" 'NullInterpretation 3 0))
                                                                     (leaf (token "4c" 'SpineData 4 0))
                                                                     (leaf (token "4c" 'SpineData 5 0))
                                                                     (leaf (token "4c" 'SpineData 6 0))
                                                                     (leaf (token "*v" 'SpineJoin 7 0)))
                                                               (list (parent (token "*^" 'SpineSplit 2 1)
                                                                             (list (leaf (token "*" 'NullInterpretation 3 1))
                                                                                   (leaf (token "4c" 'SpineData 4 1))
                                                                                   (leaf (token "4c" 'SpineData 5 1))
                                                                                   (leaf (token "4c" 'SpineData 6 1))
                                                                                   (leaf (token "*v" 'SpineJoin 7 1)))
                                                                             (list (parent (token "*^" 'SpineSplit 3 2)
                                                                                           (list (leaf (token "4c" 'SpineData 4 2))
                                                                                                 (leaf (token "4c" 'SpineData 5 2))
                                                                                                 (leaf (token "4c" 'SpineData 6 2))
                                                                                                 (leaf (token "*" 'NullInterpretation 7 2))
                                                                                                 (leaf (token "4c" 'SpineData 8 2))
                                                                                                 (leaf (token "4c" 'SpineData 9 2))
                                                                                                 (leaf (token "*v" 'SpineJoin 1 20)))
                                                                                           (list (leaf (token "4c" 'SpineData 4 3))
                                                                                                 (leaf (token "4c" 'SpineData 5 3))
                                                                                                 (leaf (token "4c" 'SpineData 6 3))
                                                                                                 (leaf (token "*" 'NullInterpretation 7 3))
                                                                                                 (leaf (token "4c" 'SpineData 8 3))
                                                                                                 (leaf (token "4c" 'SpineData 9 3))
                                                                                                 (leaf (token "*v" 'SpineJoin 10 3))))
                                                                                   (leaf (token "4c" 'SpineData 11 2))
                                                                                   (leaf (token "*v" 'SpineJoin 12 2))))
                                                                     (leaf (token "4c" 'SpineData 8 1))
                                                                     (leaf (token "4c" 'SpineData 9 1))
                                                                     (leaf (token "*" 'NullInterpretation 10 1))
                                                                     (leaf (token "4c" 'SpineData 11 1))
                                                                     (leaf (token "*v" 'SpineJoin 12 1))))
                                                       (leaf (token "*-" 'SpineTerminator 13 0)))))))
              (list (list (token "**kern" 'ExclusiveInterpretation 0 0))
                    (list (token "*^" 'SpineSplit 1 0))
                    (list (token "*" 'NullInterpretation 2 0)
                          (token "*^" 'SpineSplit 2 1))
                    (list (token "*" 'NullInterpretation 3 0)
                          (token "*" 'NullInterpretation 3 1)
                          (token "*^" 'SpineSplit 3 2))
                    (list (token "4c" 'SpineData 4 0)
                          (token "4c" 'SpineData 4 1)
                          (token "4c" 'SpineData 4 2)
                          (token "4c" 'SpineData 4 3))
                    (list (token "4c" 'SpineData 5 0)
                          (token "4c" 'SpineData 5 1)
                          (token "4c" 'SpineData 5 2)
                          (token "4c" 'SpineData 5 3))
                    (list (token "4c" 'SpineData 6 0)
                          (token "4c" 'SpineData 6 1)
                          (token "4c" 'SpineData 6 2)
                          (token "4c" 'SpineData 6 3))
                    (list (token "*v" 'SpineJoin 7 0)
                          (token "*v" 'SpineJoin 7 1)
                          (token "*" 'NullInterpretation 7 2)
                          (token "*" 'NullInterpretation 7 3))
                    (list (token "4c" 'SpineData 8 0)
                          (token "4c" 'SpineData 8 1)
                          (token "4c" 'SpineData 8 2))
                    (list (token "4c" 'SpineData 9 0)
                          (token "4c" 'SpineData 9 1)
                          (token "4c" 'SpineData 9 2))
                    (list (token "*v" 'SpineJoin 10 0)
                          (token "*v" 'SpineJoin 10 1)
                          (token "*" 'NullInterpretation 10 2))
                    (list (token "4c" 'SpineData 11 0)
                          (token "4c" 'SpineData 11 1))
                    (list (token "*v" 'SpineJoin 12 0)
                          (token "*v" 'SpineJoin 12 1))
                    (list (token "*-" 'SpineTerminator 13 0))))
(check-expect (hfile->hgraph (path->hfile "../../data/order/spine-splits-right-joins-left-c.krn"))
              (hgraph (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                        (parent (token "*^" 'SpineSplit 1 0)
                                                (list (leaf (token "*" 'NullInterpretation 2 0))
                                                      (leaf (token "*" 'NullInterpretation 3 0))
                                                      (leaf (token "4c" 'SpineData 4 0))
                                                      (leaf (token "4c" 'SpineData 5 0))
                                                      (leaf (token "4c" 'SpineData 6 0))
                                                      (leaf (token "*v" 'SpineJoin 7 0)))
                                                (list (parent (token "*^" 'SpineSplit 2 1)
                                                              (list (leaf (token "*" 'NullInterpretation 3 1))
                                                                    (leaf (token "4c" 'SpineData 4 1))
                                                                    (leaf (token "4c" 'SpineData 5 1))
                                                                    (leaf (token "4c" 'SpineData 6 1))
                                                                    (leaf (token "*v" 'SpineJoin 7 1)))
                                                              (list (parent (token "*^" 'SpineSplit 3 2)
                                                                            (list (leaf (token "4c" 'SpineData 4 2))
                                                                                  (leaf (token "4c" 'SpineData 5 2))
                                                                                  (leaf (token "4c" 'SpineData 6 2))
                                                                                  (leaf (token "*" 'NullInterpretation 7 2))
                                                                                  (leaf (token "4c" 'SpineData 8 2))
                                                                                  (leaf (token "4c" 'SpineData 9 2))
                                                                                  (leaf (token "*v" 'SpineJoin 1 20)))
                                                                            (list (leaf (token "4c" 'SpineData 4 3))
                                                                                  (leaf (token "4c" 'SpineData 5 3))
                                                                                  (leaf (token "4c" 'SpineData 6 3))
                                                                                  (leaf (token "*" 'NullInterpretation 7 3))
                                                                                  (leaf (token "4c" 'SpineData 8 3))
                                                                                  (leaf (token "4c" 'SpineData 9 3))
                                                                                  (leaf (token "*v" 'SpineJoin 10 3))))
                                                                    (leaf (token "4c" 'SpineData 11 2))
                                                                    (leaf (token "*v" 'SpineJoin 12 2))))
                                                      (leaf (token "4c" 'SpineData 8 1))
                                                      (leaf (token "4c" 'SpineData 9 1))
                                                      (leaf (token "*" 'NullInterpretation 10 1))
                                                      (leaf (token "4c" 'SpineData 11 1))
                                                      (leaf (token "*v" 'SpineJoin 12 1))))
                                        (leaf (token "*-" 'SpineTerminator 13 0)))))))
(check-expect (gspines->linked-spines (spine-parser (path->hfile "../../data/order/spine-splits-right-joins-left-c.krn"))
                                      (path->hfile "../../data/order/spine-splits-right-joins-left-c.krn"))
              (list (linked-spine KERN-0-0)))

(test)
