#lang racket/base

(require "../../../../../parser/HumdrumSyntax.rkt"
         "../../../../../parser/file-fn.rkt"
         "../../../../../parser/spine-parsing-fn.rkt"
         "../../../../../parser/humdrum-graph/HumdrumGraph.rkt"
         "../../../../../parser/humdrum-graph/hfile-to-hgraph-fn.rkt"
         "../../../../../parser/humdrum-graph/hgraph-to-hfile-fn.rkt"
         "../../../../../parser/linked-spine/LinkedSpine.rkt"
         "../../../../../parser/linked-spine/gspines-to-linked-spines-fn.rkt"
         test-engine/racket-tests)

;; Node definitions
(define TERM-7-0 (terminator-node (token "*-" 'SpineTerminator 7 0)))
(define J-6-0 (token-node (token "*v" 'SpineJoin 6 0) (box-immutable TERM-7-0)))
(define J-6-1 (token-node (token "*v" 'SpineJoin 6 1) (box-immutable TERM-7-0)))
(define NULL-5-0 (token-node (token "*" 'NullInterpretation 5 0) (box-immutable J-6-0)))
(define NULL-5-1 (token-node (token "*" 'NullInterpretation 5 1) (box-immutable J-6-1)))
(define 4c-4-0 (token-node (token "4c" 'SpineData 4 0) (box-immutable NULL-5-0)))
(define 4c-4-1 (token-node (token "4c" 'SpineData 4 1) (box-immutable NULL-5-1)))
(define 4c-3-0 (token-node (token "4c" 'SpineData 3 0) (box-immutable 4c-4-0)))
(define 4c-3-1 (token-node (token "4c" 'SpineData 3 1) (box-immutable 4c-4-1)))
(define 4c-2-0 (token-node (token "4c" 'SpineData 2 0) (box-immutable 4c-3-0)))
(define 4c-2-1 (token-node (token "4c" 'SpineData 2 1) (box-immutable 4c-3-1)))
(define S-1-0 (split-node (token "*^" 'SpineSplit 1 0)
                          (box-immutable 4c-2-0)
                          (box-immutable 4c-2-1)))
(define KERN-0-0 (token-node (token "**kern" 'ExclusiveInterpretation 0 0) (box-immutable S-1-0)))

(define TERM-7-1 (terminator-node (token "*-" 'SpineTerminator 7 1)))
(define NULL-6-2 (token-node (token "*" 'NullInterpretation 6 2) (box-immutable TERM-7-1)))
(define J-5-2 (token-node (token "*v" 'SpineJoin 5 2) (box-immutable NULL-6-2)))
(define J-5-3 (token-node (token "*v" 'SpineJoin 5 3) (box-immutable NULL-6-2)))
(define 4c-4-2 (token-node (token "4c" 'SpineData 4 2) (box-immutable J-5-2)))
(define 4c-4-3 (token-node (token "4c" 'SpineData 4 3) (box-immutable J-5-3)))
(define 4c-3-2 (token-node (token "4c" 'SpineData 3 2) (box-immutable 4c-4-2)))
(define 4c-3-3 (token-node (token "4c" 'SpineData 3 3) (box-immutable 4c-4-3)))
(define 4c-2-2 (token-node (token "4c" 'SpineData 2 2) (box-immutable 4c-3-2)))
(define 4c-2-3 (token-node (token "4c" 'SpineData 2 3) (box-immutable 4c-3-3)))
(define S-1-1 (split-node (token "*^" 'SpineSplit 1 1)
                          (box-immutable 4c-2-2)
                          (box-immutable 4c-2-3)))
(define KERN-0-1 (token-node (token "**kern" 'ExclusiveInterpretation 0 1) (box-immutable S-1-1)))

(check-expect (path->hfile "../../data/order/two-spines-split-simultaneously.krn")
              (hfile (list (record "**kern\t**kern" 'ExclusiveInterpretation
                                   (list (token "**kern" 'ExclusiveInterpretation 0 0)
                                         (token "**kern" 'ExclusiveInterpretation 0 1))
                                   0)
                           (record "*^\t*^" 'TandemInterpretation
                                   (list (token "*^" 'SpineSplit 1 0)
                                         (token "*^" 'SpineSplit 1 1))
                                   1)
                           (record "4c\t4c\t4c\t4c" 'Token
                                   (list (token "4c" 'SpineData 2 0)
                                         (token "4c" 'SpineData 2 1)
                                         (token "4c" 'SpineData 2 2)
                                         (token "4c" 'SpineData 2 3))
                                   2)
                           (record "4c\t4c\t4c\t4c" 'Token
                                   (list (token "4c" 'SpineData 3 0)
                                         (token "4c" 'SpineData 3 1)
                                         (token "4c" 'SpineData 3 2)
                                         (token "4c" 'SpineData 3 3))
                                   3)
                           (record "4c\t4c\t4c\t4c" 'Token
                                   (list (token "4c" 'SpineData 4 0)
                                         (token "4c" 'SpineData 4 1)
                                         (token "4c" 'SpineData 4 2)
                                         (token "4c" 'SpineData 4 3))
                                   4)
                           (record "*\t*\t*v\t*v" 'TandemInterpretation
                                   (list (token "*" 'NullInterpretation 5 0)
                                         (token "*" 'NullInterpretation 5 1)
                                         (token "*v" 'SpineJoin 5 2)
                                         (token "*v" 'SpineJoin 5 3))
                                   5)
                           (record "*v\t*v\t*" 'TandemInterpretation
                                   (list (token "*v" 'SpineJoin 6 0)
                                         (token "*v" 'SpineJoin 6 1)
                                         (token "*" 'NullInterpretation 6 2))
                                   6)
                           (record "*-\t*-" 'TandemInterpretation
                                   (list (token "*-" 'SpineTerminator 7 0)
                                         (token "*-" 'SpineTerminator 7 1))
                                   7))))
(check-expect (spine-parser (path->hfile "../../data/order/two-spines-split-simultaneously.krn"))
              (list (global-spine 'Kern
                                  (list (list (token "**kern" 'ExclusiveInterpretation 0 0))
                                        (list (token "*^" 'SpineSplit 1 0))
                                        (list (token "4c" 'SpineData 2 0)
                                              (token "4c" 'SpineData 2 1))
                                        (list (token "4c" 'SpineData 3 0)
                                              (token "4c" 'SpineData 3 1))
                                        (list (token "4c" 'SpineData 4 0)
                                              (token "4c" 'SpineData 4 1))
                                        (list (token "*" 'NullInterpretation 5 0)
                                              (token "*" 'NullInterpretation 5 1))
                                        (list (token "*v" 'SpineJoin 6 0)
                                              (token "*v" 'SpineJoin 6 1))
                                        (list (token "*-" 'SpineTerminator 7 0)))
                                  0)
                    (global-spine 'Kern
                                  (list (list (token "**kern" 'ExclusiveInterpretation 0 1))
                                        (list (token "*^" 'SpineSplit 1 1))
                                        (list (token "4c" 'SpineData 2 2)
                                              (token "4c" 'SpineData 2 3))
                                        (list (token "4c" 'SpineData 3 2)
                                              (token "4c" 'SpineData 3 3))
                                        (list (token "4c" 'SpineData 4 2)
                                              (token "4c" 'SpineData 4 3))
                                        (list (token "*v" 'SpineJoin 5 2)
                                              (token "*v" 'SpineJoin 5 3))
                                        (list (token "*" 'NullInterpretation 6 2))
                                        (list (token "*-" 'SpineTerminator 7 1)))
                                  1)))
(check-expect (hgraph->hfile
               (hgraph (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                         (parent (token "*^" 'SpineSplit 1 0)
                                                 (list (leaf (token "4c" 'SpineData 2 0))
                                                       (leaf (token "4c" 'SpineData 3 0))
                                                       (leaf (token "4c" 'SpineData 4 0))
                                                       (leaf (token "*" 'NullInterpretation 5 0))
                                                       (leaf (token "*v" 'SpineJoin 6 0)))
                                                 (list (leaf (token "4c" 'SpineData 2 1))
                                                       (leaf (token "4c" 'SpineData 3 1))
                                                       (leaf (token "4c" 'SpineData 4 1))
                                                       (leaf (token "*" 'NullInterpretation 5 1))
                                                       (leaf (token "*v" 'SpineJoin 6 1))))
                                         (leaf (token "*-" 'SpineTerminator 7 0)))
                                   (list (leaf (token "**kern" 'ExclusiveInterpretation 0 1))
                                         (parent (token "*^" 'SpineSplit 1 0)
                                                 (list (leaf (token "4c" 'SpineData 2 2))
                                                       (leaf (token "4c" 'SpineData 3 2))
                                                       (leaf (token "4c" 'SpineData 4 2))
                                                       (leaf (token "*v" 'SpineJoin 5 2)))
                                                 (list (leaf (token "4c" 'SpineData 2 3))
                                                       (leaf (token "4c" 'SpineData 3 3))
                                                       (leaf (token "4c" 'SpineData 4 3))
                                                       (leaf (token "*v" 'SpineJoin 5 3))))
                                         (leaf (token "*" 'NullInterpretation 6 2))
                                         (leaf (token "*-" 'SpineTerminator 7 1)))))))
              (path->hfile "../../data/order/two-spines-split-simultaneously.krn"))
(check-expect (tokens->records (list (list (token "**kern" 'ExclusiveInterpretation 0 0)
                                      (token "**kern" 'ExclusiveInterpretation 0 1))
                                (list (token "*^" 'SpineSplit 1 0)
                                      (token "*^" 'SpineSplit 1 1))
                                (list (token "4c" 'SpineData 2 0)
                                      (token "4c" 'SpineData 2 1)
                                      (token "4c" 'SpineData 2 2)
                                      (token "4c" 'SpineData 2 3))
                                (list (token "4c" 'SpineData 3 0)
                                      (token "4c" 'SpineData 3 1)
                                      (token "4c" 'SpineData 3 2)
                                      (token "4c" 'SpineData 3 3))
                                (list (token "4c" 'SpineData 4 0)
                                      (token "4c" 'SpineData 4 1)
                                      (token "4c" 'SpineData 4 2)
                                      (token "4c" 'SpineData 4 3))
                                (list (token "*" 'NullInterpretation 5 0)
                                      (token "*" 'NullInterpretation 5 1)
                                      (token "*v" 'SpineJoin 5 2)
                                      (token "*v" 'SpineJoin 5 3))
                                (list (token "*v" 'SpineJoin 6 0)
                                      (token "*v" 'SpineJoin 6 1)
                                      (token "*" 'NullInterpretation 6 2))
                                (list (token "*-" 'SpineTerminator 7 0)
                                      (token "*-" 'SpineTerminator 7 1))))
              (list (record "**kern\t**kern" 'ExclusiveInterpretation
                            (list (token "**kern" 'ExclusiveInterpretation 0 0)
                                  (token "**kern" 'ExclusiveInterpretation 0 1))
                            0)
                    (record "*^\t*^" 'TandemInterpretation
                            (list (token "*^" 'SpineSplit 1 0)
                                  (token "*^" 'SpineSplit 1 1))
                            1)
                    (record "4c\t4c\t4c\t4c" 'Token
                            (list (token "4c" 'SpineData 2 0)
                                  (token "4c" 'SpineData 2 1)
                                  (token "4c" 'SpineData 2 2)
                                  (token "4c" 'SpineData 2 3))
                            2)
                    (record "4c\t4c\t4c\t4c" 'Token
                            (list (token "4c" 'SpineData 3 0)
                                  (token "4c" 'SpineData 3 1)
                                  (token "4c" 'SpineData 3 2)
                                  (token "4c" 'SpineData 3 3))
                            3)
                    (record "4c\t4c\t4c\t4c" 'Token
                            (list (token "4c" 'SpineData 4 0)
                                  (token "4c" 'SpineData 4 1)
                                  (token "4c" 'SpineData 4 2)
                                  (token "4c" 'SpineData 4 3))
                            4)
                    (record "*\t*\t*v\t*v" 'TandemInterpretation
                            (list (token "*" 'NullInterpretation 5 0)
                                  (token "*" 'NullInterpretation 5 1)
                                  (token "*v" 'SpineJoin 5 2)
                                  (token "*v" 'SpineJoin 5 3))
                            5)
                    (record "*v\t*v\t*" 'TandemInterpretation
                            (list (token "*v" 'SpineJoin 6 0)
                                  (token "*v" 'SpineJoin 6 1)
                                  (token "*" 'NullInterpretation 6 2))
                            6)
                    (record "*-\t*-" 'TandemInterpretation
                            (list (token "*-" 'SpineTerminator 7 0)
                                  (token "*-" 'SpineTerminator 7 1))
                            7)))
(check-expect (hgraph->tokens
               (hgraph (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                         (parent (token "*^" 'SpineSplit 1 0)
                                                 (list (leaf (token "4c" 'SpineData 2 0))
                                                       (leaf (token "4c" 'SpineData 3 0))
                                                       (leaf (token "4c" 'SpineData 4 0))
                                                       (leaf (token "*" 'NullInterpretation 5 0))
                                                       (leaf (token "*v" 'SpineJoin 6 0)))
                                                 (list (leaf (token "4c" 'SpineData 2 1))
                                                       (leaf (token "4c" 'SpineData 3 1))
                                                       (leaf (token "4c" 'SpineData 4 1))
                                                       (leaf (token "*" 'NullInterpretation 5 1))
                                                       (leaf (token "*v" 'SpineJoin 6 1))))
                                         (leaf (token "*-" 'SpineTerminator 7 0)))
                                   (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                         (parent (token "*^" 'SpineSplit 1 1)
                                                 (list (leaf (token "4c" 'SpineData 2 2))
                                                       (leaf (token "4c" 'SpineData 3 2))
                                                       (leaf (token "4c" 'SpineData 4 2))
                                                       (leaf (token "*v" 'SpineJoin 5 2)))
                                                 (list (leaf (token "4c" 'SpineData 2 3))
                                                       (leaf (token "4c" 'SpineData 3 3))
                                                       (leaf (token "4c" 'SpineData 4 3))
                                                       (leaf (token "*v" 'SpineJoin 5 3))))
                                         (leaf (token "*" 'NullInterpretation 6 2))
                                         (leaf (token "*-" 'SpineTerminator 7 1)))))))
              (list (list (token "**kern" 'ExclusiveInterpretation 0 0)
                          (token "**kern" 'ExclusiveInterpretation 0 1))
                    (list (token "*^" 'SpineSplit 1 0)
                          (token "*^" 'SpineSplit 1 1))
                    (list (token "4c" 'SpineData 2 0)
                          (token "4c" 'SpineData 2 1)
                          (token "4c" 'SpineData 2 2)
                          (token "4c" 'SpineData 2 3))
                    (list (token "4c" 'SpineData 3 0)
                          (token "4c" 'SpineData 3 1)
                          (token "4c" 'SpineData 3 2)
                          (token "4c" 'SpineData 3 3))
                    (list (token "4c" 'SpineData 4 0)
                          (token "4c" 'SpineData 4 1)
                          (token "4c" 'SpineData 4 2)
                          (token "4c" 'SpineData 4 3))
                    (list (token "*" 'NullInterpretation 5 0)
                          (token "*" 'NullInterpretation 5 1)
                          (token "*v" 'SpineJoin 5 2)
                          (token "*v" 'SpineJoin 5 3))
                    (list (token "*v" 'SpineJoin 6 0)
                          (token "*v" 'SpineJoin 6 1)
                          (token "*" 'NullInterpretation 6 2))
                    (list (token "*-" 'SpineTerminator 7 0)
                          (token "*-" 'SpineTerminator 7 1))))
(check-expect (hfile->hgraph (path->hfile "../../data/order/two-spines-split-simultaneously.krn"))
              (hgraph (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                        (parent (token "*^" 'SpineSplit 1 0)
                                                (list (leaf (token "4c" 'SpineData 2 0))
                                                      (leaf (token "4c" 'SpineData 3 0))
                                                      (leaf (token "4c" 'SpineData 4 0))
                                                      (leaf (token "*" 'NullInterpretation 5 0))
                                                      (leaf (token "*v" 'SpineJoin 6 0)))
                                                (list (leaf (token "4c" 'SpineData 2 1))
                                                      (leaf (token "4c" 'SpineData 3 1))
                                                      (leaf (token "4c" 'SpineData 4 1))
                                                      (leaf (token "*" 'NullInterpretation 5 1))
                                                      (leaf (token "*v" 'SpineJoin 6 1))))
                                        (leaf (token "*-" 'SpineTerminator 7 0)))
                                  (list (leaf (token "**kern" 'ExclusiveInterpretation 0 1))
                                        (parent (token "*^" 'SpineSplit 1 1)
                                                (list (leaf (token "4c" 'SpineData 2 2))
                                                      (leaf (token "4c" 'SpineData 3 2))
                                                      (leaf (token "4c" 'SpineData 4 2))
                                                      (leaf (token "*v" 'SpineJoin 5 2)))
                                                (list (leaf (token "4c" 'SpineData 2 3))
                                                      (leaf (token "4c" 'SpineData 3 3))
                                                      (leaf (token "4c" 'SpineData 4 3))
                                                      (leaf (token "*v" 'SpineJoin 5 3))))
                                        (leaf (token "*" 'NullInterpretation 6 2))
                                        (leaf (token "*-" 'SpineTerminator 7 1)))))))
(check-expect (gspines->linked-spines (spine-parser (path->hfile "../../data/order/two-spines-split-simultaneously.krn"))
                                      (path->hfile "../../data/order/two-spines-split-simultaneously.krn"))
              (list (linked-spine KERN-0-0) (linked-spine KERN-0-1)))
(check-expect (extract-spine-arity (path->hfile "../../data/order/two-spines-split-simultaneously.krn"))
              (spine-arity 2 (list (list 1 1)
                                   (list 1 1)
                                   (list 2 2)
                                   (list 2 2)
                                   (list 2 2)
                                   (list 2 2)
                                   (list 2 1)
                                   (list 1 1))))

(test)
