#lang racket/base

(require "../../../../parser/data-definitions/data-definitions.rkt"
         "../../../../parser/functions/file.rkt"
         "../../../../parser/functions/spine-parser.rkt"
         "../../../../data-structures/abstract-humdrum-graph/data-definitions/data-definitions.rkt"
         "../../../../data-structures/abstract-humdrum-graph/functions/ab-hgraph-to-hfile.rkt"
         "../../../../data-structures/abstract-humdrum-graph/functions/hfile-to-ab-hgraph.rkt"
         test-engine/racket-tests)

(check-expect (path->hfile "../../data/count/one-spine-no-splits.krn")
              (hfile (list (record "**kern" TOKEN (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)) 0)
                           (record "*clefG2" TOKEN (list (token "*clefG2" CLEF 1)) 1)
                           (record "*k[]" TOKEN (list (token "*k[]" KEY-SIG 2)) 2)
                           (record "*a:" TOKEN (list (token "*a:" KEY-LABEL 3)) 3)
                           (record "*M3/4" TOKEN (list (token "*M3/4" TIME-SIG 4)) 4)
                           (record "4c" TOKEN (list (token "4c" SPINE-DATA 5)) 5)
                           (record "4c" TOKEN (list (token "4c" SPINE-DATA 6)) 6)
                           (record "4c" TOKEN (list (token "4c" SPINE-DATA 7)) 7)
                           (record "=2" TOKEN (list (token "=2" MEASURE 8)) 8)
                           (record "4c" TOKEN (list (token "4c" SPINE-DATA 9)) 9)
                           (record "4c" TOKEN (list (token "4c" SPINE-DATA 10)) 10)
                           (record "4c" TOKEN (list (token "4c" SPINE-DATA 11)) 11)
                           (record "=3" TOKEN (list (token "=3" MEASURE 12)) 12)
                           (record "4c" TOKEN (list (token "4c" SPINE-DATA 13)) 13)
                           (record "4c" TOKEN (list (token "4c" SPINE-DATA 14)) 14)
                           (record "4c" TOKEN (list (token "4c" SPINE-DATA 15)) 15)
                           (record "==" TOKEN (list (token "==" MEASURE 16)) 16)
                           (record "*-" TOKEN (list (token "*-" SPINE-TERMINATOR 17)) 17))))
(check-expect (spine-parser (path->hfile "../../data/count/one-spine-no-splits.krn"))
              (list (global-spine KERN
                                  (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                        (list (token "*clefG2" CLEF 1))
                                        (list (token "*k[]" KEY-SIG 2))
                                        (list (token "*a:" KEY-LABEL 3))
                                        (list (token "*M3/4" TIME-SIG 4))
                                        (list (token "4c" SPINE-DATA 5))
                                        (list (token "4c" SPINE-DATA 6))
                                        (list (token "4c" SPINE-DATA 7))
                                        (list (token "=2" MEASURE 8))
                                        (list (token "4c" SPINE-DATA 9))
                                        (list (token "4c" SPINE-DATA 10))
                                        (list (token "4c" SPINE-DATA 11))
                                        (list (token "=3" MEASURE 12))
                                        (list (token "4c" SPINE-DATA 13))
                                        (list (token "4c" SPINE-DATA 14))
                                        (list (token "4c" SPINE-DATA 15))
                                        (list (token "==" MEASURE 16))
                                        (list (token "*-" SPINE-TERMINATOR 17)))
                              0)))
(check-expect (ab-hgraph->hfile (ab-hgraph
                                 (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                                   (leaf (token "*clefG2" CLEF 1))
                                                   (leaf (token "*k[]" KEY-SIG 2))
                                                   (leaf (token "*a:" KEY-LABEL 3))
                                                   (leaf (token "*M3/4" TIME-SIG 4))
                                                   (leaf (token "4c" SPINE-DATA 5))
                                                   (leaf (token "4c" SPINE-DATA 6))
                                                   (leaf (token "4c" SPINE-DATA 7))
                                                   (leaf (token "=2" MEASURE 8))
                                                   (leaf (token "4c" SPINE-DATA 9))
                                                   (leaf (token "4c" SPINE-DATA 10))
                                                   (leaf (token "4c" SPINE-DATA 11))
                                                   (leaf (token "=3" MEASURE 12))
                                                   (leaf (token "4c" SPINE-DATA 13))
                                                   (leaf (token "4c" SPINE-DATA 14))
                                                   (leaf (token "4c" SPINE-DATA 15))
                                                   (leaf (token "==" MEASURE 16))
                                                   (leaf (token "*-" SPINE-TERMINATOR 17)))))))
              (path->hfile "../../data/count/one-spine-no-splits.krn"))
(check-expect (lolot->lor (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                            (list (token "*clefG2" CLEF 1))
                            (list (token "*k[]" KEY-SIG 2))
                            (list (token "*a:" KEY-LABEL 3))
                            (list (token "*M3/4" TIME-SIG 4))
                            (list (token "4c" SPINE-DATA 5))
                            (list (token "4c" SPINE-DATA 6))
                            (list (token "4c" SPINE-DATA 7))
                            (list (token "=2" MEASURE 8))
                            (list (token "4c" SPINE-DATA 9))
                            (list (token "4c" SPINE-DATA 10))
                            (list (token "4c" SPINE-DATA 11))
                            (list (token "=3" MEASURE 12))
                            (list (token "4c" SPINE-DATA 13))
                            (list (token "4c" SPINE-DATA 14))
                            (list (token "4c" SPINE-DATA 15))
                            (list (token "==" MEASURE 16))
                            (list (token "*-" SPINE-TERMINATOR 17))))
              (list (record "**kern" TOKEN (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)) 0)
                    (record "*clefG2" TOKEN (list (token "*clefG2" CLEF 1)) 1)
                    (record "*k[]" TOKEN (list (token "*k[]" KEY-SIG 2)) 2)
                    (record "*a:" TOKEN (list (token "*a:" KEY-LABEL 3)) 3)
                    (record "*M3/4" TOKEN (list (token "*M3/4" TIME-SIG 4)) 4)
                    (record "4c" TOKEN (list (token "4c" SPINE-DATA 5)) 5)
                    (record "4c" TOKEN (list (token "4c" SPINE-DATA 6)) 6)
                    (record "4c" TOKEN (list (token "4c" SPINE-DATA 7)) 7)
                    (record "=2" TOKEN (list (token "=2" MEASURE 8)) 8)
                    (record "4c" TOKEN (list (token "4c" SPINE-DATA 9)) 9)
                    (record "4c" TOKEN (list (token "4c" SPINE-DATA 10)) 10)
                    (record "4c" TOKEN (list (token "4c" SPINE-DATA 11)) 11)
                    (record "=3" TOKEN (list (token "=3" MEASURE 12)) 12)
                    (record "4c" TOKEN (list (token "4c" SPINE-DATA 13)) 13)
                    (record "4c" TOKEN (list (token "4c" SPINE-DATA 14)) 14)
                    (record "4c" TOKEN (list (token "4c" SPINE-DATA 15)) 15)
                    (record "==" TOKEN (list (token "==" MEASURE 16)) 16)
                    (record "*-" TOKEN (list (token "*-" SPINE-TERMINATOR 17)) 17)))
(check-expect (ab-hgraph->lolot (ab-hgraph
                                 (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                                   (leaf (token "*clefG2" CLEF 1))
                                                   (leaf (token "*k[]" KEY-SIG 2))
                                                   (leaf (token "*a:" KEY-LABEL 3))
                                                   (leaf (token "*M3/4" TIME-SIG 4))
                                                   (leaf (token "4c" SPINE-DATA 5))
                                                   (leaf (token "4c" SPINE-DATA 6))
                                                   (leaf (token "4c" SPINE-DATA 7))
                                                   (leaf (token "=2" MEASURE 8))
                                                   (leaf (token "4c" SPINE-DATA 9))
                                                   (leaf (token "4c" SPINE-DATA 10))
                                                   (leaf (token "4c" SPINE-DATA 11))
                                                   (leaf (token "=3" MEASURE 12))
                                                   (leaf (token "4c" SPINE-DATA 13))
                                                   (leaf (token "4c" SPINE-DATA 14))
                                                   (leaf (token "4c" SPINE-DATA 15))
                                                   (leaf (token "==" MEASURE 16))
                                                   (leaf (token "*-" SPINE-TERMINATOR 17)))))))
              (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                    (list (token "*clefG2" CLEF 1))
                    (list (token "*k[]" KEY-SIG 2))
                    (list (token "*a:" KEY-LABEL 3))
                    (list (token "*M3/4" TIME-SIG 4))
                    (list (token "4c" SPINE-DATA 5))
                    (list (token "4c" SPINE-DATA 6))
                    (list (token "4c" SPINE-DATA 7))
                    (list (token "=2" MEASURE 8))
                    (list (token "4c" SPINE-DATA 9))
                    (list (token "4c" SPINE-DATA 10))
                    (list (token "4c" SPINE-DATA 11))
                    (list (token "=3" MEASURE 12))
                    (list (token "4c" SPINE-DATA 13))
                    (list (token "4c" SPINE-DATA 14))
                    (list (token "4c" SPINE-DATA 15))
                    (list (token "==" MEASURE 16))
                    (list (token "*-" SPINE-TERMINATOR 17))))
(check-expect (hfile->ab-hgraph (path->hfile "../../data/count/one-spine-no-splits.krn") ab-hgraph)
              (ab-hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                           (leaf (token "*clefG2" CLEF 1))
                                           (leaf (token "*k[]" KEY-SIG 2))
                                           (leaf (token "*a:" KEY-LABEL 3))
                                           (leaf (token "*M3/4" TIME-SIG 4))
                                           (leaf (token "4c" SPINE-DATA 5))
                                           (leaf (token "4c" SPINE-DATA 6))
                                           (leaf (token "4c" SPINE-DATA 7))
                                           (leaf (token "=2" MEASURE 8))
                                           (leaf (token "4c" SPINE-DATA 9))
                                           (leaf (token "4c" SPINE-DATA 10))
                                           (leaf (token "4c" SPINE-DATA 11))
                                           (leaf (token "=3" MEASURE 12))
                                           (leaf (token "4c" SPINE-DATA 13))
                                           (leaf (token "4c" SPINE-DATA 14))
                                           (leaf (token "4c" SPINE-DATA 15))
                                           (leaf (token "==" MEASURE 16))
                                           (leaf (token "*-" SPINE-TERMINATOR 17)))))))
(check-expect (branch->lot (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                 (leaf (token "*clefG2" CLEF 1))
                                 (leaf (token "*k[]" KEY-SIG 2))
                                 (leaf (token "*a:" KEY-LABEL 3))
                                 (leaf (token "*M3/4" TIME-SIG 4))
                                 (leaf (token "4c" SPINE-DATA 5))
                                 (leaf (token "4c" SPINE-DATA 6))
                                 (leaf (token "4c" SPINE-DATA 7))
                                 (leaf (token "=2" MEASURE 8))
                                 (leaf (token "4c" SPINE-DATA 9))
                                 (leaf (token "4c" SPINE-DATA 10))
                                 (leaf (token "4c" SPINE-DATA 11))
                                 (leaf (token "=3" MEASURE 12))
                                 (leaf (token "4c" SPINE-DATA 13))
                                 (leaf (token "4c" SPINE-DATA 14))
                                 (leaf (token "4c" SPINE-DATA 15))
                                 (leaf (token "==" MEASURE 16))
                                 (leaf (token "*-" SPINE-TERMINATOR 17))))
              (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                    (token "*clefG2" CLEF 1)
                    (token "*k[]" KEY-SIG 2)
                    (token "*a:" KEY-LABEL 3)
                    (token "*M3/4" TIME-SIG 4)
                    (token "4c" SPINE-DATA 5)
                    (token "4c" SPINE-DATA 6)
                    (token "4c" SPINE-DATA 7)
                    (token "=2" MEASURE 8)
                    (token "4c" SPINE-DATA 9)
                    (token "4c" SPINE-DATA 10)
                    (token "4c" SPINE-DATA 11)
                    (token "=3" MEASURE 12)
                    (token "4c" SPINE-DATA 13)
                    (token "4c" SPINE-DATA 14)
                    (token "4c" SPINE-DATA 15)
                    (token "==" MEASURE 16)
                    (token "*-" SPINE-TERMINATOR 17)))

(test)
