#lang racket/base

(require "../../../../parser/data-definitions/data-definitions.rkt"
         "../../../../parser/functions/file.rkt"
         "../../../../parser/functions/spine-parser.rkt"
         "../../../../parser/data-structures/humdrum-graph/data-definitions/data-definitions.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hgraph-to-hfile.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hfile-to-hgraph.rkt"
         test-engine/racket-tests)

(check-expect (path->hfile "../../data/count/three-spines-one-split.krn")
              (hfile (list (record "**kern\t**kern\t**kern" TOKEN
                                   (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                                         (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                                         (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                   0)
                           (record "*clefG2\t*clefG2\t*clefG2" TOKEN
                                   (list (token "*clefG2" CLEF 1)
                                         (token "*clefG2" CLEF 1)
                                         (token "*clefG2" CLEF 1))
                                   1)
                           (record "*k[]\t*k[]\t*k[]" TOKEN
                                   (list (token "*k[]" KEY-SIG 2)
                                         (token "*k[]" KEY-SIG 2)
                                         (token "*k[]" KEY-SIG 2))
                                   2)
                           (record "*a:\t*a:\t*a:" TOKEN
                                   (list (token "*a:" KEY-LABEL 3)
                                         (token "*a:" KEY-LABEL 3)
                                         (token "*a:" KEY-LABEL 3))
                                   3)
                           (record "*M3/4\t*M3/4\t*M3/4" TOKEN
                                   (list (token "*M3/4" TIME-SIG 4)
                                         (token "*M3/4" TIME-SIG 4)
                                         (token "*M3/4" TIME-SIG 4))
                                   4)
                           (record "*^\t*\t*" TOKEN
                                   (list (token "*^" SPINE-SPLIT 5)
                                         (token "*" NULL-INTERPRETATION 5)
                                         (token "*" NULL-INTERPRETATION 5))
                                   5)
                           (record "*\t*\t*^\t*" TOKEN
                                   (list (token "*" NULL-INTERPRETATION 6)
                                         (token "*" NULL-INTERPRETATION 6)
                                         (token "*^" SPINE-SPLIT 6)
                                         (token "*" NULL-INTERPRETATION 6))
                                   6)
                           (record "*\t*\t*\t*\t*^" TOKEN
                                   (list (token "*" NULL-INTERPRETATION 7)
                                         (token "*" NULL-INTERPRETATION 7)
                                         (token "*" NULL-INTERPRETATION 7)
                                         (token "*" NULL-INTERPRETATION 7)
                                         (token "*^" SPINE-SPLIT 7))
                                   7)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 8)
                                         (token "4c" SPINE-DATA 8)
                                         (token "4c" SPINE-DATA 8)
                                         (token "4c" SPINE-DATA 8)
                                         (token "4c" SPINE-DATA 8)
                                         (token "4c" SPINE-DATA 8))
                                   8)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 9)
                                         (token "4c" SPINE-DATA 9)
                                         (token "4c" SPINE-DATA 9)
                                         (token "4c" SPINE-DATA 9)
                                         (token "4c" SPINE-DATA 9)
                                         (token "4c" SPINE-DATA 9))
                                   9)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 10)
                                         (token "4c" SPINE-DATA 10)
                                         (token "4c" SPINE-DATA 10)
                                         (token "4c" SPINE-DATA 10)
                                         (token "4c" SPINE-DATA 10)
                                         (token "4c" SPINE-DATA 10))
                                   10)
                           (record "=2\t=2\t=2\t=2\t=2\t=2" TOKEN
                                   (list (token "=2" MEASURE 11)
                                         (token "=2" MEASURE 11)
                                         (token "=2" MEASURE 11)
                                         (token "=2" MEASURE 11)
                                         (token "=2" MEASURE 11)
                                         (token "=2" MEASURE 11))
                                   11)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 12)
                                         (token "4c" SPINE-DATA 12)
                                         (token "4c" SPINE-DATA 12)
                                         (token "4c" SPINE-DATA 12)
                                         (token "4c" SPINE-DATA 12)
                                         (token "4c" SPINE-DATA 12))
                                   12)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 13)
                                         (token "4c" SPINE-DATA 13)
                                         (token "4c" SPINE-DATA 13)
                                         (token "4c" SPINE-DATA 13)
                                         (token "4c" SPINE-DATA 13)
                                         (token "4c" SPINE-DATA 13))
                                   13)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 14)
                                         (token "4c" SPINE-DATA 14)
                                         (token "4c" SPINE-DATA 14)
                                         (token "4c" SPINE-DATA 14)
                                         (token "4c" SPINE-DATA 14)
                                         (token "4c" SPINE-DATA 14))
                                   14)
                           (record "=3\t=3\t=3\t=3\t=3\t=3" TOKEN
                                   (list (token "=3" MEASURE 15)
                                         (token "=3" MEASURE 15)
                                         (token "=3" MEASURE 15)
                                         (token "=3" MEASURE 15)
                                         (token "=3" MEASURE 15)
                                         (token "=3" MEASURE 15))
                                   15)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 16)
                                         (token "4c" SPINE-DATA 16)
                                         (token "4c" SPINE-DATA 16)
                                         (token "4c" SPINE-DATA 16)
                                         (token "4c" SPINE-DATA 16)
                                         (token "4c" SPINE-DATA 16))
                                   16)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 17)
                                         (token "4c" SPINE-DATA 17)
                                         (token "4c" SPINE-DATA 17)
                                         (token "4c" SPINE-DATA 17)
                                         (token "4c" SPINE-DATA 17)
                                         (token "4c" SPINE-DATA 17))
                                   17)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 18)
                                         (token "4c" SPINE-DATA 18)
                                         (token "4c" SPINE-DATA 18)
                                         (token "4c" SPINE-DATA 18)
                                         (token "4c" SPINE-DATA 18)
                                         (token "4c" SPINE-DATA 18))
                                   18)
                           (record "*\t*\t*\t*\t*v\t*v" TOKEN
                                   (list (token "*" NULL-INTERPRETATION 19)
                                         (token "*" NULL-INTERPRETATION 19)
                                         (token "*" NULL-INTERPRETATION 19)
                                         (token "*" NULL-INTERPRETATION 19)
                                         (token "*v" SPINE-JOIN 19)
                                         (token "*v" SPINE-JOIN 19))
                                   19)
                           (record "*\t*\t*v\t*v\t*" TOKEN
                                   (list (token "*" NULL-INTERPRETATION 20)
                                         (token "*" NULL-INTERPRETATION 20)
                                         (token "*v" SPINE-JOIN 20)
                                         (token "*v" SPINE-JOIN 20)
                                         (token "*" NULL-INTERPRETATION 20))
                                   20)
                           (record "*v\t*v\t*\t*" TOKEN
                                   (list (token "*v" SPINE-JOIN 21)
                                         (token "*v" SPINE-JOIN 21)
                                         (token "*" NULL-INTERPRETATION 21)
                                         (token "*" NULL-INTERPRETATION 21))
                                   21)
                           (record "==\t==\t==" TOKEN
                                   (list (token "==" MEASURE 22)
                                         (token "==" MEASURE 22)
                                         (token "==" MEASURE 22))
                                   22)
                           (record "*-\t*-\t*-" TOKEN
                                   (list (token "*-" SPINE-TERMINATOR 23)
                                         (token "*-" SPINE-TERMINATOR 23)
                                         (token "*-" SPINE-TERMINATOR 23))
                                   23))))
(check-expect (spine-parser (path->hfile "../../data/count/three-spines-one-split.krn"))
              (list (global-spine KERN
                                  (list (list (token"**kern" EXCLUSIVE-INTERPRETATION 0))
                                        (list (token "*clefG2" CLEF 1))
                                        (list (token "*k[]" KEY-SIG 2))
                                        (list (token "*a:" KEY-LABEL 3))
                                        (list (token "*M3/4" TIME-SIG 4))
                                        (list (token "*^" SPINE-SPLIT 5))
                                        (list (token "*" NULL-INTERPRETATION 6)
                                              (token "*" NULL-INTERPRETATION 6))
                                        (list (token "*" NULL-INTERPRETATION 7)
                                              (token "*" NULL-INTERPRETATION 7))
                                        (list (token "4c" SPINE-DATA 8)
                                              (token "4c" SPINE-DATA 8))
                                        (list (token "4c" SPINE-DATA 9)
                                              (token "4c" SPINE-DATA 9))
                                        (list (token "4c" SPINE-DATA 10)
                                              (token "4c" SPINE-DATA 10))
                                        (list (token "=2" MEASURE 11)
                                              (token "=2" MEASURE 11))
                                        (list (token "4c" SPINE-DATA 12)
                                              (token "4c" SPINE-DATA 12))
                                        (list (token "4c" SPINE-DATA 13)
                                              (token "4c" SPINE-DATA 13))
                                        (list (token "4c" SPINE-DATA 14)
                                              (token "4c" SPINE-DATA 14))
                                        (list (token "=3" MEASURE 15)
                                              (token "=3" MEASURE 15))
                                        (list (token "4c" SPINE-DATA 16)
                                              (token "4c" SPINE-DATA 16))
                                        (list (token "4c" SPINE-DATA 17)
                                              (token "4c" SPINE-DATA 17))
                                        (list (token "4c" SPINE-DATA 18)
                                              (token "4c" SPINE-DATA 18))
                                        (list (token "*" NULL-INTERPRETATION 19)
                                              (token "*" NULL-INTERPRETATION 19))
                                        (list (token "*" NULL-INTERPRETATION 20)
                                              (token "*" NULL-INTERPRETATION 20))
                                        (list (token "*v" SPINE-JOIN 21)
                                              (token "*v" SPINE-JOIN 21))
                                        (list (token "==" MEASURE 22))
                                        (list (token "*-" SPINE-TERMINATOR 23)))
                                  0)
                    (global-spine KERN
                                  (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                        (list (token "*clefG2" CLEF 1))
                                        (list (token "*k[]" KEY-SIG 2))
                                        (list (token "*a:" KEY-LABEL 3))
                                        (list (token "*M3/4" TIME-SIG 4))
                                        (list (token "*" NULL-INTERPRETATION 5))
                                        (list (token "*^" SPINE-SPLIT 6))
                                        (list (token "*" NULL-INTERPRETATION 7)
                                              (token "*" NULL-INTERPRETATION 7))
                                        (list (token "4c" SPINE-DATA 8)
                                              (token "4c" SPINE-DATA 8))
                                        (list (token "4c" SPINE-DATA 9)
                                              (token "4c" SPINE-DATA 9))
                                        (list (token "4c" SPINE-DATA 10)
                                              (token "4c" SPINE-DATA 10))
                                        (list (token "=2" MEASURE 11)
                                              (token "=2" MEASURE 11))
                                        (list (token "4c" SPINE-DATA 12)
                                              (token "4c" SPINE-DATA 12))
                                        (list (token "4c" SPINE-DATA 13)
                                              (token "4c" SPINE-DATA 13))
                                        (list (token "4c" SPINE-DATA 14)
                                              (token "4c" SPINE-DATA 14))
                                        (list (token "=3" MEASURE 15)
                                              (token "=3" MEASURE 15))
                                        (list (token "4c" SPINE-DATA 16)
                                              (token "4c" SPINE-DATA 16))
                                        (list (token "4c" SPINE-DATA 17)
                                              (token "4c" SPINE-DATA 17))
                                        (list (token "4c" SPINE-DATA 18)
                                              (token "4c" SPINE-DATA 18))
                                        (list (token "*" NULL-INTERPRETATION 19)
                                              (token "*" NULL-INTERPRETATION 19))
                                        (list (token "*v" SPINE-JOIN 20)
                                              (token "*v" SPINE-JOIN 20))
                                        (list (token "*" NULL-INTERPRETATION 21))
                                        (list (token "==" MEASURE 22))
                                        (list (token "*-" SPINE-TERMINATOR 23)))
                                  1)
                    (global-spine KERN
                                  (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                        (list (token "*clefG2" CLEF 1))
                                        (list (token "*k[]" KEY-SIG 2))
                                        (list (token "*a:" KEY-LABEL 3))
                                        (list (token "*M3/4" TIME-SIG 4))
                                        (list (token "*" NULL-INTERPRETATION 5))
                                        (list (token "*" NULL-INTERPRETATION 6))
                                        (list (token "*^" SPINE-SPLIT 7))
                                        (list (token "4c" SPINE-DATA 8)
                                              (token "4c" SPINE-DATA 8))
                                        (list (token "4c" SPINE-DATA 9)
                                              (token "4c" SPINE-DATA 9))
                                        (list (token "4c" SPINE-DATA 10)
                                              (token "4c" SPINE-DATA 10))
                                        (list (token "=2" MEASURE 11)
                                              (token "=2" MEASURE 11))
                                        (list (token "4c" SPINE-DATA 12)
                                              (token "4c" SPINE-DATA 12))
                                        (list (token "4c" SPINE-DATA 13)
                                              (token "4c" SPINE-DATA 13))
                                        (list (token "4c" SPINE-DATA 14)
                                              (token "4c" SPINE-DATA 14))
                                        (list (token "=3" MEASURE 15)
                                              (token "=3" MEASURE 15))
                                        (list (token "4c" SPINE-DATA 16)
                                              (token "4c" SPINE-DATA 16))
                                        (list (token "4c" SPINE-DATA 17)
                                              (token "4c" SPINE-DATA 17))
                                        (list (token "4c" SPINE-DATA 18)
                                              (token "4c" SPINE-DATA 18))
                                        (list (token "*v" SPINE-JOIN 19)
                                              (token "*v" SPINE-JOIN 19))
                                        (list (token "*" NULL-INTERPRETATION 20))
                                        (list (token "*" NULL-INTERPRETATION 21))
                                        (list (token "==" MEASURE 22))
                                        (list (token "*-" SPINE-TERMINATOR 23)))
                                  2)))
(check-expect (hgraph->hfile
               (hgraph (root (list (list (leaf (token"**kern" EXCLUSIVE-INTERPRETATION 0))
                                         (leaf (token "*clefG2" CLEF 1))
                                         (leaf (token "*k[]" KEY-SIG 2))
                                         (leaf (token "*a:" KEY-LABEL 3))
                                         (leaf (token "*M3/4" TIME-SIG 4))
                                         (parent (token "*^" SPINE-SPLIT 5)
                                                 (list (leaf (token "*" NULL-INTERPRETATION 6))
                                                       (leaf (token "*" NULL-INTERPRETATION 7))
                                                       (leaf (token "4c" SPINE-DATA 8))
                                                       (leaf (token "4c" SPINE-DATA 9))
                                                       (leaf (token "4c" SPINE-DATA 10))
                                                       (leaf (token "=2" MEASURE 11))
                                                       (leaf (token "4c" SPINE-DATA 12))
                                                       (leaf (token "4c" SPINE-DATA 13))
                                                       (leaf (token "4c" SPINE-DATA 14))
                                                       (leaf (token "=3" MEASURE 15))
                                                       (leaf (token "4c" SPINE-DATA 16))
                                                       (leaf (token "4c" SPINE-DATA 17))
                                                       (leaf (token "4c" SPINE-DATA 18))
                                                       (leaf (token "*" NULL-INTERPRETATION 19))
                                                       (leaf (token "*" NULL-INTERPRETATION 20))
                                                       (leaf (token "*v" SPINE-JOIN 21)))
                                                 (list (leaf (token "*" NULL-INTERPRETATION 6))
                                                       (leaf (token "*" NULL-INTERPRETATION 7))
                                                       (leaf (token "4c" SPINE-DATA 8))
                                                       (leaf (token "4c" SPINE-DATA 9))
                                                       (leaf (token "4c" SPINE-DATA 10))
                                                       (leaf (token "=2" MEASURE 11))
                                                       (leaf (token "4c" SPINE-DATA 12))
                                                       (leaf (token "4c" SPINE-DATA 13))
                                                       (leaf (token "4c" SPINE-DATA 14))
                                                       (leaf (token "=3" MEASURE 15))
                                                       (leaf (token "4c" SPINE-DATA 16))
                                                       (leaf (token "4c" SPINE-DATA 17))
                                                       (leaf (token "4c" SPINE-DATA 18))
                                                       (leaf (token "*" NULL-INTERPRETATION 19))
                                                       (leaf (token "*" NULL-INTERPRETATION 20))
                                                       (leaf (token "*v" SPINE-JOIN 21))))
                                         (leaf (token "==" MEASURE 22))
                                         (leaf (token "*-" SPINE-TERMINATOR 23)))
                                   (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                         (leaf (token "*clefG2" CLEF 1))
                                         (leaf (token "*k[]" KEY-SIG 2))
                                         (leaf (token "*a:" KEY-LABEL 3))
                                         (leaf (token "*M3/4" TIME-SIG 4))
                                         (leaf (token "*" NULL-INTERPRETATION 5))
                                         (parent (token "*^" SPINE-SPLIT 6)
                                                 (list (leaf (token "*" NULL-INTERPRETATION 7))
                                                       (leaf (token "4c" SPINE-DATA 8))
                                                       (leaf (token "4c" SPINE-DATA 9))
                                                       (leaf (token "4c" SPINE-DATA 10))
                                                       (leaf (token "=2" MEASURE 11))
                                                       (leaf (token "4c" SPINE-DATA 12))
                                                       (leaf (token "4c" SPINE-DATA 13))
                                                       (leaf (token "4c" SPINE-DATA 14))
                                                       (leaf (token "=3" MEASURE 15))
                                                       (leaf (token "4c" SPINE-DATA 16))
                                                       (leaf (token "4c" SPINE-DATA 17))
                                                       (leaf (token "4c" SPINE-DATA 18))
                                                       (leaf (token "*" NULL-INTERPRETATION 19))
                                                       (leaf (token "*v" SPINE-JOIN 20)))
                                                 (list (leaf (token "*" NULL-INTERPRETATION 7))
                                                       (leaf (token "4c" SPINE-DATA 8))
                                                       (leaf (token "4c" SPINE-DATA 9))
                                                       (leaf (token "4c" SPINE-DATA 10))
                                                       (leaf (token "=2" MEASURE 11))
                                                       (leaf (token "4c" SPINE-DATA 12))
                                                       (leaf (token "4c" SPINE-DATA 13))
                                                       (leaf (token "4c" SPINE-DATA 14))
                                                       (leaf (token "=3" MEASURE 15))
                                                       (leaf (token "4c" SPINE-DATA 16))
                                                       (leaf (token "4c" SPINE-DATA 17))
                                                       (leaf (token "4c" SPINE-DATA 18))
                                                       (leaf (token "*" NULL-INTERPRETATION 19))
                                                       (leaf (token "*v" SPINE-JOIN 20))))
                                         (leaf (token "*" NULL-INTERPRETATION 21))
                                         (leaf (token "==" MEASURE 22))
                                         (leaf (token "*-" SPINE-TERMINATOR 23)))
                                   (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                         (leaf (token "*clefG2" CLEF 1))
                                         (leaf (token "*k[]" KEY-SIG 2))
                                         (leaf (token "*a:" KEY-LABEL 3))
                                         (leaf (token "*M3/4" TIME-SIG 4))
                                         (leaf (token "*" NULL-INTERPRETATION 5))
                                         (leaf (token "*" NULL-INTERPRETATION 6))
                                         (parent (token "*^" SPINE-SPLIT 7)
                                                 (list (leaf (token "4c" SPINE-DATA 8))
                                                       (leaf (token "4c" SPINE-DATA 9))
                                                       (leaf (token "4c" SPINE-DATA 10))
                                                       (leaf (token "=2" MEASURE 11))
                                                       (leaf (token "4c" SPINE-DATA 12))
                                                       (leaf (token "4c" SPINE-DATA 13))
                                                       (leaf (token "4c" SPINE-DATA 14))
                                                       (leaf (token "=3" MEASURE 15))
                                                       (leaf (token "4c" SPINE-DATA 16))
                                                       (leaf (token "4c" SPINE-DATA 17))
                                                       (leaf (token "4c" SPINE-DATA 18))
                                                       (leaf (token "*v" SPINE-JOIN 19)))
                                                 (list (leaf (token "4c" SPINE-DATA 8))
                                                       (leaf (token "4c" SPINE-DATA 9))
                                                       (leaf (token "4c" SPINE-DATA 10))
                                                       (leaf (token "=2" MEASURE 11))
                                                       (leaf (token "4c" SPINE-DATA 12))
                                                       (leaf (token "4c" SPINE-DATA 13))
                                                       (leaf (token "4c" SPINE-DATA 14))
                                                       (leaf (token "=3" MEASURE 15))
                                                       (leaf (token "4c" SPINE-DATA 16))
                                                       (leaf (token "4c" SPINE-DATA 17))
                                                       (leaf (token "4c" SPINE-DATA 18))
                                                       (leaf (token "*v" SPINE-JOIN 19))))
                                         (leaf (token "*" NULL-INTERPRETATION 20))
                                         (leaf (token "*" NULL-INTERPRETATION 21))
                                         (leaf (token "==" MEASURE 22))
                                         (leaf (token "*-" SPINE-TERMINATOR 23)))))))
              (path->hfile "../../data/count/three-spines-one-split.krn"))
(check-expect (lolot->lor (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                                      (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                                      (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                (list (token "*clefG2" CLEF 1)
                                      (token "*clefG2" CLEF 1)
                                      (token "*clefG2" CLEF 1))
                                (list (token "*k[]" KEY-SIG 2)
                                      (token "*k[]" KEY-SIG 2)
                                      (token "*k[]" KEY-SIG 2))
                                (list (token "*a:" KEY-LABEL 3)
                                      (token "*a:" KEY-LABEL 3)
                                      (token "*a:" KEY-LABEL 3))
                                (list (token "*M3/4" TIME-SIG 4)
                                      (token "*M3/4" TIME-SIG 4)
                                      (token "*M3/4" TIME-SIG 4))
                                (list (token "*^" SPINE-SPLIT 5)
                                      (token "*" NULL-INTERPRETATION 5)
                                      (token "*" NULL-INTERPRETATION 5))
                                (list (token "*" NULL-INTERPRETATION 6)
                                      (token "*" NULL-INTERPRETATION 6)
                                      (token "*^" SPINE-SPLIT 6)
                                      (token "*" NULL-INTERPRETATION 6))
                                (list (token "*" NULL-INTERPRETATION 7)
                                      (token "*" NULL-INTERPRETATION 7)
                                      (token "*" NULL-INTERPRETATION 7)
                                      (token "*" NULL-INTERPRETATION 7)
                                      (token "*^" SPINE-SPLIT 7))
                                (list (token "4c" SPINE-DATA 8)
                                      (token "4c" SPINE-DATA 8)
                                      (token "4c" SPINE-DATA 8)
                                      (token "4c" SPINE-DATA 8)
                                      (token "4c" SPINE-DATA 8)
                                      (token "4c" SPINE-DATA 8))
                                (list (token "4c" SPINE-DATA 9)
                                      (token "4c" SPINE-DATA 9)
                                      (token "4c" SPINE-DATA 9)
                                      (token "4c" SPINE-DATA 9)
                                      (token "4c" SPINE-DATA 9)
                                      (token "4c" SPINE-DATA 9))
                                (list (token "4c" SPINE-DATA 10)
                                      (token "4c" SPINE-DATA 10)
                                      (token "4c" SPINE-DATA 10)
                                      (token "4c" SPINE-DATA 10)
                                      (token "4c" SPINE-DATA 10)
                                      (token "4c" SPINE-DATA 10))
                                (list (token "=2" MEASURE 11)
                                      (token "=2" MEASURE 11)
                                      (token "=2" MEASURE 11)
                                      (token "=2" MEASURE 11)
                                      (token "=2" MEASURE 11)
                                      (token "=2" MEASURE 11))
                                (list (token "4c" SPINE-DATA 12)
                                      (token "4c" SPINE-DATA 12)
                                      (token "4c" SPINE-DATA 12)
                                      (token "4c" SPINE-DATA 12)
                                      (token "4c" SPINE-DATA 12)
                                      (token "4c" SPINE-DATA 12))
                                (list (token "4c" SPINE-DATA 13)
                                      (token "4c" SPINE-DATA 13)
                                      (token "4c" SPINE-DATA 13)
                                      (token "4c" SPINE-DATA 13)
                                      (token "4c" SPINE-DATA 13)
                                      (token "4c" SPINE-DATA 13))
                                (list (token "4c" SPINE-DATA 14)
                                      (token "4c" SPINE-DATA 14)
                                      (token "4c" SPINE-DATA 14)
                                      (token "4c" SPINE-DATA 14)
                                      (token "4c" SPINE-DATA 14)
                                      (token "4c" SPINE-DATA 14))
                                (list (token "=3" MEASURE 15)
                                      (token "=3" MEASURE 15)
                                      (token "=3" MEASURE 15)
                                      (token "=3" MEASURE 15)
                                      (token "=3" MEASURE 15)
                                      (token "=3" MEASURE 15))
                                (list (token "4c" SPINE-DATA 16)
                                      (token "4c" SPINE-DATA 16)
                                      (token "4c" SPINE-DATA 16)
                                      (token "4c" SPINE-DATA 16)
                                      (token "4c" SPINE-DATA 16)
                                      (token "4c" SPINE-DATA 16))
                                (list (token "4c" SPINE-DATA 17)
                                      (token "4c" SPINE-DATA 17)
                                      (token "4c" SPINE-DATA 17)
                                      (token "4c" SPINE-DATA 17)
                                      (token "4c" SPINE-DATA 17)
                                      (token "4c" SPINE-DATA 17))
                                (list (token "4c" SPINE-DATA 18)
                                      (token "4c" SPINE-DATA 18)
                                      (token "4c" SPINE-DATA 18)
                                      (token "4c" SPINE-DATA 18)
                                      (token "4c" SPINE-DATA 18)
                                      (token "4c" SPINE-DATA 18))
                                (list (token "*" NULL-INTERPRETATION 19)
                                      (token "*" NULL-INTERPRETATION 19)
                                      (token "*" NULL-INTERPRETATION 19)
                                      (token "*" NULL-INTERPRETATION 19)
                                      (token "*v" SPINE-JOIN 19)
                                      (token "*v" SPINE-JOIN 19))
                                (list (token "*" NULL-INTERPRETATION 20)
                                      (token "*" NULL-INTERPRETATION 20)
                                      (token "*v" SPINE-JOIN 20)
                                      (token "*v" SPINE-JOIN 20)
                                      (token "*" NULL-INTERPRETATION 20))
                                (list (token "*v" SPINE-JOIN 21)
                                      (token "*v" SPINE-JOIN 21)
                                      (token "*" NULL-INTERPRETATION 21)
                                      (token "*" NULL-INTERPRETATION 21))
                                (list (token "==" MEASURE 22)
                                      (token "==" MEASURE 22)
                                      (token "==" MEASURE 22))
                                (list (token "*-" SPINE-TERMINATOR 23)
                                      (token "*-" SPINE-TERMINATOR 23)
                                      (token "*-" SPINE-TERMINATOR 23))))
              (list (record "**kern\t**kern\t**kern" TOKEN
                            (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                                  (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                                  (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                            0)
                    (record "*clefG2\t*clefG2\t*clefG2" TOKEN
                            (list (token "*clefG2" CLEF 1)
                                  (token "*clefG2" CLEF 1)
                                  (token "*clefG2" CLEF 1))
                            1)
                    (record "*k[]\t*k[]\t*k[]" TOKEN
                            (list (token "*k[]" KEY-SIG 2)
                                  (token "*k[]" KEY-SIG 2)
                                  (token "*k[]" KEY-SIG 2))
                            2)
                    (record "*a:\t*a:\t*a:" TOKEN
                            (list (token "*a:" KEY-LABEL 3)
                                  (token "*a:" KEY-LABEL 3)
                                  (token "*a:" KEY-LABEL 3))
                            3)
                    (record "*M3/4\t*M3/4\t*M3/4" TOKEN
                            (list (token "*M3/4" TIME-SIG 4)
                                  (token "*M3/4" TIME-SIG 4)
                                  (token "*M3/4" TIME-SIG 4))
                            4)
                    (record "*^\t*\t*" TOKEN
                            (list (token "*^" SPINE-SPLIT 5)
                                  (token "*" NULL-INTERPRETATION 5)
                                  (token "*" NULL-INTERPRETATION 5))
                            5)
                    (record "*\t*\t*^\t*" TOKEN
                            (list (token "*" NULL-INTERPRETATION 6)
                                  (token "*" NULL-INTERPRETATION 6)
                                  (token "*^" SPINE-SPLIT 6)
                                  (token "*" NULL-INTERPRETATION 6))
                            6)
                    (record "*\t*\t*\t*\t*^" TOKEN
                            (list (token "*" NULL-INTERPRETATION 7)
                                  (token "*" NULL-INTERPRETATION 7)
                                  (token "*" NULL-INTERPRETATION 7)
                                  (token "*" NULL-INTERPRETATION 7)
                                  (token "*^" SPINE-SPLIT 7))
                            7)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 8)
                                  (token "4c" SPINE-DATA 8)
                                  (token "4c" SPINE-DATA 8)
                                  (token "4c" SPINE-DATA 8)
                                  (token "4c" SPINE-DATA 8)
                                  (token "4c" SPINE-DATA 8))
                            8)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 9)
                                  (token "4c" SPINE-DATA 9)
                                  (token "4c" SPINE-DATA 9)
                                  (token "4c" SPINE-DATA 9)
                                  (token "4c" SPINE-DATA 9)
                                  (token "4c" SPINE-DATA 9))
                            9)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 10)
                                  (token "4c" SPINE-DATA 10)
                                  (token "4c" SPINE-DATA 10)
                                  (token "4c" SPINE-DATA 10)
                                  (token "4c" SPINE-DATA 10)
                                  (token "4c" SPINE-DATA 10))
                            10)
                    (record "=2\t=2\t=2\t=2\t=2\t=2" TOKEN
                            (list (token "=2" MEASURE 11)
                                  (token "=2" MEASURE 11)
                                  (token "=2" MEASURE 11)
                                  (token "=2" MEASURE 11)
                                  (token "=2" MEASURE 11)
                                  (token "=2" MEASURE 11))
                            11)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 12)
                                  (token "4c" SPINE-DATA 12)
                                  (token "4c" SPINE-DATA 12)
                                  (token "4c" SPINE-DATA 12)
                                  (token "4c" SPINE-DATA 12)
                                  (token "4c" SPINE-DATA 12))
                            12)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 13)
                                  (token "4c" SPINE-DATA 13)
                                  (token "4c" SPINE-DATA 13)
                                  (token "4c" SPINE-DATA 13)
                                  (token "4c" SPINE-DATA 13)
                                  (token "4c" SPINE-DATA 13))
                            13)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 14)
                                  (token "4c" SPINE-DATA 14)
                                  (token "4c" SPINE-DATA 14)
                                  (token "4c" SPINE-DATA 14)
                                  (token "4c" SPINE-DATA 14)
                                  (token "4c" SPINE-DATA 14))
                            14)
                    (record "=3\t=3\t=3\t=3\t=3\t=3" TOKEN
                            (list (token "=3" MEASURE 15)
                                  (token "=3" MEASURE 15)
                                  (token "=3" MEASURE 15)
                                  (token "=3" MEASURE 15)
                                  (token "=3" MEASURE 15)
                                  (token "=3" MEASURE 15))
                            15)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 16)
                                  (token "4c" SPINE-DATA 16)
                                  (token "4c" SPINE-DATA 16)
                                  (token "4c" SPINE-DATA 16)
                                  (token "4c" SPINE-DATA 16)
                                  (token "4c" SPINE-DATA 16))
                            16)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 17)
                                  (token "4c" SPINE-DATA 17)
                                  (token "4c" SPINE-DATA 17)
                                  (token "4c" SPINE-DATA 17)
                                  (token "4c" SPINE-DATA 17)
                                  (token "4c" SPINE-DATA 17))
                            17)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 18)
                                  (token "4c" SPINE-DATA 18)
                                  (token "4c" SPINE-DATA 18)
                                  (token "4c" SPINE-DATA 18)
                                  (token "4c" SPINE-DATA 18)
                                  (token "4c" SPINE-DATA 18))
                            18)
                    (record "*\t*\t*\t*\t*v\t*v" TOKEN
                            (list (token "*" NULL-INTERPRETATION 19)
                                  (token "*" NULL-INTERPRETATION 19)
                                  (token "*" NULL-INTERPRETATION 19)
                                  (token "*" NULL-INTERPRETATION 19)
                                  (token "*v" SPINE-JOIN 19)
                                  (token "*v" SPINE-JOIN 19))
                            19)
                    (record "*\t*\t*v\t*v\t*" TOKEN
                            (list (token "*" NULL-INTERPRETATION 20)
                                  (token "*" NULL-INTERPRETATION 20)
                                  (token "*v" SPINE-JOIN 20)
                                  (token "*v" SPINE-JOIN 20)
                                  (token "*" NULL-INTERPRETATION 20))
                            20)
                    (record "*v\t*v\t*\t*" TOKEN
                            (list (token "*v" SPINE-JOIN 21)
                                  (token "*v" SPINE-JOIN 21)
                                  (token "*" NULL-INTERPRETATION 21)
                                  (token "*" NULL-INTERPRETATION 21))
                            21)
                    (record "==\t==\t==" TOKEN
                            (list (token "==" MEASURE 22)
                                  (token "==" MEASURE 22)
                                  (token "==" MEASURE 22))
                            22)
                    (record "*-\t*-\t*-" TOKEN
                            (list (token "*-" SPINE-TERMINATOR 23)
                                  (token "*-" SPINE-TERMINATOR 23)
                                  (token "*-" SPINE-TERMINATOR 23))
                            23)))
(check-expect (hgraph->lolot
               (hgraph (root (list (list (leaf (token"**kern" EXCLUSIVE-INTERPRETATION 0))
                                         (leaf (token "*clefG2" CLEF 1))
                                         (leaf (token "*k[]" KEY-SIG 2))
                                         (leaf (token "*a:" KEY-LABEL 3))
                                         (leaf (token "*M3/4" TIME-SIG 4))
                                         (parent (token "*^" SPINE-SPLIT 5)
                                                 (list (leaf (token "*" NULL-INTERPRETATION 6))
                                                       (leaf (token "*" NULL-INTERPRETATION 7))
                                                       (leaf (token "4c" SPINE-DATA 8))
                                                       (leaf (token "4c" SPINE-DATA 9))
                                                       (leaf (token "4c" SPINE-DATA 10))
                                                       (leaf (token "=2" MEASURE 11))
                                                       (leaf (token "4c" SPINE-DATA 12))
                                                       (leaf (token "4c" SPINE-DATA 13))
                                                       (leaf (token "4c" SPINE-DATA 14))
                                                       (leaf (token "=3" MEASURE 15))
                                                       (leaf (token "4c" SPINE-DATA 16))
                                                       (leaf (token "4c" SPINE-DATA 17))
                                                       (leaf (token "4c" SPINE-DATA 18))
                                                       (leaf (token "*" NULL-INTERPRETATION 19))
                                                       (leaf (token "*" NULL-INTERPRETATION 20))
                                                       (leaf (token "*v" SPINE-JOIN 21)))
                                                 (list (leaf (token "*" NULL-INTERPRETATION 6))
                                                       (leaf (token "*" NULL-INTERPRETATION 7))
                                                       (leaf (token "4c" SPINE-DATA 8))
                                                       (leaf (token "4c" SPINE-DATA 9))
                                                       (leaf (token "4c" SPINE-DATA 10))
                                                       (leaf (token "=2" MEASURE 11))
                                                       (leaf (token "4c" SPINE-DATA 12))
                                                       (leaf (token "4c" SPINE-DATA 13))
                                                       (leaf (token "4c" SPINE-DATA 14))
                                                       (leaf (token "=3" MEASURE 15))
                                                       (leaf (token "4c" SPINE-DATA 16))
                                                       (leaf (token "4c" SPINE-DATA 17))
                                                       (leaf (token "4c" SPINE-DATA 18))
                                                       (leaf (token "*" NULL-INTERPRETATION 19))
                                                       (leaf (token "*" NULL-INTERPRETATION 20))
                                                       (leaf (token "*v" SPINE-JOIN 21))))
                                         (leaf (token "==" MEASURE 22))
                                         (leaf (token "*-" SPINE-TERMINATOR 23)))
                                   (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                         (leaf (token "*clefG2" CLEF 1))
                                         (leaf (token "*k[]" KEY-SIG 2))
                                         (leaf (token "*a:" KEY-LABEL 3))
                                         (leaf (token "*M3/4" TIME-SIG 4))
                                         (leaf (token "*" NULL-INTERPRETATION 5))
                                         (parent (token "*^" SPINE-SPLIT 6)
                                                 (list (leaf (token "*" NULL-INTERPRETATION 7))
                                                       (leaf (token "4c" SPINE-DATA 8))
                                                       (leaf (token "4c" SPINE-DATA 9))
                                                       (leaf (token "4c" SPINE-DATA 10))
                                                       (leaf (token "=2" MEASURE 11))
                                                       (leaf (token "4c" SPINE-DATA 12))
                                                       (leaf (token "4c" SPINE-DATA 13))
                                                       (leaf (token "4c" SPINE-DATA 14))
                                                       (leaf (token "=3" MEASURE 15))
                                                       (leaf (token "4c" SPINE-DATA 16))
                                                       (leaf (token "4c" SPINE-DATA 17))
                                                       (leaf (token "4c" SPINE-DATA 18))
                                                       (leaf (token "*" NULL-INTERPRETATION 19))
                                                       (leaf (token "*v" SPINE-JOIN 20)))
                                                 (list (leaf (token "*" NULL-INTERPRETATION 7))
                                                       (leaf (token "4c" SPINE-DATA 8))
                                                       (leaf (token "4c" SPINE-DATA 9))
                                                       (leaf (token "4c" SPINE-DATA 10))
                                                       (leaf (token "=2" MEASURE 11))
                                                       (leaf (token "4c" SPINE-DATA 12))
                                                       (leaf (token "4c" SPINE-DATA 13))
                                                       (leaf (token "4c" SPINE-DATA 14))
                                                       (leaf (token "=3" MEASURE 15))
                                                       (leaf (token "4c" SPINE-DATA 16))
                                                       (leaf (token "4c" SPINE-DATA 17))
                                                       (leaf (token "4c" SPINE-DATA 18))
                                                       (leaf (token "*" NULL-INTERPRETATION 19))
                                                       (leaf (token "*v" SPINE-JOIN 20))))
                                         (leaf (token "*" NULL-INTERPRETATION 21))
                                         (leaf (token "==" MEASURE 22))
                                         (leaf (token "*-" SPINE-TERMINATOR 23)))
                                   (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                         (leaf (token "*clefG2" CLEF 1))
                                         (leaf (token "*k[]" KEY-SIG 2))
                                         (leaf (token "*a:" KEY-LABEL 3))
                                         (leaf (token "*M3/4" TIME-SIG 4))
                                         (leaf (token "*" NULL-INTERPRETATION 5))
                                         (leaf (token "*" NULL-INTERPRETATION 6))
                                         (parent (token "*^" SPINE-SPLIT 7)
                                                 (list (leaf (token "4c" SPINE-DATA 8))
                                                       (leaf (token "4c" SPINE-DATA 9))
                                                       (leaf (token "4c" SPINE-DATA 10))
                                                       (leaf (token "=2" MEASURE 11))
                                                       (leaf (token "4c" SPINE-DATA 12))
                                                       (leaf (token "4c" SPINE-DATA 13))
                                                       (leaf (token "4c" SPINE-DATA 14))
                                                       (leaf (token "=3" MEASURE 15))
                                                       (leaf (token "4c" SPINE-DATA 16))
                                                       (leaf (token "4c" SPINE-DATA 17))
                                                       (leaf (token "4c" SPINE-DATA 18))
                                                       (leaf (token "*v" SPINE-JOIN 19)))
                                                 (list (leaf (token "4c" SPINE-DATA 8))
                                                       (leaf (token "4c" SPINE-DATA 9))
                                                       (leaf (token "4c" SPINE-DATA 10))
                                                       (leaf (token "=2" MEASURE 11))
                                                       (leaf (token "4c" SPINE-DATA 12))
                                                       (leaf (token "4c" SPINE-DATA 13))
                                                       (leaf (token "4c" SPINE-DATA 14))
                                                       (leaf (token "=3" MEASURE 15))
                                                       (leaf (token "4c" SPINE-DATA 16))
                                                       (leaf (token "4c" SPINE-DATA 17))
                                                       (leaf (token "4c" SPINE-DATA 18))
                                                       (leaf (token "*v" SPINE-JOIN 19))))
                                         (leaf (token "*" NULL-INTERPRETATION 20))
                                         (leaf (token "*" NULL-INTERPRETATION 21))
                                         (leaf (token "==" MEASURE 22))
                                         (leaf (token "*-" SPINE-TERMINATOR 23)))))))
              (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                          (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                          (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                    (list (token "*clefG2" CLEF 1)
                          (token "*clefG2" CLEF 1)
                          (token "*clefG2" CLEF 1))
                    (list (token "*k[]" KEY-SIG 2)
                          (token "*k[]" KEY-SIG 2)
                          (token "*k[]" KEY-SIG 2))
                    (list (token "*a:" KEY-LABEL 3)
                          (token "*a:" KEY-LABEL 3)
                          (token "*a:" KEY-LABEL 3))
                    (list (token "*M3/4" TIME-SIG 4)
                          (token "*M3/4" TIME-SIG 4)
                          (token "*M3/4" TIME-SIG 4))
                    (list (token "*^" SPINE-SPLIT 5)
                          (token "*" NULL-INTERPRETATION 5)
                          (token "*" NULL-INTERPRETATION 5))
                    (list (token "*" NULL-INTERPRETATION 6)
                          (token "*" NULL-INTERPRETATION 6)
                          (token "*^" SPINE-SPLIT 6)
                          (token "*" NULL-INTERPRETATION 6))
                    (list (token "*" NULL-INTERPRETATION 7)
                          (token "*" NULL-INTERPRETATION 7)
                          (token "*" NULL-INTERPRETATION 7)
                          (token "*" NULL-INTERPRETATION 7)
                          (token "*^" SPINE-SPLIT 7))
                    (list (token "4c" SPINE-DATA 8)
                          (token "4c" SPINE-DATA 8)
                          (token "4c" SPINE-DATA 8)
                          (token "4c" SPINE-DATA 8)
                          (token "4c" SPINE-DATA 8)
                          (token "4c" SPINE-DATA 8))
                    (list (token "4c" SPINE-DATA 9)
                          (token "4c" SPINE-DATA 9)
                          (token "4c" SPINE-DATA 9)
                          (token "4c" SPINE-DATA 9)
                          (token "4c" SPINE-DATA 9)
                          (token "4c" SPINE-DATA 9))
                    (list (token "4c" SPINE-DATA 10)
                          (token "4c" SPINE-DATA 10)
                          (token "4c" SPINE-DATA 10)
                          (token "4c" SPINE-DATA 10)
                          (token "4c" SPINE-DATA 10)
                          (token "4c" SPINE-DATA 10))
                    (list (token "=2" MEASURE 11)
                          (token "=2" MEASURE 11)
                          (token "=2" MEASURE 11)
                          (token "=2" MEASURE 11)
                          (token "=2" MEASURE 11)
                          (token "=2" MEASURE 11))
                    (list (token "4c" SPINE-DATA 12)
                          (token "4c" SPINE-DATA 12)
                          (token "4c" SPINE-DATA 12)
                          (token "4c" SPINE-DATA 12)
                          (token "4c" SPINE-DATA 12)
                          (token "4c" SPINE-DATA 12))
                    (list (token "4c" SPINE-DATA 13)
                          (token "4c" SPINE-DATA 13)
                          (token "4c" SPINE-DATA 13)
                          (token "4c" SPINE-DATA 13)
                          (token "4c" SPINE-DATA 13)
                          (token "4c" SPINE-DATA 13))
                    (list (token "4c" SPINE-DATA 14)
                          (token "4c" SPINE-DATA 14)
                          (token "4c" SPINE-DATA 14)
                          (token "4c" SPINE-DATA 14)
                          (token "4c" SPINE-DATA 14)
                          (token "4c" SPINE-DATA 14))
                    (list (token "=3" MEASURE 15)
                          (token "=3" MEASURE 15)
                          (token "=3" MEASURE 15)
                          (token "=3" MEASURE 15)
                          (token "=3" MEASURE 15)
                          (token "=3" MEASURE 15))
                    (list (token "4c" SPINE-DATA 16)
                          (token "4c" SPINE-DATA 16)
                          (token "4c" SPINE-DATA 16)
                          (token "4c" SPINE-DATA 16)
                          (token "4c" SPINE-DATA 16)
                          (token "4c" SPINE-DATA 16))
                    (list (token "4c" SPINE-DATA 17)
                          (token "4c" SPINE-DATA 17)
                          (token "4c" SPINE-DATA 17)
                          (token "4c" SPINE-DATA 17)
                          (token "4c" SPINE-DATA 17)
                          (token "4c" SPINE-DATA 17))
                    (list (token "4c" SPINE-DATA 18)
                          (token "4c" SPINE-DATA 18)
                          (token "4c" SPINE-DATA 18)
                          (token "4c" SPINE-DATA 18)
                          (token "4c" SPINE-DATA 18)
                          (token "4c" SPINE-DATA 18))
                    (list (token "*" NULL-INTERPRETATION 19)
                          (token "*" NULL-INTERPRETATION 19)
                          (token "*" NULL-INTERPRETATION 19)
                          (token "*" NULL-INTERPRETATION 19)
                          (token "*v" SPINE-JOIN 19)
                          (token "*v" SPINE-JOIN 19))
                    (list (token "*" NULL-INTERPRETATION 20)
                          (token "*" NULL-INTERPRETATION 20)
                          (token "*v" SPINE-JOIN 20)
                          (token "*v" SPINE-JOIN 20)
                          (token "*" NULL-INTERPRETATION 20))
                    (list (token "*v" SPINE-JOIN 21)
                          (token "*v" SPINE-JOIN 21)
                          (token "*" NULL-INTERPRETATION 21)
                          (token "*" NULL-INTERPRETATION 21))
                    (list (token "==" MEASURE 22)
                          (token "==" MEASURE 22)
                          (token "==" MEASURE 22))
                    (list (token "*-" SPINE-TERMINATOR 23)
                          (token "*-" SPINE-TERMINATOR 23)
                          (token "*-" SPINE-TERMINATOR 23))))
(check-expect (hfile->hgraph (path->hfile "../../data/count/three-spines-one-split.krn"))
              (hgraph (root (list (list (leaf (token"**kern" EXCLUSIVE-INTERPRETATION 0))
                                        (leaf (token "*clefG2" CLEF 1))
                                        (leaf (token "*k[]" KEY-SIG 2))
                                        (leaf (token "*a:" KEY-LABEL 3))
                                        (leaf (token "*M3/4" TIME-SIG 4))
                                        (parent (token "*^" SPINE-SPLIT 5)
                                                (list (leaf (token "*" NULL-INTERPRETATION 6))
                                                      (leaf (token "*" NULL-INTERPRETATION 7))
                                                      (leaf (token "4c" SPINE-DATA 8))
                                                      (leaf (token "4c" SPINE-DATA 9))
                                                      (leaf (token "4c" SPINE-DATA 10))
                                                      (leaf (token "=2" MEASURE 11))
                                                      (leaf (token "4c" SPINE-DATA 12))
                                                      (leaf (token "4c" SPINE-DATA 13))
                                                      (leaf (token "4c" SPINE-DATA 14))
                                                      (leaf (token "=3" MEASURE 15))
                                                      (leaf (token "4c" SPINE-DATA 16))
                                                      (leaf (token "4c" SPINE-DATA 17))
                                                      (leaf (token "4c" SPINE-DATA 18))
                                                      (leaf (token "*" NULL-INTERPRETATION 19))
                                                      (leaf (token "*" NULL-INTERPRETATION 20))
                                                      (leaf (token "*v" SPINE-JOIN 21)))
                                                (list (leaf (token "*" NULL-INTERPRETATION 6))
                                                      (leaf (token "*" NULL-INTERPRETATION 7))
                                                      (leaf (token "4c" SPINE-DATA 8))
                                                      (leaf (token "4c" SPINE-DATA 9))
                                                      (leaf (token "4c" SPINE-DATA 10))
                                                      (leaf (token "=2" MEASURE 11))
                                                      (leaf (token "4c" SPINE-DATA 12))
                                                      (leaf (token "4c" SPINE-DATA 13))
                                                      (leaf (token "4c" SPINE-DATA 14))
                                                      (leaf (token "=3" MEASURE 15))
                                                      (leaf (token "4c" SPINE-DATA 16))
                                                      (leaf (token "4c" SPINE-DATA 17))
                                                      (leaf (token "4c" SPINE-DATA 18))
                                                      (leaf (token "*" NULL-INTERPRETATION 19))
                                                      (leaf (token "*" NULL-INTERPRETATION 20))
                                                      (leaf (token "*v" SPINE-JOIN 21))))
                                        (leaf (token "==" MEASURE 22))
                                        (leaf (token "*-" SPINE-TERMINATOR 23)))
                                  (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                        (leaf (token "*clefG2" CLEF 1))
                                        (leaf (token "*k[]" KEY-SIG 2))
                                        (leaf (token "*a:" KEY-LABEL 3))
                                        (leaf (token "*M3/4" TIME-SIG 4))
                                        (leaf (token "*" NULL-INTERPRETATION 5))
                                        (parent (token "*^" SPINE-SPLIT 6)
                                                (list (leaf (token "*" NULL-INTERPRETATION 7))
                                                      (leaf (token "4c" SPINE-DATA 8))
                                                      (leaf (token "4c" SPINE-DATA 9))
                                                      (leaf (token "4c" SPINE-DATA 10))
                                                      (leaf (token "=2" MEASURE 11))
                                                      (leaf (token "4c" SPINE-DATA 12))
                                                      (leaf (token "4c" SPINE-DATA 13))
                                                      (leaf (token "4c" SPINE-DATA 14))
                                                      (leaf (token "=3" MEASURE 15))
                                                      (leaf (token "4c" SPINE-DATA 16))
                                                      (leaf (token "4c" SPINE-DATA 17))
                                                      (leaf (token "4c" SPINE-DATA 18))
                                                      (leaf (token "*" NULL-INTERPRETATION 19))
                                                      (leaf (token "*v" SPINE-JOIN 20)))
                                                (list (leaf (token "*" NULL-INTERPRETATION 7))
                                                      (leaf (token "4c" SPINE-DATA 8))
                                                      (leaf (token "4c" SPINE-DATA 9))
                                                      (leaf (token "4c" SPINE-DATA 10))
                                                      (leaf (token "=2" MEASURE 11))
                                                      (leaf (token "4c" SPINE-DATA 12))
                                                      (leaf (token "4c" SPINE-DATA 13))
                                                      (leaf (token "4c" SPINE-DATA 14))
                                                      (leaf (token "=3" MEASURE 15))
                                                      (leaf (token "4c" SPINE-DATA 16))
                                                      (leaf (token "4c" SPINE-DATA 17))
                                                      (leaf (token "4c" SPINE-DATA 18))
                                                      (leaf (token "*" NULL-INTERPRETATION 19))
                                                      (leaf (token "*v" SPINE-JOIN 20))))
                                        (leaf (token "*" NULL-INTERPRETATION 21))
                                        (leaf (token "==" MEASURE 22))
                                        (leaf (token "*-" SPINE-TERMINATOR 23)))
                                  (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                        (leaf (token "*clefG2" CLEF 1))
                                        (leaf (token "*k[]" KEY-SIG 2))
                                        (leaf (token "*a:" KEY-LABEL 3))
                                        (leaf (token "*M3/4" TIME-SIG 4))
                                        (leaf (token "*" NULL-INTERPRETATION 5))
                                        (leaf (token "*" NULL-INTERPRETATION 6))
                                        (parent (token "*^" SPINE-SPLIT 7)
                                                (list (leaf (token "4c" SPINE-DATA 8))
                                                      (leaf (token "4c" SPINE-DATA 9))
                                                      (leaf (token "4c" SPINE-DATA 10))
                                                      (leaf (token "=2" MEASURE 11))
                                                      (leaf (token "4c" SPINE-DATA 12))
                                                      (leaf (token "4c" SPINE-DATA 13))
                                                      (leaf (token "4c" SPINE-DATA 14))
                                                      (leaf (token "=3" MEASURE 15))
                                                      (leaf (token "4c" SPINE-DATA 16))
                                                      (leaf (token "4c" SPINE-DATA 17))
                                                      (leaf (token "4c" SPINE-DATA 18))
                                                      (leaf (token "*v" SPINE-JOIN 19)))
                                                (list (leaf (token "4c" SPINE-DATA 8))
                                                      (leaf (token "4c" SPINE-DATA 9))
                                                      (leaf (token "4c" SPINE-DATA 10))
                                                      (leaf (token "=2" MEASURE 11))
                                                      (leaf (token "4c" SPINE-DATA 12))
                                                      (leaf (token "4c" SPINE-DATA 13))
                                                      (leaf (token "4c" SPINE-DATA 14))
                                                      (leaf (token "=3" MEASURE 15))
                                                      (leaf (token "4c" SPINE-DATA 16))
                                                      (leaf (token "4c" SPINE-DATA 17))
                                                      (leaf (token "4c" SPINE-DATA 18))
                                                      (leaf (token "*v" SPINE-JOIN 19))))
                                        (leaf (token "*" NULL-INTERPRETATION 20))
                                        (leaf (token "*" NULL-INTERPRETATION 21))
                                        (leaf (token "==" MEASURE 22))
                                        (leaf (token "*-" SPINE-TERMINATOR 23)))))))
; branch->lot for spine 0
(check-expect (branch->lot (list (leaf (token"**kern" EXCLUSIVE-INTERPRETATION 0))
                                 (leaf (token "*clefG2" CLEF 1))
                                 (leaf (token "*k[]" KEY-SIG 2))
                                 (leaf (token "*a:" KEY-LABEL 3))
                                 (leaf (token "*M3/4" TIME-SIG 4))
                                 (parent (token "*^" SPINE-SPLIT 5)
                                         (list (leaf (token "*" NULL-INTERPRETATION 6))
                                               (leaf (token "*" NULL-INTERPRETATION 7))
                                               (leaf (token "4c" SPINE-DATA 8))
                                               (leaf (token "4c" SPINE-DATA 9))
                                               (leaf (token "4c" SPINE-DATA 10))
                                               (leaf (token "=2" MEASURE 11))
                                               (leaf (token "4c" SPINE-DATA 12))
                                               (leaf (token "4c" SPINE-DATA 13))
                                               (leaf (token "4c" SPINE-DATA 14))
                                               (leaf (token "=3" MEASURE 15))
                                               (leaf (token "4c" SPINE-DATA 16))
                                               (leaf (token "4c" SPINE-DATA 17))
                                               (leaf (token "4c" SPINE-DATA 18))
                                               (leaf (token "*" NULL-INTERPRETATION 19))
                                               (leaf (token "*" NULL-INTERPRETATION 20))
                                               (leaf (token "*v" SPINE-JOIN 21)))
                                         (list (leaf (token "*" NULL-INTERPRETATION 6))
                                               (leaf (token "*" NULL-INTERPRETATION 7))
                                               (leaf (token "4c" SPINE-DATA 8))
                                               (leaf (token "4c" SPINE-DATA 9))
                                               (leaf (token "4c" SPINE-DATA 10))
                                               (leaf (token "=2" MEASURE 11))
                                               (leaf (token "4c" SPINE-DATA 12))
                                               (leaf (token "4c" SPINE-DATA 13))
                                               (leaf (token "4c" SPINE-DATA 14))
                                               (leaf (token "=3" MEASURE 15))
                                               (leaf (token "4c" SPINE-DATA 16))
                                               (leaf (token "4c" SPINE-DATA 17))
                                               (leaf (token "4c" SPINE-DATA 18))
                                               (leaf (token "*" NULL-INTERPRETATION 19))
                                               (leaf (token "*" NULL-INTERPRETATION 20))
                                               (leaf (token "*v" SPINE-JOIN 21))))
                                 (leaf (token "==" MEASURE 22))
                                 (leaf (token "*-" SPINE-TERMINATOR 23))))
              (list (token"**kern" EXCLUSIVE-INTERPRETATION 0)
                    (token "*clefG2" CLEF 1)
                    (token "*k[]" KEY-SIG 2)
                    (token "*a:" KEY-LABEL 3)
                    (token "*M3/4" TIME-SIG 4)
                    (token "*^" SPINE-SPLIT 5)
                    (token "*" NULL-INTERPRETATION 6)
                    (token "*" NULL-INTERPRETATION 7)
                    (token "4c" SPINE-DATA 8)
                    (token "4c" SPINE-DATA 9)
                    (token "4c" SPINE-DATA 10)
                    (token "=2" MEASURE 11)
                    (token "4c" SPINE-DATA 12)
                    (token "4c" SPINE-DATA 13)
                    (token "4c" SPINE-DATA 14)
                    (token "=3" MEASURE 15)
                    (token "4c" SPINE-DATA 16)
                    (token "4c" SPINE-DATA 17)
                    (token "4c" SPINE-DATA 18)
                    (token "*" NULL-INTERPRETATION 19)
                    (token "*" NULL-INTERPRETATION 20)
                    (token "*v" SPINE-JOIN 21)
                    (token "*" NULL-INTERPRETATION 6)
                    (token "*" NULL-INTERPRETATION 7)
                    (token "4c" SPINE-DATA 8)
                    (token "4c" SPINE-DATA 9)
                    (token "4c" SPINE-DATA 10)
                    (token "=2" MEASURE 11)
                    (token "4c" SPINE-DATA 12)
                    (token "4c" SPINE-DATA 13)
                    (token "4c" SPINE-DATA 14)
                    (token "=3" MEASURE 15)
                    (token "4c" SPINE-DATA 16)
                    (token "4c" SPINE-DATA 17)
                    (token "4c" SPINE-DATA 18)
                    (token "*" NULL-INTERPRETATION 19)
                    (token "*" NULL-INTERPRETATION 20)
                    (token "*v" SPINE-JOIN 21)
                    (token "==" MEASURE 22)
                    (token "*-" SPINE-TERMINATOR 23)))
; branch->lot for spine 1
(check-expect (branch->lot (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                 (leaf (token "*clefG2" CLEF 1))
                                 (leaf (token "*k[]" KEY-SIG 2))
                                 (leaf (token "*a:" KEY-LABEL 3))
                                 (leaf (token "*M3/4" TIME-SIG 4))
                                 (leaf (token "*" NULL-INTERPRETATION 5))
                                 (parent (token "*^" SPINE-SPLIT 6)
                                         (list (leaf (token "*" NULL-INTERPRETATION 7))
                                               (leaf (token "4c" SPINE-DATA 8))
                                               (leaf (token "4c" SPINE-DATA 9))
                                               (leaf (token "4c" SPINE-DATA 10))
                                               (leaf (token "=2" MEASURE 11))
                                               (leaf (token "4c" SPINE-DATA 12))
                                               (leaf (token "4c" SPINE-DATA 13))
                                               (leaf (token "4c" SPINE-DATA 14))
                                               (leaf (token "=3" MEASURE 15))
                                               (leaf (token "4c" SPINE-DATA 16))
                                               (leaf (token "4c" SPINE-DATA 17))
                                               (leaf (token "4c" SPINE-DATA 18))
                                               (leaf (token "*" NULL-INTERPRETATION 19))
                                               (leaf (token "*v" SPINE-JOIN 20)))
                                         (list (leaf (token "*" NULL-INTERPRETATION 7))
                                               (leaf (token "4c" SPINE-DATA 8))
                                               (leaf (token "4c" SPINE-DATA 9))
                                               (leaf (token "4c" SPINE-DATA 10))
                                               (leaf (token "=2" MEASURE 11))
                                               (leaf (token "4c" SPINE-DATA 12))
                                               (leaf (token "4c" SPINE-DATA 13))
                                               (leaf (token "4c" SPINE-DATA 14))
                                               (leaf (token "=3" MEASURE 15))
                                               (leaf (token "4c" SPINE-DATA 16))
                                               (leaf (token "4c" SPINE-DATA 17))
                                               (leaf (token "4c" SPINE-DATA 18))
                                               (leaf (token "*" NULL-INTERPRETATION 19))
                                               (leaf (token "*v" SPINE-JOIN 20))))
                                 (leaf (token "*" NULL-INTERPRETATION 21))
                                 (leaf (token "==" MEASURE 22))
                                 (leaf (token "*-" SPINE-TERMINATOR 23))))
              (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                    (token "*clefG2" CLEF 1)
                    (token "*k[]" KEY-SIG 2)
                    (token "*a:" KEY-LABEL 3)
                    (token "*M3/4" TIME-SIG 4)
                    (token "*" NULL-INTERPRETATION 5)
                    (token "*^" SPINE-SPLIT 6)
                    (token "*" NULL-INTERPRETATION 7)
                    (token "4c" SPINE-DATA 8)
                    (token "4c" SPINE-DATA 9)
                    (token "4c" SPINE-DATA 10)
                    (token "=2" MEASURE 11)
                    (token "4c" SPINE-DATA 12)
                    (token "4c" SPINE-DATA 13)
                    (token "4c" SPINE-DATA 14)
                    (token "=3" MEASURE 15)
                    (token "4c" SPINE-DATA 16)
                    (token "4c" SPINE-DATA 17)
                    (token "4c" SPINE-DATA 18)
                    (token "*" NULL-INTERPRETATION 19)
                    (token "*v" SPINE-JOIN 20)
                    (token "*" NULL-INTERPRETATION 7)
                    (token "4c" SPINE-DATA 8)
                    (token "4c" SPINE-DATA 9)
                    (token "4c" SPINE-DATA 10)
                    (token "=2" MEASURE 11)
                    (token "4c" SPINE-DATA 12)
                    (token "4c" SPINE-DATA 13)
                    (token "4c" SPINE-DATA 14)
                    (token "=3" MEASURE 15)
                    (token "4c" SPINE-DATA 16)
                    (token "4c" SPINE-DATA 17)
                    (token "4c" SPINE-DATA 18)
                    (token "*" NULL-INTERPRETATION 19)
                    (token "*v" SPINE-JOIN 20)
                    (token "*" NULL-INTERPRETATION 21)
                    (token "==" MEASURE 22)
                    (token "*-" SPINE-TERMINATOR 23)))
; branch->lot for spine 2
(check-expect (branch->lot (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                 (leaf (token "*clefG2" CLEF 1))
                                 (leaf (token "*k[]" KEY-SIG 2))
                                 (leaf (token "*a:" KEY-LABEL 3))
                                 (leaf (token "*M3/4" TIME-SIG 4))
                                 (leaf (token "*" NULL-INTERPRETATION 5))
                                 (leaf (token "*" NULL-INTERPRETATION 6))
                                 (parent (token "*^" SPINE-SPLIT 7)
                                         (list (leaf (token "4c" SPINE-DATA 8))
                                               (leaf (token "4c" SPINE-DATA 9))
                                               (leaf (token "4c" SPINE-DATA 10))
                                               (leaf (token "=2" MEASURE 11))
                                               (leaf (token "4c" SPINE-DATA 12))
                                               (leaf (token "4c" SPINE-DATA 13))
                                               (leaf (token "4c" SPINE-DATA 14))
                                               (leaf (token "=3" MEASURE 15))
                                               (leaf (token "4c" SPINE-DATA 16))
                                               (leaf (token "4c" SPINE-DATA 17))
                                               (leaf (token "4c" SPINE-DATA 18))
                                               (leaf (token "*v" SPINE-JOIN 19)))
                                         (list (leaf (token "4c" SPINE-DATA 8))
                                               (leaf (token "4c" SPINE-DATA 9))
                                               (leaf (token "4c" SPINE-DATA 10))
                                               (leaf (token "=2" MEASURE 11))
                                               (leaf (token "4c" SPINE-DATA 12))
                                               (leaf (token "4c" SPINE-DATA 13))
                                               (leaf (token "4c" SPINE-DATA 14))
                                               (leaf (token "=3" MEASURE 15))
                                               (leaf (token "4c" SPINE-DATA 16))
                                               (leaf (token "4c" SPINE-DATA 17))
                                               (leaf (token "4c" SPINE-DATA 18))
                                               (leaf (token "*v" SPINE-JOIN 19))))
                                 (leaf (token "*" NULL-INTERPRETATION 20))
                                 (leaf (token "*" NULL-INTERPRETATION 21))
                                 (leaf (token "==" MEASURE 22))
                                 (leaf (token "*-" SPINE-TERMINATOR 23))))
              (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                    (token "*clefG2" CLEF 1)
                    (token "*k[]" KEY-SIG 2)
                    (token "*a:" KEY-LABEL 3)
                    (token "*M3/4" TIME-SIG 4)
                    (token "*" NULL-INTERPRETATION 5)
                    (token "*" NULL-INTERPRETATION 6)
                    (token "*^" SPINE-SPLIT 7)
                    (token "4c" SPINE-DATA 8)
                    (token "4c" SPINE-DATA 9)
                    (token "4c" SPINE-DATA 10)
                    (token "=2" MEASURE 11)
                    (token "4c" SPINE-DATA 12)
                    (token "4c" SPINE-DATA 13)
                    (token "4c" SPINE-DATA 14)
                    (token "=3" MEASURE 15)
                    (token "4c" SPINE-DATA 16)
                    (token "4c" SPINE-DATA 17)
                    (token "4c" SPINE-DATA 18)
                    (token "*v" SPINE-JOIN 19)
                    (token "4c" SPINE-DATA 8)
                    (token "4c" SPINE-DATA 9)
                    (token "4c" SPINE-DATA 10)
                    (token "=2" MEASURE 11)
                    (token "4c" SPINE-DATA 12)
                    (token "4c" SPINE-DATA 13)
                    (token "4c" SPINE-DATA 14)
                    (token "=3" MEASURE 15)
                    (token "4c" SPINE-DATA 16)
                    (token "4c" SPINE-DATA 17)
                    (token "4c" SPINE-DATA 18)
                    (token "*v" SPINE-JOIN 19)
                    (token "*" NULL-INTERPRETATION 20)
                    (token "*" NULL-INTERPRETATION 21)
                    (token "==" MEASURE 22)
                    (token "*-" SPINE-TERMINATOR 23)))

(test)
