#lang racket/base

(require "../../../../parser/data-definitions/data-definitions.rkt"
         "../../../../parser/functions/file.rkt"
         "../../../../parser/functions/spine-parser.rkt"
         "../../../../parser/data-structures/humdrum-graph/data-definitions/data-definitions.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hgraph-to-hfile.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hfile-to-hgraph.rkt"
         "../../../../parser/data-structures/linked-spine/functions/gspines-to-linked-spines.rkt"
         test-engine/racket-tests)

(check-expect (path->hfile "../../data/count/three-spines-one-split.krn")
              (hfile (list (record "**kern\t**kern\t**kern" TOKEN
                                   (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0)
                                         (token "**kern" EXCLUSIVE-INTERPRETATION 0 1)
                                         (token "**kern" EXCLUSIVE-INTERPRETATION 0 2))
                                   0)
                           (record "*clefG2\t*clefG2\t*clefG2" TOKEN
                                   (list (token "*clefG2" CLEF 1 0)
                                         (token "*clefG2" CLEF 1 1)
                                         (token "*clefG2" CLEF 1 2))
                                   1)
                           (record "*k[]\t*k[]\t*k[]" TOKEN
                                   (list (token "*k[]" KEY-SIG 2 0)
                                         (token "*k[]" KEY-SIG 2 1)
                                         (token "*k[]" KEY-SIG 2 2))
                                   2)
                           (record "*a:\t*a:\t*a:" TOKEN
                                   (list (token "*a:" KEY-LABEL 3 0)
                                         (token "*a:" KEY-LABEL 3 1)
                                         (token "*a:" KEY-LABEL 3 2))
                                   3)
                           (record "*M3/4\t*M3/4\t*M3/4" TOKEN
                                   (list (token "*M3/4" TIME-SIG 4 0)
                                         (token "*M3/4" TIME-SIG 4 1)
                                         (token "*M3/4" TIME-SIG 4 2))
                                   4)
                           (record "*^\t*\t*" TOKEN
                                   (list (token "*^" SPINE-SPLIT 5 0)
                                         (token "*" NULL-INTERPRETATION 5 1)
                                         (token "*" NULL-INTERPRETATION 5 2))
                                   5)
                           (record "*\t*\t*^\t*" TOKEN
                                   (list (token "*" NULL-INTERPRETATION 6 0)
                                         (token "*" NULL-INTERPRETATION 6 1)
                                         (token "*^" SPINE-SPLIT 6 2)
                                         (token "*" NULL-INTERPRETATION 6 3))
                                   6)
                           (record "*\t*\t*\t*\t*^" TOKEN
                                   (list (token "*" NULL-INTERPRETATION 7 0)
                                         (token "*" NULL-INTERPRETATION 7 1)
                                         (token "*" NULL-INTERPRETATION 7 2)
                                         (token "*" NULL-INTERPRETATION 7 3)
                                         (token "*^" SPINE-SPLIT 7 4))
                                   7)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 8 0)
                                         (token "4c" SPINE-DATA 8 1)
                                         (token "4c" SPINE-DATA 8 2)
                                         (token "4c" SPINE-DATA 8 3)
                                         (token "4c" SPINE-DATA 8 4)
                                         (token "4c" SPINE-DATA 8 5))
                                   8)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 9 0)
                                         (token "4c" SPINE-DATA 9 1)
                                         (token "4c" SPINE-DATA 9 2)
                                         (token "4c" SPINE-DATA 9 3)
                                         (token "4c" SPINE-DATA 9 4)
                                         (token "4c" SPINE-DATA 9 5))
                                   9)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 10 0)
                                         (token "4c" SPINE-DATA 10 1)
                                         (token "4c" SPINE-DATA 10 2)
                                         (token "4c" SPINE-DATA 10 3)
                                         (token "4c" SPINE-DATA 10 4)
                                         (token "4c" SPINE-DATA 10 5))
                                   10)
                           (record "=2\t=2\t=2\t=2\t=2\t=2" TOKEN
                                   (list (token "=2" MEASURE 11 0)
                                         (token "=2" MEASURE 11 1)
                                         (token "=2" MEASURE 11 2)
                                         (token "=2" MEASURE 11 3)
                                         (token "=2" MEASURE 11 4)
                                         (token "=2" MEASURE 11 5))
                                   11)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 12 0)
                                         (token "4c" SPINE-DATA 12 1)
                                         (token "4c" SPINE-DATA 12 2)
                                         (token "4c" SPINE-DATA 12 3)
                                         (token "4c" SPINE-DATA 12 4)
                                         (token "4c" SPINE-DATA 12 5))
                                   12)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 13 0)
                                         (token "4c" SPINE-DATA 13 1)
                                         (token "4c" SPINE-DATA 13 2)
                                         (token "4c" SPINE-DATA 13 3)
                                         (token "4c" SPINE-DATA 13 4)
                                         (token "4c" SPINE-DATA 13 5))
                                   13)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 14 0)
                                         (token "4c" SPINE-DATA 14 1)
                                         (token "4c" SPINE-DATA 14 2)
                                         (token "4c" SPINE-DATA 14 3)
                                         (token "4c" SPINE-DATA 14 4)
                                         (token "4c" SPINE-DATA 14 5))
                                   14)
                           (record "=3\t=3\t=3\t=3\t=3\t=3" TOKEN
                                   (list (token "=3" MEASURE 15 0)
                                         (token "=3" MEASURE 15 1)
                                         (token "=3" MEASURE 15 2)
                                         (token "=3" MEASURE 15 3)
                                         (token "=3" MEASURE 15 4)
                                         (token "=3" MEASURE 15 5))
                                   15)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 16 0)
                                         (token "4c" SPINE-DATA 16 1)
                                         (token "4c" SPINE-DATA 16 2)
                                         (token "4c" SPINE-DATA 16 3)
                                         (token "4c" SPINE-DATA 16 4)
                                         (token "4c" SPINE-DATA 16 5))
                                   16)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 17 0)
                                         (token "4c" SPINE-DATA 17 1)
                                         (token "4c" SPINE-DATA 17 2)
                                         (token "4c" SPINE-DATA 17 3)
                                         (token "4c" SPINE-DATA 17 4)
                                         (token "4c" SPINE-DATA 17 5))
                                   17)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 18 0)
                                         (token "4c" SPINE-DATA 18 1)
                                         (token "4c" SPINE-DATA 18 2)
                                         (token "4c" SPINE-DATA 18 3)
                                         (token "4c" SPINE-DATA 18 4)
                                         (token "4c" SPINE-DATA 18 5))
                                   18)
                           (record "*\t*\t*\t*\t*v\t*v" TOKEN
                                   (list (token "*" NULL-INTERPRETATION 19 0)
                                         (token "*" NULL-INTERPRETATION 19 1)
                                         (token "*" NULL-INTERPRETATION 19 2)
                                         (token "*" NULL-INTERPRETATION 19 3)
                                         (token "*v" SPINE-JOIN 19 4)
                                         (token "*v" SPINE-JOIN 19 5))
                                   19)
                           (record "*\t*\t*v\t*v\t*" TOKEN
                                   (list (token "*" NULL-INTERPRETATION 20 0)
                                         (token "*" NULL-INTERPRETATION 20 1)
                                         (token "*v" SPINE-JOIN 20 2)
                                         (token "*v" SPINE-JOIN 20 3)
                                         (token "*" NULL-INTERPRETATION 20 4))
                                   20)
                           (record "*v\t*v\t*\t*" TOKEN
                                   (list (token "*v" SPINE-JOIN 21 0)
                                         (token "*v" SPINE-JOIN 21 1)
                                         (token "*" NULL-INTERPRETATION 21 2)
                                         (token "*" NULL-INTERPRETATION 21 3))
                                   21)
                           (record "==\t==\t==" TOKEN
                                   (list (token "==" MEASURE 22 0)
                                         (token "==" MEASURE 22 1)
                                         (token "==" MEASURE 22 2))
                                   22)
                           (record "*-\t*-\t*-" TOKEN
                                   (list (token "*-" SPINE-TERMINATOR 23 0)
                                         (token "*-" SPINE-TERMINATOR 23 1)
                                         (token "*-" SPINE-TERMINATOR 23 2))
                                   23))))
(check-expect (spine-parser (path->hfile "../../data/count/three-spines-one-split.krn"))
              (list (global-spine KERN
                                  (list (list (token"**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                        (list (token "*clefG2" CLEF 1 0))
                                        (list (token "*k[]" KEY-SIG 2 0))
                                        (list (token "*a:" KEY-LABEL 3 0))
                                        (list (token "*M3/4" TIME-SIG 4 0))
                                        (list (token "*^" SPINE-SPLIT 5 0))
                                        (list (token "*" NULL-INTERPRETATION 6 0)
                                              (token "*" NULL-INTERPRETATION 6 1))
                                        (list (token "*" NULL-INTERPRETATION 7 0)
                                              (token "*" NULL-INTERPRETATION 7 1))
                                        (list (token "4c" SPINE-DATA 8 0)
                                              (token "4c" SPINE-DATA 8 1))
                                        (list (token "4c" SPINE-DATA 9 0)
                                              (token "4c" SPINE-DATA 9 1))
                                        (list (token "4c" SPINE-DATA 10 0)
                                              (token "4c" SPINE-DATA 10 1))
                                        (list (token "=2" MEASURE 11 0)
                                              (token "=2" MEASURE 11 1))
                                        (list (token "4c" SPINE-DATA 12 0)
                                              (token "4c" SPINE-DATA 12 1))
                                        (list (token "4c" SPINE-DATA 13 0)
                                              (token "4c" SPINE-DATA 13 1))
                                        (list (token "4c" SPINE-DATA 14 0)
                                              (token "4c" SPINE-DATA 14 1))
                                        (list (token "=3" MEASURE 15 0)
                                              (token "=3" MEASURE 15 1))
                                        (list (token "4c" SPINE-DATA 16 0)
                                              (token "4c" SPINE-DATA 16 1))
                                        (list (token "4c" SPINE-DATA 17 0)
                                              (token "4c" SPINE-DATA 17 1))
                                        (list (token "4c" SPINE-DATA 18 0)
                                              (token "4c" SPINE-DATA 18 1))
                                        (list (token "*" NULL-INTERPRETATION 19 0)
                                              (token "*" NULL-INTERPRETATION 19 1))
                                        (list (token "*" NULL-INTERPRETATION 20 0)
                                              (token "*" NULL-INTERPRETATION 20 1))
                                        (list (token "*v" SPINE-JOIN 21 0)
                                              (token "*v" SPINE-JOIN 21 1))
                                        (list (token "==" MEASURE 22 0))
                                        (list (token "*-" SPINE-TERMINATOR 23 0)))
                                  0)
                    (global-spine KERN
                                  (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 1))
                                        (list (token "*clefG2" CLEF 1 1))
                                        (list (token "*k[]" KEY-SIG 2 1))
                                        (list (token "*a:" KEY-LABEL 3 1))
                                        (list (token "*M3/4" TIME-SIG 4 1))
                                        (list (token "*" NULL-INTERPRETATION 5 1))
                                        (list (token "*^" SPINE-SPLIT 6 2))
                                        (list (token "*" NULL-INTERPRETATION 7 2)
                                              (token "*" NULL-INTERPRETATION 7 3))
                                        (list (token "4c" SPINE-DATA 8 2)
                                              (token "4c" SPINE-DATA 8 3))
                                        (list (token "4c" SPINE-DATA 9 2)
                                              (token "4c" SPINE-DATA 9 3))
                                        (list (token "4c" SPINE-DATA 10 2)
                                              (token "4c" SPINE-DATA 10 3))
                                        (list (token "=2" MEASURE 11 2)
                                              (token "=2" MEASURE 11 3))
                                        (list (token "4c" SPINE-DATA 12 2)
                                              (token "4c" SPINE-DATA 12 3))
                                        (list (token "4c" SPINE-DATA 13 2)
                                              (token "4c" SPINE-DATA 13 3))
                                        (list (token "4c" SPINE-DATA 14 2)
                                              (token "4c" SPINE-DATA 14 3))
                                        (list (token "=3" MEASURE 15 2)
                                              (token "=3" MEASURE 15 3))
                                        (list (token "4c" SPINE-DATA 16 2)
                                              (token "4c" SPINE-DATA 16 3))
                                        (list (token "4c" SPINE-DATA 17 2)
                                              (token "4c" SPINE-DATA 17 3))
                                        (list (token "4c" SPINE-DATA 18 2)
                                              (token "4c" SPINE-DATA 18 3))
                                        (list (token "*" NULL-INTERPRETATION 19 2)
                                              (token "*" NULL-INTERPRETATION 19 3))
                                        (list (token "*v" SPINE-JOIN 20 2)
                                              (token "*v" SPINE-JOIN 20 3))
                                        (list (token "*" NULL-INTERPRETATION 21 2))
                                        (list (token "==" MEASURE 22 1))
                                        (list (token "*-" SPINE-TERMINATOR 23 1)))
                                  1)
                    (global-spine KERN
                                  (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 2))
                                        (list (token "*clefG2" CLEF 1 2))
                                        (list (token "*k[]" KEY-SIG 2 2))
                                        (list (token "*a:" KEY-LABEL 3 2))
                                        (list (token "*M3/4" TIME-SIG 4 2))
                                        (list (token "*" NULL-INTERPRETATION 5 2))
                                        (list (token "*" NULL-INTERPRETATION 6 3))
                                        (list (token "*^" SPINE-SPLIT 7 4))
                                        (list (token "4c" SPINE-DATA 8 4)
                                              (token "4c" SPINE-DATA 8 5))
                                        (list (token "4c" SPINE-DATA 9 4)
                                              (token "4c" SPINE-DATA 9 5))
                                        (list (token "4c" SPINE-DATA 10 4)
                                              (token "4c" SPINE-DATA 10 5))
                                        (list (token "=2" MEASURE 11 4)
                                              (token "=2" MEASURE 11 5))
                                        (list (token "4c" SPINE-DATA 12 4)
                                              (token "4c" SPINE-DATA 12 5))
                                        (list (token "4c" SPINE-DATA 13 4)
                                              (token "4c" SPINE-DATA 13 5))
                                        (list (token "4c" SPINE-DATA 14 4)
                                              (token "4c" SPINE-DATA 14 5))
                                        (list (token "=3" MEASURE 15 4)
                                              (token "=3" MEASURE 15 5))
                                        (list (token "4c" SPINE-DATA 16 4)
                                              (token "4c" SPINE-DATA 16 5))
                                        (list (token "4c" SPINE-DATA 17 4)
                                              (token "4c" SPINE-DATA 17 5))
                                        (list (token "4c" SPINE-DATA 18 4)
                                              (token "4c" SPINE-DATA 18 5))
                                        (list (token "*v" SPINE-JOIN 19 4)
                                              (token "*v" SPINE-JOIN 19 5))
                                        (list (token "*" NULL-INTERPRETATION 20 4))
                                        (list (token "*" NULL-INTERPRETATION 21 3))
                                        (list (token "==" MEASURE 22 2))
                                        (list (token "*-" SPINE-TERMINATOR 23 2)))
                                  2)))
(check-expect (hgraph->hfile
               (hgraph (root (list (list (leaf (token"**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                         (leaf (token "*clefG2" CLEF 1 0))
                                         (leaf (token "*k[]" KEY-SIG 2 0))
                                         (leaf (token "*a:" KEY-LABEL 3 0))
                                         (leaf (token "*M3/4" TIME-SIG 4 0))
                                         (parent (token "*^" SPINE-SPLIT 5 0)
                                                 (list (leaf (token "*" NULL-INTERPRETATION 6 0))
                                                       (leaf (token "*" NULL-INTERPRETATION 7 0))
                                                       (leaf (token "4c" SPINE-DATA 8 0))
                                                       (leaf (token "4c" SPINE-DATA 9 0))
                                                       (leaf (token "4c" SPINE-DATA 10 0))
                                                       (leaf (token "=2" MEASURE 11 0))
                                                       (leaf (token "4c" SPINE-DATA 12 0))
                                                       (leaf (token "4c" SPINE-DATA 13 0))
                                                       (leaf (token "4c" SPINE-DATA 14 0))
                                                       (leaf (token "=3" MEASURE 15 0))
                                                       (leaf (token "4c" SPINE-DATA 16 0))
                                                       (leaf (token "4c" SPINE-DATA 17 0))
                                                       (leaf (token "4c" SPINE-DATA 18 0))
                                                       (leaf (token "*" NULL-INTERPRETATION 19 0))
                                                       (leaf (token "*" NULL-INTERPRETATION 20 0))
                                                       (leaf (token "*v" SPINE-JOIN 21 0)))
                                                 (list (leaf (token "*" NULL-INTERPRETATION 6 1))
                                                       (leaf (token "*" NULL-INTERPRETATION 7 1))
                                                       (leaf (token "4c" SPINE-DATA 8 1))
                                                       (leaf (token "4c" SPINE-DATA 9 1))
                                                       (leaf (token "4c" SPINE-DATA 10 1))
                                                       (leaf (token "=2" MEASURE 11 1))
                                                       (leaf (token "4c" SPINE-DATA 12 1))
                                                       (leaf (token "4c" SPINE-DATA 13 1))
                                                       (leaf (token "4c" SPINE-DATA 14 1))
                                                       (leaf (token "=3" MEASURE 15 1))
                                                       (leaf (token "4c" SPINE-DATA 16 1))
                                                       (leaf (token "4c" SPINE-DATA 17 1))
                                                       (leaf (token "4c" SPINE-DATA 18 1))
                                                       (leaf (token "*" NULL-INTERPRETATION 19 1))
                                                       (leaf (token "*" NULL-INTERPRETATION 20 1))
                                                       (leaf (token "*v" SPINE-JOIN 21 1))))
                                         (leaf (token "==" MEASURE 22 0))
                                         (leaf (token "*-" SPINE-TERMINATOR 23 0)))
                                   (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 1))
                                         (leaf (token "*clefG2" CLEF 1 1))
                                         (leaf (token "*k[]" KEY-SIG 2 1))
                                         (leaf (token "*a:" KEY-LABEL 3 1))
                                         (leaf (token "*M3/4" TIME-SIG 4 1))
                                         (leaf (token "*" NULL-INTERPRETATION 5 1))
                                         (parent (token "*^" SPINE-SPLIT 6 2)
                                                 (list (leaf (token "*" NULL-INTERPRETATION 7 2))
                                                       (leaf (token "4c" SPINE-DATA 8 2))
                                                       (leaf (token "4c" SPINE-DATA 9 2))
                                                       (leaf (token "4c" SPINE-DATA 10 2))
                                                       (leaf (token "=2" MEASURE 11 2))
                                                       (leaf (token "4c" SPINE-DATA 12 2))
                                                       (leaf (token "4c" SPINE-DATA 13 2))
                                                       (leaf (token "4c" SPINE-DATA 14 2))
                                                       (leaf (token "=3" MEASURE 15 2))
                                                       (leaf (token "4c" SPINE-DATA 16 2))
                                                       (leaf (token "4c" SPINE-DATA 17 2))
                                                       (leaf (token "4c" SPINE-DATA 18 2))
                                                       (leaf (token "*" NULL-INTERPRETATION 19 2))
                                                       (leaf (token "*v" SPINE-JOIN 20 2)))
                                                 (list (leaf (token "*" NULL-INTERPRETATION 7 3))
                                                       (leaf (token "4c" SPINE-DATA 8 3))
                                                       (leaf (token "4c" SPINE-DATA 9 3))
                                                       (leaf (token "4c" SPINE-DATA 10 3))
                                                       (leaf (token "=2" MEASURE 11 3))
                                                       (leaf (token "4c" SPINE-DATA 12 3))
                                                       (leaf (token "4c" SPINE-DATA 13 3))
                                                       (leaf (token "4c" SPINE-DATA 14 3))
                                                       (leaf (token "=3" MEASURE 15 3))
                                                       (leaf (token "4c" SPINE-DATA 16 3))
                                                       (leaf (token "4c" SPINE-DATA 17 3))
                                                       (leaf (token "4c" SPINE-DATA 18 3))
                                                       (leaf (token "*" NULL-INTERPRETATION 19 3))
                                                       (leaf (token "*v" SPINE-JOIN 20 3))))
                                         (leaf (token "*" NULL-INTERPRETATION 21 2))
                                         (leaf (token "==" MEASURE 22 1))
                                         (leaf (token "*-" SPINE-TERMINATOR 23 1)))
                                   (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 2))
                                         (leaf (token "*clefG2" CLEF 1 2))
                                         (leaf (token "*k[]" KEY-SIG 2 2))
                                         (leaf (token "*a:" KEY-LABEL 3 2))
                                         (leaf (token "*M3/4" TIME-SIG 4 2))
                                         (leaf (token "*" NULL-INTERPRETATION 5 2))
                                         (leaf (token "*" NULL-INTERPRETATION 6 3))
                                         (parent (token "*^" SPINE-SPLIT 7 4)
                                                 (list (leaf (token "4c" SPINE-DATA 8 4))
                                                       (leaf (token "4c" SPINE-DATA 9 4))
                                                       (leaf (token "4c" SPINE-DATA 10 4))
                                                       (leaf (token "=2" MEASURE 11 4))
                                                       (leaf (token "4c" SPINE-DATA 12 4))
                                                       (leaf (token "4c" SPINE-DATA 13 4))
                                                       (leaf (token "4c" SPINE-DATA 14 4))
                                                       (leaf (token "=3" MEASURE 15 4))
                                                       (leaf (token "4c" SPINE-DATA 16 4))
                                                       (leaf (token "4c" SPINE-DATA 17 4))
                                                       (leaf (token "4c" SPINE-DATA 18 4))
                                                       (leaf (token "*v" SPINE-JOIN 19 4)))
                                                 (list (leaf (token "4c" SPINE-DATA 8 5))
                                                       (leaf (token "4c" SPINE-DATA 9 5))
                                                       (leaf (token "4c" SPINE-DATA 10 5))
                                                       (leaf (token "=2" MEASURE 11 5))
                                                       (leaf (token "4c" SPINE-DATA 12 5))
                                                       (leaf (token "4c" SPINE-DATA 13 5))
                                                       (leaf (token "4c" SPINE-DATA 14 5))
                                                       (leaf (token "=3" MEASURE 15 5))
                                                       (leaf (token "4c" SPINE-DATA 16 5))
                                                       (leaf (token "4c" SPINE-DATA 17 5))
                                                       (leaf (token "4c" SPINE-DATA 18 5))
                                                       (leaf (token "*v" SPINE-JOIN 19 5))))
                                         (leaf (token "*" NULL-INTERPRETATION 20 4))
                                         (leaf (token "*" NULL-INTERPRETATION 21 3))
                                         (leaf (token "==" MEASURE 22 2))
                                         (leaf (token "*-" SPINE-TERMINATOR 23 2)))))))
              (path->hfile "../../data/count/three-spines-one-split.krn"))
(check-expect (lolot->lor (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0)
                                      (token "**kern" EXCLUSIVE-INTERPRETATION 0 1)
                                      (token "**kern" EXCLUSIVE-INTERPRETATION 0 2))
                                (list (token "*clefG2" CLEF 1 0)
                                      (token "*clefG2" CLEF 1 1)
                                      (token "*clefG2" CLEF 1 2))
                                (list (token "*k[]" KEY-SIG 2 0)
                                      (token "*k[]" KEY-SIG 2 1)
                                      (token "*k[]" KEY-SIG 2 2))
                                (list (token "*a:" KEY-LABEL 3 0)
                                      (token "*a:" KEY-LABEL 3 1)
                                      (token "*a:" KEY-LABEL 3 2))
                                (list (token "*M3/4" TIME-SIG 4 0)
                                      (token "*M3/4" TIME-SIG 4 1)
                                      (token "*M3/4" TIME-SIG 4 2))
                                (list (token "*^" SPINE-SPLIT 5 0)
                                      (token "*" NULL-INTERPRETATION 5 1)
                                      (token "*" NULL-INTERPRETATION 5 2))
                                (list (token "*" NULL-INTERPRETATION 6 0)
                                      (token "*" NULL-INTERPRETATION 6 1)
                                      (token "*^" SPINE-SPLIT 6 2)
                                      (token "*" NULL-INTERPRETATION 6 3))
                                (list (token "*" NULL-INTERPRETATION 7 0)
                                      (token "*" NULL-INTERPRETATION 7 1)
                                      (token "*" NULL-INTERPRETATION 7 2)
                                      (token "*" NULL-INTERPRETATION 7 3)
                                      (token "*^" SPINE-SPLIT 7 4))
                                (list (token "4c" SPINE-DATA 8 0)
                                      (token "4c" SPINE-DATA 8 1)
                                      (token "4c" SPINE-DATA 8 2)
                                      (token "4c" SPINE-DATA 8 3)
                                      (token "4c" SPINE-DATA 8 4)
                                      (token "4c" SPINE-DATA 8 5))
                                (list (token "4c" SPINE-DATA 9 0)
                                      (token "4c" SPINE-DATA 9 1)
                                      (token "4c" SPINE-DATA 9 2)
                                      (token "4c" SPINE-DATA 9 3)
                                      (token "4c" SPINE-DATA 9 4)
                                      (token "4c" SPINE-DATA 9 5))
                                (list (token "4c" SPINE-DATA 10 0)
                                      (token "4c" SPINE-DATA 10 1)
                                      (token "4c" SPINE-DATA 10 2)
                                      (token "4c" SPINE-DATA 10 3)
                                      (token "4c" SPINE-DATA 10 4)
                                      (token "4c" SPINE-DATA 10 5))
                                (list (token "=2" MEASURE 11 0)
                                      (token "=2" MEASURE 11 1)
                                      (token "=2" MEASURE 11 2)
                                      (token "=2" MEASURE 11 3)
                                      (token "=2" MEASURE 11 4)
                                      (token "=2" MEASURE 11 5))
                                (list (token "4c" SPINE-DATA 12 0)
                                      (token "4c" SPINE-DATA 12 1)
                                      (token "4c" SPINE-DATA 12 2)
                                      (token "4c" SPINE-DATA 12 3)
                                      (token "4c" SPINE-DATA 12 4)
                                      (token "4c" SPINE-DATA 12 5))
                                (list (token "4c" SPINE-DATA 13 0)
                                      (token "4c" SPINE-DATA 13 1)
                                      (token "4c" SPINE-DATA 13 2)
                                      (token "4c" SPINE-DATA 13 3)
                                      (token "4c" SPINE-DATA 13 4)
                                      (token "4c" SPINE-DATA 13 5))
                                (list (token "4c" SPINE-DATA 14 0)
                                      (token "4c" SPINE-DATA 14 1)
                                      (token "4c" SPINE-DATA 14 2)
                                      (token "4c" SPINE-DATA 14 3)
                                      (token "4c" SPINE-DATA 14 4)
                                      (token "4c" SPINE-DATA 14 5))
                                (list (token "=3" MEASURE 15 0)
                                      (token "=3" MEASURE 15 1)
                                      (token "=3" MEASURE 15 2)
                                      (token "=3" MEASURE 15 3)
                                      (token "=3" MEASURE 15 4)
                                      (token "=3" MEASURE 15 5))
                                (list (token "4c" SPINE-DATA 16 0)
                                      (token "4c" SPINE-DATA 16 1)
                                      (token "4c" SPINE-DATA 16 2)
                                      (token "4c" SPINE-DATA 16 3)
                                      (token "4c" SPINE-DATA 16 4)
                                      (token "4c" SPINE-DATA 16 5))
                                (list (token "4c" SPINE-DATA 17 0)
                                      (token "4c" SPINE-DATA 17 1)
                                      (token "4c" SPINE-DATA 17 2)
                                      (token "4c" SPINE-DATA 17 3)
                                      (token "4c" SPINE-DATA 17 4)
                                      (token "4c" SPINE-DATA 17 5))
                                (list (token "4c" SPINE-DATA 18 0)
                                      (token "4c" SPINE-DATA 18 1)
                                      (token "4c" SPINE-DATA 18 2)
                                      (token "4c" SPINE-DATA 18 3)
                                      (token "4c" SPINE-DATA 18 4)
                                      (token "4c" SPINE-DATA 18 5))
                                (list (token "*" NULL-INTERPRETATION 19 0)
                                      (token "*" NULL-INTERPRETATION 19 1)
                                      (token "*" NULL-INTERPRETATION 19 2)
                                      (token "*" NULL-INTERPRETATION 19 3)
                                      (token "*v" SPINE-JOIN 19 4)
                                      (token "*v" SPINE-JOIN 19 5))
                                (list (token "*" NULL-INTERPRETATION 20 0)
                                      (token "*" NULL-INTERPRETATION 20 1)
                                      (token "*v" SPINE-JOIN 20 2)
                                      (token "*v" SPINE-JOIN 20 3)
                                      (token "*" NULL-INTERPRETATION 20 4))
                                (list (token "*v" SPINE-JOIN 21 0)
                                      (token "*v" SPINE-JOIN 21 1)
                                      (token "*" NULL-INTERPRETATION 21 2)
                                      (token "*" NULL-INTERPRETATION 21 3))
                                (list (token "==" MEASURE 22 0)
                                      (token "==" MEASURE 22 1)
                                      (token "==" MEASURE 22 2))
                                (list (token "*-" SPINE-TERMINATOR 23 0)
                                      (token "*-" SPINE-TERMINATOR 23 1)
                                      (token "*-" SPINE-TERMINATOR 23 2))))
              (list (record "**kern\t**kern\t**kern" TOKEN
                            (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0)
                                  (token "**kern" EXCLUSIVE-INTERPRETATION 0 1)
                                  (token "**kern" EXCLUSIVE-INTERPRETATION 0 2))
                            0)
                    (record "*clefG2\t*clefG2\t*clefG2" TOKEN
                            (list (token "*clefG2" CLEF 1 0)
                                  (token "*clefG2" CLEF 1 1)
                                  (token "*clefG2" CLEF 1 2))
                            1)
                    (record "*k[]\t*k[]\t*k[]" TOKEN
                            (list (token "*k[]" KEY-SIG 2 0)
                                  (token "*k[]" KEY-SIG 2 1)
                                  (token "*k[]" KEY-SIG 2 2))
                            2)
                    (record "*a:\t*a:\t*a:" TOKEN
                            (list (token "*a:" KEY-LABEL 3 0)
                                  (token "*a:" KEY-LABEL 3 1)
                                  (token "*a:" KEY-LABEL 3 2))
                            3)
                    (record "*M3/4\t*M3/4\t*M3/4" TOKEN
                            (list (token "*M3/4" TIME-SIG 4 0)
                                  (token "*M3/4" TIME-SIG 4 1)
                                  (token "*M3/4" TIME-SIG 4 2))
                            4)
                    (record "*^\t*\t*" TOKEN
                            (list (token "*^" SPINE-SPLIT 5 0)
                                  (token "*" NULL-INTERPRETATION 5 1)
                                  (token "*" NULL-INTERPRETATION 5 2))
                            5)
                    (record "*\t*\t*^\t*" TOKEN
                            (list (token "*" NULL-INTERPRETATION 6 0)
                                  (token "*" NULL-INTERPRETATION 6 1)
                                  (token "*^" SPINE-SPLIT 6 2)
                                  (token "*" NULL-INTERPRETATION 6 3))
                            6)
                    (record "*\t*\t*\t*\t*^" TOKEN
                            (list (token "*" NULL-INTERPRETATION 7 0)
                                  (token "*" NULL-INTERPRETATION 7 1)
                                  (token "*" NULL-INTERPRETATION 7 2)
                                  (token "*" NULL-INTERPRETATION 7 3)
                                  (token "*^" SPINE-SPLIT 7 4))
                            7)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 8 0)
                                  (token "4c" SPINE-DATA 8 1)
                                  (token "4c" SPINE-DATA 8 2)
                                  (token "4c" SPINE-DATA 8 3)
                                  (token "4c" SPINE-DATA 8 4)
                                  (token "4c" SPINE-DATA 8 5))
                            8)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 9 0)
                                  (token "4c" SPINE-DATA 9 1)
                                  (token "4c" SPINE-DATA 9 2)
                                  (token "4c" SPINE-DATA 9 3)
                                  (token "4c" SPINE-DATA 9 4)
                                  (token "4c" SPINE-DATA 9 5))
                            9)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 10 0)
                                  (token "4c" SPINE-DATA 10 1)
                                  (token "4c" SPINE-DATA 10 2)
                                  (token "4c" SPINE-DATA 10 3)
                                  (token "4c" SPINE-DATA 10 4)
                                  (token "4c" SPINE-DATA 10 5))
                            10)
                    (record "=2\t=2\t=2\t=2\t=2\t=2" TOKEN
                            (list (token "=2" MEASURE 11 0)
                                  (token "=2" MEASURE 11 1)
                                  (token "=2" MEASURE 11 2)
                                  (token "=2" MEASURE 11 3)
                                  (token "=2" MEASURE 11 4)
                                  (token "=2" MEASURE 11 5))
                            11)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 12 0)
                                  (token "4c" SPINE-DATA 12 1)
                                  (token "4c" SPINE-DATA 12 2)
                                  (token "4c" SPINE-DATA 12 3)
                                  (token "4c" SPINE-DATA 12 4)
                                  (token "4c" SPINE-DATA 12 5))
                            12)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 13 0)
                                  (token "4c" SPINE-DATA 13 1)
                                  (token "4c" SPINE-DATA 13 2)
                                  (token "4c" SPINE-DATA 13 3)
                                  (token "4c" SPINE-DATA 13 4)
                                  (token "4c" SPINE-DATA 13 5))
                            13)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 14 0)
                                  (token "4c" SPINE-DATA 14 1)
                                  (token "4c" SPINE-DATA 14 2)
                                  (token "4c" SPINE-DATA 14 3)
                                  (token "4c" SPINE-DATA 14 4)
                                  (token "4c" SPINE-DATA 14 5))
                            14)
                    (record "=3\t=3\t=3\t=3\t=3\t=3" TOKEN
                            (list (token "=3" MEASURE 15 0)
                                  (token "=3" MEASURE 15 1)
                                  (token "=3" MEASURE 15 2)
                                  (token "=3" MEASURE 15 3)
                                  (token "=3" MEASURE 15 4)
                                  (token "=3" MEASURE 15 5))
                            15)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 16 0)
                                  (token "4c" SPINE-DATA 16 1)
                                  (token "4c" SPINE-DATA 16 2)
                                  (token "4c" SPINE-DATA 16 3)
                                  (token "4c" SPINE-DATA 16 4)
                                  (token "4c" SPINE-DATA 16 5))
                            16)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 17 0)
                                  (token "4c" SPINE-DATA 17 1)
                                  (token "4c" SPINE-DATA 17 2)
                                  (token "4c" SPINE-DATA 17 3)
                                  (token "4c" SPINE-DATA 17 4)
                                  (token "4c" SPINE-DATA 17 5))
                            17)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 18 0)
                                  (token "4c" SPINE-DATA 18 1)
                                  (token "4c" SPINE-DATA 18 2)
                                  (token "4c" SPINE-DATA 18 3)
                                  (token "4c" SPINE-DATA 18 4)
                                  (token "4c" SPINE-DATA 18 5))
                            18)
                    (record "*\t*\t*\t*\t*v\t*v" TOKEN
                            (list (token "*" NULL-INTERPRETATION 19 0)
                                  (token "*" NULL-INTERPRETATION 19 1)
                                  (token "*" NULL-INTERPRETATION 19 2)
                                  (token "*" NULL-INTERPRETATION 19 3)
                                  (token "*v" SPINE-JOIN 19 4)
                                  (token "*v" SPINE-JOIN 19 5))
                            19)
                    (record "*\t*\t*v\t*v\t*" TOKEN
                            (list (token "*" NULL-INTERPRETATION 20 0)
                                  (token "*" NULL-INTERPRETATION 20 1)
                                  (token "*v" SPINE-JOIN 20 2)
                                  (token "*v" SPINE-JOIN 20 3)
                                  (token "*" NULL-INTERPRETATION 20 4))
                            20)
                    (record "*v\t*v\t*\t*" TOKEN
                            (list (token "*v" SPINE-JOIN 21 0)
                                  (token "*v" SPINE-JOIN 21 1)
                                  (token "*" NULL-INTERPRETATION 21 2)
                                  (token "*" NULL-INTERPRETATION 21 3))
                            21)
                    (record "==\t==\t==" TOKEN
                            (list (token "==" MEASURE 22 0)
                                  (token "==" MEASURE 22 1)
                                  (token "==" MEASURE 22 2))
                            22)
                    (record "*-\t*-\t*-" TOKEN
                            (list (token "*-" SPINE-TERMINATOR 23 0)
                                  (token "*-" SPINE-TERMINATOR 23 1)
                                  (token "*-" SPINE-TERMINATOR 23 2))
                            23)))
(check-expect (hgraph->lolot
               (hgraph (root (list (list (leaf (token"**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                         (leaf (token "*clefG2" CLEF 1 0))
                                         (leaf (token "*k[]" KEY-SIG 2 0))
                                         (leaf (token "*a:" KEY-LABEL 3 0))
                                         (leaf (token "*M3/4" TIME-SIG 4 0))
                                         (parent (token "*^" SPINE-SPLIT 5 0)
                                                 (list (leaf (token "*" NULL-INTERPRETATION 6 0))
                                                       (leaf (token "*" NULL-INTERPRETATION 7 0))
                                                       (leaf (token "4c" SPINE-DATA 8 0))
                                                       (leaf (token "4c" SPINE-DATA 9 0))
                                                       (leaf (token "4c" SPINE-DATA 10 0))
                                                       (leaf (token "=2" MEASURE 11 0))
                                                       (leaf (token "4c" SPINE-DATA 12 0))
                                                       (leaf (token "4c" SPINE-DATA 13 0))
                                                       (leaf (token "4c" SPINE-DATA 14 0))
                                                       (leaf (token "=3" MEASURE 15 0))
                                                       (leaf (token "4c" SPINE-DATA 16 0))
                                                       (leaf (token "4c" SPINE-DATA 17 0))
                                                       (leaf (token "4c" SPINE-DATA 18 0))
                                                       (leaf (token "*" NULL-INTERPRETATION 19 0))
                                                       (leaf (token "*" NULL-INTERPRETATION 20 0))
                                                       (leaf (token "*v" SPINE-JOIN 21 0)))
                                                 (list (leaf (token "*" NULL-INTERPRETATION 6 1))
                                                       (leaf (token "*" NULL-INTERPRETATION 7 1))
                                                       (leaf (token "4c" SPINE-DATA 8 1))
                                                       (leaf (token "4c" SPINE-DATA 9 1))
                                                       (leaf (token "4c" SPINE-DATA 10 1))
                                                       (leaf (token "=2" MEASURE 11 1))
                                                       (leaf (token "4c" SPINE-DATA 12 1))
                                                       (leaf (token "4c" SPINE-DATA 13 1))
                                                       (leaf (token "4c" SPINE-DATA 14 1))
                                                       (leaf (token "=3" MEASURE 15 1))
                                                       (leaf (token "4c" SPINE-DATA 16 1))
                                                       (leaf (token "4c" SPINE-DATA 17 1))
                                                       (leaf (token "4c" SPINE-DATA 18 1))
                                                       (leaf (token "*" NULL-INTERPRETATION 19 1))
                                                       (leaf (token "*" NULL-INTERPRETATION 20 1))
                                                       (leaf (token "*v" SPINE-JOIN 21 1))))
                                         (leaf (token "==" MEASURE 22 0))
                                         (leaf (token "*-" SPINE-TERMINATOR 23 0)))
                                   (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 1))
                                         (leaf (token "*clefG2" CLEF 1 1))
                                         (leaf (token "*k[]" KEY-SIG 2 1))
                                         (leaf (token "*a:" KEY-LABEL 3 1))
                                         (leaf (token "*M3/4" TIME-SIG 4 1))
                                         (leaf (token "*" NULL-INTERPRETATION 5 1))
                                         (parent (token "*^" SPINE-SPLIT 6 2)
                                                 (list (leaf (token "*" NULL-INTERPRETATION 7 2))
                                                       (leaf (token "4c" SPINE-DATA 8 2))
                                                       (leaf (token "4c" SPINE-DATA 9 2))
                                                       (leaf (token "4c" SPINE-DATA 10 2))
                                                       (leaf (token "=2" MEASURE 11 2))
                                                       (leaf (token "4c" SPINE-DATA 12 2))
                                                       (leaf (token "4c" SPINE-DATA 13 2))
                                                       (leaf (token "4c" SPINE-DATA 14 2))
                                                       (leaf (token "=3" MEASURE 15 2))
                                                       (leaf (token "4c" SPINE-DATA 16 2))
                                                       (leaf (token "4c" SPINE-DATA 17 2))
                                                       (leaf (token "4c" SPINE-DATA 18 2))
                                                       (leaf (token "*" NULL-INTERPRETATION 19 2))
                                                       (leaf (token "*v" SPINE-JOIN 20 2)))
                                                 (list (leaf (token "*" NULL-INTERPRETATION 7 3))
                                                       (leaf (token "4c" SPINE-DATA 8 3))
                                                       (leaf (token "4c" SPINE-DATA 9 3))
                                                       (leaf (token "4c" SPINE-DATA 10 3))
                                                       (leaf (token "=2" MEASURE 11 3))
                                                       (leaf (token "4c" SPINE-DATA 12 3))
                                                       (leaf (token "4c" SPINE-DATA 13 3))
                                                       (leaf (token "4c" SPINE-DATA 14 3))
                                                       (leaf (token "=3" MEASURE 15 3))
                                                       (leaf (token "4c" SPINE-DATA 16 3))
                                                       (leaf (token "4c" SPINE-DATA 17 3))
                                                       (leaf (token "4c" SPINE-DATA 18 3))
                                                       (leaf (token "*" NULL-INTERPRETATION 19 3))
                                                       (leaf (token "*v" SPINE-JOIN 20 3))))
                                         (leaf (token "*" NULL-INTERPRETATION 21 2))
                                         (leaf (token "==" MEASURE 22 1))
                                         (leaf (token "*-" SPINE-TERMINATOR 23 1)))
                                   (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 2))
                                         (leaf (token "*clefG2" CLEF 1 2))
                                         (leaf (token "*k[]" KEY-SIG 2 2))
                                         (leaf (token "*a:" KEY-LABEL 3 2))
                                         (leaf (token "*M3/4" TIME-SIG 4 2))
                                         (leaf (token "*" NULL-INTERPRETATION 5 2))
                                         (leaf (token "*" NULL-INTERPRETATION 6 3))
                                         (parent (token "*^" SPINE-SPLIT 7 4)
                                                 (list (leaf (token "4c" SPINE-DATA 8 4))
                                                       (leaf (token "4c" SPINE-DATA 9 4))
                                                       (leaf (token "4c" SPINE-DATA 10 4))
                                                       (leaf (token "=2" MEASURE 11 4))
                                                       (leaf (token "4c" SPINE-DATA 12 4))
                                                       (leaf (token "4c" SPINE-DATA 13 4))
                                                       (leaf (token "4c" SPINE-DATA 14 4))
                                                       (leaf (token "=3" MEASURE 15 4))
                                                       (leaf (token "4c" SPINE-DATA 16 4))
                                                       (leaf (token "4c" SPINE-DATA 17 4))
                                                       (leaf (token "4c" SPINE-DATA 18 4))
                                                       (leaf (token "*v" SPINE-JOIN 19 4)))
                                                 (list (leaf (token "4c" SPINE-DATA 8 5))
                                                       (leaf (token "4c" SPINE-DATA 9 5))
                                                       (leaf (token "4c" SPINE-DATA 10 5))
                                                       (leaf (token "=2" MEASURE 11 5))
                                                       (leaf (token "4c" SPINE-DATA 12 5))
                                                       (leaf (token "4c" SPINE-DATA 13 5))
                                                       (leaf (token "4c" SPINE-DATA 14 5))
                                                       (leaf (token "=3" MEASURE 15 5))
                                                       (leaf (token "4c" SPINE-DATA 16 5))
                                                       (leaf (token "4c" SPINE-DATA 17 5))
                                                       (leaf (token "4c" SPINE-DATA 18 5))
                                                       (leaf (token "*v" SPINE-JOIN 19 5))))
                                         (leaf (token "*" NULL-INTERPRETATION 20 4))
                                         (leaf (token "*" NULL-INTERPRETATION 21 3))
                                         (leaf (token "==" MEASURE 22 2))
                                         (leaf (token "*-" SPINE-TERMINATOR 23 2)))))))
              (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0)
                          (token "**kern" EXCLUSIVE-INTERPRETATION 0 1)
                          (token "**kern" EXCLUSIVE-INTERPRETATION 0 2))
                    (list (token "*clefG2" CLEF 1 0)
                          (token "*clefG2" CLEF 1 1)
                          (token "*clefG2" CLEF 1 2))
                    (list (token "*k[]" KEY-SIG 2 0)
                          (token "*k[]" KEY-SIG 2 1)
                          (token "*k[]" KEY-SIG 2 2))
                    (list (token "*a:" KEY-LABEL 3 0)
                          (token "*a:" KEY-LABEL 3 1)
                          (token "*a:" KEY-LABEL 3 2))
                    (list (token "*M3/4" TIME-SIG 4 0)
                          (token "*M3/4" TIME-SIG 4 1)
                          (token "*M3/4" TIME-SIG 4 2))
                    (list (token "*^" SPINE-SPLIT 5 0)
                          (token "*" NULL-INTERPRETATION 5 1)
                          (token "*" NULL-INTERPRETATION 5 2))
                    (list (token "*" NULL-INTERPRETATION 6 0)
                          (token "*" NULL-INTERPRETATION 6 1)
                          (token "*^" SPINE-SPLIT 6 2)
                          (token "*" NULL-INTERPRETATION 6 3))
                    (list (token "*" NULL-INTERPRETATION 7 0)
                          (token "*" NULL-INTERPRETATION 7 1)
                          (token "*" NULL-INTERPRETATION 7 2)
                          (token "*" NULL-INTERPRETATION 7 3)
                          (token "*^" SPINE-SPLIT 7 4))
                    (list (token "4c" SPINE-DATA 8 0)
                          (token "4c" SPINE-DATA 8 1)
                          (token "4c" SPINE-DATA 8 2)
                          (token "4c" SPINE-DATA 8 3)
                          (token "4c" SPINE-DATA 8 4)
                          (token "4c" SPINE-DATA 8 5))
                    (list (token "4c" SPINE-DATA 9 0)
                          (token "4c" SPINE-DATA 9 1)
                          (token "4c" SPINE-DATA 9 2)
                          (token "4c" SPINE-DATA 9 3)
                          (token "4c" SPINE-DATA 9 4)
                          (token "4c" SPINE-DATA 9 5))
                    (list (token "4c" SPINE-DATA 10 0)
                          (token "4c" SPINE-DATA 10 1)
                          (token "4c" SPINE-DATA 10 2)
                          (token "4c" SPINE-DATA 10 3)
                          (token "4c" SPINE-DATA 10 4)
                          (token "4c" SPINE-DATA 10 5))
                    (list (token "=2" MEASURE 11 0)
                          (token "=2" MEASURE 11 1)
                          (token "=2" MEASURE 11 2)
                          (token "=2" MEASURE 11 3)
                          (token "=2" MEASURE 11 4)
                          (token "=2" MEASURE 11 5))
                    (list (token "4c" SPINE-DATA 12 0)
                          (token "4c" SPINE-DATA 12 1)
                          (token "4c" SPINE-DATA 12 2)
                          (token "4c" SPINE-DATA 12 3)
                          (token "4c" SPINE-DATA 12 4)
                          (token "4c" SPINE-DATA 12 5))
                    (list (token "4c" SPINE-DATA 13 0)
                          (token "4c" SPINE-DATA 13 1)
                          (token "4c" SPINE-DATA 13 2)
                          (token "4c" SPINE-DATA 13 3)
                          (token "4c" SPINE-DATA 13 4)
                          (token "4c" SPINE-DATA 13 5))
                    (list (token "4c" SPINE-DATA 14 0)
                          (token "4c" SPINE-DATA 14 1)
                          (token "4c" SPINE-DATA 14 2)
                          (token "4c" SPINE-DATA 14 3)
                          (token "4c" SPINE-DATA 14 4)
                          (token "4c" SPINE-DATA 14 5))
                    (list (token "=3" MEASURE 15 0)
                          (token "=3" MEASURE 15 1)
                          (token "=3" MEASURE 15 2)
                          (token "=3" MEASURE 15 3)
                          (token "=3" MEASURE 15 4)
                          (token "=3" MEASURE 15 5))
                    (list (token "4c" SPINE-DATA 16 0)
                          (token "4c" SPINE-DATA 16 1)
                          (token "4c" SPINE-DATA 16 2)
                          (token "4c" SPINE-DATA 16 3)
                          (token "4c" SPINE-DATA 16 4)
                          (token "4c" SPINE-DATA 16 5))
                    (list (token "4c" SPINE-DATA 17 0)
                          (token "4c" SPINE-DATA 17 1)
                          (token "4c" SPINE-DATA 17 2)
                          (token "4c" SPINE-DATA 17 3)
                          (token "4c" SPINE-DATA 17 4)
                          (token "4c" SPINE-DATA 17 5))
                    (list (token "4c" SPINE-DATA 18 0)
                          (token "4c" SPINE-DATA 18 1)
                          (token "4c" SPINE-DATA 18 2)
                          (token "4c" SPINE-DATA 18 3)
                          (token "4c" SPINE-DATA 18 4)
                          (token "4c" SPINE-DATA 18 5))
                    (list (token "*" NULL-INTERPRETATION 19 0)
                          (token "*" NULL-INTERPRETATION 19 1)
                          (token "*" NULL-INTERPRETATION 19 2)
                          (token "*" NULL-INTERPRETATION 19 3)
                          (token "*v" SPINE-JOIN 19 4)
                          (token "*v" SPINE-JOIN 19 5))
                    (list (token "*" NULL-INTERPRETATION 20 0)
                          (token "*" NULL-INTERPRETATION 20 1)
                          (token "*v" SPINE-JOIN 20 2)
                          (token "*v" SPINE-JOIN 20 3)
                          (token "*" NULL-INTERPRETATION 20 4))
                    (list (token "*v" SPINE-JOIN 21 0)
                          (token "*v" SPINE-JOIN 21 1)
                          (token "*" NULL-INTERPRETATION 21 2)
                          (token "*" NULL-INTERPRETATION 21 3))
                    (list (token "==" MEASURE 22 0)
                          (token "==" MEASURE 22 1)
                          (token "==" MEASURE 22 2))
                    (list (token "*-" SPINE-TERMINATOR 23 0)
                          (token "*-" SPINE-TERMINATOR 23 1)
                          (token "*-" SPINE-TERMINATOR 23 2))))
(check-expect (hfile->hgraph (path->hfile "../../data/count/three-spines-one-split.krn"))
              (hgraph (root (list (list (leaf (token"**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                        (leaf (token "*clefG2" CLEF 1 0))
                                        (leaf (token "*k[]" KEY-SIG 2 0))
                                        (leaf (token "*a:" KEY-LABEL 3 0))
                                        (leaf (token "*M3/4" TIME-SIG 4 0))
                                        (parent (token "*^" SPINE-SPLIT 5 0)
                                                (list (leaf (token "*" NULL-INTERPRETATION 6 0))
                                                      (leaf (token "*" NULL-INTERPRETATION 7 0))
                                                      (leaf (token "4c" SPINE-DATA 8 0))
                                                      (leaf (token "4c" SPINE-DATA 9 0))
                                                      (leaf (token "4c" SPINE-DATA 10 0))
                                                      (leaf (token "=2" MEASURE 11 0))
                                                      (leaf (token "4c" SPINE-DATA 12 0))
                                                      (leaf (token "4c" SPINE-DATA 13 0))
                                                      (leaf (token "4c" SPINE-DATA 14 0))
                                                      (leaf (token "=3" MEASURE 15 0))
                                                      (leaf (token "4c" SPINE-DATA 16 0))
                                                      (leaf (token "4c" SPINE-DATA 17 0))
                                                      (leaf (token "4c" SPINE-DATA 18 0))
                                                      (leaf (token "*" NULL-INTERPRETATION 19 0))
                                                      (leaf (token "*" NULL-INTERPRETATION 20 0))
                                                      (leaf (token "*v" SPINE-JOIN 21 0)))
                                                (list (leaf (token "*" NULL-INTERPRETATION 6 1))
                                                      (leaf (token "*" NULL-INTERPRETATION 7 1))
                                                      (leaf (token "4c" SPINE-DATA 8 1))
                                                      (leaf (token "4c" SPINE-DATA 9 1))
                                                      (leaf (token "4c" SPINE-DATA 10 1))
                                                      (leaf (token "=2" MEASURE 11 1))
                                                      (leaf (token "4c" SPINE-DATA 12 1))
                                                      (leaf (token "4c" SPINE-DATA 13 1))
                                                      (leaf (token "4c" SPINE-DATA 14 1))
                                                      (leaf (token "=3" MEASURE 15 1))
                                                      (leaf (token "4c" SPINE-DATA 16 1))
                                                      (leaf (token "4c" SPINE-DATA 17 1))
                                                      (leaf (token "4c" SPINE-DATA 18 1))
                                                      (leaf (token "*" NULL-INTERPRETATION 19 1))
                                                      (leaf (token "*" NULL-INTERPRETATION 20 1))
                                                      (leaf (token "*v" SPINE-JOIN 21 1))))
                                        (leaf (token "==" MEASURE 22 0))
                                        (leaf (token "*-" SPINE-TERMINATOR 23 0)))
                                  (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 1))
                                        (leaf (token "*clefG2" CLEF 1 1))
                                        (leaf (token "*k[]" KEY-SIG 2 1))
                                        (leaf (token "*a:" KEY-LABEL 3 1))
                                        (leaf (token "*M3/4" TIME-SIG 4 1))
                                        (leaf (token "*" NULL-INTERPRETATION 5 1))
                                        (parent (token "*^" SPINE-SPLIT 6 2)
                                                (list (leaf (token "*" NULL-INTERPRETATION 7 2))
                                                      (leaf (token "4c" SPINE-DATA 8 2))
                                                      (leaf (token "4c" SPINE-DATA 9 2))
                                                      (leaf (token "4c" SPINE-DATA 10 2))
                                                      (leaf (token "=2" MEASURE 11 2))
                                                      (leaf (token "4c" SPINE-DATA 12 2))
                                                      (leaf (token "4c" SPINE-DATA 13 2))
                                                      (leaf (token "4c" SPINE-DATA 14 2))
                                                      (leaf (token "=3" MEASURE 15 2))
                                                      (leaf (token "4c" SPINE-DATA 16 2))
                                                      (leaf (token "4c" SPINE-DATA 17 2))
                                                      (leaf (token "4c" SPINE-DATA 18 2))
                                                      (leaf (token "*" NULL-INTERPRETATION 19 2))
                                                      (leaf (token "*v" SPINE-JOIN 20 2)))
                                                (list (leaf (token "*" NULL-INTERPRETATION 7 3))
                                                      (leaf (token "4c" SPINE-DATA 8 3))
                                                      (leaf (token "4c" SPINE-DATA 9 3))
                                                      (leaf (token "4c" SPINE-DATA 10 3))
                                                      (leaf (token "=2" MEASURE 11 3))
                                                      (leaf (token "4c" SPINE-DATA 12 3))
                                                      (leaf (token "4c" SPINE-DATA 13 3))
                                                      (leaf (token "4c" SPINE-DATA 14 3))
                                                      (leaf (token "=3" MEASURE 15 3))
                                                      (leaf (token "4c" SPINE-DATA 16 3))
                                                      (leaf (token "4c" SPINE-DATA 17 3))
                                                      (leaf (token "4c" SPINE-DATA 18 3))
                                                      (leaf (token "*" NULL-INTERPRETATION 19 3))
                                                      (leaf (token "*v" SPINE-JOIN 20 3))))
                                        (leaf (token "*" NULL-INTERPRETATION 21 2))
                                        (leaf (token "==" MEASURE 22 1))
                                        (leaf (token "*-" SPINE-TERMINATOR 23 1)))
                                  (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 2))
                                        (leaf (token "*clefG2" CLEF 1 2))
                                        (leaf (token "*k[]" KEY-SIG 2 2))
                                        (leaf (token "*a:" KEY-LABEL 3 2))
                                        (leaf (token "*M3/4" TIME-SIG 4 2))
                                        (leaf (token "*" NULL-INTERPRETATION 5 2))
                                        (leaf (token "*" NULL-INTERPRETATION 6 3))
                                        (parent (token "*^" SPINE-SPLIT 7 4)
                                                (list (leaf (token "4c" SPINE-DATA 8 4))
                                                      (leaf (token "4c" SPINE-DATA 9 4))
                                                      (leaf (token "4c" SPINE-DATA 10 4))
                                                      (leaf (token "=2" MEASURE 11 4))
                                                      (leaf (token "4c" SPINE-DATA 12 4))
                                                      (leaf (token "4c" SPINE-DATA 13 4))
                                                      (leaf (token "4c" SPINE-DATA 14 4))
                                                      (leaf (token "=3" MEASURE 15 4))
                                                      (leaf (token "4c" SPINE-DATA 16 4))
                                                      (leaf (token "4c" SPINE-DATA 17 4))
                                                      (leaf (token "4c" SPINE-DATA 18 4))
                                                      (leaf (token "*v" SPINE-JOIN 19 4)))
                                                (list (leaf (token "4c" SPINE-DATA 8 5))
                                                      (leaf (token "4c" SPINE-DATA 9 5))
                                                      (leaf (token "4c" SPINE-DATA 10 5))
                                                      (leaf (token "=2" MEASURE 11 5))
                                                      (leaf (token "4c" SPINE-DATA 12 5))
                                                      (leaf (token "4c" SPINE-DATA 13 5))
                                                      (leaf (token "4c" SPINE-DATA 14 5))
                                                      (leaf (token "=3" MEASURE 15 5))
                                                      (leaf (token "4c" SPINE-DATA 16 5))
                                                      (leaf (token "4c" SPINE-DATA 17 5))
                                                      (leaf (token "4c" SPINE-DATA 18 5))
                                                      (leaf (token "*v" SPINE-JOIN 19 5))))
                                        (leaf (token "*" NULL-INTERPRETATION 20 4))
                                        (leaf (token "*" NULL-INTERPRETATION 21 3))
                                        (leaf (token "==" MEASURE 22 2))
                                        (leaf (token "*-" SPINE-TERMINATOR 23 2)))))))

; branch->lot for spine 0
(check-expect (branch->lot (list (leaf (token"**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                 (leaf (token "*clefG2" CLEF 1 0))
                                 (leaf (token "*k[]" KEY-SIG 2 0))
                                 (leaf (token "*a:" KEY-LABEL 3 0))
                                 (leaf (token "*M3/4" TIME-SIG 4 0))
                                 (parent (token "*^" SPINE-SPLIT 5 0)
                                         (list (leaf (token "*" NULL-INTERPRETATION 6 0))
                                               (leaf (token "*" NULL-INTERPRETATION 7 0))
                                               (leaf (token "4c" SPINE-DATA 8 0))
                                               (leaf (token "4c" SPINE-DATA 9 0))
                                               (leaf (token "4c" SPINE-DATA 10 0))
                                               (leaf (token "=2" MEASURE 11 0))
                                               (leaf (token "4c" SPINE-DATA 12 0))
                                               (leaf (token "4c" SPINE-DATA 13 0))
                                               (leaf (token "4c" SPINE-DATA 14 0))
                                               (leaf (token "=3" MEASURE 15 0))
                                               (leaf (token "4c" SPINE-DATA 16 0))
                                               (leaf (token "4c" SPINE-DATA 17 0))
                                               (leaf (token "4c" SPINE-DATA 18 0))
                                               (leaf (token "*" NULL-INTERPRETATION 19 0))
                                               (leaf (token "*" NULL-INTERPRETATION 20 0))
                                               (leaf (token "*v" SPINE-JOIN 21 0)))
                                         (list (leaf (token "*" NULL-INTERPRETATION 6 1))
                                               (leaf (token "*" NULL-INTERPRETATION 7 1))
                                               (leaf (token "4c" SPINE-DATA 8 1))
                                               (leaf (token "4c" SPINE-DATA 9 1))
                                               (leaf (token "4c" SPINE-DATA 10 1))
                                               (leaf (token "=2" MEASURE 11 1))
                                               (leaf (token "4c" SPINE-DATA 12 1))
                                               (leaf (token "4c" SPINE-DATA 13 1))
                                               (leaf (token "4c" SPINE-DATA 14 1))
                                               (leaf (token "=3" MEASURE 15 1))
                                               (leaf (token "4c" SPINE-DATA 16 1))
                                               (leaf (token "4c" SPINE-DATA 17 1))
                                               (leaf (token "4c" SPINE-DATA 18 1))
                                               (leaf (token "*" NULL-INTERPRETATION 19 1))
                                               (leaf (token "*" NULL-INTERPRETATION 20 1))
                                               (leaf (token "*v" SPINE-JOIN 21 1))))
                                 (leaf (token "==" MEASURE 22 0))
                                 (leaf (token "*-" SPINE-TERMINATOR 23 0))))
              (list (token"**kern" EXCLUSIVE-INTERPRETATION 0 0)
                    (token "*clefG2" CLEF 1 0)
                    (token "*k[]" KEY-SIG 2 0)
                    (token "*a:" KEY-LABEL 3 0)
                    (token "*M3/4" TIME-SIG 4 0)
                    (token "*^" SPINE-SPLIT 5 0)
                    (token "*" NULL-INTERPRETATION 6 0)
                    (token "*" NULL-INTERPRETATION 7 0)
                    (token "4c" SPINE-DATA 8 0)
                    (token "4c" SPINE-DATA 9 0)
                    (token "4c" SPINE-DATA 10 0)
                    (token "=2" MEASURE 11 0)
                    (token "4c" SPINE-DATA 12 0)
                    (token "4c" SPINE-DATA 13 0)
                    (token "4c" SPINE-DATA 14 0)
                    (token "=3" MEASURE 15 0)
                    (token "4c" SPINE-DATA 16 0)
                    (token "4c" SPINE-DATA 17 0)
                    (token "4c" SPINE-DATA 18 0)
                    (token "*" NULL-INTERPRETATION 19 0)
                    (token "*" NULL-INTERPRETATION 20 0)
                    (token "*v" SPINE-JOIN 21 0)
                    (token "*" NULL-INTERPRETATION 6 1)
                    (token "*" NULL-INTERPRETATION 7 1)
                    (token "4c" SPINE-DATA 8 1)
                    (token "4c" SPINE-DATA 9 1)
                    (token "4c" SPINE-DATA 10 1)
                    (token "=2" MEASURE 11 1)
                    (token "4c" SPINE-DATA 12 1)
                    (token "4c" SPINE-DATA 13 1)
                    (token "4c" SPINE-DATA 14 1)
                    (token "=3" MEASURE 15 1)
                    (token "4c" SPINE-DATA 16 1)
                    (token "4c" SPINE-DATA 17 1)
                    (token "4c" SPINE-DATA 18 1)
                    (token "*" NULL-INTERPRETATION 19 1)
                    (token "*" NULL-INTERPRETATION 20 1)
                    (token "*v" SPINE-JOIN 21 1)
                    (token "==" MEASURE 22 0)
                    (token "*-" SPINE-TERMINATOR 23 0)))

; branch->lot for spine 1
(check-expect (branch->lot
               (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 1))
                     (leaf (token "*clefG2" CLEF 1 1))
                     (leaf (token "*k[]" KEY-SIG 2 1))
                     (leaf (token "*a:" KEY-LABEL 3 1))
                     (leaf (token "*M3/4" TIME-SIG 4 1))
                     (leaf (token "*" NULL-INTERPRETATION 5 1))
                     (parent (token "*^" SPINE-SPLIT 6 2)
                             (list (leaf (token "*" NULL-INTERPRETATION 7 2))
                                   (leaf (token "4c" SPINE-DATA 8 2))
                                   (leaf (token "4c" SPINE-DATA 9 2))
                                   (leaf (token "4c" SPINE-DATA 10 2))
                                   (leaf (token "=2" MEASURE 11 2))
                                   (leaf (token "4c" SPINE-DATA 12 2))
                                   (leaf (token "4c" SPINE-DATA 13 2))
                                   (leaf (token "4c" SPINE-DATA 14 2))
                                   (leaf (token "=3" MEASURE 15 2))
                                   (leaf (token "4c" SPINE-DATA 16 2))
                                   (leaf (token "4c" SPINE-DATA 17 2))
                                   (leaf (token "4c" SPINE-DATA 18 2))
                                   (leaf (token "*" NULL-INTERPRETATION 19 2))
                                   (leaf (token "*v" SPINE-JOIN 20 2)))
                             (list (leaf (token "*" NULL-INTERPRETATION 7 3))
                                   (leaf (token "4c" SPINE-DATA 8 3))
                                   (leaf (token "4c" SPINE-DATA 9 3))
                                   (leaf (token "4c" SPINE-DATA 10 3))
                                   (leaf (token "=2" MEASURE 11 3))
                                   (leaf (token "4c" SPINE-DATA 12 3))
                                   (leaf (token "4c" SPINE-DATA 13 3))
                                   (leaf (token "4c" SPINE-DATA 14 3))
                                   (leaf (token "=3" MEASURE 15 3))
                                   (leaf (token "4c" SPINE-DATA 16 3))
                                   (leaf (token "4c" SPINE-DATA 17 3))
                                   (leaf (token "4c" SPINE-DATA 18 3))
                                   (leaf (token "*" NULL-INTERPRETATION 19 3))
                                   (leaf (token "*v" SPINE-JOIN 20 3))))
                     (leaf (token "*" NULL-INTERPRETATION 21 2))
                     (leaf (token "==" MEASURE 22 1))
                     (leaf (token "*-" SPINE-TERMINATOR 23 1))))
              (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 1)
                    (token "*clefG2" CLEF 1 1)
                    (token "*k[]" KEY-SIG 2 1)
                    (token "*a:" KEY-LABEL 3 1)
                    (token "*M3/4" TIME-SIG 4 1)
                    (token "*" NULL-INTERPRETATION 5 1)
                    (token "*^" SPINE-SPLIT 6 2)
                    (token "*" NULL-INTERPRETATION 7 2)
                    (token "4c" SPINE-DATA 8 2)
                    (token "4c" SPINE-DATA 9 2)
                    (token "4c" SPINE-DATA 10 2)
                    (token "=2" MEASURE 11 2)
                    (token "4c" SPINE-DATA 12 2)
                    (token "4c" SPINE-DATA 13 2)
                    (token "4c" SPINE-DATA 14 2)
                    (token "=3" MEASURE 15 2)
                    (token "4c" SPINE-DATA 16 2)
                    (token "4c" SPINE-DATA 17 2)
                    (token "4c" SPINE-DATA 18 2)
                    (token "*" NULL-INTERPRETATION 19 2)
                    (token "*v" SPINE-JOIN 20 2)
                    (token "*" NULL-INTERPRETATION 7 3)
                    (token "4c" SPINE-DATA 8 3)
                    (token "4c" SPINE-DATA 9 3)
                    (token "4c" SPINE-DATA 10 3)
                    (token "=2" MEASURE 11 3)
                    (token "4c" SPINE-DATA 12 3)
                    (token "4c" SPINE-DATA 13 3)
                    (token "4c" SPINE-DATA 14 3)
                    (token "=3" MEASURE 15 3)
                    (token "4c" SPINE-DATA 16 3)
                    (token "4c" SPINE-DATA 17 3)
                    (token "4c" SPINE-DATA 18 3)
                    (token "*" NULL-INTERPRETATION 19 3)
                    (token "*v" SPINE-JOIN 20 3)
                    (token "*" NULL-INTERPRETATION 21 2)
                    (token "==" MEASURE 22 1)
                    (token "*-" SPINE-TERMINATOR 23 1)))

; branch->lot for spine 2
(check-expect (branch->lot
               (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 2))
                     (leaf (token "*clefG2" CLEF 1 2))
                     (leaf (token "*k[]" KEY-SIG 2 2))
                     (leaf (token "*a:" KEY-LABEL 3 2))
                     (leaf (token "*M3/4" TIME-SIG 4 2))
                     (leaf (token "*" NULL-INTERPRETATION 5 2))
                     (leaf (token "*" NULL-INTERPRETATION 6 3))
                     (parent (token "*^" SPINE-SPLIT 7 4)
                             (list (leaf (token "4c" SPINE-DATA 8 4))
                                   (leaf (token "4c" SPINE-DATA 9 4))
                                   (leaf (token "4c" SPINE-DATA 10 4))
                                   (leaf (token "=2" MEASURE 11 4))
                                   (leaf (token "4c" SPINE-DATA 12 4))
                                   (leaf (token "4c" SPINE-DATA 13 4))
                                   (leaf (token "4c" SPINE-DATA 14 4))
                                   (leaf (token "=3" MEASURE 15 4))
                                   (leaf (token "4c" SPINE-DATA 16 4))
                                   (leaf (token "4c" SPINE-DATA 17 4))
                                   (leaf (token "4c" SPINE-DATA 18 4))
                                   (leaf (token "*v" SPINE-JOIN 19 4)))
                             (list (leaf (token "4c" SPINE-DATA 8 5))
                                   (leaf (token "4c" SPINE-DATA 9 5))
                                   (leaf (token "4c" SPINE-DATA 10 5))
                                   (leaf (token "=2" MEASURE 11 5))
                                   (leaf (token "4c" SPINE-DATA 12 5))
                                   (leaf (token "4c" SPINE-DATA 13 5))
                                   (leaf (token "4c" SPINE-DATA 14 5))
                                   (leaf (token "=3" MEASURE 15 5))
                                   (leaf (token "4c" SPINE-DATA 16 5))
                                   (leaf (token "4c" SPINE-DATA 17 5))
                                   (leaf (token "4c" SPINE-DATA 18 5))
                                   (leaf (token "*v" SPINE-JOIN 19 5))))
                     (leaf (token "*" NULL-INTERPRETATION 20 4))
                     (leaf (token "*" NULL-INTERPRETATION 21 3))
                     (leaf (token "==" MEASURE 22 2))
                     (leaf (token "*-" SPINE-TERMINATOR 23 2))))
              (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 2)
                    (token "*clefG2" CLEF 1 2)
                    (token "*k[]" KEY-SIG 2 2)
                    (token "*a:" KEY-LABEL 3 2)
                    (token "*M3/4" TIME-SIG 4 2)
                    (token "*" NULL-INTERPRETATION 5 2)
                    (token "*" NULL-INTERPRETATION 6 3)
                    (token "*^" SPINE-SPLIT 7 4)
                    (token "4c" SPINE-DATA 8 4)
                    (token "4c" SPINE-DATA 9 4)
                    (token "4c" SPINE-DATA 10 4)
                    (token "=2" MEASURE 11 4)
                    (token "4c" SPINE-DATA 12 4)
                    (token "4c" SPINE-DATA 13 4)
                    (token "4c" SPINE-DATA 14 4)
                    (token "=3" MEASURE 15 4)
                    (token "4c" SPINE-DATA 16 4)
                    (token "4c" SPINE-DATA 17 4)
                    (token "4c" SPINE-DATA 18 4)
                    (token "*v" SPINE-JOIN 19 4)
                    (token "4c" SPINE-DATA 8 5)
                    (token "4c" SPINE-DATA 9 5)
                    (token "4c" SPINE-DATA 10 5)
                    (token "=2" MEASURE 11 5)
                    (token "4c" SPINE-DATA 12 5)
                    (token "4c" SPINE-DATA 13 5)
                    (token "4c" SPINE-DATA 14 5)
                    (token "=3" MEASURE 15 5)
                    (token "4c" SPINE-DATA 16 5)
                    (token "4c" SPINE-DATA 17 5)
                    (token "4c" SPINE-DATA 18 5)
                    (token "*v" SPINE-JOIN 19 5)
                    (token "*" NULL-INTERPRETATION 20 4)
                    (token "*" NULL-INTERPRETATION 21 3)
                    (token "==" MEASURE 22 2)
                    (token "*-" SPINE-TERMINATOR 23 2)))

(test)
