#lang racket/base

(require "../../../../parser/data-definitions/data-definitions.rkt"
         "../../../../parser/functions/file.rkt"
         "../../../../parser/functions/spine-parser.rkt"
         "../../../../data-structures/abstract-humdrum-graph/data-definitions/data-definitions.rkt"
         "../../../../data-structures/abstract-humdrum-graph/functions/ab-hgraph-to-hfile.rkt"
         "../../../../data-structures/abstract-humdrum-graph/functions/hfile-to-ab-hgraph.rkt"
         test-engine/racket-tests)

(check-expect (path->hfile "../../data/count/two-spines-two-splits.krn")
              (hfile (list (record "**kern\t**kern" TOKEN
                                   (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                                         (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                   0)
                           (record "*clefG2\t*clefG2" TOKEN (list (token "*clefG2" CLEF 1)
                                                                  (token "*clefG2" CLEF 1))
                                   1)
                           (record "*k[]\t*k[]" TOKEN (list (token "*k[]" KEY-SIG 2)
                                                            (token "*k[]" KEY-SIG 2))
                                   2)
                           (record "*a:\t*a:" TOKEN (list (token "*a:" KEY-LABEL 3)
                                                          (token "*a:" KEY-LABEL 3))
                                   3)
                           (record "*M3/4\t*M3/4" TOKEN (list (token "*M3/4" TIME-SIG 4)
                                                              (token "*M3/4" TIME-SIG 4))
                                   4)
                           (record "*^\t*" TOKEN (list (token "*^" SPINE-SPLIT 5)
                                                       (token "*" NULL-INTERPRETATION 5))
                                   5)
                           (record "*\t*\t*^" TOKEN (list (token "*" NULL-INTERPRETATION 6)
                                                          (token "*" NULL-INTERPRETATION 6)
                                                          (token "*^" SPINE-SPLIT 6))
                                   6)
                           (record "*\t*^\t*\t*" TOKEN (list (token "*" NULL-INTERPRETATION 7)
                                                             (token "*^" SPINE-SPLIT 7)
                                                             (token "*" NULL-INTERPRETATION 7)
                                                             (token "*" NULL-INTERPRETATION 7))
                                   7)
                           (record "*\t*\t*\t*\t*^" TOKEN (list (token "*" NULL-INTERPRETATION 8)
                                                                (token "*" NULL-INTERPRETATION 8)
                                                                (token "*" NULL-INTERPRETATION 8)
                                                                (token "*" NULL-INTERPRETATION 8)
                                                                (token "*^" SPINE-SPLIT 8))
                                   8)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 9)
                                                                        (token "4c" SPINE-DATA 9)
                                                                        (token "4c" SPINE-DATA 9)
                                                                        (token "4c" SPINE-DATA 9)
                                                                        (token "4c" SPINE-DATA 9)
                                                                        (token "4c" SPINE-DATA 9))
                                   9)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 10)
                                                                        (token "4c" SPINE-DATA 10)
                                                                        (token "4c" SPINE-DATA 10)
                                                                        (token "4c" SPINE-DATA 10)
                                                                        (token "4c" SPINE-DATA 10)
                                                                        (token "4c" SPINE-DATA 10))
                                   10)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 11)
                                                                        (token "4c" SPINE-DATA 11)
                                                                        (token "4c" SPINE-DATA 11)
                                                                        (token "4c" SPINE-DATA 11)
                                                                        (token "4c" SPINE-DATA 11)
                                                                        (token "4c" SPINE-DATA 11))
                                   11)
                           (record "=2\t=2\t=2\t=2\t=2\t=2" TOKEN (list (token "=2" MEASURE 12)
                                                                        (token "=2" MEASURE 12)
                                                                        (token "=2" MEASURE 12)
                                                                        (token "=2" MEASURE 12)
                                                                        (token "=2" MEASURE 12)
                                                                        (token "=2" MEASURE 12))
                                   12)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 13)
                                                                        (token "4c" SPINE-DATA 13)
                                                                        (token "4c" SPINE-DATA 13)
                                                                        (token "4c" SPINE-DATA 13)
                                                                        (token "4c" SPINE-DATA 13)
                                                                        (token "4c" SPINE-DATA 13))
                                   13)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 14)
                                                                        (token "4c" SPINE-DATA 14)
                                                                        (token "4c" SPINE-DATA 14)
                                                                        (token "4c" SPINE-DATA 14)
                                                                        (token "4c" SPINE-DATA 14)
                                                                        (token "4c" SPINE-DATA 14))
                                   14)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 15)
                                                                        (token "4c" SPINE-DATA 15)
                                                                        (token "4c" SPINE-DATA 15)
                                                                        (token "4c" SPINE-DATA 15)
                                                                        (token "4c" SPINE-DATA 15)
                                                                        (token "4c" SPINE-DATA 15))
                                   15)
                           (record "=3\t=3\t=3\t=3\t=3\t=3" TOKEN (list (token "=3" MEASURE 16)
                                                                        (token "=3" MEASURE 16)
                                                                        (token "=3" MEASURE 16)
                                                                        (token "=3" MEASURE 16)
                                                                        (token "=3" MEASURE 16)
                                                                        (token "=3" MEASURE 16))
                                   16)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 17)
                                                                        (token "4c" SPINE-DATA 17)
                                                                        (token "4c" SPINE-DATA 17)
                                                                        (token "4c" SPINE-DATA 17)
                                                                        (token "4c" SPINE-DATA 17)
                                                                        (token "4c" SPINE-DATA 17))
                                   17)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 18)
                                                                        (token "4c" SPINE-DATA 18)
                                                                        (token "4c" SPINE-DATA 18)
                                                                        (token "4c" SPINE-DATA 18)
                                                                        (token "4c" SPINE-DATA 18)
                                                                        (token "4c" SPINE-DATA 18))
                                   18)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 19)
                                                                        (token "4c" SPINE-DATA 19)
                                                                        (token "4c" SPINE-DATA 19)
                                                                        (token "4c" SPINE-DATA 19)
                                                                        (token "4c" SPINE-DATA 19)
                                                                        (token "4c" SPINE-DATA 19))
                                   19)
                           (record "*\t*\t*\t*\t*v\t*v" TOKEN (list (token "*" NULL-INTERPRETATION 20)
                                                                    (token "*" NULL-INTERPRETATION 20)
                                                                    (token "*" NULL-INTERPRETATION 20)
                                                                    (token "*" NULL-INTERPRETATION 20)
                                                                    (token "*v" SPINE-JOIN 20)
                                                                    (token "*v" SPINE-JOIN 20))
                                   20)
                           (record "*\t*\t*\t*v\t*v" TOKEN (list (token "*" NULL-INTERPRETATION 21)
                                                                 (token "*" NULL-INTERPRETATION 21)
                                                                 (token "*" NULL-INTERPRETATION 21)
                                                                 (token "*v" SPINE-JOIN 21)
                                                                 (token "*v" SPINE-JOIN 21))
                                   21)
                           (record "*\t*v\t*v\t*" TOKEN (list (token "*" NULL-INTERPRETATION 22)
                                                              (token "*v" SPINE-JOIN 22)
                                                              (token "*v" SPINE-JOIN 22)
                                                              (token "*" NULL-INTERPRETATION 22))
                                   22)
                           (record "*v\t*v\t*" TOKEN (list (token "*v" SPINE-JOIN 23)
                                                           (token "*v" SPINE-JOIN 23)
                                                           (token "*" NULL-INTERPRETATION 23))
                                   23)
                           (record "==\t==" TOKEN (list (token "==" MEASURE 24)
                                                        (token "==" MEASURE 24))
                                   24)
                           (record "*-\t*-" TOKEN (list (token "*-" SPINE-TERMINATOR 25)
                                                        (token "*-" SPINE-TERMINATOR 25))
                                   25))))
(check-expect (spine-parser (path->hfile "../../data/count/two-spines-two-splits.krn"))
              (list (global-spine KERN
                                  (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                        (list (token "*clefG2" CLEF 1))
                                        (list (token "*k[]" KEY-SIG 2))
                                        (list (token "*a:" KEY-LABEL 3))
                                        (list (token "*M3/4" TIME-SIG 4))
                                        (list (token "*^" SPINE-SPLIT 5))
                                        (list (token "*" NULL-INTERPRETATION 6)
                                              (token "*" NULL-INTERPRETATION 6))
                                        (list (token "*" NULL-INTERPRETATION 7)
                                              (token "*^" SPINE-SPLIT 7))
                                        (list (token "*" NULL-INTERPRETATION 8)
                                              (token "*" NULL-INTERPRETATION 8)
                                              (token "*" NULL-INTERPRETATION 8))
                                        (list (token "4c" SPINE-DATA 9)
                                              (token "4c" SPINE-DATA 9)
                                              (token "4c" SPINE-DATA 9))
                                        (list (token "4c" SPINE-DATA 10)
                                              (token "4c" SPINE-DATA 10)
                                              (token "4c" SPINE-DATA 10))
                                        (list (token "4c" SPINE-DATA 11)
                                              (token "4c" SPINE-DATA 11)
                                              (token "4c" SPINE-DATA 11))
                                        (list (token "=2" MEASURE 12)
                                              (token "=2" MEASURE 12)
                                              (token "=2" MEASURE 12))
                                        (list (token "4c" SPINE-DATA 13)
                                              (token "4c" SPINE-DATA 13)
                                              (token "4c" SPINE-DATA 13))
                                        (list (token "4c" SPINE-DATA 14)
                                              (token "4c" SPINE-DATA 14)
                                              (token "4c" SPINE-DATA 14))
                                        (list (token "4c" SPINE-DATA 15)
                                              (token "4c" SPINE-DATA 15)
                                              (token "4c" SPINE-DATA 15))
                                        (list (token "=3" MEASURE 16)
                                              (token "=3" MEASURE 16)
                                              (token "=3" MEASURE 16))
                                        (list (token "4c" SPINE-DATA 17)
                                              (token "4c" SPINE-DATA 17)
                                              (token "4c" SPINE-DATA 17))
                                        (list (token "4c" SPINE-DATA 18)
                                              (token "4c" SPINE-DATA 18)
                                              (token "4c" SPINE-DATA 18))
                                        (list (token "4c" SPINE-DATA 19)
                                              (token "4c" SPINE-DATA 19)
                                              (token "4c" SPINE-DATA 19))
                                        (list (token "*" NULL-INTERPRETATION 20)
                                              (token "*" NULL-INTERPRETATION 20)
                                              (token "*" NULL-INTERPRETATION 20))
                                        (list (token "*" NULL-INTERPRETATION 21)
                                              (token "*" NULL-INTERPRETATION 21)
                                              (token "*" NULL-INTERPRETATION 21))
                                        (list (token "*" NULL-INTERPRETATION 22)
                                              (token "*v" SPINE-JOIN 22)
                                              (token "*v" SPINE-JOIN 22))
                                        (list (token "*v" SPINE-JOIN 23)
                                              (token "*v" SPINE-JOIN 23))
                                        (list (token "==" MEASURE 24))
                                        (list (token "*-" SPINE-TERMINATOR 25)))
                                  0)
                    (global-spine KERN
                                  (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                        (list (token "*clefG2" CLEF 1))
                                        (list (token "*k[]" KEY-SIG 2))
                                        (list (token "*a:" KEY-LABEL 3))
                                        (list (token "*M3/4" TIME-SIG 4))
                                        (list (token "*" NULL-INTERPRETATION 5))
                                        (list (token "*^" SPINE-SPLIT 6))
                                        (list (token "*" NULL-INTERPRETATION 7)
                                              (token "*" NULL-INTERPRETATION 7))
                                        (list (token "*" NULL-INTERPRETATION 8)
                                              (token "*^" SPINE-SPLIT 8))
                                        (list (token "4c" SPINE-DATA 9)
                                              (token "4c" SPINE-DATA 9)
                                              (token "4c" SPINE-DATA 9))
                                        (list (token "4c" SPINE-DATA 10)
                                              (token "4c" SPINE-DATA 10)
                                              (token "4c" SPINE-DATA 10))
                                        (list (token "4c" SPINE-DATA 11)
                                              (token "4c" SPINE-DATA 11)
                                              (token "4c" SPINE-DATA 11))
                                        (list (token "=2" MEASURE 12)
                                              (token "=2" MEASURE 12)
                                              (token "=2" MEASURE 12))
                                        (list (token "4c" SPINE-DATA 13)
                                              (token "4c" SPINE-DATA 13)
                                              (token "4c" SPINE-DATA 13))
                                        (list (token "4c" SPINE-DATA 14)
                                              (token "4c" SPINE-DATA 14)
                                              (token "4c" SPINE-DATA 14))
                                        (list (token "4c" SPINE-DATA 15)
                                              (token "4c" SPINE-DATA 15)
                                              (token "4c" SPINE-DATA 15))
                                        (list (token "=3" MEASURE 16)
                                              (token "=3" MEASURE 16)
                                              (token "=3" MEASURE 16))
                                        (list (token "4c" SPINE-DATA 17)
                                              (token "4c" SPINE-DATA 17)
                                              (token "4c" SPINE-DATA 17))
                                        (list (token "4c" SPINE-DATA 18)
                                              (token "4c" SPINE-DATA 18)
                                              (token "4c" SPINE-DATA 18))
                                        (list (token "4c" SPINE-DATA 19)
                                              (token "4c" SPINE-DATA 19)
                                              (token "4c" SPINE-DATA 19))
                                        (list (token "*" NULL-INTERPRETATION 20)
                                              (token "*v" SPINE-JOIN 20)
                                              (token "*v" SPINE-JOIN 20))
                                        (list (token "*v" SPINE-JOIN 21)
                                              (token "*v" SPINE-JOIN 21))
                                        (list (token "*" NULL-INTERPRETATION 22))
                                        (list (token "*" NULL-INTERPRETATION 23))
                                        (list (token "==" MEASURE 24))
                                        (list (token "*-" SPINE-TERMINATOR 25)))
                                  1)))
(check-expect (ab-hgraph->hfile
               (ab-hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                            (leaf (token "*clefG2" CLEF 1))
                                            (leaf (token "*k[]" KEY-SIG 2))
                                            (leaf (token "*a:" KEY-LABEL 3))
                                            (leaf (token "*M3/4" TIME-SIG 4))
                                            (parent (token "*^" SPINE-SPLIT 5)
                                                    (list (leaf (token "*" NULL-INTERPRETATION 6))
                                                          (leaf (token "*" NULL-INTERPRETATION 7))
                                                          (leaf (token "*" NULL-INTERPRETATION 8))
                                                          (leaf (token "4c" SPINE-DATA 9))
                                                          (leaf (token "4c" SPINE-DATA 10))
                                                          (leaf (token "4c" SPINE-DATA 11))
                                                          (leaf (token "=2" MEASURE 12))
                                                          (leaf (token "4c" SPINE-DATA 13))
                                                          (leaf (token "4c" SPINE-DATA 14))
                                                          (leaf (token "4c" SPINE-DATA 15))
                                                          (leaf (token "=3" MEASURE 16))
                                                          (leaf (token "4c" SPINE-DATA 17))
                                                          (leaf (token "4c" SPINE-DATA 18))
                                                          (leaf (token "4c" SPINE-DATA 19))
                                                          (leaf (token "*" NULL-INTERPRETATION 20))
                                                          (leaf (token "*" NULL-INTERPRETATION 21))
                                                          (leaf (token "*" NULL-INTERPRETATION 22))
                                                          (leaf (token "*v" SPINE-JOIN 23)))
                                                    (list (leaf (token "*" NULL-INTERPRETATION 6))
                                                          (parent (token "*^" SPINE-SPLIT 7)
                                                                  (list (leaf (token "*" NULL-INTERPRETATION 8))
                                                                        (leaf (token "4c" SPINE-DATA 9))
                                                                        (leaf (token "4c" SPINE-DATA 10))
                                                                        (leaf (token "4c" SPINE-DATA 11))
                                                                        (leaf (token "=2" MEASURE 12))
                                                                        (leaf (token "4c" SPINE-DATA 13))
                                                                        (leaf (token "4c" SPINE-DATA 14))
                                                                        (leaf (token "4c" SPINE-DATA 15))
                                                                        (leaf (token "=3" MEASURE 16))
                                                                        (leaf (token "4c" SPINE-DATA 17))
                                                                        (leaf (token "4c" SPINE-DATA 18))
                                                                        (leaf (token "4c" SPINE-DATA 19))
                                                                        (leaf (token "*" NULL-INTERPRETATION 20))
                                                                        (leaf (token "*" NULL-INTERPRETATION 21))
                                                                        (leaf (token "*v" SPINE-JOIN 22)))
                                                                  (list (leaf (token "*" NULL-INTERPRETATION 8))
                                                                        (leaf (token "4c" SPINE-DATA 9))
                                                                        (leaf (token "4c" SPINE-DATA 10))
                                                                        (leaf (token "4c" SPINE-DATA 11))
                                                                        (leaf (token "=2" MEASURE 12))
                                                                        (leaf (token "4c" SPINE-DATA 13))
                                                                        (leaf (token "4c" SPINE-DATA 14))
                                                                        (leaf (token "4c" SPINE-DATA 15))
                                                                        (leaf (token "=3" MEASURE 16))
                                                                        (leaf (token "4c" SPINE-DATA 17))
                                                                        (leaf (token "4c" SPINE-DATA 18))
                                                                        (leaf (token "4c" SPINE-DATA 19))
                                                                        (leaf (token "*" NULL-INTERPRETATION 20))
                                                                        (leaf (token "*" NULL-INTERPRETATION 21))
                                                                        (leaf (token "*v" SPINE-JOIN 22))))
                                                          (leaf (token "*v" SPINE-JOIN 23))))
                                            (leaf (token "==" MEASURE 24))
                                            (leaf (token "*-" SPINE-TERMINATOR 25)))
                                      (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                            (leaf (token "*clefG2" CLEF 1))
                                            (leaf (token "*k[]" KEY-SIG 2))
                                            (leaf (token "*a:" KEY-LABEL 3))
                                            (leaf (token "*M3/4" TIME-SIG 4))
                                            (leaf (token "*" NULL-INTERPRETATION 5))
                                            (parent (token "*^" SPINE-SPLIT 6)
                                                    (list (leaf (token "*" NULL-INTERPRETATION 7))
                                                          (leaf (token "*" NULL-INTERPRETATION 8))
                                                          (leaf (token "4c" SPINE-DATA 9))
                                                          (leaf (token "4c" SPINE-DATA 10))
                                                          (leaf (token "4c" SPINE-DATA 11))
                                                          (leaf (token "=2" MEASURE 12))
                                                          (leaf (token "4c" SPINE-DATA 13))
                                                          (leaf (token "4c" SPINE-DATA 14))
                                                          (leaf (token "4c" SPINE-DATA 15))
                                                          (leaf (token "=3" MEASURE 16))
                                                          (leaf (token "4c" SPINE-DATA 17))
                                                          (leaf (token "4c" SPINE-DATA 18))
                                                          (leaf (token "4c" SPINE-DATA 19))
                                                          (leaf (token "*" NULL-INTERPRETATION 20))
                                                          (leaf (token "*v" SPINE-JOIN 21)))
                                                    (list (leaf (token "*" NULL-INTERPRETATION 7))
                                                          (parent (token "*^" SPINE-SPLIT 8)
                                                                  (list (leaf (token "4c" SPINE-DATA 9))
                                                                        (leaf (token "4c" SPINE-DATA 10))
                                                                        (leaf (token "4c" SPINE-DATA 11))
                                                                        (leaf (token "=2" MEASURE 12))
                                                                        (leaf (token "4c" SPINE-DATA 13))
                                                                        (leaf (token "4c" SPINE-DATA 14))
                                                                        (leaf (token "4c" SPINE-DATA 15))
                                                                        (leaf (token "=3" MEASURE 16))
                                                                        (leaf (token "4c" SPINE-DATA 17))
                                                                        (leaf (token "4c" SPINE-DATA 18))
                                                                        (leaf (token "4c" SPINE-DATA 19))
                                                                        (leaf (token "*v" SPINE-JOIN 20)))
                                                                  (list (leaf (token "4c" SPINE-DATA 9))
                                                                        (leaf (token "4c" SPINE-DATA 10))
                                                                        (leaf (token "4c" SPINE-DATA 11))
                                                                        (leaf (token "=2" MEASURE 12))
                                                                        (leaf (token "4c" SPINE-DATA 13))
                                                                        (leaf (token "4c" SPINE-DATA 14))
                                                                        (leaf (token "4c" SPINE-DATA 15))
                                                                        (leaf (token "=3" MEASURE 16))
                                                                        (leaf (token "4c" SPINE-DATA 17))
                                                                        (leaf (token "4c" SPINE-DATA 18))
                                                                        (leaf (token "4c" SPINE-DATA 19))
                                                                        (leaf (token "*v" SPINE-JOIN 20))))
                                                          (leaf (token "*v" SPINE-JOIN 21))))
                                            (leaf (token "*" NULL-INTERPRETATION 22))
                                            (leaf (token "*" NULL-INTERPRETATION 23))
                                            (leaf (token "==" MEASURE 24))
                                            (leaf (token "*-" SPINE-TERMINATOR 25)))))))
              (path->hfile "../../data/count/two-spines-two-splits.krn"))
(check-expect (lolot->lor (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                                      (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                (list (token "*clefG2" CLEF 1)
                                      (token "*clefG2" CLEF 1))
                                (list (token "*k[]" KEY-SIG 2)
                                      (token "*k[]" KEY-SIG 2))
                                (list (token "*a:" KEY-LABEL 3)
                                      (token "*a:" KEY-LABEL 3))
                                (list (token "*M3/4" TIME-SIG 4)
                                      (token "*M3/4" TIME-SIG 4))
                                (list (token "*^" SPINE-SPLIT 5)
                                      (token "*" NULL-INTERPRETATION 5))
                                (list (token "*" NULL-INTERPRETATION 6)
                                      (token "*" NULL-INTERPRETATION 6)
                                      (token "*^" SPINE-SPLIT 6))
                                (list (token "*" NULL-INTERPRETATION 7)
                                      (token "*^" SPINE-SPLIT 7)
                                      (token "*" NULL-INTERPRETATION 7)
                                      (token "*" NULL-INTERPRETATION 7))
                                (list (token "*" NULL-INTERPRETATION 8)
                                      (token "*" NULL-INTERPRETATION 8)
                                      (token "*" NULL-INTERPRETATION 8)
                                      (token "*" NULL-INTERPRETATION 8)
                                      (token "*^" SPINE-SPLIT 8))
                                (list (token "4c" SPINE-DATA 9)
                                      (token "4c" SPINE-DATA 9)
                                      (token "4c" SPINE-DATA 9)
                                      (token "4c" SPINE-DATA 9)
                                      (token "4c" SPINE-DATA 9)
                                      (token "4c" SPINE-DATA 9))
                                (list (token "4c" SPINE-DATA 10)
                                      (token "4c" SPINE-DATA 10)
                                      (token "4c" SPINE-DATA 10)
                                      (token "4c" SPINE-DATA 10)
                                      (token "4c" SPINE-DATA 10)
                                      (token "4c" SPINE-DATA 10))
                                (list (token "4c" SPINE-DATA 11)
                                      (token "4c" SPINE-DATA 11)
                                      (token "4c" SPINE-DATA 11)
                                      (token "4c" SPINE-DATA 11)
                                      (token "4c" SPINE-DATA 11)
                                      (token "4c" SPINE-DATA 11))
                                (list (token "=2" MEASURE 12)
                                      (token "=2" MEASURE 12)
                                      (token "=2" MEASURE 12)
                                      (token "=2" MEASURE 12)
                                      (token "=2" MEASURE 12)
                                      (token "=2" MEASURE 12))
                                (list (token "4c" SPINE-DATA 13)
                                      (token "4c" SPINE-DATA 13)
                                      (token "4c" SPINE-DATA 13)
                                      (token "4c" SPINE-DATA 13)
                                      (token "4c" SPINE-DATA 13)
                                      (token "4c" SPINE-DATA 13))
                                (list (token "4c" SPINE-DATA 14)
                                      (token "4c" SPINE-DATA 14)
                                      (token "4c" SPINE-DATA 14)
                                      (token "4c" SPINE-DATA 14)
                                      (token "4c" SPINE-DATA 14)
                                      (token "4c" SPINE-DATA 14))
                                (list (token "4c" SPINE-DATA 15)
                                      (token "4c" SPINE-DATA 15)
                                      (token "4c" SPINE-DATA 15)
                                      (token "4c" SPINE-DATA 15)
                                      (token "4c" SPINE-DATA 15)
                                      (token "4c" SPINE-DATA 15))
                                (list (token "=3" MEASURE 16)
                                      (token "=3" MEASURE 16)
                                      (token "=3" MEASURE 16)
                                      (token "=3" MEASURE 16)
                                      (token "=3" MEASURE 16)
                                      (token "=3" MEASURE 16))
                                (list (token "4c" SPINE-DATA 17)
                                      (token "4c" SPINE-DATA 17)
                                      (token "4c" SPINE-DATA 17)
                                      (token "4c" SPINE-DATA 17)
                                      (token "4c" SPINE-DATA 17)
                                      (token "4c" SPINE-DATA 17))
                                (list (token "4c" SPINE-DATA 18)
                                      (token "4c" SPINE-DATA 18)
                                      (token "4c" SPINE-DATA 18)
                                      (token "4c" SPINE-DATA 18)
                                      (token "4c" SPINE-DATA 18)
                                      (token "4c" SPINE-DATA 18))
                                (list (token "4c" SPINE-DATA 19)
                                      (token "4c" SPINE-DATA 19)
                                      (token "4c" SPINE-DATA 19)
                                      (token "4c" SPINE-DATA 19)
                                      (token "4c" SPINE-DATA 19)
                                      (token "4c" SPINE-DATA 19))
                                (list (token "*" NULL-INTERPRETATION 20)
                                      (token "*" NULL-INTERPRETATION 20)
                                      (token "*" NULL-INTERPRETATION 20)
                                      (token "*" NULL-INTERPRETATION 20)
                                      (token "*v" SPINE-JOIN 20)
                                      (token "*v" SPINE-JOIN 20))
                                (list (token "*" NULL-INTERPRETATION 21)
                                      (token "*" NULL-INTERPRETATION 21)
                                      (token "*" NULL-INTERPRETATION 21)
                                      (token "*v" SPINE-JOIN 21)
                                      (token "*v" SPINE-JOIN 21))
                                (list (token "*" NULL-INTERPRETATION 22)
                                      (token "*v" SPINE-JOIN 22)
                                      (token "*v" SPINE-JOIN 22)
                                      (token "*" NULL-INTERPRETATION 22))
                                (list (token "*v" SPINE-JOIN 23)
                                      (token "*v" SPINE-JOIN 23)
                                      (token "*" NULL-INTERPRETATION 23))
                                (list (token "==" MEASURE 24)
                                      (token "==" MEASURE 24))
                                (list (token "*-" SPINE-TERMINATOR 25)
                                      (token "*-" SPINE-TERMINATOR 25))))
              (list (record "**kern\t**kern" TOKEN
                            (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                                  (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                            0)
                    (record "*clefG2\t*clefG2" TOKEN (list (token "*clefG2" CLEF 1)
                                                           (token "*clefG2" CLEF 1))
                            1)
                    (record "*k[]\t*k[]" TOKEN (list (token "*k[]" KEY-SIG 2)
                                                     (token "*k[]" KEY-SIG 2))
                            2)
                    (record "*a:\t*a:" TOKEN (list (token "*a:" KEY-LABEL 3)
                                                   (token "*a:" KEY-LABEL 3))
                            3)
                    (record "*M3/4\t*M3/4" TOKEN (list (token "*M3/4" TIME-SIG 4)
                                                       (token "*M3/4" TIME-SIG 4))
                            4)
                    (record "*^\t*" TOKEN (list (token "*^" SPINE-SPLIT 5)
                                                (token "*" NULL-INTERPRETATION 5))
                            5)
                    (record "*\t*\t*^" TOKEN (list (token "*" NULL-INTERPRETATION 6)
                                                   (token "*" NULL-INTERPRETATION 6)
                                                   (token "*^" SPINE-SPLIT 6))
                            6)
                    (record "*\t*^\t*\t*" TOKEN (list (token "*" NULL-INTERPRETATION 7)
                                                      (token "*^" SPINE-SPLIT 7)
                                                      (token "*" NULL-INTERPRETATION 7)
                                                      (token "*" NULL-INTERPRETATION 7))
                            7)
                    (record "*\t*\t*\t*\t*^" TOKEN (list (token "*" NULL-INTERPRETATION 8)
                                                         (token "*" NULL-INTERPRETATION 8)
                                                         (token "*" NULL-INTERPRETATION 8)
                                                         (token "*" NULL-INTERPRETATION 8)
                                                         (token "*^" SPINE-SPLIT 8))
                            8)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 9)
                                                                 (token "4c" SPINE-DATA 9)
                                                                 (token "4c" SPINE-DATA 9)
                                                                 (token "4c" SPINE-DATA 9)
                                                                 (token "4c" SPINE-DATA 9)
                                                                 (token "4c" SPINE-DATA 9))
                            9)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 10)
                                                                 (token "4c" SPINE-DATA 10)
                                                                 (token "4c" SPINE-DATA 10)
                                                                 (token "4c" SPINE-DATA 10)
                                                                 (token "4c" SPINE-DATA 10)
                                                                 (token "4c" SPINE-DATA 10))
                            10)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 11)
                                                                 (token "4c" SPINE-DATA 11)
                                                                 (token "4c" SPINE-DATA 11)
                                                                 (token "4c" SPINE-DATA 11)
                                                                 (token "4c" SPINE-DATA 11)
                                                                 (token "4c" SPINE-DATA 11))
                            11)
                    (record "=2\t=2\t=2\t=2\t=2\t=2" TOKEN (list (token "=2" MEASURE 12)
                                                                 (token "=2" MEASURE 12)
                                                                 (token "=2" MEASURE 12)
                                                                 (token "=2" MEASURE 12)
                                                                 (token "=2" MEASURE 12)
                                                                 (token "=2" MEASURE 12))
                            12)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 13)
                                                                 (token "4c" SPINE-DATA 13)
                                                                 (token "4c" SPINE-DATA 13)
                                                                 (token "4c" SPINE-DATA 13)
                                                                 (token "4c" SPINE-DATA 13)
                                                                 (token "4c" SPINE-DATA 13))
                            13)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 14)
                                                                 (token "4c" SPINE-DATA 14)
                                                                 (token "4c" SPINE-DATA 14)
                                                                 (token "4c" SPINE-DATA 14)
                                                                 (token "4c" SPINE-DATA 14)
                                                                 (token "4c" SPINE-DATA 14))
                            14)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 15)
                                                                 (token "4c" SPINE-DATA 15)
                                                                 (token "4c" SPINE-DATA 15)
                                                                 (token "4c" SPINE-DATA 15)
                                                                 (token "4c" SPINE-DATA 15)
                                                                 (token "4c" SPINE-DATA 15))
                            15)
                    (record "=3\t=3\t=3\t=3\t=3\t=3" TOKEN (list (token "=3" MEASURE 16)
                                                                 (token "=3" MEASURE 16)
                                                                 (token "=3" MEASURE 16)
                                                                 (token "=3" MEASURE 16)
                                                                 (token "=3" MEASURE 16)
                                                                 (token "=3" MEASURE 16))
                            16)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 17)
                                                                 (token "4c" SPINE-DATA 17)
                                                                 (token "4c" SPINE-DATA 17)
                                                                 (token "4c" SPINE-DATA 17)
                                                                 (token "4c" SPINE-DATA 17)
                                                                 (token "4c" SPINE-DATA 17))
                            17)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 18)
                                                                 (token "4c" SPINE-DATA 18)
                                                                 (token "4c" SPINE-DATA 18)
                                                                 (token "4c" SPINE-DATA 18)
                                                                 (token "4c" SPINE-DATA 18)
                                                                 (token "4c" SPINE-DATA 18))
                            18)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 19)
                                                                 (token "4c" SPINE-DATA 19)
                                                                 (token "4c" SPINE-DATA 19)
                                                                 (token "4c" SPINE-DATA 19)
                                                                 (token "4c" SPINE-DATA 19)
                                                                 (token "4c" SPINE-DATA 19))
                            19)
                    (record "*\t*\t*\t*\t*v\t*v" TOKEN (list (token "*" NULL-INTERPRETATION 20)
                                                             (token "*" NULL-INTERPRETATION 20)
                                                             (token "*" NULL-INTERPRETATION 20)
                                                             (token "*" NULL-INTERPRETATION 20)
                                                             (token "*v" SPINE-JOIN 20)
                                                             (token "*v" SPINE-JOIN 20))
                            20)
                    (record "*\t*\t*\t*v\t*v" TOKEN (list (token "*" NULL-INTERPRETATION 21)
                                                          (token "*" NULL-INTERPRETATION 21)
                                                          (token "*" NULL-INTERPRETATION 21)
                                                          (token "*v" SPINE-JOIN 21)
                                                          (token "*v" SPINE-JOIN 21))
                            21)
                    (record "*\t*v\t*v\t*" TOKEN (list (token "*" NULL-INTERPRETATION 22)
                                                       (token "*v" SPINE-JOIN 22)
                                                       (token "*v" SPINE-JOIN 22)
                                                       (token "*" NULL-INTERPRETATION 22))
                            22)
                    (record "*v\t*v\t*" TOKEN (list (token "*v" SPINE-JOIN 23)
                                                    (token "*v" SPINE-JOIN 23)
                                                    (token "*" NULL-INTERPRETATION 23))
                            23)
                    (record "==\t==" TOKEN (list (token "==" MEASURE 24)
                                                 (token "==" MEASURE 24))
                            24)
                    (record "*-\t*-" TOKEN (list (token "*-" SPINE-TERMINATOR 25)
                                                 (token "*-" SPINE-TERMINATOR 25))
                            25)))
(check-expect (ab-hgraph->lolot
               (ab-hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                            (leaf (token "*clefG2" CLEF 1))
                                            (leaf (token "*k[]" KEY-SIG 2))
                                            (leaf (token "*a:" KEY-LABEL 3))
                                            (leaf (token "*M3/4" TIME-SIG 4))
                                            (parent (token "*^" SPINE-SPLIT 5)
                                                    (list (leaf (token "*" NULL-INTERPRETATION 6))
                                                          (leaf (token "*" NULL-INTERPRETATION 7))
                                                          (leaf (token "*" NULL-INTERPRETATION 8))
                                                          (leaf (token "4c" SPINE-DATA 9))
                                                          (leaf (token "4c" SPINE-DATA 10))
                                                          (leaf (token "4c" SPINE-DATA 11))
                                                          (leaf (token "=2" MEASURE 12))
                                                          (leaf (token "4c" SPINE-DATA 13))
                                                          (leaf (token "4c" SPINE-DATA 14))
                                                          (leaf (token "4c" SPINE-DATA 15))
                                                          (leaf (token "=3" MEASURE 16))
                                                          (leaf (token "4c" SPINE-DATA 17))
                                                          (leaf (token "4c" SPINE-DATA 18))
                                                          (leaf (token "4c" SPINE-DATA 19))
                                                          (leaf (token "*" NULL-INTERPRETATION 20))
                                                          (leaf (token "*" NULL-INTERPRETATION 21))
                                                          (leaf (token "*" NULL-INTERPRETATION 22))
                                                          (leaf (token "*v" SPINE-JOIN 23)))
                                                    (list (leaf (token "*" NULL-INTERPRETATION 6))
                                                          (parent (token "*^" SPINE-SPLIT 7)
                                                                  (list (leaf (token "*" NULL-INTERPRETATION 8))
                                                                        (leaf (token "4c" SPINE-DATA 9))
                                                                        (leaf (token "4c" SPINE-DATA 10))
                                                                        (leaf (token "4c" SPINE-DATA 11))
                                                                        (leaf (token "=2" MEASURE 12))
                                                                        (leaf (token "4c" SPINE-DATA 13))
                                                                        (leaf (token "4c" SPINE-DATA 14))
                                                                        (leaf (token "4c" SPINE-DATA 15))
                                                                        (leaf (token "=3" MEASURE 16))
                                                                        (leaf (token "4c" SPINE-DATA 17))
                                                                        (leaf (token "4c" SPINE-DATA 18))
                                                                        (leaf (token "4c" SPINE-DATA 19))
                                                                        (leaf (token "*" NULL-INTERPRETATION 20))
                                                                        (leaf (token "*" NULL-INTERPRETATION 21))
                                                                        (leaf (token "*v" SPINE-JOIN 22)))
                                                                  (list (leaf (token "*" NULL-INTERPRETATION 8))
                                                                        (leaf (token "4c" SPINE-DATA 9))
                                                                        (leaf (token "4c" SPINE-DATA 10))
                                                                        (leaf (token "4c" SPINE-DATA 11))
                                                                        (leaf (token "=2" MEASURE 12))
                                                                        (leaf (token "4c" SPINE-DATA 13))
                                                                        (leaf (token "4c" SPINE-DATA 14))
                                                                        (leaf (token "4c" SPINE-DATA 15))
                                                                        (leaf (token "=3" MEASURE 16))
                                                                        (leaf (token "4c" SPINE-DATA 17))
                                                                        (leaf (token "4c" SPINE-DATA 18))
                                                                        (leaf (token "4c" SPINE-DATA 19))
                                                                        (leaf (token "*" NULL-INTERPRETATION 20))
                                                                        (leaf (token "*" NULL-INTERPRETATION 21))
                                                                        (leaf (token "*v" SPINE-JOIN 22))))
                                                          (leaf (token "*v" SPINE-JOIN 23))))
                                            (leaf (token "==" MEASURE 24))
                                            (leaf (token "*-" SPINE-TERMINATOR 25)))
                                      (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                            (leaf (token "*clefG2" CLEF 1))
                                            (leaf (token "*k[]" KEY-SIG 2))
                                            (leaf (token "*a:" KEY-LABEL 3))
                                            (leaf (token "*M3/4" TIME-SIG 4))
                                            (leaf (token "*" NULL-INTERPRETATION 5))
                                            (parent (token "*^" SPINE-SPLIT 6)
                                                    (list (leaf (token "*" NULL-INTERPRETATION 7))
                                                          (leaf (token "*" NULL-INTERPRETATION 8))
                                                          (leaf (token "4c" SPINE-DATA 9))
                                                          (leaf (token "4c" SPINE-DATA 10))
                                                          (leaf (token "4c" SPINE-DATA 11))
                                                          (leaf (token "=2" MEASURE 12))
                                                          (leaf (token "4c" SPINE-DATA 13))
                                                          (leaf (token "4c" SPINE-DATA 14))
                                                          (leaf (token "4c" SPINE-DATA 15))
                                                          (leaf (token "=3" MEASURE 16))
                                                          (leaf (token "4c" SPINE-DATA 17))
                                                          (leaf (token "4c" SPINE-DATA 18))
                                                          (leaf (token "4c" SPINE-DATA 19))
                                                          (leaf (token "*" NULL-INTERPRETATION 20))
                                                          (leaf (token "*v" SPINE-JOIN 21)))
                                                    (list (leaf (token "*" NULL-INTERPRETATION 7))
                                                          (parent (token "*^" SPINE-SPLIT 8)
                                                                  (list (leaf (token "4c" SPINE-DATA 9))
                                                                        (leaf (token "4c" SPINE-DATA 10))
                                                                        (leaf (token "4c" SPINE-DATA 11))
                                                                        (leaf (token "=2" MEASURE 12))
                                                                        (leaf (token "4c" SPINE-DATA 13))
                                                                        (leaf (token "4c" SPINE-DATA 14))
                                                                        (leaf (token "4c" SPINE-DATA 15))
                                                                        (leaf (token "=3" MEASURE 16))
                                                                        (leaf (token "4c" SPINE-DATA 17))
                                                                        (leaf (token "4c" SPINE-DATA 18))
                                                                        (leaf (token "4c" SPINE-DATA 19))
                                                                        (leaf (token "*v" SPINE-JOIN 20)))
                                                                  (list (leaf (token "4c" SPINE-DATA 9))
                                                                        (leaf (token "4c" SPINE-DATA 10))
                                                                        (leaf (token "4c" SPINE-DATA 11))
                                                                        (leaf (token "=2" MEASURE 12))
                                                                        (leaf (token "4c" SPINE-DATA 13))
                                                                        (leaf (token "4c" SPINE-DATA 14))
                                                                        (leaf (token "4c" SPINE-DATA 15))
                                                                        (leaf (token "=3" MEASURE 16))
                                                                        (leaf (token "4c" SPINE-DATA 17))
                                                                        (leaf (token "4c" SPINE-DATA 18))
                                                                        (leaf (token "4c" SPINE-DATA 19))
                                                                        (leaf (token "*v" SPINE-JOIN 20))))
                                                          (leaf (token "*v" SPINE-JOIN 21))))
                                            (leaf (token "*" NULL-INTERPRETATION 22))
                                            (leaf (token "*" NULL-INTERPRETATION 23))
                                            (leaf (token "==" MEASURE 24))
                                            (leaf (token "*-" SPINE-TERMINATOR 25)))))))
              (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                          (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                    (list (token "*clefG2" CLEF 1)
                          (token "*clefG2" CLEF 1))
                    (list (token "*k[]" KEY-SIG 2)
                          (token "*k[]" KEY-SIG 2))
                    (list (token "*a:" KEY-LABEL 3)
                          (token "*a:" KEY-LABEL 3))
                    (list (token "*M3/4" TIME-SIG 4)
                          (token "*M3/4" TIME-SIG 4))
                    (list (token "*^" SPINE-SPLIT 5)
                          (token "*" NULL-INTERPRETATION 5))
                    (list (token "*" NULL-INTERPRETATION 6)
                          (token "*" NULL-INTERPRETATION 6)
                          (token "*^" SPINE-SPLIT 6))
                    (list (token "*" NULL-INTERPRETATION 7)
                          (token "*^" SPINE-SPLIT 7)
                          (token "*" NULL-INTERPRETATION 7)
                          (token "*" NULL-INTERPRETATION 7))
                    (list (token "*" NULL-INTERPRETATION 8)
                          (token "*" NULL-INTERPRETATION 8)
                          (token "*" NULL-INTERPRETATION 8)
                          (token "*" NULL-INTERPRETATION 8)
                          (token "*^" SPINE-SPLIT 8))
                    (list (token "4c" SPINE-DATA 9)
                          (token "4c" SPINE-DATA 9)
                          (token "4c" SPINE-DATA 9)
                          (token "4c" SPINE-DATA 9)
                          (token "4c" SPINE-DATA 9)
                          (token "4c" SPINE-DATA 9))
                    (list (token "4c" SPINE-DATA 10)
                          (token "4c" SPINE-DATA 10)
                          (token "4c" SPINE-DATA 10)
                          (token "4c" SPINE-DATA 10)
                          (token "4c" SPINE-DATA 10)
                          (token "4c" SPINE-DATA 10))
                    (list (token "4c" SPINE-DATA 11)
                          (token "4c" SPINE-DATA 11)
                          (token "4c" SPINE-DATA 11)
                          (token "4c" SPINE-DATA 11)
                          (token "4c" SPINE-DATA 11)
                          (token "4c" SPINE-DATA 11))
                    (list (token "=2" MEASURE 12)
                          (token "=2" MEASURE 12)
                          (token "=2" MEASURE 12)
                          (token "=2" MEASURE 12)
                          (token "=2" MEASURE 12)
                          (token "=2" MEASURE 12))
                    (list (token "4c" SPINE-DATA 13)
                          (token "4c" SPINE-DATA 13)
                          (token "4c" SPINE-DATA 13)
                          (token "4c" SPINE-DATA 13)
                          (token "4c" SPINE-DATA 13)
                          (token "4c" SPINE-DATA 13))
                    (list (token "4c" SPINE-DATA 14)
                          (token "4c" SPINE-DATA 14)
                          (token "4c" SPINE-DATA 14)
                          (token "4c" SPINE-DATA 14)
                          (token "4c" SPINE-DATA 14)
                          (token "4c" SPINE-DATA 14))
                    (list (token "4c" SPINE-DATA 15)
                          (token "4c" SPINE-DATA 15)
                          (token "4c" SPINE-DATA 15)
                          (token "4c" SPINE-DATA 15)
                          (token "4c" SPINE-DATA 15)
                          (token "4c" SPINE-DATA 15))
                    (list (token "=3" MEASURE 16)
                          (token "=3" MEASURE 16)
                          (token "=3" MEASURE 16)
                          (token "=3" MEASURE 16)
                          (token "=3" MEASURE 16)
                          (token "=3" MEASURE 16))
                    (list (token "4c" SPINE-DATA 17)
                          (token "4c" SPINE-DATA 17)
                          (token "4c" SPINE-DATA 17)
                          (token "4c" SPINE-DATA 17)
                          (token "4c" SPINE-DATA 17)
                          (token "4c" SPINE-DATA 17))
                    (list (token "4c" SPINE-DATA 18)
                          (token "4c" SPINE-DATA 18)
                          (token "4c" SPINE-DATA 18)
                          (token "4c" SPINE-DATA 18)
                          (token "4c" SPINE-DATA 18)
                          (token "4c" SPINE-DATA 18))
                    (list (token "4c" SPINE-DATA 19)
                          (token "4c" SPINE-DATA 19)
                          (token "4c" SPINE-DATA 19)
                          (token "4c" SPINE-DATA 19)
                          (token "4c" SPINE-DATA 19)
                          (token "4c" SPINE-DATA 19))
                    (list (token "*" NULL-INTERPRETATION 20)
                          (token "*" NULL-INTERPRETATION 20)
                          (token "*" NULL-INTERPRETATION 20)
                          (token "*" NULL-INTERPRETATION 20)
                          (token "*v" SPINE-JOIN 20)
                          (token "*v" SPINE-JOIN 20))
                    (list (token "*" NULL-INTERPRETATION 21)
                          (token "*" NULL-INTERPRETATION 21)
                          (token "*" NULL-INTERPRETATION 21)
                          (token "*v" SPINE-JOIN 21)
                          (token "*v" SPINE-JOIN 21))
                    (list (token "*" NULL-INTERPRETATION 22)
                          (token "*v" SPINE-JOIN 22)
                          (token "*v" SPINE-JOIN 22)
                          (token "*" NULL-INTERPRETATION 22))
                    (list (token "*v" SPINE-JOIN 23)
                          (token "*v" SPINE-JOIN 23)
                          (token "*" NULL-INTERPRETATION 23))
                    (list (token "==" MEASURE 24)
                          (token "==" MEASURE 24))
                    (list (token "*-" SPINE-TERMINATOR 25)
                          (token "*-" SPINE-TERMINATOR 25))))
(check-expect (hfile->ab-hgraph (path->hfile "../../data/count/two-spines-two-splits.krn")
                                ab-hgraph)
              (ab-hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                           (leaf (token "*clefG2" CLEF 1))
                                           (leaf (token "*k[]" KEY-SIG 2))
                                           (leaf (token "*a:" KEY-LABEL 3))
                                           (leaf (token "*M3/4" TIME-SIG 4))
                                           (parent (token "*^" SPINE-SPLIT 5)
                                                   (list (leaf (token "*" NULL-INTERPRETATION 6))
                                                         (leaf (token "*" NULL-INTERPRETATION 7))
                                                         (leaf (token "*" NULL-INTERPRETATION 8))
                                                         (leaf (token "4c" SPINE-DATA 9))
                                                         (leaf (token "4c" SPINE-DATA 10))
                                                         (leaf (token "4c" SPINE-DATA 11))
                                                         (leaf (token "=2" MEASURE 12))
                                                         (leaf (token "4c" SPINE-DATA 13))
                                                         (leaf (token "4c" SPINE-DATA 14))
                                                         (leaf (token "4c" SPINE-DATA 15))
                                                         (leaf (token "=3" MEASURE 16))
                                                         (leaf (token "4c" SPINE-DATA 17))
                                                         (leaf (token "4c" SPINE-DATA 18))
                                                         (leaf (token "4c" SPINE-DATA 19))
                                                         (leaf (token "*" NULL-INTERPRETATION 20))
                                                         (leaf (token "*" NULL-INTERPRETATION 21))
                                                         (leaf (token "*" NULL-INTERPRETATION 22))
                                                         (leaf (token "*v" SPINE-JOIN 23)))
                                                   (list (leaf (token "*" NULL-INTERPRETATION 6))
                                                         (parent (token "*^" SPINE-SPLIT 7)
                                                                 (list (leaf (token "*" NULL-INTERPRETATION 8))
                                                                       (leaf (token "4c" SPINE-DATA 9))
                                                                       (leaf (token "4c" SPINE-DATA 10))
                                                                       (leaf (token "4c" SPINE-DATA 11))
                                                                       (leaf (token "=2" MEASURE 12))
                                                                       (leaf (token "4c" SPINE-DATA 13))
                                                                       (leaf (token "4c" SPINE-DATA 14))
                                                                       (leaf (token "4c" SPINE-DATA 15))
                                                                       (leaf (token "=3" MEASURE 16))
                                                                       (leaf (token "4c" SPINE-DATA 17))
                                                                       (leaf (token "4c" SPINE-DATA 18))
                                                                       (leaf (token "4c" SPINE-DATA 19))
                                                                       (leaf (token "*" NULL-INTERPRETATION 20))
                                                                       (leaf (token "*" NULL-INTERPRETATION 21))
                                                                       (leaf (token "*v" SPINE-JOIN 22)))
                                                                 (list (leaf (token "*" NULL-INTERPRETATION 8))
                                                                       (leaf (token "4c" SPINE-DATA 9))
                                                                       (leaf (token "4c" SPINE-DATA 10))
                                                                       (leaf (token "4c" SPINE-DATA 11))
                                                                       (leaf (token "=2" MEASURE 12))
                                                                       (leaf (token "4c" SPINE-DATA 13))
                                                                       (leaf (token "4c" SPINE-DATA 14))
                                                                       (leaf (token "4c" SPINE-DATA 15))
                                                                       (leaf (token "=3" MEASURE 16))
                                                                       (leaf (token "4c" SPINE-DATA 17))
                                                                       (leaf (token "4c" SPINE-DATA 18))
                                                                       (leaf (token "4c" SPINE-DATA 19))
                                                                       (leaf (token "*" NULL-INTERPRETATION 20))
                                                                       (leaf (token "*" NULL-INTERPRETATION 21))
                                                                       (leaf (token "*v" SPINE-JOIN 22))))
                                                         (leaf (token "*v" SPINE-JOIN 23))))
                                           (leaf (token "==" MEASURE 24))
                                           (leaf (token "*-" SPINE-TERMINATOR 25)))
                                     (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                           (leaf (token "*clefG2" CLEF 1))
                                           (leaf (token "*k[]" KEY-SIG 2))
                                           (leaf (token "*a:" KEY-LABEL 3))
                                           (leaf (token "*M3/4" TIME-SIG 4))
                                           (leaf (token "*" NULL-INTERPRETATION 5))
                                           (parent (token "*^" SPINE-SPLIT 6)
                                                   (list (leaf (token "*" NULL-INTERPRETATION 7))
                                                         (leaf (token "*" NULL-INTERPRETATION 8))
                                                         (leaf (token "4c" SPINE-DATA 9))
                                                         (leaf (token "4c" SPINE-DATA 10))
                                                         (leaf (token "4c" SPINE-DATA 11))
                                                         (leaf (token "=2" MEASURE 12))
                                                         (leaf (token "4c" SPINE-DATA 13))
                                                         (leaf (token "4c" SPINE-DATA 14))
                                                         (leaf (token "4c" SPINE-DATA 15))
                                                         (leaf (token "=3" MEASURE 16))
                                                         (leaf (token "4c" SPINE-DATA 17))
                                                         (leaf (token "4c" SPINE-DATA 18))
                                                         (leaf (token "4c" SPINE-DATA 19))
                                                         (leaf (token "*" NULL-INTERPRETATION 20))
                                                         (leaf (token "*v" SPINE-JOIN 21)))
                                                   (list (leaf (token "*" NULL-INTERPRETATION 7))
                                                         (parent (token "*^" SPINE-SPLIT 8)
                                                                 (list (leaf (token "4c" SPINE-DATA 9))
                                                                       (leaf (token "4c" SPINE-DATA 10))
                                                                       (leaf (token "4c" SPINE-DATA 11))
                                                                       (leaf (token "=2" MEASURE 12))
                                                                       (leaf (token "4c" SPINE-DATA 13))
                                                                       (leaf (token "4c" SPINE-DATA 14))
                                                                       (leaf (token "4c" SPINE-DATA 15))
                                                                       (leaf (token "=3" MEASURE 16))
                                                                       (leaf (token "4c" SPINE-DATA 17))
                                                                       (leaf (token "4c" SPINE-DATA 18))
                                                                       (leaf (token "4c" SPINE-DATA 19))
                                                                       (leaf (token "*v" SPINE-JOIN 20)))
                                                                 (list (leaf (token "4c" SPINE-DATA 9))
                                                                       (leaf (token "4c" SPINE-DATA 10))
                                                                       (leaf (token "4c" SPINE-DATA 11))
                                                                       (leaf (token "=2" MEASURE 12))
                                                                       (leaf (token "4c" SPINE-DATA 13))
                                                                       (leaf (token "4c" SPINE-DATA 14))
                                                                       (leaf (token "4c" SPINE-DATA 15))
                                                                       (leaf (token "=3" MEASURE 16))
                                                                       (leaf (token "4c" SPINE-DATA 17))
                                                                       (leaf (token "4c" SPINE-DATA 18))
                                                                       (leaf (token "4c" SPINE-DATA 19))
                                                                       (leaf (token "*v" SPINE-JOIN 20))))
                                                         (leaf (token "*v" SPINE-JOIN 21))))
                                           (leaf (token "*" NULL-INTERPRETATION 22))
                                           (leaf (token "*" NULL-INTERPRETATION 23))
                                           (leaf (token "==" MEASURE 24))
                                           (leaf (token "*-" SPINE-TERMINATOR 25)))))))
; branch->lot for spine 0
(check-expect (branch->lot (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                 (leaf (token "*clefG2" CLEF 1))
                                 (leaf (token "*k[]" KEY-SIG 2))
                                 (leaf (token "*a:" KEY-LABEL 3))
                                 (leaf (token "*M3/4" TIME-SIG 4))
                                 (parent (token "*^" SPINE-SPLIT 5)
                                         (list (leaf (token "*" NULL-INTERPRETATION 6))
                                               (leaf (token "*" NULL-INTERPRETATION 7))
                                               (leaf (token "*" NULL-INTERPRETATION 8))
                                               (leaf (token "4c" SPINE-DATA 9))
                                               (leaf (token "4c" SPINE-DATA 10))
                                               (leaf (token "4c" SPINE-DATA 11))
                                               (leaf (token "=2" MEASURE 12))
                                               (leaf (token "4c" SPINE-DATA 13))
                                               (leaf (token "4c" SPINE-DATA 14))
                                               (leaf (token "4c" SPINE-DATA 15))
                                               (leaf (token "=3" MEASURE 16))
                                               (leaf (token "4c" SPINE-DATA 17))
                                               (leaf (token "4c" SPINE-DATA 18))
                                               (leaf (token "4c" SPINE-DATA 19))
                                               (leaf (token "*" NULL-INTERPRETATION 20))
                                               (leaf (token "*" NULL-INTERPRETATION 21))
                                               (leaf (token "*" NULL-INTERPRETATION 22))
                                               (leaf (token "*v" SPINE-JOIN 23)))
                                         (list (leaf (token "*" NULL-INTERPRETATION 6))
                                                     (parent (token "*^" SPINE-SPLIT 7)
                                                             (list (leaf (token "*" NULL-INTERPRETATION 8))
                                                                   (leaf (token "4c" SPINE-DATA 9))
                                                                   (leaf (token "4c" SPINE-DATA 10))
                                                                   (leaf (token "4c" SPINE-DATA 11))
                                                                   (leaf (token "=2" MEASURE 12))
                                                                   (leaf (token "4c" SPINE-DATA 13))
                                                                   (leaf (token "4c" SPINE-DATA 14))
                                                                   (leaf (token "4c" SPINE-DATA 15))
                                                                   (leaf (token "=3" MEASURE 16))
                                                                   (leaf (token "4c" SPINE-DATA 17))
                                                                   (leaf (token "4c" SPINE-DATA 18))
                                                                   (leaf (token "4c" SPINE-DATA 19))
                                                                   (leaf (token "*" NULL-INTERPRETATION 20))
                                                                   (leaf (token "*" NULL-INTERPRETATION 21))
                                                                   (leaf (token "*v" SPINE-JOIN 22)))
                                                             (list (leaf (token "*" NULL-INTERPRETATION 8))
                                                                   (leaf (token "4c" SPINE-DATA 9))
                                                                   (leaf (token "4c" SPINE-DATA 10))
                                                                   (leaf (token "4c" SPINE-DATA 11))
                                                                   (leaf (token "=2" MEASURE 12))
                                                                   (leaf (token "4c" SPINE-DATA 13))
                                                                   (leaf (token "4c" SPINE-DATA 14))
                                                                   (leaf (token "4c" SPINE-DATA 15))
                                                                   (leaf (token "=3" MEASURE 16))
                                                                   (leaf (token "4c" SPINE-DATA 17))
                                                                   (leaf (token "4c" SPINE-DATA 18))
                                                                   (leaf (token "4c" SPINE-DATA 19))
                                                                   (leaf (token "*" NULL-INTERPRETATION 20))
                                                                   (leaf (token "*" NULL-INTERPRETATION 21))
                                                                   (leaf (token "*v" SPINE-JOIN 22))))
                                                             (leaf (token "*v" SPINE-JOIN 23))))
                                               (leaf (token "==" MEASURE 24))
                                               (leaf (token "*-" SPINE-TERMINATOR 25))))
              (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                    (token "*clefG2" CLEF 1)
                    (token "*k[]" KEY-SIG 2)
                    (token "*a:" KEY-LABEL 3)
                    (token "*M3/4" TIME-SIG 4)
                    (token "*^" SPINE-SPLIT 5)
                    (token "*" NULL-INTERPRETATION 6)
                    (token "*" NULL-INTERPRETATION 7)
                    (token "*" NULL-INTERPRETATION 8)
                    (token "4c" SPINE-DATA 9)
                    (token "4c" SPINE-DATA 10)
                    (token "4c" SPINE-DATA 11)
                    (token "=2" MEASURE 12)
                    (token "4c" SPINE-DATA 13)
                    (token "4c" SPINE-DATA 14)
                    (token "4c" SPINE-DATA 15)
                    (token "=3" MEASURE 16)
                    (token "4c" SPINE-DATA 17)
                    (token "4c" SPINE-DATA 18)
                    (token "4c" SPINE-DATA 19)
                    (token "*" NULL-INTERPRETATION 20)
                    (token "*" NULL-INTERPRETATION 21)
                    (token "*" NULL-INTERPRETATION 22)
                    (token "*v" SPINE-JOIN 23)
                    (token "*" NULL-INTERPRETATION 6)
                    (token "*^" SPINE-SPLIT 7)
                    (token "*" NULL-INTERPRETATION 8)
                    (token "4c" SPINE-DATA 9)
                    (token "4c" SPINE-DATA 10)
                    (token "4c" SPINE-DATA 11)
                    (token "=2" MEASURE 12)
                    (token "4c" SPINE-DATA 13)
                    (token "4c" SPINE-DATA 14)
                    (token "4c" SPINE-DATA 15)
                    (token "=3" MEASURE 16)
                    (token "4c" SPINE-DATA 17)
                    (token "4c" SPINE-DATA 18)
                    (token "4c" SPINE-DATA 19)
                    (token "*" NULL-INTERPRETATION 20)
                    (token "*" NULL-INTERPRETATION 21)
                    (token "*v" SPINE-JOIN 22)
                    (token "*" NULL-INTERPRETATION 8)
                    (token "4c" SPINE-DATA 9)
                    (token "4c" SPINE-DATA 10)
                    (token "4c" SPINE-DATA 11)
                    (token "=2" MEASURE 12)
                    (token "4c" SPINE-DATA 13)
                    (token "4c" SPINE-DATA 14)
                    (token "4c" SPINE-DATA 15)
                    (token "=3" MEASURE 16)
                    (token "4c" SPINE-DATA 17)
                    (token "4c" SPINE-DATA 18)
                    (token "4c" SPINE-DATA 19)
                    (token "*" NULL-INTERPRETATION 20)
                    (token "*" NULL-INTERPRETATION 21)
                    (token "*v" SPINE-JOIN 22)
                    (token "*v" SPINE-JOIN 23)
                    (token "==" MEASURE 24)
                    (token "*-" SPINE-TERMINATOR 25)))
; branch->lot for spine 1
(check-expect (branch->lot (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                 (leaf (token "*clefG2" CLEF 1))
                                 (leaf (token "*k[]" KEY-SIG 2))
                                 (leaf (token "*a:" KEY-LABEL 3))
                                 (leaf (token "*M3/4" TIME-SIG 4))
                                 (leaf (token "*" NULL-INTERPRETATION 5))
                                 (parent (token "*^" SPINE-SPLIT 6)
                                         (list (leaf (token "*" NULL-INTERPRETATION 7))
                                               (leaf (token "*" NULL-INTERPRETATION 8))
                                               (leaf (token "4c" SPINE-DATA 9))
                                               (leaf (token "4c" SPINE-DATA 10))
                                               (leaf (token "4c" SPINE-DATA 11))
                                               (leaf (token "=2" MEASURE 12))
                                               (leaf (token "4c" SPINE-DATA 13))
                                               (leaf (token "4c" SPINE-DATA 14))
                                               (leaf (token "4c" SPINE-DATA 15))
                                               (leaf (token "=3" MEASURE 16))
                                               (leaf (token "4c" SPINE-DATA 17))
                                               (leaf (token "4c" SPINE-DATA 18))
                                               (leaf (token "4c" SPINE-DATA 19))
                                               (leaf (token "*" NULL-INTERPRETATION 20))
                                               (leaf (token "*v" SPINE-JOIN 21)))
                                         (list (leaf (token "*" NULL-INTERPRETATION 7))
                                               (parent (token "*^" SPINE-SPLIT 8)
                                                       (list (leaf (token "4c" SPINE-DATA 9))
                                                             (leaf (token "4c" SPINE-DATA 10))
                                                             (leaf (token "4c" SPINE-DATA 11))
                                                             (leaf (token "=2" MEASURE 12))
                                                             (leaf (token "4c" SPINE-DATA 13))
                                                             (leaf (token "4c" SPINE-DATA 14))
                                                             (leaf (token "4c" SPINE-DATA 15))
                                                             (leaf (token "=3" MEASURE 16))
                                                             (leaf (token "4c" SPINE-DATA 17))
                                                             (leaf (token "4c" SPINE-DATA 18))
                                                             (leaf (token "4c" SPINE-DATA 19))
                                                             (leaf (token "*v" SPINE-JOIN 20)))
                                                       (list (leaf (token "4c" SPINE-DATA 9))
                                                             (leaf (token "4c" SPINE-DATA 10))
                                                             (leaf (token "4c" SPINE-DATA 11))
                                                             (leaf (token "=2" MEASURE 12))
                                                             (leaf (token "4c" SPINE-DATA 13))
                                                             (leaf (token "4c" SPINE-DATA 14))
                                                             (leaf (token "4c" SPINE-DATA 15))
                                                             (leaf (token "=3" MEASURE 16))
                                                             (leaf (token "4c" SPINE-DATA 17))
                                                             (leaf (token "4c" SPINE-DATA 18))
                                                             (leaf (token "4c" SPINE-DATA 19))
                                                             (leaf (token "*v" SPINE-JOIN 20))))
                                               (leaf (token "*v" SPINE-JOIN 21))))
                                 (leaf (token "*" NULL-INTERPRETATION 22))
                                 (leaf (token "*" NULL-INTERPRETATION 23))
                                 (leaf (token "==" MEASURE 24))
                                 (leaf (token "*-" SPINE-TERMINATOR 25))))
              (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                    (token "*clefG2" CLEF 1)
                    (token "*k[]" KEY-SIG 2)
                    (token "*a:" KEY-LABEL 3)
                    (token "*M3/4" TIME-SIG 4)
                    (token "*" NULL-INTERPRETATION 5)
                    (token "*^" SPINE-SPLIT 6)
                    (token "*" NULL-INTERPRETATION 7)
                    (token "*" NULL-INTERPRETATION 8)
                    (token "4c" SPINE-DATA 9)
                    (token "4c" SPINE-DATA 10)
                    (token "4c" SPINE-DATA 11)
                    (token "=2" MEASURE 12)
                    (token "4c" SPINE-DATA 13)
                    (token "4c" SPINE-DATA 14)
                    (token "4c" SPINE-DATA 15)
                    (token "=3" MEASURE 16)
                    (token "4c" SPINE-DATA 17)
                    (token "4c" SPINE-DATA 18)
                    (token "4c" SPINE-DATA 19)
                    (token "*" NULL-INTERPRETATION 20)
                    (token "*v" SPINE-JOIN 21)
                    (token "*" NULL-INTERPRETATION 7)
                    (token "*^" SPINE-SPLIT 8)
                    (token "4c" SPINE-DATA 9)
                    (token "4c" SPINE-DATA 10)
                    (token "4c" SPINE-DATA 11)
                    (token "=2" MEASURE 12)
                    (token "4c" SPINE-DATA 13)
                    (token "4c" SPINE-DATA 14)
                    (token "4c" SPINE-DATA 15)
                    (token "=3" MEASURE 16)
                    (token "4c" SPINE-DATA 17)
                    (token "4c" SPINE-DATA 18)
                    (token "4c" SPINE-DATA 19)
                    (token "*v" SPINE-JOIN 20)
                    (token "4c" SPINE-DATA 9)
                    (token "4c" SPINE-DATA 10)
                    (token "4c" SPINE-DATA 11)
                    (token "=2" MEASURE 12)
                    (token "4c" SPINE-DATA 13)
                    (token "4c" SPINE-DATA 14)
                    (token "4c" SPINE-DATA 15)
                    (token "=3" MEASURE 16)
                    (token "4c" SPINE-DATA 17)
                    (token "4c" SPINE-DATA 18)
                    (token "4c" SPINE-DATA 19)
                    (token "*v" SPINE-JOIN 20)
                    (token "*v" SPINE-JOIN 21)
                    (token "*" NULL-INTERPRETATION 22)
                    (token "*" NULL-INTERPRETATION 23)
                    (token "==" MEASURE 24)
                    (token "*-" SPINE-TERMINATOR 25)))

(test)
