#lang racket/base

(require "../../../../../parser/HumdrumSyntax.rkt"
         "../../../../../parser/file-fn.rkt"
         "../../../../../parser/spine-parsing-fn.rkt"
         "../../../../../parser/humdrum-graph/HumdrumGraph.rkt"
         "../../../../../parser/humdrum-graph/hfile-to-hgraph-fn.rkt"
         "../../../../../parser/humdrum-graph/hgraph-to-hfile-fn.rkt"
         "../../../../../parser/linked-spine/LinkedSpine.rkt"
         "../../../../../parser/linked-spine/gspines-to-linked-spines-fn.rkt"
         test-engine/racket-tests)

(define one-spine-no-splits (path->hfile "../../data/count/one-spine-no-splits.krn"))

;; Node definitions
(define TERM-17-0 (terminator-node (token "*-" 'SpineTerminator 17 0)))
(define M-16-0 (token-node (token "==" 'Measure 16 0) (box-immutable TERM-17-0)))
(define 4c-15-0 (token-node (token "4c" 'SpineData 15 0) (box-immutable M-16-0)))
(define 4c-14-0 (token-node (token "4c" 'SpineData 14 0) (box-immutable 4c-15-0)))
(define 4c-13-0 (token-node (token "4c" 'SpineData 13 0) (box-immutable 4c-14-0)))
(define M-12-0 (token-node (token "=3" 'Measure 12 0) (box-immutable 4c-13-0)))
(define 4c-11-0 (token-node (token "4c" 'SpineData 11 0) (box-immutable M-12-0)))
(define 4c-10-0 (token-node (token "4c" 'SpineData 10 0) (box-immutable 4c-11-0)))
(define 4c-9-0 (token-node (token "4c" 'SpineData 9 0) (box-immutable 4c-10-0)))
(define M-8-0 (token-node (token "=2" 'Measure 8 0) (box-immutable 4c-9-0)))
(define 4c-7-0 (token-node (token "4c" 'SpineData 7 0) (box-immutable M-8-0)))
(define 4c-6-0 (token-node (token "4c" 'SpineData 6 0) (box-immutable 4c-7-0)))
(define 4c-5-0 (token-node (token "4c" 'SpineData 5 0) (box-immutable 4c-6-0)))
(define TS-4-0 (token-node (token "*M3/4" 'TimeSignature 4 0) (box-immutable 4c-5-0)))
(define KL-3-0 (token-node (token "*a:" 'KeyLabel 3 0) (box-immutable TS-4-0)))
(define KS-2-0 (token-node (token "*k[]" 'KeySignature 2 0) (box-immutable KL-3-0)))
(define CL-1-0 (token-node (token "*clefG2" 'Clef 1 0) (box-immutable KS-2-0)))
(define KERN-0-0 (token-node (token "**kern" 'ExclusiveInterpretation 0 0) (box-immutable CL-1-0)))

(check-expect (path->hfile "../../data/count/one-spine-no-splits.krn")
              (hfile (list (record "**kern"
                                   'ExclusiveInterpretation
                                   (list (token "**kern" 'ExclusiveInterpretation 0 0))
                                   0)
                           (record "*clefG2"
                                   'TandemInterpretation
                                   (list (token "*clefG2" 'Clef 1 0))
                                   1)
                           (record "*k[]"
                                   'TandemInterpretation
                                   (list (token "*k[]" 'KeySignature 2 0))
                                   2)
                           (record "*a:"
                                   'TandemInterpretation
                                   (list (token "*a:" 'KeyLabel 3 0))
                                   3)
                           (record "*M3/4"
                                   'TandemInterpretation
                                   (list (token "*M3/4" 'TimeSignature 4 0))
                                   4)
                           (record "4c" 'Token (list (token "4c" 'SpineData 5 0)) 5)
                           (record "4c" 'Token (list (token "4c" 'SpineData 6 0)) 6)
                           (record "4c" 'Token (list (token "4c" 'SpineData 7 0)) 7)
                           (record "=2" 'Measure (list (token "=2" 'Measure 8 0)) 8)
                           (record "4c" 'Token (list (token "4c" 'SpineData 9 0)) 9)
                           (record "4c" 'Token (list (token "4c" 'SpineData 10 0)) 10)
                           (record "4c" 'Token (list (token "4c" 'SpineData 11 0)) 11)
                           (record "=3" 'Measure (list (token "=3" 'Measure 12 0)) 12)
                           (record "4c" 'Token (list (token "4c" 'SpineData 13 0)) 13)
                           (record "4c" 'Token (list (token "4c" 'SpineData 14 0)) 14)
                           (record "4c" 'Token (list (token "4c" 'SpineData 15 0)) 15)
                           (record "==" 'Measure (list (token "==" 'Measure 16 0)) 16)
                           (record "*-"
                                   'TandemInterpretation
                                   (list (token "*-" 'SpineTerminator 17 0))
                                   17))))
(check-expect (spine-parser one-spine-no-splits)
              (list (global-spine 'Kern
                                  (list (list (token "**kern" 'ExclusiveInterpretation 0 0))
                                        (list (token "*clefG2" 'Clef 1 0))
                                        (list (token "*k[]" 'KeySignature 2 0))
                                        (list (token "*a:" 'KeyLabel 3 0))
                                        (list (token "*M3/4" 'TimeSignature 4 0))
                                        (list (token "4c" 'SpineData 5 0))
                                        (list (token "4c" 'SpineData 6 0))
                                        (list (token "4c" 'SpineData 7 0))
                                        (list (token "=2" 'Measure 8 0))
                                        (list (token "4c" 'SpineData 9 0))
                                        (list (token "4c" 'SpineData 10 0))
                                        (list (token "4c" 'SpineData 11 0))
                                        (list (token "=3" 'Measure 12 0))
                                        (list (token "4c" 'SpineData 13 0))
                                        (list (token "4c" 'SpineData 14 0))
                                        (list (token "4c" 'SpineData 15 0))
                                        (list (token "==" 'Measure 16 0))
                                        (list (token "*-" 'SpineTerminator 17 0)))
                                  0)))
(check-expect (hgraph->hfile (hgraph
                              (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                                (leaf (token "*clefG2" 'Clef 1 0))
                                                (leaf (token "*k[]" 'KeySignature 2 0))
                                                (leaf (token "*a:" 'KeyLabel 3 0))
                                                (leaf (token "*M3/4" 'TimeSignature 4 0))
                                                (leaf (token "4c" 'SpineData 5 0))
                                                (leaf (token "4c" 'SpineData 6 0))
                                                (leaf (token "4c" 'SpineData 7 0))
                                                (leaf (token "=2" 'Measure 8 0))
                                                (leaf (token "4c" 'SpineData 9 0))
                                                (leaf (token "4c" 'SpineData 10 0))
                                                (leaf (token "4c" 'SpineData 11 0))
                                                (leaf (token "=3" 'Measure 12 0))
                                                (leaf (token "4c" 'SpineData 13 0))
                                                (leaf (token "4c" 'SpineData 14 0))
                                                (leaf (token "4c" 'SpineData 15 0))
                                                (leaf (token "==" 'Measure 16 0))
                                                (leaf (token "*-" 'SpineTerminator 17 0)))))))
              one-spine-no-splits)
(check-expect (tokens->records (list (list (token "**kern" 'ExclusiveInterpretation 0 0))
                                (list (token "*clefG2" 'Clef 1 0))
                                (list (token "*k[]" 'KeySignature 2 0))
                                (list (token "*a:" 'KeyLabel 3 0))
                                (list (token "*M3/4" 'TimeSignature 4 0))
                                (list (token "4c" 'SpineData 5 0))
                                (list (token "4c" 'SpineData 6 0))
                                (list (token "4c" 'SpineData 7 0))
                                (list (token "=2" 'Measure 8 0))
                                (list (token "4c" 'SpineData 9 0))
                                (list (token "4c" 'SpineData 10 0))
                                (list (token "4c" 'SpineData 11 0))
                                (list (token "=3" 'Measure 12 0))
                                (list (token "4c" 'SpineData 13 0))
                                (list (token "4c" 'SpineData 14 0))
                                (list (token "4c" 'SpineData 15 0))
                                (list (token "==" 'Measure 16 0))
                                (list (token "*-" 'SpineTerminator 17 0))))
              (list (record "**kern"
                            'ExclusiveInterpretation
                            (list (token "**kern" 'ExclusiveInterpretation 0 0))
                            0)
                    (record "*clefG2" 'TandemInterpretation (list (token "*clefG2" 'Clef 1 0)) 1)
                    (record "*k[]" 'TandemInterpretation (list (token "*k[]" 'KeySignature 2 0)) 2)
                    (record "*a:" 'TandemInterpretation (list (token "*a:" 'KeyLabel 3 0)) 3)
                    (record "*M3/4"
                            'TandemInterpretation
                            (list (token "*M3/4" 'TimeSignature 4 0))
                            4)
                    (record "4c" 'Token (list (token "4c" 'SpineData 5 0)) 5)
                    (record "4c" 'Token (list (token "4c" 'SpineData 6 0)) 6)
                    (record "4c" 'Token (list (token "4c" 'SpineData 7 0)) 7)
                    (record "=2" 'Measure (list (token "=2" 'Measure 8 0)) 8)
                    (record "4c" 'Token (list (token "4c" 'SpineData 9 0)) 9)
                    (record "4c" 'Token (list (token "4c" 'SpineData 10 0)) 10)
                    (record "4c" 'Token (list (token "4c" 'SpineData 11 0)) 11)
                    (record "=3" 'Measure (list (token "=3" 'Measure 12 0)) 12)
                    (record "4c" 'Token (list (token "4c" 'SpineData 13 0)) 13)
                    (record "4c" 'Token (list (token "4c" 'SpineData 14 0)) 14)
                    (record "4c" 'Token (list (token "4c" 'SpineData 15 0)) 15)
                    (record "==" 'Measure (list (token "==" 'Measure 16 0)) 16)
                    (record "*-"
                            'TandemInterpretation
                            (list (token "*-" 'SpineTerminator 17 0))
                            17)))
(check-expect (hgraph->tokens (hgraph
                              (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                                (leaf (token "*clefG2" 'Clef 1 0))
                                                (leaf (token "*k[]" 'KeySignature 2 0))
                                                (leaf (token "*a:" 'KeyLabel 3 0))
                                                (leaf (token "*M3/4" 'TimeSignature 4 0))
                                                (leaf (token "4c" 'SpineData 5 0))
                                                (leaf (token "4c" 'SpineData 6 0))
                                                (leaf (token "4c" 'SpineData 7 0))
                                                (leaf (token "=2" 'Measure 8 0))
                                                (leaf (token "4c" 'SpineData 9 0))
                                                (leaf (token "4c" 'SpineData 10 0))
                                                (leaf (token "4c" 'SpineData 11 0))
                                                (leaf (token "=3" 'Measure 12 0))
                                                (leaf (token "4c" 'SpineData 13 0))
                                                (leaf (token "4c" 'SpineData 14 0))
                                                (leaf (token "4c" 'SpineData 15 0))
                                                (leaf (token "==" 'Measure 16 0))
                                                (leaf (token "*-" 'SpineTerminator 17 0)))))))
              (list (list (token "**kern" 'ExclusiveInterpretation 0 0))
                    (list (token "*clefG2" 'Clef 1 0))
                    (list (token "*k[]" 'KeySignature 2 0))
                    (list (token "*a:" 'KeyLabel 3 0))
                    (list (token "*M3/4" 'TimeSignature 4 0))
                    (list (token "4c" 'SpineData 5 0))
                    (list (token "4c" 'SpineData 6 0))
                    (list (token "4c" 'SpineData 7 0))
                    (list (token "=2" 'Measure 8 0))
                    (list (token "4c" 'SpineData 9 0))
                    (list (token "4c" 'SpineData 10 0))
                    (list (token "4c" 'SpineData 11 0))
                    (list (token "=3" 'Measure 12 0))
                    (list (token "4c" 'SpineData 13 0))
                    (list (token "4c" 'SpineData 14 0))
                    (list (token "4c" 'SpineData 15 0))
                    (list (token "==" 'Measure 16 0))
                    (list (token "*-" 'SpineTerminator 17 0))))
#|
(check-expect (hfile->hgraph one-spine-no-splits)
              (hgraph (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                        (leaf (token "*clefG2" 'Clef 1 0))
                                        (leaf (token "*k[]" 'KeySignature 2 0))
                                        (leaf (token "*a:" 'KeyLabel 3 0))
                                        (leaf (token "*M3/4" 'TimeSignature 4 0))
                                        (leaf (token "4c" 'SpineData 5 0))
                                        (leaf (token "4c" 'SpineData 6 0))
                                        (leaf (token "4c" 'SpineData 7 0))
                                        (leaf (token "=2" 'Measure 8 0))
                                        (leaf (token "4c" 'SpineData 9 0))
                                        (leaf (token "4c" 'SpineData 10 0))
                                        (leaf (token "4c" 'SpineData 11 0))
                                        (leaf (token "=3" 'Measure 12 0))
                                        (leaf (token "4c" 'SpineData 13 0))
                                        (leaf (token "4c" 'SpineData 14 0))
                                        (leaf (token "4c" 'SpineData 15 0))
                                        (leaf (token "==" 'Measure 16 0))
                                        (leaf (token "*-" 'SpineTerminator 17 0)))))))
|#
(check-expect (gspines->linked-spines (spine-parser
                                        one-spine-no-splits)
                                      one-spine-no-splits)
              (list (linked-spine KERN-0-0)))

(test)
