#lang racket/base

(require "../../../../../parser/HumdrumSyntax.rkt"
         "../../../../../parser/file-fn.rkt"
         "../../../../../parser/spine-parsing-fn.rkt"
         "../../../../../parser/humdrum-graph/HumdrumGraph.rkt"
         "../../../../../parser/humdrum-graph/hfile-to-hgraph-fn.rkt"
         "../../../../../parser/humdrum-graph/hgraph-to-hfile-fn.rkt"
         "../../../../../parser/linked-spine/LinkedSpine.rkt"
         "../../../../../parser/linked-spine/gspines-to-linked-spines-fn.rkt"
         test-engine/racket-tests)

;; Node definitions
(define TERM-23-0 (terminator-node (token "*-" 'SpineTerminator 23 0)))
(define M-22-0 (token-node (token "==" 'Measure 22 0) (box-immutable TERM-23-0)))
(define J-21-0 (token-node (token "*v" 'SpineJoin 21 0) (box-immutable M-22-0)))
(define J-21-1 (token-node (token "*v" 'SpineJoin 21 1) (box-immutable M-22-0)))
(define NULL-20-0 (token-node (token "*" 'NullInterpretation 20 0) (box-immutable J-21-0)))
(define J-20-1 (token-node (token "*v" 'SpineJoin 20 1) (box-immutable J-21-1)))
(define J-20-2 (token-node (token "*v" 'SpineJoin 20 2) (box-immutable J-21-1)))
(define NULL-19-0 (token-node (token "*" 'NullInterpretation 19 0) (box-immutable NULL-20-0)))
(define NULL-19-1 (token-node (token "*" 'NullInterpretation 19 1) (box-immutable J-20-1)))
(define J-19-2 (token-node (token "*v" 'SpineJoin 19 2) (box-immutable J-20-2)))
(define J-19-3 (token-node (token "*v" 'SpineJoin 19 3) (box-immutable J-20-2)))
(define 4c-18-0 (token-node (token "4c" 'SpineData 18 0) (box-immutable NULL-19-0)))
(define 4c-18-1 (token-node (token "4c" 'SpineData 18 1) (box-immutable NULL-19-1)))
(define 4c-18-2 (token-node (token "4c" 'SpineData 18 2) (box-immutable J-19-2)))
(define 4c-18-3 (token-node (token "4c" 'SpineData 18 3) (box-immutable J-19-3)))
(define 4c-17-0 (token-node (token "4c" 'SpineData 17 0) (box-immutable 4c-18-0)))
(define 4c-17-1 (token-node (token "4c" 'SpineData 17 1) (box-immutable 4c-18-1)))
(define 4c-17-2 (token-node (token "4c" 'SpineData 17 2) (box-immutable 4c-18-2)))
(define 4c-17-3 (token-node (token "4c" 'SpineData 17 3) (box-immutable 4c-18-3)))
(define 4c-16-0 (token-node (token "4c" 'SpineData 16 0) (box-immutable 4c-17-0)))
(define 4c-16-1 (token-node (token "4c" 'SpineData 16 1) (box-immutable 4c-17-1)))
(define 4c-16-2 (token-node (token "4c" 'SpineData 16 2) (box-immutable 4c-17-2)))
(define 4c-16-3 (token-node (token "4c" 'SpineData 16 3) (box-immutable 4c-17-3)))
(define M-15-0 (token-node (token "=3" 'Measure 15 0) (box-immutable 4c-16-0)))
(define M-15-1 (token-node (token "=3" 'Measure 15 1) (box-immutable 4c-16-1)))
(define M-15-2 (token-node (token "=3" 'Measure 15 2) (box-immutable 4c-16-2)))
(define M-15-3 (token-node (token "=3" 'Measure 15 3) (box-immutable 4c-16-3)))
(define 4c-14-0 (token-node (token "4c" 'SpineData 14 0) (box-immutable M-15-0)))
(define 4c-14-1 (token-node (token "4c" 'SpineData 14 1) (box-immutable M-15-1)))
(define 4c-14-2 (token-node (token "4c" 'SpineData 14 2) (box-immutable M-15-2)))
(define 4c-14-3 (token-node (token "4c" 'SpineData 14 3) (box-immutable M-15-3)))
(define 4c-13-0 (token-node (token "4c" 'SpineData 13 0) (box-immutable 4c-14-0)))
(define 4c-13-1 (token-node (token "4c" 'SpineData 13 1) (box-immutable 4c-14-1)))
(define 4c-13-2 (token-node (token "4c" 'SpineData 13 2) (box-immutable 4c-14-2)))
(define 4c-13-3 (token-node (token "4c" 'SpineData 13 3) (box-immutable 4c-14-3)))
(define 4c-12-0 (token-node (token "4c" 'SpineData 12 0) (box-immutable 4c-13-0)))
(define 4c-12-1 (token-node (token "4c" 'SpineData 12 1) (box-immutable 4c-13-1)))
(define 4c-12-2 (token-node (token "4c" 'SpineData 12 2) (box-immutable 4c-13-2)))
(define 4c-12-3 (token-node (token "4c" 'SpineData 12 3) (box-immutable 4c-13-3)))
(define M-11-0 (token-node (token "=2" 'Measure 11 0) (box-immutable 4c-12-0)))
(define M-11-1 (token-node (token "=2" 'Measure 11 1) (box-immutable 4c-12-1)))
(define M-11-2 (token-node (token "=2" 'Measure 11 2) (box-immutable 4c-12-2)))
(define M-11-3 (token-node (token "=2" 'Measure 11 3) (box-immutable 4c-12-3)))
(define 4c-10-0 (token-node (token "4c" 'SpineData 10 0) (box-immutable M-11-0)))
(define 4c-10-1 (token-node (token "4c" 'SpineData 10 1) (box-immutable M-11-1)))
(define 4c-10-2 (token-node (token "4c" 'SpineData 10 2) (box-immutable M-11-2)))
(define 4c-10-3 (token-node (token "4c" 'SpineData 10 3) (box-immutable M-11-3)))
(define 4c-9-0 (token-node (token "4c" 'SpineData 9 0) (box-immutable 4c-10-0)))
(define 4c-9-1 (token-node (token "4c" 'SpineData 9 1) (box-immutable 4c-10-1)))
(define 4c-9-2 (token-node (token "4c" 'SpineData 9 2) (box-immutable 4c-10-2)))
(define 4c-9-3 (token-node (token "4c" 'SpineData 9 3) (box-immutable 4c-10-3)))
(define 4c-8-0 (token-node (token "4c" 'SpineData 8 0) (box-immutable 4c-9-0)))
(define 4c-8-1 (token-node (token "4c" 'SpineData 8 1) (box-immutable 4c-9-1)))
(define 4c-8-2 (token-node (token "4c" 'SpineData 8 2) (box-immutable 4c-9-2)))
(define 4c-8-3 (token-node (token "4c" 'SpineData 8 3) (box-immutable 4c-9-3)))
(define NULL-7-0 (token-node (token "*" 'NullInterpretation 7 0) (box-immutable 4c-8-0)))
(define NULL-7-1 (token-node (token "*" 'NullInterpretation 7 1) (box-immutable 4c-8-1)))
(define S-7-2 (split-node (token "*^" 'SpineSplit 7 2)
                          (box-immutable 4c-8-2)
                          (box-immutable 4c-8-3)))
(define NULL-6-0 (token-node (token "*" 'NullInterpretation 6 0) (box-immutable NULL-7-0)))
(define S-6-1 (split-node (token "*^" 'SpineSplit 6 1)
                          (box-immutable NULL-7-1)
                          (box-immutable S-7-2)))
(define S-5-0 (split-node (token "*^" 'SpineSplit 5 0)
                          (box-immutable NULL-6-0)
                          (box-immutable S-6-1)))
(define TS-4-0 (token-node (token "*M3/4" 'TimeSignature 4 0) (box-immutable S-5-0)))
(define KL-3-0 (token-node (token "*a:" 'KeyLabel 3 0) (box-immutable TS-4-0)))
(define KS-2-0 (token-node (token "*k[]" 'KeySignature 2 0) (box-immutable KL-3-0)))
(define CL-1-0 (token-node (token "*clefG2" 'Clef 1 0) (box-immutable KS-2-0)))
(define KERN-0-0 (token-node (token "**kern" 'ExclusiveInterpretation 0 0) (box-immutable CL-1-0)))

(check-expect (path->hfile "../../data/count/one-spine-three-splits.krn")
              (hfile (list (record "**kern"
                                   'ExclusiveInterpretation
                                   (list (token "**kern" 'ExclusiveInterpretation 0 0))
                                   0)
                           (record "*clefG2" 'TandemInterpretation (list (token "*clefG2" 'Clef 1 0)) 1)
                           (record "*k[]" 'TandemInterpretation (list (token "*k[]" 'KeySignature 2 0)) 2)
                           (record "*a:" 'TandemInterpretation (list (token "*a:" 'KeyLabel 3 0)) 3)
                           (record "*M3/4" 'TandemInterpretation (list (token "*M3/4" 'TimeSignature 4 0)) 4)
                           (record "*^" 'TandemInterpretation (list (token "*^" 'SpineSplit 5 0)) 5)
                           (record "*\t*^" 'TandemInterpretation (list (token "*" 'NullInterpretation 6 0)
                                                       (token "*^" 'SpineSplit 6 1))
                                   6)
                           (record "*\t*\t*^" 'TandemInterpretation (list (token "*" 'NullInterpretation 7 0)
                                                          (token "*" 'NullInterpretation 7 1)
                                                          (token "*^" 'SpineSplit 7 2))
                                   7)
                           (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 8 0)
                                                                (token "4c" 'SpineData 8 1)
                                                                (token "4c" 'SpineData 8 2)
                                                                (token "4c" 'SpineData 8 3))
                                   8)
                           (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 9 0)
                                                                (token "4c" 'SpineData 9 1)
                                                                (token "4c" 'SpineData 9 2)
                                                                (token "4c" 'SpineData 9 3))
                                   9)
                           (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 10 0)
                                                                (token "4c" 'SpineData 10 1)
                                                                (token "4c" 'SpineData 10 2)
                                                                (token "4c" 'SpineData 10 3))
                                   10)
                           (record "=2\t=2\t=2\t=2" 'Measure (list (token "=2" 'Measure 11 0)
                                                                (token "=2" 'Measure 11 1)
                                                                (token "=2" 'Measure 11 2)
                                                                (token "=2" 'Measure 11 3))
                                   11)
                           (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 12 0)
                                                                (token "4c" 'SpineData 12 1)
                                                                (token "4c" 'SpineData 12 2)
                                                                (token "4c" 'SpineData 12 3))
                                   12)
                           (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 13 0)
                                                                (token "4c" 'SpineData 13 1)
                                                                (token "4c" 'SpineData 13 2)
                                                                (token "4c" 'SpineData 13 3))
                                   13)
                           (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 14 0)
                                                                (token "4c" 'SpineData 14 1)
                                                                (token "4c" 'SpineData 14 2)
                                                                (token "4c" 'SpineData 14 3))
                                   14)
                           (record "=3\t=3\t=3\t=3" 'Measure (list (token "=3" 'Measure 15 0)
                                                                (token "=3" 'Measure 15 1)
                                                                (token "=3" 'Measure 15 2)
                                                                (token "=3" 'Measure 15 3))
                                   15)
                           (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 16 0)
                                                                (token "4c" 'SpineData 16 1)
                                                                (token "4c" 'SpineData 16 2)
                                                                (token "4c" 'SpineData 16 3))
                                   16)
                           (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 17 0)
                                                                (token "4c" 'SpineData 17 1)
                                                                (token "4c" 'SpineData 17 2)
                                                                (token "4c" 'SpineData 17 3))
                                   17)
                           (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 18 0)
                                                                (token "4c" 'SpineData 18 1)
                                                                (token "4c" 'SpineData 18 2)
                                                                (token "4c" 'SpineData 18 3))
                                   18)
                           (record "*\t*\t*v\t*v" 'TandemInterpretation (list (token "*" 'NullInterpretation 19 0)
                                                              (token "*" 'NullInterpretation 19 1)
                                                              (token "*v" 'SpineJoin 19 2)
                                                              (token "*v" 'SpineJoin 19 3))
                                   19)
                           (record "*\t*v\t*v" 'TandemInterpretation (list (token "*" 'NullInterpretation 20 0)
                                                           (token "*v" 'SpineJoin 20 1)
                                                           (token "*v" 'SpineJoin 20 2))
                                   20)
                           (record "*v\t*v" 'TandemInterpretation (list (token "*v" 'SpineJoin 21 0)
                                                        (token "*v" 'SpineJoin 21 1))
                                   21)
                           (record "==" 'Measure (list (token "==" 'Measure 22 0)) 22)
                           (record "*-" 'TandemInterpretation (list (token "*-" 'SpineTerminator 23 0)) 23))))
(check-expect (spine-parser (path->hfile "../../data/count/one-spine-three-splits.krn"))
              (list (global-spine 'Kern
                                  (list (list (token "**kern" 'ExclusiveInterpretation 0 0))
                                        (list (token "*clefG2" 'Clef 1 0))
                                        (list (token "*k[]" 'KeySignature 2 0))
                                        (list (token "*a:" 'KeyLabel 3 0))
                                        (list (token "*M3/4" 'TimeSignature 4 0))
                                        (list (token "*^" 'SpineSplit 5 0))
                                        (list (token "*" 'NullInterpretation 6 0)
                                              (token "*^" 'SpineSplit 6 1))
                                        (list (token "*" 'NullInterpretation 7 0)
                                              (token "*" 'NullInterpretation 7 1)
                                              (token "*^" 'SpineSplit 7 2))
                                        (list (token "4c" 'SpineData 8 0)
                                              (token "4c" 'SpineData 8 1)
                                              (token "4c" 'SpineData 8 2)
                                              (token "4c" 'SpineData 8 3))
                                        (list (token "4c" 'SpineData 9 0)
                                              (token "4c" 'SpineData 9 1)
                                              (token "4c" 'SpineData 9 2)
                                              (token "4c" 'SpineData 9 3))
                                        (list (token "4c" 'SpineData 10 0)
                                              (token "4c" 'SpineData 10 1)
                                              (token "4c" 'SpineData 10 2)
                                              (token "4c" 'SpineData 10 3))
                                        (list (token "=2" 'Measure 11 0)
                                              (token "=2" 'Measure 11 1)
                                              (token "=2" 'Measure 11 2)
                                              (token "=2" 'Measure 11 3))
                                        (list (token "4c" 'SpineData 12 0)
                                              (token "4c" 'SpineData 12 1)
                                              (token "4c" 'SpineData 12 2)
                                              (token "4c" 'SpineData 12 3))
                                        (list (token "4c" 'SpineData 13 0)
                                              (token "4c" 'SpineData 13 1)
                                              (token "4c" 'SpineData 13 2)
                                              (token "4c" 'SpineData 13 3))
                                        (list (token "4c" 'SpineData 14 0)
                                              (token "4c" 'SpineData 14 1)
                                              (token "4c" 'SpineData 14 2)
                                              (token "4c" 'SpineData 14 3))
                                        (list (token "=3" 'Measure 15 0)
                                              (token "=3" 'Measure 15 1)
                                              (token "=3" 'Measure 15 2)
                                              (token "=3" 'Measure 15 3))
                                        (list (token "4c" 'SpineData 16 0)
                                              (token "4c" 'SpineData 16 1)
                                              (token "4c" 'SpineData 16 2)
                                              (token "4c" 'SpineData 16 3))
                                        (list (token "4c" 'SpineData 17 0)
                                              (token "4c" 'SpineData 17 1)
                                              (token "4c" 'SpineData 17 2)
                                              (token "4c" 'SpineData 17 3))
                                        (list (token "4c" 'SpineData 18 0)
                                              (token "4c" 'SpineData 18 1)
                                              (token "4c" 'SpineData 18 2)
                                              (token "4c" 'SpineData 18 3))
                                        (list (token "*" 'NullInterpretation 19 0)
                                              (token "*" 'NullInterpretation 19 1)
                                              (token "*v" 'SpineJoin 19 2)
                                              (token "*v" 'SpineJoin 19 3))
                                        (list (token "*" 'NullInterpretation 20 0)
                                              (token "*v" 'SpineJoin 20 1)
                                              (token "*v" 'SpineJoin 20 2))
                                        (list (token "*v" 'SpineJoin 21 0)
                                              (token "*v" 'SpineJoin 21 1))
                                        (list (token "==" 'Measure 22 0))
                                        (list (token "*-" 'SpineTerminator 23 0)))
                                  0)))
(check-expect (hgraph->hfile
               (hgraph (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                         (leaf (token "*clefG2" 'Clef 1 0))
                                         (leaf (token "*k[]" 'KeySignature 2 0))
                                         (leaf (token "*a:" 'KeyLabel 3 0))
                                         (leaf (token "*M3/4" 'TimeSignature 4 0))
                                         (parent (token "*^" 'SpineSplit 5 0)
                                                 (list (leaf (token "*" 'NullInterpretation 6 0))
                                                       (leaf (token "*" 'NullInterpretation 7 0))
                                                       (leaf (token "4c" 'SpineData 8 0))
                                                       (leaf (token "4c" 'SpineData 9 0))
                                                       (leaf (token "4c" 'SpineData 10 0))
                                                       (leaf (token "=2" 'Measure 11 0))
                                                       (leaf (token "4c" 'SpineData 12 0))
                                                       (leaf (token "4c" 'SpineData 13 0))
                                                       (leaf (token "4c" 'SpineData 14 0))
                                                       (leaf (token "=3" 'Measure 15 0))
                                                       (leaf (token "4c" 'SpineData 16 0))
                                                       (leaf (token "4c" 'SpineData 17 0))
                                                       (leaf (token "4c" 'SpineData 18 0))
                                                       (leaf (token "*" 'NullInterpretation 19 0))
                                                       (leaf (token "*" 'NullInterpretation 20 0))
                                                       (leaf (token "*v" 'SpineJoin 21 0)))
                                                 (list (parent (token "*^" 'SpineSplit 6 1)
                                                               (list (leaf (token "*" 'NullInterpretation 7 1))
                                                                     (leaf (token "4c" 'SpineData 8 1))
                                                                     (leaf (token "4c" 'SpineData 9 1))
                                                                     (leaf (token "4c" 'SpineData 10 1))
                                                                     (leaf (token "=2" 'Measure 11 1))
                                                                     (leaf (token "4c" 'SpineData 12 1))
                                                                     (leaf (token "4c" 'SpineData 13 1))
                                                                     (leaf (token "4c" 'SpineData 14 1))
                                                                     (leaf (token "=3" 'Measure 15 1))
                                                                     (leaf (token "4c" 'SpineData 16 1))
                                                                     (leaf (token "4c" 'SpineData 17 1))
                                                                     (leaf (token "4c" 'SpineData 18 1))
                                                                     (leaf (token "*" 'NullInterpretation 19 1))
                                                                     (leaf (token "*v" 'SpineJoin 20 1)))
                                                               (list (parent (token "*^" 'SpineSplit 7 2)
                                                                             (list (leaf (token "4c" 'SpineData 8 2))
                                                                                   (leaf (token "4c" 'SpineData 9 2))
                                                                                   (leaf (token "4c" 'SpineData 10 2))
                                                                                   (leaf (token "=2" 'Measure 11 2))
                                                                                   (leaf (token "4c" 'SpineData 12 2))
                                                                                   (leaf (token "4c" 'SpineData 13 2))
                                                                                   (leaf (token "4c" 'SpineData 14 2))
                                                                                   (leaf (token "=3" 'Measure 15 2))
                                                                                   (leaf (token "4c" 'SpineData 16 2))
                                                                                   (leaf (token "4c" 'SpineData 17 2))
                                                                                   (leaf (token "4c" 'SpineData 18 2))
                                                                                   (leaf (token "*v" 'SpineJoin 19 2)))
                                                                             (list (leaf (token "4c" 'SpineData 8 3))
                                                                                   (leaf (token "4c" 'SpineData 9 3))
                                                                                   (leaf (token "4c" 'SpineData 10 3))
                                                                                   (leaf (token "=2" 'Measure 11 3))
                                                                                   (leaf (token "4c" 'SpineData 12 3))
                                                                                   (leaf (token "4c" 'SpineData 13 3))
                                                                                   (leaf (token "4c" 'SpineData 14 3))
                                                                                   (leaf (token "=3" 'Measure 15 3))
                                                                                   (leaf (token "4c" 'SpineData 16 3))
                                                                                   (leaf (token "4c" 'SpineData 17 3))
                                                                                   (leaf (token "4c" 'SpineData 18 3))
                                                                                   (leaf (token "*v" 'SpineJoin 19 3))))
                                                                     (leaf (token "*v" 'SpineJoin 20 2))))
                                                       (leaf (token "*v" 'SpineJoin 21 1))))
                                         (leaf (token "==" 'Measure 22 0))
                                         (leaf (token "*-" 'SpineTerminator 23 0)))))))
              (path->hfile "../../data/count/one-spine-three-splits.krn"))
(check-expect (tokens->records (list (list (token "**kern" 'ExclusiveInterpretation 0 0))
                                (list (token "*clefG2" 'Clef 1 0))
                                (list (token "*k[]" 'KeySignature 2 0))
                                (list (token "*a:" 'KeyLabel 3 0))
                                (list (token "*M3/4" 'Measure 4 0))
                                (list (token "*^" 'SpineSplit 5 0))
                                (list (token "*" 'NullInterpretation 6 0)
                                      (token "*^" 'SpineSplit 6 1))
                                (list (token "*" 'NullInterpretation 7 0)
                                      (token "*" 'NullInterpretation 7 1)
                                      (token "*^" 'SpineSplit 7 2))
                                (list (token "4c" 'SpineData 8 0)
                                      (token "4c" 'SpineData 8 1)
                                      (token "4c" 'SpineData 8 2)
                                      (token "4c" 'SpineData 8 3))
                                (list (token "4c" 'SpineData 9 0)
                                      (token "4c" 'SpineData 9 1)
                                      (token "4c" 'SpineData 9 2)
                                      (token "4c" 'SpineData 9 3))
                                (list (token "4c" 'SpineData 10 0)
                                      (token "4c" 'SpineData 10 1)
                                      (token "4c" 'SpineData 10 2)
                                      (token "4c" 'SpineData 10 3))
                                (list (token "=2" 'Measure 11 0)
                                      (token "=2" 'Measure 11 1)
                                      (token "=2" 'Measure 11 2)
                                      (token "=2" 'Measure 11 3))
                                (list (token "4c" 'SpineData 12 0)
                                      (token "4c" 'SpineData 12 1)
                                      (token "4c" 'SpineData 12 2)
                                      (token "4c" 'SpineData 12 3))
                                (list (token "4c" 'SpineData 13 0)
                                      (token "4c" 'SpineData 13 1)
                                      (token "4c" 'SpineData 13 2)
                                      (token "4c" 'SpineData 13 3))
                                (list (token "4c" 'SpineData 14 0)
                                      (token "4c" 'SpineData 14 1)
                                      (token "4c" 'SpineData 14 2)
                                      (token "4c" 'SpineData 14 3))
                                (list (token "=3" 'Measure 15 0)
                                      (token "=3" 'Measure 15 1)
                                      (token "=3" 'Measure 15 2)
                                      (token "=3" 'Measure 15 3))
                                (list (token "4c" 'SpineData 16 0)
                                      (token "4c" 'SpineData 16 1)
                                      (token "4c" 'SpineData 16 2)
                                      (token "4c" 'SpineData 16 3))
                                (list (token "4c" 'SpineData 17 0)
                                      (token "4c" 'SpineData 17 1)
                                      (token "4c" 'SpineData 17 2)
                                      (token "4c" 'SpineData 17 3))
                                (list (token "4c" 'SpineData 18 0)
                                      (token "4c" 'SpineData 18 1)
                                      (token "4c" 'SpineData 18 2)
                                      (token "4c" 'SpineData 18 3))
                                (list (token "*" 'NullInterpretation 19 0)
                                      (token "*" 'NullInterpretation 19 1)
                                      (token "*v" 'SpineJoin 19 2)
                                      (token "*v" 'SpineJoin 19 3))
                                (list (token "*" 'NullInterpretation 20 0)
                                      (token "*v" 'SpineJoin 20 1)
                                      (token "*v" 'SpineJoin 20 2))
                                (list (token "*v" 'SpineJoin 21 0)
                                      (token "*v" 'SpineJoin 21 1))
                                (list (token "==" 'Measure 22 0))
                                (list (token "*-" 'SpineTerminator 23 0))))
              (list (record "**kern"
                            'ExclusiveInterpretation
                            (list (token "**kern" 'ExclusiveInterpretation 0 0))
                            0)
                    (record "*clefG2" 'TandemInterpretation (list (token "*clefG2" 'Clef 1 0)) 1)
                    (record "*k[]" 'TandemInterpretation (list (token "*k[]" 'KeySignature 2 0)) 2)
                    (record "*a:" 'TandemInterpretation (list (token "*a:" 'KeyLabel 3 0)) 3)
                    (record "*M3/4" 'TandemInterpretation (list (token "*M3/4" 'Measure 4 0)) 4)
                    (record "*^" 'TandemInterpretation (list (token "*^" 'SpineSplit 5 0)) 5)
                    (record "*\t*^" 'TandemInterpretation (list (token "*" 'NullInterpretation 6 0)
                                                (token "*^" 'SpineSplit 6 1))
                            6)
                    (record "*\t*\t*^" 'TandemInterpretation (list (token "*" 'NullInterpretation 7 0)
                                                   (token "*" 'NullInterpretation 7 1)
                                                   (token "*^" 'SpineSplit 7 2))
                            7)
                    (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 8 0)
                                                         (token "4c" 'SpineData 8 1)
                                                         (token "4c" 'SpineData 8 2)
                                                         (token "4c" 'SpineData 8 3))
                            8)
                    (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 9 0)
                                                         (token "4c" 'SpineData 9 1)
                                                         (token "4c" 'SpineData 9 2)
                                                         (token "4c" 'SpineData 9 3))
                            9)
                    (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 10 0)
                                                         (token "4c" 'SpineData 10 1)
                                                         (token "4c" 'SpineData 10 2)
                                                         (token "4c" 'SpineData 10 3))
                            10)
                    (record "=2\t=2\t=2\t=2" 'Measure (list (token "=2" 'Measure 11 0)
                                                         (token "=2" 'Measure 11 1)
                                                         (token "=2" 'Measure 11 2)
                                                         (token "=2" 'Measure 11 3))
                            11)
                    (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 12 0)
                                                         (token "4c" 'SpineData 12 1)
                                                         (token "4c" 'SpineData 12 2)
                                                         (token "4c" 'SpineData 12 3))
                            12)
                    (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 13 0)
                                                         (token "4c" 'SpineData 13 1)
                                                         (token "4c" 'SpineData 13 2)
                                                         (token "4c" 'SpineData 13 3))
                            13)
                    (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 14 0)
                                                         (token "4c" 'SpineData 14 1)
                                                         (token "4c" 'SpineData 14 2)
                                                         (token "4c" 'SpineData 14 3))
                            14)
                    (record "=3\t=3\t=3\t=3" 'Measure (list (token "=3" 'Measure 15 0)
                                                         (token "=3" 'Measure 15 1)
                                                         (token "=3" 'Measure 15 2)
                                                         (token "=3" 'Measure 15 3))
                            15)
                    (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 16 0)
                                                         (token "4c" 'SpineData 16 1)
                                                         (token "4c" 'SpineData 16 2)
                                                         (token "4c" 'SpineData 16 3))
                            16)
                    (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 17 0)
                                                         (token "4c" 'SpineData 17 1)
                                                         (token "4c" 'SpineData 17 2)
                                                         (token "4c" 'SpineData 17 3))
                            17)
                    (record "4c\t4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 18 0)
                                                         (token "4c" 'SpineData 18 1)
                                                         (token "4c" 'SpineData 18 2)
                                                         (token "4c" 'SpineData 18 3))
                            18)
                    (record "*\t*\t*v\t*v" 'TandemInterpretation (list (token "*" 'NullInterpretation 19 0)
                                                       (token "*" 'NullInterpretation 19 1)
                                                       (token "*v" 'SpineJoin 19 2)
                                                       (token "*v" 'SpineJoin 19 3))
                            19)
                    (record "*\t*v\t*v" 'TandemInterpretation (list (token "*" 'NullInterpretation 20 0)
                                                    (token "*v" 'SpineJoin 20 1)
                                                    (token "*v" 'SpineJoin 20 2))
                            20)
                    (record "*v\t*v" 'TandemInterpretation (list (token "*v" 'SpineJoin 21 0)
                                                 (token "*v" 'SpineJoin 21 1))
                            21)
                    (record "==" 'Measure (list (token "==" 'Measure 22 0)) 22)
                    (record "*-" 'TandemInterpretation (list (token "*-" 'SpineTerminator 23 0)) 23)))
(check-expect (hgraph->tokens
               (hgraph (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                         (leaf (token "*clefG2" 'Clef 1 0))
                                         (leaf (token "*k[]" 'KeySignature 2 0))
                                         (leaf (token "*a:" 'KeyLabel 3 0))
                                         (leaf (token "*M3/4" 'Measure 4 0))
                                         (parent (token "*^" 'SpineSplit 5 0)
                                                 (list (leaf (token "*" 'NullInterpretation 6 0))
                                                       (leaf (token "*" 'NullInterpretation 7 0))
                                                       (leaf (token "4c" 'SpineData 8 0))
                                                       (leaf (token "4c" 'SpineData 9 0))
                                                       (leaf (token "4c" 'SpineData 10 0))
                                                       (leaf (token "=2" 'Measure 11 0))
                                                       (leaf (token "4c" 'SpineData 12 0))
                                                       (leaf (token "4c" 'SpineData 13 0))
                                                       (leaf (token "4c" 'SpineData 14 0))
                                                       (leaf (token "=3" 'Measure 15 0))
                                                       (leaf (token "4c" 'SpineData 16 0))
                                                       (leaf (token "4c" 'SpineData 17 0))
                                                       (leaf (token "4c" 'SpineData 18 0))
                                                       (leaf (token "*" 'NullInterpretation 19 0))
                                                       (leaf (token "*" 'NullInterpretation 20 0))
                                                       (leaf (token "*v" 'SpineJoin 21 0)))
                                                 (list (parent (token "*^" 'SpineSplit 6 1)
                                                               (list (leaf (token "*" 'NullInterpretation 7 1))
                                                                     (leaf (token "4c" 'SpineData 8 1))
                                                                     (leaf (token "4c" 'SpineData 9 1))
                                                                     (leaf (token "4c" 'SpineData 10 1))
                                                                     (leaf (token "=2" 'Measure 11 1))
                                                                     (leaf (token "4c" 'SpineData 12 1))
                                                                     (leaf (token "4c" 'SpineData 13 1))
                                                                     (leaf (token "4c" 'SpineData 14 1))
                                                                     (leaf (token "=3" 'Measure 15 1))
                                                                     (leaf (token "4c" 'SpineData 16 1))
                                                                     (leaf (token "4c" 'SpineData 17 1))
                                                                     (leaf (token "4c" 'SpineData 18 1))
                                                                     (leaf (token "*" 'NullInterpretation 19 1))
                                                                     (leaf (token "*v" 'SpineJoin 20 1)))
                                                               (list (parent (token "*^" 'SpineSplit 7 2)
                                                                             (list (leaf (token "4c" 'SpineData 8 2))
                                                                                   (leaf (token "4c" 'SpineData 9 2))
                                                                                   (leaf (token "4c" 'SpineData 10 2))
                                                                                   (leaf (token "=2" 'Measure 11 2))
                                                                                   (leaf (token "4c" 'SpineData 12 2))
                                                                                   (leaf (token "4c" 'SpineData 13 2))
                                                                                   (leaf (token "4c" 'SpineData 14 2))
                                                                                   (leaf (token "=3" 'Measure 15 2))
                                                                                   (leaf (token "4c" 'SpineData 16 2))
                                                                                   (leaf (token "4c" 'SpineData 17 2))
                                                                                   (leaf (token "4c" 'SpineData 18 2))
                                                                                   (leaf (token "*v" 'SpineJoin 19 2)))
                                                                             (list (leaf (token "4c" 'SpineData 8 3))
                                                                                   (leaf (token "4c" 'SpineData 9 3))
                                                                                   (leaf (token "4c" 'SpineData 10 3))
                                                                                   (leaf (token "=2" 'Measure 11 3))
                                                                                   (leaf (token "4c" 'SpineData 12 3))
                                                                                   (leaf (token "4c" 'SpineData 13 3))
                                                                                   (leaf (token "4c" 'SpineData 14 3))
                                                                                   (leaf (token "=3" 'Measure 15 3))
                                                                                   (leaf (token "4c" 'SpineData 16 3))
                                                                                   (leaf (token "4c" 'SpineData 17 3))
                                                                                   (leaf (token "4c" 'SpineData 18 3))
                                                                                   (leaf (token "*v" 'SpineJoin 19 3))))
                                                                     (leaf (token "*v" 'SpineJoin 20 2))))
                                                       (leaf (token "*v" 'SpineJoin 21 1))))
                                         (leaf (token "==" 'Measure 22 0))
                                         (leaf (token "*-" 'SpineTerminator 23 0)))))))
              (list (list (token "**kern" 'ExclusiveInterpretation 0 0))
                    (list (token "*clefG2" 'Clef 1 0))
                    (list (token "*k[]" 'KeySignature 2 0))
                    (list (token "*a:" 'KeyLabel 3 0))
                    (list (token "*M3/4" 'Measure 4 0))
                    (list (token "*^" 'SpineSplit 5 0))
                    (list (token "*" 'NullInterpretation 6 0)
                          (token "*^" 'SpineSplit 6 1))
                    (list (token "*" 'NullInterpretation 7 0)
                          (token "*" 'NullInterpretation 7 1)
                          (token "*^" 'SpineSplit 7 2))
                    (list (token "4c" 'SpineData 8 0)
                          (token "4c" 'SpineData 8 1)
                          (token "4c" 'SpineData 8 2)
                          (token "4c" 'SpineData 8 3))
                    (list (token "4c" 'SpineData 9 0)
                          (token "4c" 'SpineData 9 1)
                          (token "4c" 'SpineData 9 2)
                          (token "4c" 'SpineData 9 3))
                    (list (token "4c" 'SpineData 10 0)
                          (token "4c" 'SpineData 10 1)
                          (token "4c" 'SpineData 10 2)
                          (token "4c" 'SpineData 10 3))
                    (list (token "=2" 'Measure 11 0)
                          (token "=2" 'Measure 11 1)
                          (token "=2" 'Measure 11 2)
                          (token "=2" 'Measure 11 3))
                    (list (token "4c" 'SpineData 12 0)
                          (token "4c" 'SpineData 12 1)
                          (token "4c" 'SpineData 12 2)
                          (token "4c" 'SpineData 12 3))
                    (list (token "4c" 'SpineData 13 0)
                          (token "4c" 'SpineData 13 1)
                          (token "4c" 'SpineData 13 2)
                          (token "4c" 'SpineData 13 3))
                    (list (token "4c" 'SpineData 14 0)
                          (token "4c" 'SpineData 14 1)
                          (token "4c" 'SpineData 14 2)
                          (token "4c" 'SpineData 14 3))
                    (list (token "=3" 'Measure 15 0)
                          (token "=3" 'Measure 15 1)
                          (token "=3" 'Measure 15 2)
                          (token "=3" 'Measure 15 3))
                    (list (token "4c" 'SpineData 16 0)
                          (token "4c" 'SpineData 16 1)
                          (token "4c" 'SpineData 16 2)
                          (token "4c" 'SpineData 16 3))
                    (list (token "4c" 'SpineData 17 0)
                          (token "4c" 'SpineData 17 1)
                          (token "4c" 'SpineData 17 2)
                          (token "4c" 'SpineData 17 3))
                    (list (token "4c" 'SpineData 18 0)
                          (token "4c" 'SpineData 18 1)
                          (token "4c" 'SpineData 18 2)
                          (token "4c" 'SpineData 18 3))
                    (list (token "*" 'NullInterpretation 19 0)
                          (token "*" 'NullInterpretation 19 1)
                          (token "*v" 'SpineJoin 19 2)
                          (token "*v" 'SpineJoin 19 3))
                    (list (token "*" 'NullInterpretation 20 0)
                          (token "*v" 'SpineJoin 20 1)
                          (token "*v" 'SpineJoin 20 2))
                    (list (token "*v" 'SpineJoin 21 0)
                          (token "*v" 'SpineJoin 21 1))
                    (list (token "==" 'Measure 22 0))
                    (list (token "*-" 'SpineTerminator 23 0))))
(check-expect (hfile->hgraph (path->hfile "../../data/count/one-spine-three-splits.krn"))
              (hgraph (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                        (leaf (token "*clefG2" 'Clef 1 0))
                                        (leaf (token "*k[]" 'KeySignature 2 0))
                                        (leaf (token "*a:" 'KeyLabel 3 0))
                                        (leaf (token "*M3/4" 'TimeSignature 4 0))
                                        (parent (token "*^" 'SpineSplit 5 0)
                                                (list (leaf (token "*" 'NullInterpretation 6 0))
                                                      (leaf (token "*" 'NullInterpretation 7 0))
                                                      (leaf (token "4c" 'SpineData 8 0))
                                                      (leaf (token "4c" 'SpineData 9 0))
                                                      (leaf (token "4c" 'SpineData 10 0))
                                                      (leaf (token "=2" 'Measure 11 0))
                                                      (leaf (token "4c" 'SpineData 12 0))
                                                      (leaf (token "4c" 'SpineData 13 0))
                                                      (leaf (token "4c" 'SpineData 14 0))
                                                      (leaf (token "=3" 'Measure 15 0))
                                                      (leaf (token "4c" 'SpineData 16 0))
                                                      (leaf (token "4c" 'SpineData 17 0))
                                                      (leaf (token "4c" 'SpineData 18 0))
                                                      (leaf (token "*" 'NullInterpretation 19 0))
                                                      (leaf (token "*" 'NullInterpretation 20 0))
                                                      (leaf (token "*v" 'SpineJoin 21 0)))
                                                (list (parent (token "*^" 'SpineSplit 6 1)
                                                              (list (leaf (token "*" 'NullInterpretation 7 1))
                                                                    (leaf (token "4c" 'SpineData 8 1))
                                                                    (leaf (token "4c" 'SpineData 9 1))
                                                                    (leaf (token "4c" 'SpineData 10 1))
                                                                    (leaf (token "=2" 'Measure 11 1))
                                                                    (leaf (token "4c" 'SpineData 12 1))
                                                                    (leaf (token "4c" 'SpineData 13 1))
                                                                    (leaf (token "4c" 'SpineData 14 1))
                                                                    (leaf (token "=3" 'Measure 15 1))
                                                                    (leaf (token "4c" 'SpineData 16 1))
                                                                    (leaf (token "4c" 'SpineData 17 1))
                                                                    (leaf (token "4c" 'SpineData 18 1))
                                                                    (leaf (token "*" 'NullInterpretation 19 1))
                                                                    (leaf (token "*v" 'SpineJoin 20 1)))
                                                              (list (parent (token "*^" 'SpineSplit 7 2)
                                                                            (list (leaf (token "4c" 'SpineData 8 2))
                                                                                  (leaf (token "4c" 'SpineData 9 2))
                                                                                  (leaf (token "4c" 'SpineData 10 2))
                                                                                  (leaf (token "=2" 'Measure 11 2))
                                                                                  (leaf (token "4c" 'SpineData 12 2))
                                                                                  (leaf (token "4c" 'SpineData 13 2))
                                                                                  (leaf (token "4c" 'SpineData 14 2))
                                                                                  (leaf (token "=3" 'Measure 15 2))
                                                                                  (leaf (token "4c" 'SpineData 16 2))
                                                                                  (leaf (token "4c" 'SpineData 17 2))
                                                                                  (leaf (token "4c" 'SpineData 18 2))
                                                                                  (leaf (token "*v" 'SpineJoin 19 2)))
                                                                            (list (leaf (token "4c" 'SpineData 8 3))
                                                                                  (leaf (token "4c" 'SpineData 9 3))
                                                                                  (leaf (token "4c" 'SpineData 10 3))
                                                                                  (leaf (token "=2" 'Measure 11 3))
                                                                                  (leaf (token "4c" 'SpineData 12 3))
                                                                                  (leaf (token "4c" 'SpineData 13 3))
                                                                                  (leaf (token "4c" 'SpineData 14 3))
                                                                                  (leaf (token "=3" 'Measure 15 3))
                                                                                  (leaf (token "4c" 'SpineData 16 3))
                                                                                  (leaf (token "4c" 'SpineData 17 3))
                                                                                  (leaf (token "4c" 'SpineData 18 3))
                                                                                  (leaf (token "*v" 'SpineJoin 19 3))))
                                                                    (leaf (token "*v" 'SpineJoin 20 2))))
                                                      (leaf (token "*v" 'SpineJoin 21 1))))
                                        (leaf (token "==" 'Measure 22 0))
                                        (leaf (token "*-" 'SpineTerminator 23 0)))))))
(check-expect (gspines->linked-spines (spine-parser (path->hfile "../../data/count/one-spine-three-splits.krn"))
                                      (path->hfile "../../data/count/one-spine-three-splits.krn"))
              (list (linked-spine KERN-0-0)))

(test)
