#lang racket/base

(require "../../../../../parser/HumdrumSyntax.rkt"
         "../../../../../parser/file-fn.rkt"
         "../../../../../parser/spine-parsing-fn.rkt"
         "../../../../../parser/humdrum-graph/HumdrumGraph.rkt"
         "../../../../../parser/humdrum-graph/hfile-to-hgraph-fn.rkt"
         "../../../../../parser/humdrum-graph/hgraph-to-hfile-fn.rkt"
         "../../../../../parser/linked-spine/LinkedSpine.rkt"
         "../../../../../parser/linked-spine/gspines-to-linked-spines-fn.rkt"
         test-engine/racket-tests)

;; Node definitions
(define TERM-17-0 (terminator-node (token "*-" 'SpineTerminator 17 0)))
(define M-16-0 (token-node (token "==" 'Measure 16 0) (box-immutable TERM-17-0)))
(define 4c-15-0 (token-node (token "4c" 'SpineData 15 0) (box-immutable M-16-0)))
(define 4c-14-0 (token-node (token "4c" 'SpineData 14 0) (box-immutable 4c-15-0)))
(define 4c-13-0 (token-node (token "4c" 'SpineData 13 0) (box-immutable 4c-14-0)))
(define M-12-0 (token-node (token "=3" 'Measure 12 0) (box-immutable 4c-13-0)))
(define 4c-11-0 (token-node (token "4c" 'SpineData 11 0) (box-immutable M-12-0)))
(define 4c-10-0 (token-node (token "4c" 'SpineData 10 0) (box-immutable 4c-11-0)))
(define 4c-9-0 (token-node (token "4c" 'SpineData 9 0) (box-immutable 4c-10-0)))
(define M-8-0 (token-node (token "=2" 'Measure 8 0) (box-immutable 4c-9-0)))
(define 4c-7-0 (token-node (token "4c" 'SpineData 7 0) (box-immutable M-8-0)))
(define 4c-6-0 (token-node (token "4c" 'SpineData 6 0) (box-immutable 4c-7-0)))
(define 4c-5-0 (token-node (token "4c" 'SpineData 5 0) (box-immutable 4c-6-0)))
(define TS-4-0 (token-node (token "*M3/4" 'TimeSignature 4 0) (box-immutable 4c-5-0)))
(define KL-3-0 (token-node (token "*a:" 'KeyLabel 3 0) (box-immutable TS-4-0)))
(define KS-2-0 (token-node (token "*k[]" 'KeySignature 2 0) (box-immutable KL-3-0)))
(define CL-1-0 (token-node (token "*clefG2" 'Clef 1 0) (box-immutable KS-2-0)))
(define KERN-0-0 (token-node (token "**kern" 'ExclusiveInterpretation 0 0) (box-immutable CL-1-0)))

(define TERM-17-1 (terminator-node (token "*-" 'SpineTerminator 17 1)))
(define M-16-1 (token-node (token "==" 'Measure 16 1) (box-immutable TERM-17-1)))
(define 4c-15-1 (token-node (token "4c" 'SpineData 15 1) (box-immutable M-16-1)))
(define 4c-14-1 (token-node (token "4c" 'SpineData 14 1) (box-immutable 4c-15-1)))
(define 4c-13-1 (token-node (token "4c" 'SpineData 13 1) (box-immutable 4c-14-1)))
(define M-12-1 (token-node (token "=3" 'Measure 12 1) (box-immutable 4c-13-1)))
(define 4c-11-1 (token-node (token "4c" 'SpineData 11 1) (box-immutable M-12-1)))
(define 4c-10-1 (token-node (token "4c" 'SpineData 10 1) (box-immutable 4c-11-1)))
(define 4c-9-1 (token-node (token "4c" 'SpineData 9 1) (box-immutable 4c-10-1)))
(define M-8-1 (token-node (token "=2" 'Measure 8 1) (box-immutable 4c-9-1)))
(define 4c-7-1 (token-node (token "4c" 'SpineData 7 1) (box-immutable M-8-1)))
(define 4c-6-1 (token-node (token "4c" 'SpineData 6 1) (box-immutable 4c-7-1)))
(define 4c-5-1 (token-node (token "4c" 'SpineData 5 1) (box-immutable 4c-6-1)))
(define TS-4-1 (token-node (token "*M3/4" 'TimeSignature 4 1) (box-immutable 4c-5-1)))
(define KL-3-1 (token-node (token "*a:" 'KeyLabel 3 1) (box-immutable TS-4-1)))
(define KS-2-1 (token-node (token "*k[]" 'KeySignature 2 1) (box-immutable KL-3-1)))
(define CL-1-1 (token-node (token "*clefG2" 'Clef 1 1) (box-immutable KS-2-1)))
(define KERN-0-1 (token-node (token "**kern" 'ExclusiveInterpretation 0 1) (box-immutable CL-1-1)))

(define TERM-17-2 (terminator-node (token "*-" 'SpineTerminator 17 2)))
(define M-16-2 (token-node (token "==" 'Measure 16 2) (box-immutable TERM-17-2)))
(define 4c-15-2 (token-node (token "4c" 'SpineData 15 2) (box-immutable M-16-2)))
(define 4c-14-2 (token-node (token "4c" 'SpineData 14 2) (box-immutable 4c-15-2)))
(define 4c-13-2 (token-node (token "4c" 'SpineData 13 2) (box-immutable 4c-14-2)))
(define M-12-2 (token-node (token "=3" 'Measure 12 2) (box-immutable 4c-13-2)))
(define 4c-11-2 (token-node (token "4c" 'SpineData 11 2) (box-immutable M-12-2)))
(define 4c-10-2 (token-node (token "4c" 'SpineData 10 2) (box-immutable 4c-11-2)))
(define 4c-9-2 (token-node (token "4c" 'SpineData 9 2) (box-immutable 4c-10-2)))
(define M-8-2 (token-node (token "=2" 'Measure 8 2) (box-immutable 4c-9-2)))
(define 4c-7-2 (token-node (token "4c" 'SpineData 7 2) (box-immutable M-8-2)))
(define 4c-6-2 (token-node (token "4c" 'SpineData 6 2) (box-immutable 4c-7-2)))
(define 4c-5-2 (token-node (token "4c" 'SpineData 5 2) (box-immutable 4c-6-2)))
(define TS-4-2 (token-node (token "*M3/4" 'TimeSignature 4 2) (box-immutable 4c-5-2)))
(define KL-3-2 (token-node (token "*a:" 'KeyLabel 3 2) (box-immutable TS-4-2)))
(define KS-2-2 (token-node (token "*k[]" 'KeySignature 2 2) (box-immutable KL-3-2)))
(define CL-1-2 (token-node (token "*clefG2" 'Clef 1 2) (box-immutable KS-2-2)))
(define KERN-0-2 (token-node (token "**kern" 'ExclusiveInterpretation 0 2) (box-immutable CL-1-2)))

(check-expect (path->hfile "../../data/count/three-spines-no-splits.krn")
              (hfile (list (record "**kern\t**kern\t**kern"
                                   'ExclusiveInterpretation
                                   (list (token "**kern" 'ExclusiveInterpretation 0 0)
                                         (token "**kern" 'ExclusiveInterpretation 0 1)
                                         (token "**kern" 'ExclusiveInterpretation 0 2))
                                   0)
                           (record "*clefG2\t*clefG2\t*clefG2" 'TandemInterpretation (list (token "*clefG2" 'Clef 1 0)
                                                                           (token "*clefG2" 'Clef 1 1)
                                                                           (token "*clefG2" 'Clef 1 2))
                                   1)
                           (record "*k[]\t*k[]\t*k[]" 'TandemInterpretation (list (token "*k[]" 'KeySignature 2 0)
                                                                  (token "*k[]" 'KeySignature 2 1)
                                                                  (token "*k[]" 'KeySignature 2 2))
                                   2)
                           (record "*a:\t*a:\t*a:" 'TandemInterpretation (list (token "*a:" 'KeyLabel 3 0)
                                                               (token "*a:" 'KeyLabel 3 1)
                                                               (token "*a:" 'KeyLabel 3 2))
                                   3)
                           (record "*M3/4\t*M3/4\t*M3/4" 'TandemInterpretation (list (token "*M3/4" 'TimeSignature 4 0)
                                                                     (token "*M3/4" 'TimeSignature 4 1)
                                                                     (token "*M3/4" 'TimeSignature 4 2))
                                   4)
                           (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 5 0)
                                                            (token "4c" 'SpineData 5 1)
                                                            (token "4c" 'SpineData 5 2))
                                   5)
                           (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 6 0)
                                                            (token "4c" 'SpineData 6 1)
                                                            (token "4c" 'SpineData 6 2))
                                   6)
                           (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 7 0)
                                                            (token "4c" 'SpineData 7 1)
                                                            (token "4c" 'SpineData 7 2))
                                   7)
                           (record "=2\t=2\t=2" 'Measure (list (token "=2" 'Measure 8 0)
                                                            (token "=2" 'Measure 8 1)
                                                            (token "=2" 'Measure 8 2))
                                   8)
                           (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 9 0)
                                                            (token "4c" 'SpineData 9 1)
                                                            (token "4c" 'SpineData 9 2))
                                   9)
                           (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 10 0)
                                                            (token "4c" 'SpineData 10 1)
                                                            (token "4c" 'SpineData 10 2))
                                   10)
                           (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 11 0)
                                                            (token "4c" 'SpineData 11 1)
                                                            (token "4c" 'SpineData 11 2))
                                   11)
                           (record "=3\t=3\t=3" 'Measure (list (token "=3" 'Measure 12 0)
                                                            (token "=3" 'Measure 12 1)
                                                            (token "=3" 'Measure 12 2))
                                   12)
                           (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 13 0)
                                                            (token "4c" 'SpineData 13 1)
                                                            (token "4c" 'SpineData 13 2))
                                   13)
                           (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 14 0)
                                                            (token "4c" 'SpineData 14 1)
                                                            (token "4c" 'SpineData 14 2))
                                   14)
                           (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 15 0)
                                                            (token "4c" 'SpineData 15 1)
                                                            (token "4c" 'SpineData 15 2))
                                   15)
                           (record "==\t==\t==" 'Measure (list (token "==" 'Measure 16 0)
                                                            (token "==" 'Measure 16 1)
                                                            (token "==" 'Measure 16 2))
                                   16)
                           (record "*-\t*-\t*-" 'TandemInterpretation (list (token "*-" 'SpineTerminator 17 0)
                                                            (token "*-" 'SpineTerminator 17 1)
                                                            (token "*-" 'SpineTerminator 17 2))
                                   17))))
(check-expect (spine-parser (path->hfile "../../data/count/three-spines-no-splits.krn"))
              (list (global-spine 'Kern
                                  (list (list (token  "**kern" 'ExclusiveInterpretation 0 0))
                                        (list (token  "*clefG2" 'Clef 1 0))
                                        (list (token  "*k[]" 'KeySignature 2 0))
                                        (list (token  "*a:" 'KeyLabel 3 0))
                                        (list (token  "*M3/4" 'TimeSignature 4 0))
                                        (list (token  "4c" 'SpineData 5 0))
                                        (list (token  "4c" 'SpineData 6 0))
                                        (list (token  "4c" 'SpineData 7 0))
                                        (list (token  "=2" 'Measure 8 0))
                                        (list (token  "4c" 'SpineData 9 0))
                                        (list (token  "4c" 'SpineData 10 0))
                                        (list (token  "4c" 'SpineData 11 0))
                                        (list (token  "=3" 'Measure 12 0))
                                        (list (token  "4c" 'SpineData 13 0))
                                        (list (token  "4c" 'SpineData 14 0))
                                        (list (token  "4c" 'SpineData 15 0))
                                        (list (token  "==" 'Measure 16 0))
                                        (list (token  "*-" 'SpineTerminator 17 0)))
                                  0)
                    (global-spine 'Kern
                                  (list (list (token  "**kern" 'ExclusiveInterpretation 0 1))
                                        (list (token  "*clefG2" 'Clef 1 1))
                                        (list (token  "*k[]" 'KeySignature 2 1))
                                        (list (token  "*a:" 'KeyLabel 3 1))
                                        (list (token  "*M3/4" 'TimeSignature 4 1))
                                        (list (token  "4c" 'SpineData 5 1))
                                        (list (token  "4c" 'SpineData 6 1))
                                        (list (token  "4c" 'SpineData 7 1))
                                        (list (token  "=2" 'Measure 8 1))
                                        (list (token  "4c" 'SpineData 9 1))
                                        (list (token  "4c" 'SpineData 10 1))
                                        (list (token  "4c" 'SpineData 11 1))
                                        (list (token  "=3" 'Measure 12 1))
                                        (list (token  "4c" 'SpineData 13 1))
                                        (list (token  "4c" 'SpineData 14 1))
                                        (list (token  "4c" 'SpineData 15 1))
                                        (list (token  "==" 'Measure 16 1))
                                        (list (token  "*-" 'SpineTerminator 17 1)))
                                  1)
                    (global-spine 'Kern
                                  (list (list (token  "**kern" 'ExclusiveInterpretation 0 2))
                                        (list (token  "*clefG2" 'Clef 1 2))
                                        (list (token  "*k[]" 'KeySignature 2 2))
                                        (list (token  "*a:" 'KeyLabel 3 2))
                                        (list (token  "*M3/4" 'TimeSignature 4 2))
                                        (list (token  "4c" 'SpineData 5 2))
                                        (list (token  "4c" 'SpineData 6 2))
                                        (list (token  "4c" 'SpineData 7 2))
                                        (list (token  "=2" 'Measure 8 2))
                                        (list (token  "4c" 'SpineData 9 2))
                                        (list (token  "4c" 'SpineData 10 2))
                                        (list (token  "4c" 'SpineData 11 2))
                                        (list (token  "=3" 'Measure 12 2))
                                        (list (token  "4c" 'SpineData 13 2))
                                        (list (token  "4c" 'SpineData 14 2))
                                        (list (token  "4c" 'SpineData 15 2))
                                        (list (token  "==" 'Measure 16 2))
                                        (list (token  "*-" 'SpineTerminator 17 2)))
                                  2)))
(check-expect (hgraph->hfile
               (hgraph (root (list (list (leaf (token  "**kern" 'ExclusiveInterpretation 0 0))
                                         (leaf (token  "*clefG2" 'Clef 1 0))
                                         (leaf (token  "*k[]" 'KeySignature 2 0))
                                         (leaf (token  "*a:" 'KeyLabel 3 0))
                                         (leaf (token  "*M3/4" 'TimeSignature 4 0))
                                         (leaf (token  "4c" 'SpineData 5 0))
                                         (leaf (token  "4c" 'SpineData 6 0))
                                         (leaf (token  "4c" 'SpineData 7 0))
                                         (leaf (token  "=2" 'Measure 8 0))
                                         (leaf (token  "4c" 'SpineData 9 0))
                                         (leaf (token  "4c" 'SpineData 10 0))
                                         (leaf (token  "4c" 'SpineData 11 0))
                                         (leaf (token  "=3" 'Measure 12 0))
                                         (leaf (token  "4c" 'SpineData 13 0))
                                         (leaf (token  "4c" 'SpineData 14 0))
                                         (leaf (token  "4c" 'SpineData 15 0))
                                         (leaf (token  "==" 'Measure 16 0))
                                         (leaf (token  "*-" 'SpineTerminator 17 0)))
                                   (list (leaf (token  "**kern" 'ExclusiveInterpretation 0 1))
                                         (leaf (token  "*clefG2" 'Clef 1 1))
                                         (leaf (token  "*k[]" 'KeySignature 2 1))
                                         (leaf (token  "*a:" 'KeyLabel 3 1))
                                         (leaf (token  "*M3/4" 'TimeSignature 4 1))
                                         (leaf (token  "4c" 'SpineData 5 1))
                                         (leaf (token  "4c" 'SpineData 6 1))
                                         (leaf (token  "4c" 'SpineData 7 1))
                                         (leaf (token  "=2" 'Measure 8 1))
                                         (leaf (token  "4c" 'SpineData 9 1))
                                         (leaf (token  "4c" 'SpineData 10 1))
                                         (leaf (token  "4c" 'SpineData 11 1))
                                         (leaf (token  "=3" 'Measure 12 1))
                                         (leaf (token  "4c" 'SpineData 13 1))
                                         (leaf (token  "4c" 'SpineData 14 1))
                                         (leaf (token  "4c" 'SpineData 15 1))
                                         (leaf (token  "==" 'Measure 16 1))
                                         (leaf (token  "*-" 'SpineTerminator 17 1)))
                                   (list (leaf (token  "**kern" 'ExclusiveInterpretation 0 2))
                                         (leaf (token  "*clefG2" 'Clef 1 2))
                                         (leaf (token  "*k[]" 'KeySignature 2 2))
                                         (leaf (token  "*a:" 'KeyLabel 3 2))
                                         (leaf (token  "*M3/4" 'TimeSignature 4 2))
                                         (leaf (token  "4c" 'SpineData 5 2))
                                         (leaf (token  "4c" 'SpineData 6 2))
                                         (leaf (token  "4c" 'SpineData 7 2))
                                         (leaf (token  "=2" 'Measure 8 2))
                                         (leaf (token  "4c" 'SpineData 9 2))
                                         (leaf (token  "4c" 'SpineData 10 2))
                                         (leaf (token  "4c" 'SpineData 11 2))
                                         (leaf (token  "=3" 'Measure 12 2))
                                         (leaf (token  "4c" 'SpineData 13 2))
                                         (leaf (token  "4c" 'SpineData 14 2))
                                         (leaf (token  "4c" 'SpineData 15 2))
                                         (leaf (token  "==" 'Measure 16 2))
                                         (leaf (token  "*-" 'SpineTerminator 17 2)))))))
              (path->hfile "../../data/count/three-spines-no-splits.krn"))
(check-expect (tokens->records (list (list (token "**kern" 'ExclusiveInterpretation 0 0)
                                      (token "**kern" 'ExclusiveInterpretation 0 1)
                                      (token "**kern" 'ExclusiveInterpretation 0 2))
                                (list (token "*clefG2" 'Clef 1 0)
                                      (token "*clefG2" 'Clef 1 1)
                                      (token "*clefG2" 'Clef 1 2))
                                (list (token "*k[]" 'KeySignature 2 0)
                                      (token "*k[]" 'KeySignature 2 1)
                                      (token "*k[]" 'KeySignature 2 2))
                                (list (token "*a:" 'KeyLabel 3 0)
                                      (token "*a:" 'KeyLabel 3 1)
                                      (token "*a:" 'KeyLabel 3 2))
                                (list (token "*M3/4" 'TimeSignature 4 0)
                                      (token "*M3/4" 'TimeSignature 4 1)
                                      (token "*M3/4" 'TimeSignature 4 2))
                                (list (token "4c" 'SpineData 5 0)
                                      (token "4c" 'SpineData 5 1)
                                      (token "4c" 'SpineData 5 2))
                                (list (token "4c" 'SpineData 6 0)
                                      (token "4c" 'SpineData 6 1)
                                      (token "4c" 'SpineData 6 2))
                                (list (token "4c" 'SpineData 7 0)
                                      (token "4c" 'SpineData 7 1)
                                      (token "4c" 'SpineData 7 2))
                                (list (token "=2" 'Measure 8 0)
                                      (token "=2" 'Measure 8 1)
                                      (token "=2" 'Measure 8 2))
                                (list (token "4c" 'SpineData 9 0)
                                      (token "4c" 'SpineData 9 1)
                                      (token "4c" 'SpineData 9 2))
                                (list (token "4c" 'SpineData 10 0)
                                      (token "4c" 'SpineData 10 1)
                                      (token "4c" 'SpineData 10 2))
                                (list (token "4c" 'SpineData 11 0)
                                      (token "4c" 'SpineData 11 1)
                                      (token "4c" 'SpineData 11 2))
                                (list (token "=3" 'Measure 12 0)
                                      (token "=3" 'Measure 12 1)
                                      (token "=3" 'Measure 12 2))
                                (list (token "4c" 'SpineData 13 0)
                                      (token "4c" 'SpineData 13 1)
                                      (token "4c" 'SpineData 13 2))
                                (list (token "4c" 'SpineData 14 0)
                                      (token "4c" 'SpineData 14 1)
                                      (token "4c" 'SpineData 14 2))
                                (list (token "4c" 'SpineData 15 0)
                                      (token "4c" 'SpineData 15 1)
                                      (token "4c" 'SpineData 15 2))
                                (list (token "==" 'Measure 16 0)
                                      (token "==" 'Measure 16 1)
                                      (token "==" 'Measure 16 2))
                                (list (token "*-" 'SpineTerminator 17 0)
                                      (token "*-" 'SpineTerminator 17 1)
                                      (token "*-" 'SpineTerminator 17 2))))
              (list (record "**kern\t**kern\t**kern"
                            'ExclusiveInterpretation
                            (list (token "**kern" 'ExclusiveInterpretation 0 0)
                                  (token "**kern" 'ExclusiveInterpretation 0 1)
                                  (token "**kern" 'ExclusiveInterpretation 0 2))
                            0)
                    (record "*clefG2\t*clefG2\t*clefG2" 'TandemInterpretation (list (token "*clefG2" 'Clef 1 0)
                                                                    (token "*clefG2" 'Clef 1 1)
                                                                    (token "*clefG2" 'Clef 1 2))
                            1)
                    (record "*k[]\t*k[]\t*k[]" 'TandemInterpretation (list (token "*k[]" 'KeySignature 2 0)
                                                           (token "*k[]" 'KeySignature 2 1)
                                                           (token "*k[]" 'KeySignature 2 2))
                            2)
                    (record "*a:\t*a:\t*a:" 'TandemInterpretation (list (token "*a:" 'KeyLabel 3 0)
                                                        (token "*a:" 'KeyLabel 3 1)
                                                        (token "*a:" 'KeyLabel 3 2))
                            3)
                    (record "*M3/4\t*M3/4\t*M3/4" 'TandemInterpretation (list (token "*M3/4" 'TimeSignature 4 0)
                                                              (token "*M3/4" 'TimeSignature 4 1)
                                                              (token "*M3/4" 'TimeSignature 4 2))
                            4)
                    (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 5 0)
                                                     (token "4c" 'SpineData 5 1)
                                                     (token "4c" 'SpineData 5 2))
                            5)
                    (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 6 0)
                                                     (token "4c" 'SpineData 6 1)
                                                     (token "4c" 'SpineData 6 2))
                            6)
                    (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 7 0)
                                                     (token "4c" 'SpineData 7 1)
                                                     (token "4c" 'SpineData 7 2))
                            7)
                    (record "=2\t=2\t=2" 'Measure (list (token "=2" 'Measure 8 0)
                                                     (token "=2" 'Measure 8 1)
                                                     (token "=2" 'Measure 8 2))
                            8)
                    (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 9 0)
                                                     (token "4c" 'SpineData 9 1)
                                                     (token "4c" 'SpineData 9 2))
                            9)
                    (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 10 0)
                                                     (token "4c" 'SpineData 10 1)
                                                     (token "4c" 'SpineData 10 2))
                            10)
                    (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 11 0)
                                                     (token "4c" 'SpineData 11 1)
                                                     (token "4c" 'SpineData 11 2))
                            11)
                    (record "=3\t=3\t=3" 'Measure (list (token "=3" 'Measure 12 0)
                                                     (token "=3" 'Measure 12 1)
                                                     (token "=3" 'Measure 12 2))
                            12)
                    (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 13 0)
                                                     (token "4c" 'SpineData 13 1)
                                                     (token "4c" 'SpineData 13 2))
                            13)
                    (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 14 0)
                                                     (token "4c" 'SpineData 14 1)
                                                     (token "4c" 'SpineData 14 2))
                            14)
                    (record "4c\t4c\t4c" 'Token (list (token "4c" 'SpineData 15 0)
                                                     (token "4c" 'SpineData 15 1)
                                                     (token "4c" 'SpineData 15 2))
                            15)
                    (record "==\t==\t==" 'Measure (list (token "==" 'Measure 16 0)
                                                     (token "==" 'Measure 16 1)
                                                     (token "==" 'Measure 16 2))
                            16)
                    (record "*-\t*-\t*-" 'TandemInterpretation (list (token "*-" 'SpineTerminator 17 0)
                                                     (token "*-" 'SpineTerminator 17 1)
                                                     (token "*-" 'SpineTerminator 17 2))
                            17)))
(check-expect (hgraph->tokens
               (hgraph (root (list (list (leaf (token  "**kern" 'ExclusiveInterpretation 0 0))
                                         (leaf (token  "*clefG2" 'Clef 1 0))
                                         (leaf (token  "*k[]" 'KeySignature 2 0))
                                         (leaf (token  "*a:" 'KeyLabel 3 0))
                                         (leaf (token  "*M3/4" 'TimeSignature 4 0))
                                         (leaf (token  "4c" 'SpineData 5 0))
                                         (leaf (token  "4c" 'SpineData 6 0))
                                         (leaf (token  "4c" 'SpineData 7 0))
                                         (leaf (token  "=2" 'Measure 8 0))
                                         (leaf (token  "4c" 'SpineData 9 0))
                                         (leaf (token  "4c" 'SpineData 10 0))
                                         (leaf (token  "4c" 'SpineData 11 0))
                                         (leaf (token  "=3" 'Measure 12 0))
                                         (leaf (token  "4c" 'SpineData 13 0))
                                         (leaf (token  "4c" 'SpineData 14 0))
                                         (leaf (token  "4c" 'SpineData 15 0))
                                         (leaf (token  "==" 'Measure 16 0))
                                         (leaf (token  "*-" 'SpineTerminator 17 0)))
                                   (list (leaf (token  "**kern" 'ExclusiveInterpretation 0 1))
                                         (leaf (token  "*clefG2" 'Clef 1 1))
                                         (leaf (token  "*k[]" 'KeySignature 2 1))
                                         (leaf (token  "*a:" 'KeyLabel 3 1))
                                         (leaf (token  "*M3/4" 'TimeSignature 4 1))
                                         (leaf (token  "4c" 'SpineData 5 1))
                                         (leaf (token  "4c" 'SpineData 6 1))
                                         (leaf (token  "4c" 'SpineData 7 1))
                                         (leaf (token  "=2" 'Measure 8 1))
                                         (leaf (token  "4c" 'SpineData 9 1))
                                         (leaf (token  "4c" 'SpineData 10 1))
                                         (leaf (token  "4c" 'SpineData 11 1))
                                         (leaf (token  "=3" 'Measure 12 1))
                                         (leaf (token  "4c" 'SpineData 13 1))
                                         (leaf (token  "4c" 'SpineData 14 1))
                                         (leaf (token  "4c" 'SpineData 15 1))
                                         (leaf (token  "==" 'Measure 16 1))
                                         (leaf (token  "*-" 'SpineTerminator 17 1)))
                                   (list (leaf (token  "**kern" 'ExclusiveInterpretation 0 2))
                                         (leaf (token  "*clefG2" 'Clef 1 2))
                                         (leaf (token  "*k[]" 'KeySignature 2 2))
                                         (leaf (token  "*a:" 'KeyLabel 3 2))
                                         (leaf (token  "*M3/4" 'TimeSignature 4 2))
                                         (leaf (token  "4c" 'SpineData 5 2))
                                         (leaf (token  "4c" 'SpineData 6 2))
                                         (leaf (token  "4c" 'SpineData 7 2))
                                         (leaf (token  "=2" 'Measure 8 2))
                                         (leaf (token  "4c" 'SpineData 9 2))
                                         (leaf (token  "4c" 'SpineData 10 2))
                                         (leaf (token  "4c" 'SpineData 11 2))
                                         (leaf (token  "=3" 'Measure 12 2))
                                         (leaf (token  "4c" 'SpineData 13 2))
                                         (leaf (token  "4c" 'SpineData 14 2))
                                         (leaf (token  "4c" 'SpineData 15 2))
                                         (leaf (token  "==" 'Measure 16 2))
                                         (leaf (token  "*-" 'SpineTerminator 17 2)))))))
              (list (list (token "**kern" 'ExclusiveInterpretation 0 0)
                          (token "**kern" 'ExclusiveInterpretation 0 1)
                          (token "**kern" 'ExclusiveInterpretation 0 2))
                    (list (token "*clefG2" 'Clef 1 0)
                          (token "*clefG2" 'Clef 1 1)
                          (token "*clefG2" 'Clef 1 2))
                    (list (token "*k[]" 'KeySignature 2 0)
                          (token "*k[]" 'KeySignature 2 1)
                          (token "*k[]" 'KeySignature 2 2))
                    (list (token "*a:" 'KeyLabel 3 0)
                          (token "*a:" 'KeyLabel 3 1)
                          (token "*a:" 'KeyLabel 3 2))
                    (list (token "*M3/4" 'TimeSignature 4 0)
                          (token "*M3/4" 'TimeSignature 4 1)
                          (token "*M3/4" 'TimeSignature 4 2))
                    (list (token "4c" 'SpineData 5 0)
                          (token "4c" 'SpineData 5 1)
                          (token "4c" 'SpineData 5 2))
                    (list (token "4c" 'SpineData 6 0)
                          (token "4c" 'SpineData 6 1)
                          (token "4c" 'SpineData 6 2))
                    (list (token "4c" 'SpineData 7 0)
                          (token "4c" 'SpineData 7 1)
                          (token "4c" 'SpineData 7 2))
                    (list (token "=2" 'Measure 8 0)
                          (token "=2" 'Measure 8 1)
                          (token "=2" 'Measure 8 2))
                    (list (token "4c" 'SpineData 9 0)
                          (token "4c" 'SpineData 9 1)
                          (token "4c" 'SpineData 9 2))
                    (list (token "4c" 'SpineData 10 0)
                          (token "4c" 'SpineData 10 1)
                          (token "4c" 'SpineData 10 2))
                    (list (token "4c" 'SpineData 11 0)
                          (token "4c" 'SpineData 11 1)
                          (token "4c" 'SpineData 11 2))
                    (list (token "=3" 'Measure 12 0)
                          (token "=3" 'Measure 12 1)
                          (token "=3" 'Measure 12 2))
                    (list (token "4c" 'SpineData 13 0)
                          (token "4c" 'SpineData 13 1)
                          (token "4c" 'SpineData 13 2))
                    (list (token "4c" 'SpineData 14 0)
                          (token "4c" 'SpineData 14 1)
                          (token "4c" 'SpineData 14 2))
                    (list (token "4c" 'SpineData 15 0)
                          (token "4c" 'SpineData 15 1)
                          (token "4c" 'SpineData 15 2))
                    (list (token "==" 'Measure 16 0)
                          (token "==" 'Measure 16 1)
                          (token "==" 'Measure 16 2))
                    (list (token "*-" 'SpineTerminator 17 0)
                          (token "*-" 'SpineTerminator 17 1)
                          (token "*-" 'SpineTerminator 17 2))))
(check-expect (hfile->hgraph (path->hfile "../../data/count/three-spines-no-splits.krn"))
              (hgraph (root (list (list (leaf (token  "**kern" 'ExclusiveInterpretation 0 0))
                                        (leaf (token  "*clefG2" 'Clef 1 0))
                                        (leaf (token  "*k[]" 'KeySignature 2 0))
                                        (leaf (token  "*a:" 'KeyLabel 3 0))
                                        (leaf (token  "*M3/4" 'TimeSignature 4 0))
                                        (leaf (token  "4c" 'SpineData 5 0))
                                        (leaf (token  "4c" 'SpineData 6 0))
                                        (leaf (token  "4c" 'SpineData 7 0))
                                        (leaf (token  "=2" 'Measure 8 0))
                                        (leaf (token  "4c" 'SpineData 9 0))
                                        (leaf (token  "4c" 'SpineData 10 0))
                                        (leaf (token  "4c" 'SpineData 11 0))
                                        (leaf (token  "=3" 'Measure 12 0))
                                        (leaf (token  "4c" 'SpineData 13 0))
                                        (leaf (token  "4c" 'SpineData 14 0))
                                        (leaf (token  "4c" 'SpineData 15 0))
                                        (leaf (token  "==" 'Measure 16 0))
                                        (leaf (token  "*-" 'SpineTerminator 17 0)))
                                  (list (leaf (token  "**kern" 'ExclusiveInterpretation 0 1))
                                        (leaf (token  "*clefG2" 'Clef 1 1))
                                        (leaf (token  "*k[]" 'KeySignature 2 1))
                                        (leaf (token  "*a:" 'KeyLabel 3 1))
                                        (leaf (token  "*M3/4" 'TimeSignature 4 1))
                                        (leaf (token  "4c" 'SpineData 5 1))
                                        (leaf (token  "4c" 'SpineData 6 1))
                                        (leaf (token  "4c" 'SpineData 7 1))
                                        (leaf (token  "=2" 'Measure 8 1))
                                        (leaf (token  "4c" 'SpineData 9 1))
                                        (leaf (token  "4c" 'SpineData 10 1))
                                        (leaf (token  "4c" 'SpineData 11 1))
                                        (leaf (token  "=3" 'Measure 12 1))
                                        (leaf (token  "4c" 'SpineData 13 1))
                                        (leaf (token  "4c" 'SpineData 14 1))
                                        (leaf (token  "4c" 'SpineData 15 1))
                                        (leaf (token  "==" 'Measure 16 1))
                                        (leaf (token  "*-" 'SpineTerminator 17 1)))
                                  (list (leaf (token  "**kern" 'ExclusiveInterpretation 0 2))
                                        (leaf (token  "*clefG2" 'Clef 1 2))
                                        (leaf (token  "*k[]" 'KeySignature 2 2))
                                        (leaf (token  "*a:" 'KeyLabel 3 2))
                                        (leaf (token  "*M3/4" 'TimeSignature 4 2))
                                        (leaf (token  "4c" 'SpineData 5 2))
                                        (leaf (token  "4c" 'SpineData 6 2))
                                        (leaf (token  "4c" 'SpineData 7 2))
                                        (leaf (token  "=2" 'Measure 8 2))
                                        (leaf (token  "4c" 'SpineData 9 2))
                                        (leaf (token  "4c" 'SpineData 10 2))
                                        (leaf (token  "4c" 'SpineData 11 2))
                                        (leaf (token  "=3" 'Measure 12 2))
                                        (leaf (token  "4c" 'SpineData 13 2))
                                        (leaf (token  "4c" 'SpineData 14 2))
                                        (leaf (token  "4c" 'SpineData 15 2))
                                        (leaf (token  "==" 'Measure 16 2))
                                        (leaf (token  "*-" 'SpineTerminator 17 2)))))))
(check-expect (gspines->linked-spines (spine-parser (path->hfile "../../data/count/three-spines-no-splits.krn"))
                                      (path->hfile "../../data/count/three-spines-no-splits.krn"))
              (list (linked-spine KERN-0-0) (linked-spine KERN-0-1) (linked-spine KERN-0-2)))

(test)
