#lang racket/base

(require "../../../../parser/data-definitions/data-definitions.rkt"
         "../../../../parser/functions/file.rkt"
         "../../../../parser/functions/spine-parser.rkt"
         "../../../../parser/data-structures/humdrum-graph/data-definitions/data-definitions.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hgraph-to-hfile.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hfile-to-hgraph.rkt"
         "../../../../parser/data-structures/linked-spine/data-definitions/data-definitions.rkt"
         "../../../../parser/data-structures/linked-spine/functions/gspines-to-linked-spines.rkt"
         test-engine/racket-tests)

;; Node definitions
(define TERM-17-0 (terminator-node (token "*-" SPINE-TERMINATOR 17 0)))
(define M-16-0 (token-node (token "==" MEASURE 16 0) (box-immutable TERM-17-0)))
(define 4c-15-0 (token-node (token "4c" SPINE-DATA 15 0) (box-immutable M-16-0)))
(define 4c-14-0 (token-node (token "4c" SPINE-DATA 14 0) (box-immutable 4c-15-0)))
(define 4c-13-0 (token-node (token "4c" SPINE-DATA 13 0) (box-immutable 4c-14-0)))
(define M-12-0 (token-node (token "=3" MEASURE 12 0) (box-immutable 4c-13-0)))
(define 4c-11-0 (token-node (token "4c" SPINE-DATA 11 0) (box-immutable M-12-0)))
(define 4c-10-0 (token-node (token "4c" SPINE-DATA 10 0) (box-immutable 4c-11-0)))
(define 4c-9-0 (token-node (token "4c" SPINE-DATA 9 0) (box-immutable 4c-10-0)))
(define M-8-0 (token-node (token "=2" MEASURE 8 0) (box-immutable 4c-9-0)))
(define 4c-7-0 (token-node (token "4c" SPINE-DATA 7 0) (box-immutable M-8-0)))
(define 4c-6-0 (token-node (token "4c" SPINE-DATA 6 0) (box-immutable 4c-7-0)))
(define 4c-5-0 (token-node (token "4c" SPINE-DATA 5 0) (box-immutable 4c-6-0)))
(define TS-4-0 (token-node (token "*M3/4" TIME-SIG 4 0) (box-immutable 4c-5-0)))
(define KL-3-0 (token-node (token "*a:" KEY-LABEL 3 0) (box-immutable TS-4-0)))
(define KS-2-0 (token-node (token "*k[]" KEY-SIG 2 0) (box-immutable KL-3-0)))
(define CL-1-0 (token-node (token "*clefG2" CLEF 1 0) (box-immutable KS-2-0)))
(define KERN-0-0 (token-node (token "**kern" EXCLUSIVE-INTERPRETATION 0 0) (box-immutable CL-1-0)))

(define TERM-17-1 (terminator-node (token "*-" SPINE-TERMINATOR 17 1)))
(define M-16-1 (token-node (token "==" MEASURE 16 1) (box-immutable TERM-17-1)))
(define 4c-15-1 (token-node (token "4c" SPINE-DATA 15 1) (box-immutable M-16-1)))
(define 4c-14-1 (token-node (token "4c" SPINE-DATA 14 1) (box-immutable 4c-15-1)))
(define 4c-13-1 (token-node (token "4c" SPINE-DATA 13 1) (box-immutable 4c-14-1)))
(define M-12-1 (token-node (token "=3" MEASURE 12 1) (box-immutable 4c-13-1)))
(define 4c-11-1 (token-node (token "4c" SPINE-DATA 11 1) (box-immutable M-12-1)))
(define 4c-10-1 (token-node (token "4c" SPINE-DATA 10 1) (box-immutable 4c-11-1)))
(define 4c-9-1 (token-node (token "4c" SPINE-DATA 9 1) (box-immutable 4c-10-1)))
(define M-8-1 (token-node (token "=2" MEASURE 8 1) (box-immutable 4c-9-1)))
(define 4c-7-1 (token-node (token "4c" SPINE-DATA 7 1) (box-immutable M-8-1)))
(define 4c-6-1 (token-node (token "4c" SPINE-DATA 6 1) (box-immutable 4c-7-1)))
(define 4c-5-1 (token-node (token "4c" SPINE-DATA 5 1) (box-immutable 4c-6-1)))
(define TS-4-1 (token-node (token "*M3/4" TIME-SIG 4 1) (box-immutable 4c-5-1)))
(define KL-3-1 (token-node (token "*a:" KEY-LABEL 3 1) (box-immutable TS-4-1)))
(define KS-2-1 (token-node (token "*k[]" KEY-SIG 2 1) (box-immutable KL-3-1)))
(define CL-1-1 (token-node (token "*clefG2" CLEF 1 1) (box-immutable KS-2-1)))
(define KERN-0-1 (token-node (token "**kern" EXCLUSIVE-INTERPRETATION 0 1) (box-immutable CL-1-1)))

(check-expect (path->hfile "../../data/count/two-spines-no-splits.krn")
              (hfile (list (record "**kern\t**kern"
                                   TOKEN
                                   (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0)
                                         (token "**kern" EXCLUSIVE-INTERPRETATION 0 1))
                                   0)
                           (record "*clefG2\t*clefG2"
                                   TOKEN
                                   (list (token "*clefG2" CLEF 1 0)
                                         (token "*clefG2" CLEF 1 1))
                                   1)
                           (record "*k[]\t*k[]" TOKEN (list (token "*k[]" KEY-SIG 2 0)
                                                            (token "*k[]" KEY-SIG 2 1))
                                   2)
                           (record "*a:\t*a:" TOKEN (list (token "*a:" KEY-LABEL 3 0)
                                                          (token "*a:" KEY-LABEL 3 1))
                                   3)
                           (record "*M3/4\t*M3/4" TOKEN (list (token "*M3/4" TIME-SIG 4 0)
                                                              (token "*M3/4" TIME-SIG 4 1))
                                   4)
                           (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 5 0)
                                                        (token "4c" SPINE-DATA 5 1))
                                   5)
                           (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 6 0)
                                                        (token "4c" SPINE-DATA 6 1))
                                   6)
                           (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 7 0)
                                                        (token "4c" SPINE-DATA 7 1))
                                   7)
                           (record "=2\t=2" TOKEN (list (token "=2" MEASURE 8 0)
                                                        (token "=2" MEASURE 8 1))
                                   8)
                           (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 9 0)
                                                        (token "4c" SPINE-DATA 9 1))
                                   9)
                           (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 10 0)
                                                        (token "4c" SPINE-DATA 10 1))
                                   10)
                           (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 11 0)
                                                        (token "4c" SPINE-DATA 11 1))
                                   11)
                           (record "=3\t=3" TOKEN (list (token "=3" MEASURE 12 0)
                                                        (token "=3" MEASURE 12 1))
                                   12)
                           (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 13 0)
                                                        (token "4c" SPINE-DATA 13 1))
                                   13)
                           (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 14 0)
                                                        (token "4c" SPINE-DATA 14 1))
                                   14)
                           (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 15 0)
                                                        (token "4c" SPINE-DATA 15 1))
                                   15)
                           (record "==\t==" TOKEN (list (token "==" MEASURE 16 0)
                                                        (token "==" MEASURE 16 1))
                                   16)
                           (record "*-\t*-" TOKEN (list (token "*-" SPINE-TERMINATOR 17 0)
                                                        (token "*-" SPINE-TERMINATOR 17 1))
                                   17))))
(check-expect (spine-parser (path->hfile "../../data/count/two-spines-no-splits.krn"))
              (list (global-spine KERN
                                  (list  (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                         (list (token "*clefG2" CLEF 1 0))
                                         (list (token "*k[]" KEY-SIG 2 0))
                                         (list (token "*a:" KEY-LABEL 3 0))
                                         (list (token "*M3/4" TIME-SIG 4 0))
                                         (list (token "4c" SPINE-DATA 5 0))
                                         (list (token "4c" SPINE-DATA 6 0))
                                         (list (token "4c" SPINE-DATA 7 0))
                                         (list (token "=2" MEASURE 8 0))
                                         (list (token "4c" SPINE-DATA 9 0))
                                         (list (token "4c" SPINE-DATA 10 0))
                                         (list (token "4c" SPINE-DATA 11 0))
                                         (list (token "=3" MEASURE 12 0))
                                         (list (token "4c" SPINE-DATA 13 0))
                                         (list (token "4c" SPINE-DATA 14 0))
                                         (list (token "4c" SPINE-DATA 15 0))
                                         (list (token "==" MEASURE 16 0))
                                         (list (token "*-" SPINE-TERMINATOR 17 0)))
                                  0)
                    (global-spine KERN
                                  (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 1))
                                        (list (token "*clefG2" CLEF 1 1))
                                        (list (token "*k[]" KEY-SIG 2 1))
                                        (list (token "*a:" KEY-LABEL 3 1))
                                        (list (token "*M3/4" TIME-SIG 4 1))
                                        (list (token "4c" SPINE-DATA 5 1))
                                        (list (token "4c" SPINE-DATA 6 1))
                                        (list (token "4c" SPINE-DATA 7 1))
                                        (list (token "=2" MEASURE 8 1))
                                        (list (token "4c" SPINE-DATA 9 1))
                                        (list (token "4c" SPINE-DATA 10 1))
                                        (list (token "4c" SPINE-DATA 11 1))
                                        (list (token "=3" MEASURE 12 1))
                                        (list (token "4c" SPINE-DATA 13 1))
                                        (list (token "4c" SPINE-DATA 14 1))
                                        (list (token "4c" SPINE-DATA 15 1))
                                        (list (token "==" MEASURE 16 1))
                                        (list (token "*-" SPINE-TERMINATOR 17 1)))
                                  1)))
(check-expect (hgraph->hfile
               (hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                         (leaf (token "*clefG2" CLEF 1 0))
                                         (leaf (token "*k[]" KEY-SIG 2 0))
                                         (leaf (token "*a:" KEY-LABEL 3 0))
                                         (leaf (token "*M3/4" TIME-SIG 4 0))
                                         (leaf (token "4c" SPINE-DATA 5 0))
                                         (leaf (token "4c" SPINE-DATA 6 0))
                                         (leaf (token "4c" SPINE-DATA 7 0))
                                         (leaf (token "=2" MEASURE 8 0))
                                         (leaf (token "4c" SPINE-DATA 9 0))
                                         (leaf (token "4c" SPINE-DATA 10 0))
                                         (leaf (token "4c" SPINE-DATA 11 0))
                                         (leaf (token "=3" MEASURE 12 0))
                                         (leaf (token "4c" SPINE-DATA 13 0))
                                         (leaf (token "4c" SPINE-DATA 14 0))
                                         (leaf (token "4c" SPINE-DATA 15 0))
                                         (leaf (token "==" MEASURE 16 0))
                                         (leaf (token "*-" SPINE-TERMINATOR 17 0)))
                                   (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 1))
                                         (leaf (token "*clefG2" CLEF 1 1))
                                         (leaf (token "*k[]" KEY-SIG 2 1))
                                         (leaf (token "*a:" KEY-LABEL 3 1))
                                         (leaf (token "*M3/4" TIME-SIG 4 1))
                                         (leaf (token "4c" SPINE-DATA 5 1))
                                         (leaf (token "4c" SPINE-DATA 6 1))
                                         (leaf (token "4c" SPINE-DATA 7 1))
                                         (leaf (token "=2" MEASURE 8 1))
                                         (leaf (token "4c" SPINE-DATA 9 1))
                                         (leaf (token "4c" SPINE-DATA 10 1))
                                         (leaf (token "4c" SPINE-DATA 11 1))
                                         (leaf (token "=3" MEASURE 12 1))
                                         (leaf (token "4c" SPINE-DATA 13 1))
                                         (leaf (token "4c" SPINE-DATA 14 1))
                                         (leaf (token "4c" SPINE-DATA 15 1))
                                         (leaf (token "==" MEASURE 16 1))
                                         (leaf (token "*-" SPINE-TERMINATOR 17 1)))))))
              (path->hfile "../../data/count/two-spines-no-splits.krn"))
(check-expect (lolot->lor (list  (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0)
                                       (token "**kern" EXCLUSIVE-INTERPRETATION 0 1))
                                 (list (token "*clefG2" CLEF 1 0)
                                       (token "*clefG2" CLEF 1 1))
                                 (list (token "*k[]" KEY-SIG 2 0) (token "*k[]" KEY-SIG 2 1))
                                 (list (token "*a:" KEY-LABEL 3 0) (token "*a:" KEY-LABEL 3 1))
                                 (list (token "*M3/4" TIME-SIG 4 0) (token "*M3/4" TIME-SIG 4 1))
                                 (list (token "4c" SPINE-DATA 5 0) (token "4c" SPINE-DATA 5 1))
                                 (list (token "4c" SPINE-DATA 6 0) (token "4c" SPINE-DATA 6 1))
                                 (list (token "4c" SPINE-DATA 7 0) (token "4c" SPINE-DATA 7 1))
                                 (list (token "=2" MEASURE 8 0) (token "=2" MEASURE 8 1))
                                 (list (token "4c" SPINE-DATA 9 0) (token "4c" SPINE-DATA 9 1))
                                 (list (token "4c" SPINE-DATA 10 0) (token "4c" SPINE-DATA 10 1))
                                 (list (token "4c" SPINE-DATA 11 0) (token "4c" SPINE-DATA 11 1))
                                 (list (token "=3" MEASURE 12 0) (token "=3" MEASURE 12 1))
                                 (list (token "4c" SPINE-DATA 13 0) (token "4c" SPINE-DATA 13 1))
                                 (list (token "4c" SPINE-DATA 14 0) (token "4c" SPINE-DATA 14 1))
                                 (list (token "4c" SPINE-DATA 15 0) (token "4c" SPINE-DATA 15 1))
                                 (list (token "==" MEASURE 16 0) (token "==" MEASURE 16 1))
                                 (list (token "*-" SPINE-TERMINATOR 17 0)
                                       (token "*-" SPINE-TERMINATOR 17 1))))
              (list (record "**kern\t**kern"
                            TOKEN
                            (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0)
                                  (token "**kern" EXCLUSIVE-INTERPRETATION 0 1))
                            0)
                    (record "*clefG2\t*clefG2"
                            TOKEN
                            (list (token "*clefG2" CLEF 1 0)
                                  (token "*clefG2" CLEF 1 1))
                            1)
                    (record "*k[]\t*k[]" TOKEN (list (token "*k[]" KEY-SIG 2 0)
                                                     (token "*k[]" KEY-SIG 2 1))
                            2)
                    (record "*a:\t*a:" TOKEN (list (token "*a:" KEY-LABEL 3 0)
                                                   (token "*a:" KEY-LABEL 3 1))
                            3)
                    (record "*M3/4\t*M3/4" TOKEN (list (token "*M3/4" TIME-SIG 4 0)
                                                       (token "*M3/4" TIME-SIG 4 1))
                            4)
                    (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 5 0)
                                                 (token "4c" SPINE-DATA 5 1))
                            5)
                    (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 6 0)
                                                 (token "4c" SPINE-DATA 6 1))
                            6)
                    (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 7 0)
                                                 (token "4c" SPINE-DATA 7 1))
                            7)
                    (record "=2\t=2" TOKEN (list (token "=2" MEASURE 8 0)
                                                 (token "=2" MEASURE 8 1))
                            8)
                    (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 9 0)
                                                 (token "4c" SPINE-DATA 9 1))
                            9)
                    (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 10 0)
                                                 (token "4c" SPINE-DATA 10 1))
                            10)
                    (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 11 0)
                                                 (token "4c" SPINE-DATA 11 1))
                            11)
                    (record "=3\t=3" TOKEN (list (token "=3" MEASURE 12 0)
                                                 (token "=3" MEASURE 12 1))
                            12)
                    (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 13 0)
                                                 (token "4c" SPINE-DATA 13 1))
                            13)
                    (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 14 0)
                                                 (token "4c" SPINE-DATA 14 1))
                            14)
                    (record "4c\t4c" TOKEN (list (token "4c" SPINE-DATA 15 0)
                                                 (token "4c" SPINE-DATA 15 1))
                            15)
                    (record "==\t==" TOKEN (list (token "==" MEASURE 16 0)
                                                 (token "==" MEASURE 16 1))
                            16)
                    (record "*-\t*-" TOKEN (list (token "*-" SPINE-TERMINATOR 17 0)
                                                 (token "*-" SPINE-TERMINATOR 17 1))
                            17)))
(check-expect (hgraph->lolot
               (hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                         (leaf (token "*clefG2" CLEF 1 0))
                                         (leaf (token "*k[]" KEY-SIG 2 0))
                                         (leaf (token "*a:" KEY-LABEL 3 0))
                                         (leaf (token "*M3/4" TIME-SIG 4 0))
                                         (leaf (token "4c" SPINE-DATA 5 0))
                                         (leaf (token "4c" SPINE-DATA 6 0))
                                         (leaf (token "4c" SPINE-DATA 7 0))
                                         (leaf (token "=2" MEASURE 8 0))
                                         (leaf (token "4c" SPINE-DATA 9 0))
                                         (leaf (token "4c" SPINE-DATA 10 0))
                                         (leaf (token "4c" SPINE-DATA 11 0))
                                         (leaf (token "=3" MEASURE 12 0))
                                         (leaf (token "4c" SPINE-DATA 13 0))
                                         (leaf (token "4c" SPINE-DATA 14 0))
                                         (leaf (token "4c" SPINE-DATA 15 0))
                                         (leaf (token "==" MEASURE 16 0))
                                         (leaf (token "*-" SPINE-TERMINATOR 17 0)))
                                   (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 1))
                                         (leaf (token "*clefG2" CLEF 1 1))
                                         (leaf (token "*k[]" KEY-SIG 2 1))
                                         (leaf (token "*a:" KEY-LABEL 3 1))
                                         (leaf (token "*M3/4" TIME-SIG 4 1))
                                         (leaf (token "4c" SPINE-DATA 5 1))
                                         (leaf (token "4c" SPINE-DATA 6 1))
                                         (leaf (token "4c" SPINE-DATA 7 1))
                                         (leaf (token "=2" MEASURE 8 1))
                                         (leaf (token "4c" SPINE-DATA 9 1))
                                         (leaf (token "4c" SPINE-DATA 10 1))
                                         (leaf (token "4c" SPINE-DATA 11 1))
                                         (leaf (token "=3" MEASURE 12 1))
                                         (leaf (token "4c" SPINE-DATA 13 1))
                                         (leaf (token "4c" SPINE-DATA 14 1))
                                         (leaf (token "4c" SPINE-DATA 15 1))
                                         (leaf (token "==" MEASURE 16 1))
                                         (leaf (token "*-" SPINE-TERMINATOR 17 1)))))))
              (list  (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0)
                           (token "**kern" EXCLUSIVE-INTERPRETATION 0 1))
                     (list (token "*clefG2" CLEF 1 0)
                           (token "*clefG2" CLEF 1 1))
                     (list (token "*k[]" KEY-SIG 2 0) (token "*k[]" KEY-SIG 2 1))
                     (list (token "*a:" KEY-LABEL 3 0) (token "*a:" KEY-LABEL 3 1))
                     (list (token "*M3/4" TIME-SIG 4 0) (token "*M3/4" TIME-SIG 4 1))
                     (list (token "4c" SPINE-DATA 5 0) (token "4c" SPINE-DATA 5 1))
                     (list (token "4c" SPINE-DATA 6 0) (token "4c" SPINE-DATA 6 1))
                     (list (token "4c" SPINE-DATA 7 0) (token "4c" SPINE-DATA 7 1))
                     (list (token "=2" MEASURE 8 0) (token "=2" MEASURE 8 1))
                     (list (token "4c" SPINE-DATA 9 0) (token "4c" SPINE-DATA 9 1))
                     (list (token "4c" SPINE-DATA 10 0) (token "4c" SPINE-DATA 10 1))
                     (list (token "4c" SPINE-DATA 11 0) (token "4c" SPINE-DATA 11 1))
                     (list (token "=3" MEASURE 12 0) (token "=3" MEASURE 12 1))
                     (list (token "4c" SPINE-DATA 13 0) (token "4c" SPINE-DATA 13 1))
                     (list (token "4c" SPINE-DATA 14 0) (token "4c" SPINE-DATA 14 1))
                     (list (token "4c" SPINE-DATA 15 0) (token "4c" SPINE-DATA 15 1))
                     (list (token "==" MEASURE 16 0) (token "==" MEASURE 16 1))
                     (list (token "*-" SPINE-TERMINATOR 17 0) (token "*-" SPINE-TERMINATOR 17 1))))
(check-expect (hfile->hgraph (path->hfile "../../data/count/two-spines-no-splits.krn"))
              (hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                        (leaf (token "*clefG2" CLEF 1 0))
                                        (leaf (token "*k[]" KEY-SIG 2 0))
                                        (leaf (token "*a:" KEY-LABEL 3 0))
                                        (leaf (token "*M3/4" TIME-SIG 4 0))
                                        (leaf (token "4c" SPINE-DATA 5 0))
                                        (leaf (token "4c" SPINE-DATA 6 0))
                                        (leaf (token "4c" SPINE-DATA 7 0))
                                        (leaf (token "=2" MEASURE 8 0))
                                        (leaf (token "4c" SPINE-DATA 9 0))
                                        (leaf (token "4c" SPINE-DATA 10 0))
                                        (leaf (token "4c" SPINE-DATA 11 0))
                                        (leaf (token "=3" MEASURE 12 0))
                                        (leaf (token "4c" SPINE-DATA 13 0))
                                        (leaf (token "4c" SPINE-DATA 14 0))
                                        (leaf (token "4c" SPINE-DATA 15 0))
                                        (leaf (token "==" MEASURE 16 0))
                                        (leaf (token "*-" SPINE-TERMINATOR 17 0)))
                                  (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 1))
                                        (leaf (token "*clefG2" CLEF 1 1))
                                        (leaf (token "*k[]" KEY-SIG 2 1))
                                        (leaf (token "*a:" KEY-LABEL 3 1))
                                        (leaf (token "*M3/4" TIME-SIG 4 1))
                                        (leaf (token "4c" SPINE-DATA 5 1))
                                        (leaf (token "4c" SPINE-DATA 6 1))
                                        (leaf (token "4c" SPINE-DATA 7 1))
                                        (leaf (token "=2" MEASURE 8 1))
                                        (leaf (token "4c" SPINE-DATA 9 1))
                                        (leaf (token "4c" SPINE-DATA 10 1))
                                        (leaf (token "4c" SPINE-DATA 11 1))
                                        (leaf (token "=3" MEASURE 12 1))
                                        (leaf (token "4c" SPINE-DATA 13 1))
                                        (leaf (token "4c" SPINE-DATA 14 1))
                                        (leaf (token "4c" SPINE-DATA 15 1))
                                        (leaf (token "==" MEASURE 16 1))
                                        (leaf (token "*-" SPINE-TERMINATOR 17 1)))))))
; branch->lot test for spine 0
(check-expect (branch->lot (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                 (leaf (token "*clefG2" CLEF 1 0))
                                 (leaf (token "*k[]" KEY-SIG 2 0))
                                 (leaf (token "*a:" KEY-LABEL 3 0))
                                 (leaf (token "*M3/4" TIME-SIG 4 0))
                                 (leaf (token "4c" SPINE-DATA 5 0))
                                 (leaf (token "4c" SPINE-DATA 6 0))
                                 (leaf (token "4c" SPINE-DATA 7 0))
                                 (leaf (token "=2" MEASURE 8 0))
                                 (leaf (token "4c" SPINE-DATA 9 0))
                                 (leaf (token "4c" SPINE-DATA 10 0))
                                 (leaf (token "4c" SPINE-DATA 11 0))
                                 (leaf (token "=3" MEASURE 12 0))
                                 (leaf (token "4c" SPINE-DATA 13 0))
                                 (leaf (token "4c" SPINE-DATA 14 0))
                                 (leaf (token "4c" SPINE-DATA 15 0))
                                 (leaf (token "==" MEASURE 16 0))
                                 (leaf (token "*-" SPINE-TERMINATOR 17 0))))
              (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0)
                    (token "*clefG2" CLEF 1 0)
                    (token "*k[]" KEY-SIG 2 0)
                    (token "*a:" KEY-LABEL 3 0)
                    (token "*M3/4" TIME-SIG 4 0)
                    (token "4c" SPINE-DATA 5 0)
                    (token "4c" SPINE-DATA 6 0)
                    (token "4c" SPINE-DATA 7 0)
                    (token "=2" MEASURE 8 0)
                    (token "4c" SPINE-DATA 9 0)
                    (token "4c" SPINE-DATA 10 0)
                    (token "4c" SPINE-DATA 11 0)
                    (token "=3" MEASURE 12 0)
                    (token "4c" SPINE-DATA 13 0)
                    (token "4c" SPINE-DATA 14 0)
                    (token "4c" SPINE-DATA 15 0)
                    (token "==" MEASURE 16 0)
                    (token "*-" SPINE-TERMINATOR 17 0)))
; branch->lot test for spine 1
(check-expect (branch->lot (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 1))
                                 (leaf (token "*clefG2" CLEF 1 1))
                                 (leaf (token "*k[]" KEY-SIG 2 1))
                                 (leaf (token "*a:" KEY-LABEL 3 1))
                                 (leaf (token "*M3/4" TIME-SIG 4 1))
                                 (leaf (token "4c" SPINE-DATA 5 1))
                                 (leaf (token "4c" SPINE-DATA 6 1))
                                 (leaf (token "4c" SPINE-DATA 7 1))
                                 (leaf (token "=2" MEASURE 8 1))
                                 (leaf (token "4c" SPINE-DATA 9 1))
                                 (leaf (token "4c" SPINE-DATA 10 1))
                                 (leaf (token "4c" SPINE-DATA 11 1))
                                 (leaf (token "=3" MEASURE 12 1))
                                 (leaf (token "4c" SPINE-DATA 13 1))
                                 (leaf (token "4c" SPINE-DATA 14 1))
                                 (leaf (token "4c" SPINE-DATA 15 1))
                                 (leaf (token "==" MEASURE 16 1))
                                 (leaf (token "*-" SPINE-TERMINATOR 17 1))))
              (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 1)
                    (token "*clefG2" CLEF 1 1)
                    (token "*k[]" KEY-SIG 2 1)
                    (token "*a:" KEY-LABEL 3 1)
                    (token "*M3/4" TIME-SIG 4 1)
                    (token "4c" SPINE-DATA 5 1)
                    (token "4c" SPINE-DATA 6 1)
                    (token "4c" SPINE-DATA 7 1)
                    (token "=2" MEASURE 8 1)
                    (token "4c" SPINE-DATA 9 1)
                    (token "4c" SPINE-DATA 10 1)
                    (token "4c" SPINE-DATA 11 1)
                    (token "=3" MEASURE 12 1)
                    (token "4c" SPINE-DATA 13 1)
                    (token "4c" SPINE-DATA 14 1)
                    (token "4c" SPINE-DATA 15 1)
                    (token "==" MEASURE 16 1)
                    (token "*-" SPINE-TERMINATOR 17 1)))
(check-expect (gspines->linked-spines (spine-parser (path->hfile "../../data/count/two-spines-no-splits.krn"))
                                      (path->hfile "../../data/count/two-spines-no-splits.krn"))
              (list (linked-spine KERN-0-0) (linked-spine KERN-0-1)))

(test)
