#lang racket/base

(require "../../../../parser/data-definitions/data-definitions.rkt"
         "../../../../parser/functions/file.rkt"
         "../../../../parser/functions/spine-parser.rkt"
         "../../../../parser/data-structures/humdrum-graph/data-definitions/data-definitions.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hgraph-to-hfile.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hfile-to-hgraph.rkt"
         "../../../../parser/data-structures/linked-spine/data-definitions/data-definitions.rkt"
         "../../../../parser/data-structures/linked-spine/functions/gspines-to-linked-spines.rkt"
         test-engine/racket-tests)

;; Node definitions
(define TERM-21-0 (terminator-node (token "*-" 'SpineTerminator 21 0)))
(define M-20-0 (token-node (token "==" 'Measure 20 0) (box-immutable TERM-21-0)))
(define J-19-0 (token-node (token "*v" 'SpineJoin 19 0) (box-immutable M-20-0)))
(define J-19-1 (token-node (token "*v" 'SpineJoin 19 1) (box-immutable M-20-0)))
(define NULL-18-0 (token-node (token "*" 'NullInterpretation 18 0) (box-immutable J-19-0)))
(define NULL-18-1 (token-node (token "*" 'NullInterpretation 18 1) (box-immutable J-19-1)))
(define 4c-17-0 (token-node (token "4c" 'SpineData 17 0) (box-immutable NULL-18-0)))
(define 4c-17-1 (token-node (token "4c" 'SpineData 17 1) (box-immutable NULL-18-1)))
(define 4c-16-0 (token-node (token "4c" 'SpineData 16 0) (box-immutable 4c-17-0)))
(define 4c-16-1 (token-node (token "4c" 'SpineData 16 1) (box-immutable 4c-17-1)))
(define 4c-15-0 (token-node (token "4c" 'SpineData 15 0) (box-immutable 4c-16-0)))
(define 4c-15-1 (token-node (token "4c" 'SpineData 15 1) (box-immutable 4c-16-1)))
(define M-14-0 (token-node (token "=3" 'Measure 14 0) (box-immutable 4c-15-0)))
(define M-14-1 (token-node (token "=3" 'Measure 14 1) (box-immutable 4c-15-1)))
(define 4c-13-0 (token-node (token "4c" 'SpineData 13 0) (box-immutable M-14-0)))
(define 4c-13-1 (token-node (token "4c" 'SpineData 13 1) (box-immutable M-14-1)))
(define 4c-12-0 (token-node (token "4c" 'SpineData 12 0) (box-immutable 4c-13-0)))
(define 4c-12-1 (token-node (token "4c" 'SpineData 12 1) (box-immutable 4c-13-1)))
(define 4c-11-0 (token-node (token "4c" 'SpineData 11 0) (box-immutable 4c-12-0)))
(define 4c-11-1 (token-node (token "4c" 'SpineData 11 1) (box-immutable 4c-12-1)))
(define M-10-0 (token-node (token "=2" 'Measure 10 0) (box-immutable 4c-11-0)))
(define M-10-1 (token-node (token "=2" 'Measure 10 1) (box-immutable 4c-11-1)))
(define 4c-9-0 (token-node (token "4c" 'SpineData 9 0) (box-immutable M-10-0)))
(define 4c-9-1 (token-node (token "4c" 'SpineData 9 1) (box-immutable M-10-1)))
(define 4c-8-0 (token-node (token "4c" 'SpineData 8 0) (box-immutable 4c-9-0)))
(define 4c-8-1 (token-node (token "4c" 'SpineData 8 1) (box-immutable 4c-9-1)))
(define 4c-7-0 (token-node (token "4c" 'SpineData 7 0) (box-immutable 4c-8-0)))
(define 4c-7-1 (token-node (token "4c" 'SpineData 7 1) (box-immutable 4c-8-1)))
(define NULL-6-0 (token-node (token "*" 'NullInterpretation 6 0) (box-immutable 4c-7-0)))
(define NULL-6-1 (token-node (token "*" 'NullInterpretation 6 1) (box-immutable 4c-7-1)))
(define S-5-0 (split-node (token "*^" 'SpineSplit 5 0)
                          (box-immutable NULL-6-0)
                          (box-immutable NULL-6-1)))
(define TS-4-0 (token-node (token "*M3/4" 'TimeSignature 4 0) (box-immutable S-5-0)))
(define KL-3-0 (token-node (token "*a:" 'KeyLabel 3 0) (box-immutable TS-4-0)))
(define KS-2-0 (token-node (token "*k[]" 'KeySignature 2 0) (box-immutable KL-3-0)))
(define CL-1-0 (token-node (token "*clefG2" 'Clef 1 0) (box-immutable KS-2-0)))
(define KERN-0-0 (token-node (token "**kern" 'ExclusiveInterpretation 0 0) (box-immutable CL-1-0)))

(define TERM-21-1 (terminator-node (token "*-" 'SpineTerminator 21 1)))
(define M-20-1 (token-node (token "==" 'Measure 20 1) (box-immutable TERM-21-1)))
(define NULL-19-2 (token-node (token "*" 'NullInterpretation 19 2) (box-immutable M-20-1)))
(define J-18-2 (token-node (token "*v" 'SpineJoin 18 2) (box-immutable NULL-19-2)))
(define J-18-3 (token-node (token "*v" 'SpineJoin 18 3) (box-immutable NULL-19-2)))
(define 4c-17-2 (token-node (token "4c" 'SpineData 17 2) (box-immutable J-18-2)))
(define 4c-17-3 (token-node (token "4c" 'SpineData 17 3) (box-immutable J-18-3)))
(define 4c-16-2 (token-node (token "4c" 'SpineData 16 2) (box-immutable 4c-17-2)))
(define 4c-16-3 (token-node (token "4c" 'SpineData 16 3) (box-immutable 4c-17-3)))
(define 4c-15-2 (token-node (token "4c" 'SpineData 15 2) (box-immutable 4c-16-2)))
(define 4c-15-3 (token-node (token "4c" 'SpineData 15 3) (box-immutable 4c-16-3)))
(define M-14-2 (token-node (token "=3" 'Measure 14 2) (box-immutable 4c-15-2)))
(define M-14-3 (token-node (token "=3" 'Measure 14 3) (box-immutable 4c-15-3)))
(define 4c-13-2 (token-node (token "4c" 'SpineData 13 2) (box-immutable M-14-2)))
(define 4c-13-3 (token-node (token "4c" 'SpineData 13 3) (box-immutable M-14-3)))
(define 4c-12-2 (token-node (token "4c" 'SpineData 12 2) (box-immutable 4c-13-2)))
(define 4c-12-3 (token-node (token "4c" 'SpineData 12 3) (box-immutable 4c-13-3)))
(define 4c-11-2 (token-node (token "4c" 'SpineData 11 2) (box-immutable 4c-12-2)))
(define 4c-11-3 (token-node (token "4c" 'SpineData 11 3) (box-immutable 4c-12-3)))
(define M-10-2 (token-node (token "=2" 'Measure 10 2) (box-immutable 4c-11-2)))
(define M-10-3 (token-node (token "=2" 'Measure 10 3) (box-immutable 4c-11-3)))
(define 4c-9-2 (token-node (token "4c" 'SpineData 9 2) (box-immutable M-10-2)))
(define 4c-9-3 (token-node (token "4c" 'SpineData 9 3) (box-immutable M-10-3)))
(define 4c-8-2 (token-node (token "4c" 'SpineData 8 2) (box-immutable 4c-9-2)))
(define 4c-8-3 (token-node (token "4c" 'SpineData 8 3) (box-immutable 4c-9-3)))
(define 4c-7-2 (token-node (token "4c" 'SpineData 7 2) (box-immutable 4c-8-2)))
(define 4c-7-3 (token-node (token "4c" 'SpineData 7 3) (box-immutable 4c-8-3)))
(define S-6-2 (split-node (token "*^" 'SpineSplit 6 2)
                          (box-immutable 4c-7-2)
                          (box-immutable 4c-7-3)))
(define NULL-5-1 (token-node (token "*" 'NullInterpretation 5 1) (box-immutable S-6-2))) 
(define TS-4-1 (token-node (token "*M3/4" 'TimeSignature 4 1) (box-immutable NULL-5-1)))
(define KL-3-1 (token-node (token "*a:" 'KeyLabel 3 1) (box-immutable TS-4-1)))
(define KS-2-1 (token-node (token "*k[]" 'KeySignature 2 1) (box-immutable KL-3-1)))
(define CL-1-1 (token-node (token "*clefG2" 'Clef 1 1) (box-immutable KS-2-1)))
(define KERN-0-1 (token-node (token "**kern" 'ExclusiveInterpretation 0 1) (box-immutable CL-1-1)))

(check-expect (path->hfile "../../data/count/two-spines-one-split.krn")
              (hfile (list (record "**kern\t**kern"
                                   TOKEN
                                  (list (token "**kern" 'ExclusiveInterpretation 0 0)
                                         (token "**kern" 'ExclusiveInterpretation 0 1))
                                   0)
                           (record "*clefG2\t*clefG2" TOKEN (list (token "*clefG2" 'Clef 1 0)
                                                                  (token "*clefG2" 'Clef 1 1))
                                   1)
                           (record "*k[]\t*k[]" TOKEN (list (token "*k[]" 'KeySignature 2 0)
                                                            (token "*k[]" 'KeySignature 2 1))
                                   2)
                           (record "*a:\t*a:" TOKEN (list (token "*a:" 'KeyLabel 3 0)
                                                          (token "*a:" 'KeyLabel 3 1))
                                   3)
                           (record "*M3/4\t*M3/4" TOKEN (list (token "*M3/4" 'TimeSignature 4 0)
                                                              (token "*M3/4" 'TimeSignature 4 1))
                                   4)
                           (record "*^\t*" TOKEN (list (token "*^" 'SpineSplit 5 0)
                                                       (token "*" 'NullInterpretation 5 1))
                                   5)
                           (record "*\t*\t*^" TOKEN (list (token "*" 'NullInterpretation 6 0)
                                                          (token "*" 'NullInterpretation 6 1)
                                                          (token "*^" 'SpineSplit 6 2))
                                   6)
                           (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 7 0)
                                                                (token "4c" 'SpineData 7 1)
                                                                (token "4c" 'SpineData 7 2)
                                                                (token "4c" 'SpineData 7 3))
                                   7)
                           (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 8 0)
                                                                (token "4c" 'SpineData 8 1)
                                                                (token "4c" 'SpineData 8 2)
                                                                (token "4c" 'SpineData 8 3))
                                   8)
                           (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 9 0)
                                                                (token "4c" 'SpineData 9 1)
                                                                (token "4c" 'SpineData 9 2)
                                                                (token "4c" 'SpineData 9 3))
                                   9)
                           (record "=2\t=2\t=2\t=2" TOKEN (list (token "=2" 'Measure 10 0)
                                                                (token "=2" 'Measure 10 1)
                                                                (token "=2" 'Measure 10 2)
                                                                (token "=2" 'Measure 10 3))
                                   10)
                           (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 11 0)
                                                                (token "4c" 'SpineData 11 1)
                                                                (token "4c" 'SpineData 11 2)
                                                                (token "4c" 'SpineData 11 3))
                                   11)
                           (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 12 0)
                                                                (token "4c" 'SpineData 12 1)
                                                                (token "4c" 'SpineData 12 2)
                                                                (token "4c" 'SpineData 12 3))
                                   12)
                           (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 13 0)
                                                                (token "4c" 'SpineData 13 1)
                                                                (token "4c" 'SpineData 13 2)
                                                                (token "4c" 'SpineData 13 3))
                                   13)
                           (record "=3\t=3\t=3\t=3" TOKEN (list (token "=3" 'Measure 14 0)
                                                                (token "=3" 'Measure 14 1)
                                                                (token "=3" 'Measure 14 2)
                                                                (token "=3" 'Measure 14 3))
                                   14)
                           (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 15 0)
                                                                (token "4c" 'SpineData 15 1)
                                                                (token "4c" 'SpineData 15 2)
                                                                (token "4c" 'SpineData 15 3))
                                   15)
                           (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 16 0)
                                                                (token "4c" 'SpineData 16 1)
                                                                (token "4c" 'SpineData 16 2)
                                                                (token "4c" 'SpineData 16 3))
                                   16)
                           (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 17 0)
                                                                (token "4c" 'SpineData 17 1)
                                                                (token "4c" 'SpineData 17 2)
                                                                (token "4c" 'SpineData 17 3))
                                   17)
                           (record "*\t*\t*v\t*v" TOKEN (list (token "*" 'NullInterpretation 18 0)
                                                              (token "*" 'NullInterpretation 18 1)
                                                              (token "*v" 'SpineJoin 18 2)
                                                              (token "*v" 'SpineJoin 18 3))
                                   18)
                           (record "*v\t*v\t*" TOKEN (list (token "*v" 'SpineJoin 19 0)
                                                           (token "*v" 'SpineJoin 19 1)
                                                           (token "*" 'NullInterpretation 19 2))
                                   19)
                           (record "==\t==" TOKEN (list (token "==" 'Measure 20 0)
                                                        (token "==" 'Measure 20 1))
                                   20)
                           (record "*-\t*-" TOKEN (list (token "*-" 'SpineTerminator 21 0)
                                                        (token "*-" 'SpineTerminator 21 1))
                                   21))))
(check-expect (spine-parser (path->hfile "../../data/count/two-spines-one-split.krn"))
              (list (global-spine KERN
                                  (list (list (token "**kern" 'ExclusiveInterpretation 0 0))
                                        (list (token "*clefG2" 'Clef 1 0))
                                        (list (token "*k[]" 'KeySignature 2 0))
                                        (list (token "*a:" 'KeyLabel 3 0))
                                        (list (token "*M3/4" 'TimeSignature 4 0))
                                        (list (token "*^" 'SpineSplit 5 0))
                                        (list (token "*" 'NullInterpretation 6 0)
                                              (token "*" 'NullInterpretation 6 1))
                                        (list (token "4c" 'SpineData 7 0)
                                              (token "4c" 'SpineData 7 1))
                                        (list (token "4c" 'SpineData 8 0)
                                              (token "4c" 'SpineData 8 1))
                                        (list (token "4c" 'SpineData 9 0)
                                              (token "4c" 'SpineData 9 1))
                                        (list (token "=2" 'Measure 10 0)
                                              (token "=2" 'Measure 10 1))
                                        (list (token "4c" 'SpineData 11 0)
                                              (token "4c" 'SpineData 11 1))
                                        (list (token "4c" 'SpineData 12 0)
                                              (token "4c" 'SpineData 12 1))
                                        (list (token "4c" 'SpineData 13 0)
                                              (token "4c" 'SpineData 13 1))
                                        (list (token "=3" 'Measure 14 0)
                                              (token "=3" 'Measure 14 1))
                                        (list (token "4c" 'SpineData 15 0)
                                              (token "4c" 'SpineData 15 1))
                                        (list (token "4c" 'SpineData 16 0)
                                              (token "4c" 'SpineData 16 1))
                                        (list (token "4c" 'SpineData 17 0)
                                              (token "4c" 'SpineData 17 1))
                                        (list (token "*" 'NullInterpretation 18 0)
                                              (token "*" 'NullInterpretation 18 1))
                                        (list (token "*v" 'SpineJoin 19 0)
                                              (token "*v" 'SpineJoin 19 1))
                                        (list (token "==" 'Measure 20 0))
                                        (list (token "*-" 'SpineTerminator 21 0)))
                                  0)
                    (global-spine KERN
                                  (list (list (token "**kern" 'ExclusiveInterpretation 0 1))
                                        (list (token "*clefG2" 'Clef 1 1))
                                        (list (token "*k[]" 'KeySignature 2 1))
                                        (list (token "*a:" 'KeyLabel 3 1))
                                        (list (token "*M3/4" 'TimeSignature 4 1))
                                        (list (token "*" 'NullInterpretation 5 1))
                                        (list (token "*^" 'SpineSplit 6 2))
                                        (list (token "4c" 'SpineData 7 2)
                                              (token "4c" 'SpineData 7 3))
                                        (list (token "4c" 'SpineData 8 2)
                                              (token "4c" 'SpineData 8 3))
                                        (list (token "4c" 'SpineData 9 2)
                                              (token "4c" 'SpineData 9 3))
                                        (list (token "=2" 'Measure 10 2)
                                              (token "=2" 'Measure 10 3))
                                        (list (token "4c" 'SpineData 11 2)
                                              (token "4c" 'SpineData 11 3))
                                        (list (token "4c" 'SpineData 12 2)
                                              (token "4c" 'SpineData 12 3))
                                        (list (token "4c" 'SpineData 13 2)
                                              (token "4c" 'SpineData 13 3))
                                        (list (token "=3" 'Measure 14 2)
                                              (token "=3" 'Measure 14 3))
                                        (list (token "4c" 'SpineData 15 2)
                                              (token "4c" 'SpineData 15 3))
                                        (list (token "4c" 'SpineData 16 2)
                                              (token "4c" 'SpineData 16 3))
                                        (list (token "4c" 'SpineData 17 2)
                                              (token "4c" 'SpineData 17 3))
                                        (list (token "*v" 'SpineJoin 18 2)
                                              (token "*v" 'SpineJoin 18 3))
                                        (list (token "*" 'NullInterpretation 19 2))
                                        (list (token "==" 'Measure 20 1))
                                        (list (token "*-" 'SpineTerminator 21 1)))
                                  1)))
(check-expect (hgraph->hfile
               (hgraph (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                         (leaf (token "*clefG2" 'Clef 1 0))
                                         (leaf (token "*k[]" 'KeySignature 2 0))
                                         (leaf (token "*a:" 'KeyLabel 3 0))
                                         (leaf (token "*M3/4" 'TimeSignature 4 0))
                                         (parent (token "*^" 'SpineSplit 5 0)
                                                 (list (leaf (token "*" 'NullInterpretation 6 0))
                                                       (leaf (token "4c" 'SpineData 7 0))
                                                       (leaf (token "4c" 'SpineData 8 0))
                                                       (leaf (token "4c" 'SpineData 9 0))
                                                       (leaf (token "=2" 'Measure 10 0))
                                                       (leaf (token "4c" 'SpineData 11 0))
                                                       (leaf (token "4c" 'SpineData 12 0))
                                                       (leaf (token "4c" 'SpineData 13 0))
                                                       (leaf (token "=3" 'Measure 14 0))
                                                       (leaf (token "4c" 'SpineData 15 0))
                                                       (leaf (token "4c" 'SpineData 16 0))
                                                       (leaf (token "4c" 'SpineData 17 0))
                                                       (leaf (token "*" 'NullInterpretation 18 0))
                                                       (leaf (token "*v" 'SpineJoin 19 0)))
                                                 (list (leaf (token "*" 'NullInterpretation 6 1))
                                                       (leaf (token "4c" 'SpineData 7 1))
                                                       (leaf (token "4c" 'SpineData 8 1))
                                                       (leaf (token "4c" 'SpineData 9 1))
                                                       (leaf (token "=2" 'Measure 10 1))
                                                       (leaf (token "4c" 'SpineData 11 1))
                                                       (leaf (token "4c" 'SpineData 12 1))
                                                       (leaf (token "4c" 'SpineData 13 1))
                                                       (leaf (token "=3" 'Measure 14 1))
                                                       (leaf (token "4c" 'SpineData 15 1))
                                                       (leaf (token "4c" 'SpineData 16 1))
                                                       (leaf (token "4c" 'SpineData 17 1))
                                                       (leaf (token "*" 'NullInterpretation 18 1))
                                                       (leaf (token "*v" 'SpineJoin 19 1))))
                                         (leaf (token "==" 'Measure 20 0))
                                         (leaf (token "*-" 'SpineTerminator 21 0)))
                                   (list (leaf (token "**kern" 'ExclusiveInterpretation 0 1))
                                         (leaf (token "*clefG2" 'Clef 1 1))
                                         (leaf (token "*k[]" 'KeySignature 2 1))
                                         (leaf (token "*a:" 'KeyLabel 3 1))
                                         (leaf (token "*M3/4" 'TimeSignature 4 1))
                                         (leaf (token "*" 'NullInterpretation 5 1))
                                         (parent (token "*^" 'SpineSplit 6 2)
                                                 (list (leaf (token "4c" 'SpineData 7 2))
                                                       (leaf (token "4c" 'SpineData 8 2))
                                                       (leaf (token "4c" 'SpineData 9 2))
                                                       (leaf (token "=2" 'Measure 10 2))
                                                       (leaf (token "4c" 'SpineData 11 2))
                                                       (leaf (token "4c" 'SpineData 12 2))
                                                       (leaf (token "4c" 'SpineData 13 2))
                                                       (leaf (token "=3" 'Measure 14 2))
                                                       (leaf (token "4c" 'SpineData 15 2))
                                                       (leaf (token "4c" 'SpineData 16 2))
                                                       (leaf (token "4c" 'SpineData 17 2))
                                                       (leaf (token "*v" 'SpineJoin 18 2)))
                                                 (list (leaf (token "4c" 'SpineData 7 3))
                                                       (leaf (token "4c" 'SpineData 8 3))
                                                       (leaf (token "4c" 'SpineData 9 3))
                                                       (leaf (token "=2" 'Measure 10 3))
                                                       (leaf (token "4c" 'SpineData 11 3))
                                                       (leaf (token "4c" 'SpineData 12 3))
                                                       (leaf (token "4c" 'SpineData 13 3))
                                                       (leaf (token "=3" 'Measure 14 3))
                                                       (leaf (token "4c" 'SpineData 15 3))
                                                       (leaf (token "4c" 'SpineData 16 3))
                                                       (leaf (token "4c" 'SpineData 17 3))
                                                       (leaf (token "*v" 'SpineJoin 18 3))))
                                         (leaf (token "*" 'NullInterpretation 19 2))
                                         (leaf (token "==" 'Measure 20 1))
                                         (leaf (token "*-" 'SpineTerminator 21 1)))))))
              (path->hfile "../../data/count/two-spines-one-split.krn"))
(check-expect (tokens->records (list (list (token "**kern" 'ExclusiveInterpretation 0 0)
                                      (token "**kern" 'ExclusiveInterpretation 0 1))
                                (list (token "*clefG2" 'Clef 1 0)
                                      (token "*clefG2" 'Clef 1 1))
                                (list (token "*k[]" 'KeySignature 2 0)
                                      (token "*k[]" 'KeySignature 2 1))
                                (list (token "*a:" 'KeyLabel 3 0)
                                      (token "*a:" 'KeyLabel 3 1))
                                (list (token "*M3/4" 'TimeSignature 4 0)
                                      (token "*M3/4" 'TimeSignature 4 1))
                                (list (token "*^" 'SpineSplit 5 0)
                                      (token "*" 'NullInterpretation 5 1))
                                (list (token "*" 'NullInterpretation 6 0)
                                      (token "*" 'NullInterpretation 6 1)
                                      (token "*^" 'SpineSplit 6 2))
                                (list (token "4c" 'SpineData 7 0)
                                      (token "4c" 'SpineData 7 1)
                                      (token "4c" 'SpineData 7 2)
                                      (token "4c" 'SpineData 7 3))
                                (list (token "4c" 'SpineData 8 0)
                                      (token "4c" 'SpineData 8 1)
                                      (token "4c" 'SpineData 8 2)
                                      (token "4c" 'SpineData 8 3))
                                (list (token "4c" 'SpineData 9 0)
                                      (token "4c" 'SpineData 9 1)
                                      (token "4c" 'SpineData 9 2)
                                      (token "4c" 'SpineData 9 3))
                                (list (token "=2" 'Measure 10 0)
                                      (token "=2" 'Measure 10 1)
                                      (token "=2" 'Measure 10 2)
                                      (token "=2" 'Measure 10 3))
                                (list (token "4c" 'SpineData 11 0)
                                      (token "4c" 'SpineData 11 1)
                                      (token "4c" 'SpineData 11 2)
                                      (token "4c" 'SpineData 11 3))
                                (list (token "4c" 'SpineData 12 0)
                                      (token "4c" 'SpineData 12 1)
                                      (token "4c" 'SpineData 12 2)
                                      (token "4c" 'SpineData 12 3))
                                (list (token "4c" 'SpineData 13 0)
                                      (token "4c" 'SpineData 13 1)
                                      (token "4c" 'SpineData 13 2)
                                      (token "4c" 'SpineData 13 3))
                                (list (token "=3" 'Measure 14 0)
                                      (token "=3" 'Measure 14 1)
                                      (token "=3" 'Measure 14 2)
                                      (token "=3" 'Measure 14 3))
                                (list (token "4c" 'SpineData 15 0)
                                      (token "4c" 'SpineData 15 1)
                                      (token "4c" 'SpineData 15 2)
                                      (token "4c" 'SpineData 15 3))
                                (list (token "4c" 'SpineData 16 0)
                                      (token "4c" 'SpineData 16 1)
                                      (token "4c" 'SpineData 16 2)
                                      (token "4c" 'SpineData 16 3))
                                (list (token "4c" 'SpineData 17 0)
                                      (token "4c" 'SpineData 17 1)
                                      (token "4c" 'SpineData 17 2)
                                      (token "4c" 'SpineData 17 3))
                                (list (token "*" 'NullInterpretation 18 0)
                                      (token "*" 'NullInterpretation 18 1)
                                      (token "*v" 'SpineJoin 18 2)
                                      (token "*v" 'SpineJoin 18 3))
                                (list (token "*v" 'SpineJoin 19 0)
                                      (token "*v" 'SpineJoin 19 1)
                                      (token "*" 'NullInterpretation 19 2))
                                (list (token "==" 'Measure 20 0)
                                      (token "==" 'Measure 20 1))
                                (list (token "*-" 'SpineTerminator 21 0)
                                      (token "*-" 'SpineTerminator 21 1))))
              (list (record "**kern\t**kern"
                            TOKEN
                            (list (token "**kern" 'ExclusiveInterpretation 0 0)
                                  (token "**kern" 'ExclusiveInterpretation 0 1))
                            0)
                    (record "*clefG2\t*clefG2" TOKEN (list (token "*clefG2" 'Clef 1 0)
                                                           (token "*clefG2" 'Clef 1 1))
                            1)
                    (record "*k[]\t*k[]" TOKEN (list (token "*k[]" 'KeySignature 2 0)
                                                     (token "*k[]" 'KeySignature 2 1))
                            2)
                    (record "*a:\t*a:" TOKEN (list (token "*a:" 'KeyLabel 3 0)
                                                   (token "*a:" 'KeyLabel 3 1))
                            3)
                    (record "*M3/4\t*M3/4" TOKEN (list (token "*M3/4" 'TimeSignature 4 0)
                                                       (token "*M3/4" 'TimeSignature 4 1))
                            4)
                    (record "*^\t*" TOKEN (list (token "*^" 'SpineSplit 5 0)
                                                (token "*" 'NullInterpretation 5 1))
                            5)
                    (record "*\t*\t*^" TOKEN (list (token "*" 'NullInterpretation 6 0)
                                                   (token "*" 'NullInterpretation 6 1)
                                                   (token "*^" 'SpineSplit 6 2))
                            6)
                    (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 7 0)
                                                         (token "4c" 'SpineData 7 1)
                                                         (token "4c" 'SpineData 7 2)
                                                         (token "4c" 'SpineData 7 3))
                            7)
                    (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 8 0)
                                                         (token "4c" 'SpineData 8 1)
                                                         (token "4c" 'SpineData 8 2)
                                                         (token "4c" 'SpineData 8 3))
                            8)
                    (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 9 0)
                                                         (token "4c" 'SpineData 9 1)
                                                         (token "4c" 'SpineData 9 2)
                                                         (token "4c" 'SpineData 9 3))
                            9)
                    (record "=2\t=2\t=2\t=2" TOKEN (list (token "=2" 'Measure 10 0)
                                                         (token "=2" 'Measure 10 1)
                                                         (token "=2" 'Measure 10 2)
                                                         (token "=2" 'Measure 10 3))
                            10)
                    (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 11 0)
                                                         (token "4c" 'SpineData 11 1)
                                                         (token "4c" 'SpineData 11 2)
                                                         (token "4c" 'SpineData 11 3))
                            11)
                    (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 12 0)
                                                         (token "4c" 'SpineData 12 1)
                                                         (token "4c" 'SpineData 12 2)
                                                         (token "4c" 'SpineData 12 3))
                            12)
                    (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 13 0)
                                                         (token "4c" 'SpineData 13 1)
                                                         (token "4c" 'SpineData 13 2)
                                                         (token "4c" 'SpineData 13 3))
                            13)
                    (record "=3\t=3\t=3\t=3" TOKEN (list (token "=3" 'Measure 14 0)
                                                         (token "=3" 'Measure 14 1)
                                                         (token "=3" 'Measure 14 2)
                                                         (token "=3" 'Measure 14 3))
                            14)
                    (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 15 0)
                                                         (token "4c" 'SpineData 15 1)
                                                         (token "4c" 'SpineData 15 2)
                                                         (token "4c" 'SpineData 15 3))
                            15)
                    (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 16 0)
                                                         (token "4c" 'SpineData 16 1)
                                                         (token "4c" 'SpineData 16 2)
                                                         (token "4c" 'SpineData 16 3))
                            16)
                    (record "4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 17 0)
                                                         (token "4c" 'SpineData 17 1)
                                                         (token "4c" 'SpineData 17 2)
                                                         (token "4c" 'SpineData 17 3))
                            17)
                    (record "*\t*\t*v\t*v" TOKEN (list (token "*" 'NullInterpretation 18 0)
                                                       (token "*" 'NullInterpretation 18 1)
                                                       (token "*v" 'SpineJoin 18 2)
                                                       (token "*v" 'SpineJoin 18 3))
                            18)
                    (record "*v\t*v\t*" TOKEN (list (token "*v" 'SpineJoin 19 0)
                                                    (token "*v" 'SpineJoin 19 1)
                                                    (token "*" 'NullInterpretation 19 2))
                            19)
                    (record "==\t==" TOKEN (list (token "==" 'Measure 20 0)
                                                 (token "==" 'Measure 20 1))
                            20)
                    (record "*-\t*-" TOKEN (list (token "*-" 'SpineTerminator 21 0)
                                                 (token "*-" 'SpineTerminator 21 1))
                            21)))
(check-expect (hgraph->tokens
               (hgraph (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                         (leaf (token "*clefG2" 'Clef 1 0))
                                         (leaf (token "*k[]" 'KeySignature 2 0))
                                         (leaf (token "*a:" 'KeyLabel 3 0))
                                         (leaf (token "*M3/4" 'TimeSignature 4 0))
                                         (parent (token "*^" 'SpineSplit 5 0)
                                                 (list (leaf (token "*" 'NullInterpretation 6 0))
                                                       (leaf (token "4c" 'SpineData 7 0))
                                                       (leaf (token "4c" 'SpineData 8 0))
                                                       (leaf (token "4c" 'SpineData 9 0))
                                                       (leaf (token "=2" 'Measure 10 0))
                                                       (leaf (token "4c" 'SpineData 11 0))
                                                       (leaf (token "4c" 'SpineData 12 0))
                                                       (leaf (token "4c" 'SpineData 13 0))
                                                       (leaf (token "=3" 'Measure 14 0))
                                                       (leaf (token "4c" 'SpineData 15 0))
                                                       (leaf (token "4c" 'SpineData 16 0))
                                                       (leaf (token "4c" 'SpineData 17 0))
                                                       (leaf (token "*" 'NullInterpretation 18 0))
                                                       (leaf (token "*v" 'SpineJoin 19 0)))
                                                 (list (leaf (token "*" 'NullInterpretation 6 1))
                                                       (leaf (token "4c" 'SpineData 7 1))
                                                       (leaf (token "4c" 'SpineData 8 1))
                                                       (leaf (token "4c" 'SpineData 9 1))
                                                       (leaf (token "=2" 'Measure 10 1))
                                                       (leaf (token "4c" 'SpineData 11 1))
                                                       (leaf (token "4c" 'SpineData 12 1))
                                                       (leaf (token "4c" 'SpineData 13 1))
                                                       (leaf (token "=3" 'Measure 14 1))
                                                       (leaf (token "4c" 'SpineData 15 1))
                                                       (leaf (token "4c" 'SpineData 16 1))
                                                       (leaf (token "4c" 'SpineData 17 1))
                                                       (leaf (token "*" 'NullInterpretation 18 1))
                                                       (leaf (token "*v" 'SpineJoin 19 1))))
                                         (leaf (token "==" 'Measure 20 0))
                                         (leaf (token "*-" 'SpineTerminator 21 0)))
                                   (list (leaf (token "**kern" 'ExclusiveInterpretation 0 1))
                                         (leaf (token "*clefG2" 'Clef 1 1))
                                         (leaf (token "*k[]" 'KeySignature 2 1))
                                         (leaf (token "*a:" 'KeyLabel 3 1))
                                         (leaf (token "*M3/4" 'TimeSignature 4 1))
                                         (leaf (token "*" 'NullInterpretation 5 1))
                                         (parent (token "*^" 'SpineSplit 6 2)
                                                 (list (leaf (token "4c" 'SpineData 7 2))
                                                       (leaf (token "4c" 'SpineData 8 2))
                                                       (leaf (token "4c" 'SpineData 9 2))
                                                       (leaf (token "=2" 'Measure 10 2))
                                                       (leaf (token "4c" 'SpineData 11 2))
                                                       (leaf (token "4c" 'SpineData 12 2))
                                                       (leaf (token "4c" 'SpineData 13 2))
                                                       (leaf (token "=3" 'Measure 14 2))
                                                       (leaf (token "4c" 'SpineData 15 2))
                                                       (leaf (token "4c" 'SpineData 16 2))
                                                       (leaf (token "4c" 'SpineData 17 2))
                                                       (leaf (token "*v" 'SpineJoin 18 2)))
                                                 (list (leaf (token "4c" 'SpineData 7 3))
                                                       (leaf (token "4c" 'SpineData 8 3))
                                                       (leaf (token "4c" 'SpineData 9 3))
                                                       (leaf (token "=2" 'Measure 10 3))
                                                       (leaf (token "4c" 'SpineData 11 3))
                                                       (leaf (token "4c" 'SpineData 12 3))
                                                       (leaf (token "4c" 'SpineData 13 3))
                                                       (leaf (token "=3" 'Measure 14 3))
                                                       (leaf (token "4c" 'SpineData 15 3))
                                                       (leaf (token "4c" 'SpineData 16 3))
                                                       (leaf (token "4c" 'SpineData 17 3))
                                                       (leaf (token "*v" 'SpineJoin 18 3))))
                                         (leaf (token "*" 'NullInterpretation 19 2))
                                         (leaf (token "==" 'Measure 20 1))
                                         (leaf (token "*-" 'SpineTerminator 21 1)))))))
              (list (list (token "**kern" 'ExclusiveInterpretation 0 0)
                          (token "**kern" 'ExclusiveInterpretation 0 1))
                    (list (token "*clefG2" 'Clef 1 0)
                          (token "*clefG2" 'Clef 1 1))
                    (list (token "*k[]" 'KeySignature 2 0)
                          (token "*k[]" 'KeySignature 2 1))
                    (list (token "*a:" 'KeyLabel 3 0)
                          (token "*a:" 'KeyLabel 3 1))
                    (list (token "*M3/4" 'TimeSignature 4 0)
                          (token "*M3/4" 'TimeSignature 4 1))
                    (list (token "*^" 'SpineSplit 5 0)
                          (token "*" 'NullInterpretation 5 1))
                    (list (token "*" 'NullInterpretation 6 0)
                          (token "*" 'NullInterpretation 6 1)
                          (token "*^" 'SpineSplit 6 2))
                    (list (token "4c" 'SpineData 7 0)
                          (token "4c" 'SpineData 7 1)
                          (token "4c" 'SpineData 7 2)
                          (token "4c" 'SpineData 7 3))
                    (list (token "4c" 'SpineData 8 0)
                          (token "4c" 'SpineData 8 1)
                          (token "4c" 'SpineData 8 2)
                          (token "4c" 'SpineData 8 3))
                    (list (token "4c" 'SpineData 9 0)
                          (token "4c" 'SpineData 9 1)
                          (token "4c" 'SpineData 9 2)
                          (token "4c" 'SpineData 9 3))
                    (list (token "=2" 'Measure 10 0)
                          (token "=2" 'Measure 10 1)
                          (token "=2" 'Measure 10 2)
                          (token "=2" 'Measure 10 3))
                    (list (token "4c" 'SpineData 11 0)
                          (token "4c" 'SpineData 11 1)
                          (token "4c" 'SpineData 11 2)
                          (token "4c" 'SpineData 11 3))
                    (list (token "4c" 'SpineData 12 0)
                          (token "4c" 'SpineData 12 1)
                          (token "4c" 'SpineData 12 2)
                          (token "4c" 'SpineData 12 3))
                    (list (token "4c" 'SpineData 13 0)
                          (token "4c" 'SpineData 13 1)
                          (token "4c" 'SpineData 13 2)
                          (token "4c" 'SpineData 13 3))
                    (list (token "=3" 'Measure 14 0)
                          (token "=3" 'Measure 14 1)
                          (token "=3" 'Measure 14 2)
                          (token "=3" 'Measure 14 3))
                    (list (token "4c" 'SpineData 15 0)
                          (token "4c" 'SpineData 15 1)
                          (token "4c" 'SpineData 15 2)
                          (token "4c" 'SpineData 15 3))
                    (list (token "4c" 'SpineData 16 0)
                          (token "4c" 'SpineData 16 1)
                          (token "4c" 'SpineData 16 2)
                          (token "4c" 'SpineData 16 3))
                    (list (token "4c" 'SpineData 17 0)
                          (token "4c" 'SpineData 17 1)
                          (token "4c" 'SpineData 17 2)
                          (token "4c" 'SpineData 17 3))
                    (list (token "*" 'NullInterpretation 18 0)
                          (token "*" 'NullInterpretation 18 1)
                          (token "*v" 'SpineJoin 18 2)
                          (token "*v" 'SpineJoin 18 3))
                    (list (token "*v" 'SpineJoin 19 0)
                          (token "*v" 'SpineJoin 19 1)
                          (token "*" 'NullInterpretation 19 2))
                    (list (token "==" 'Measure 20 0)
                          (token "==" 'Measure 20 1))
                    (list (token "*-" 'SpineTerminator 21 0)
                          (token "*-" 'SpineTerminator 21 1))))
#|
(check-expect (hfile->hgraph (path->hfile "../../data/count/two-spines-one-split.krn"))
              (hgraph (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                        (leaf (token "*clefG2" 'Clef 1 0))
                                        (leaf (token "*k[]" 'KeySignature 2 0))
                                        (leaf (token "*a:" 'KeyLabel 3 0))
                                        (leaf (token "*M3/4" 'TimeSignature 4 0))
                                        (parent (token "*^" 'SpineSplit 5 0)
                                                (list (leaf (token "*" 'NullInterpretation 6 0))
                                                      (leaf (token "4c" 'SpineData 7 0))
                                                      (leaf (token "4c" 'SpineData 8 0))
                                                      (leaf (token "4c" 'SpineData 9 0))
                                                      (leaf (token "=2" 'Measure 10 0))
                                                      (leaf (token "4c" 'SpineData 11 0))
                                                      (leaf (token "4c" 'SpineData 12 0))
                                                      (leaf (token "4c" 'SpineData 13 0))
                                                      (leaf (token "=3" 'Measure 14 0))
                                                      (leaf (token "4c" 'SpineData 15 0))
                                                      (leaf (token "4c" 'SpineData 16 0))
                                                      (leaf (token "4c" 'SpineData 17 0))
                                                      (leaf (token "*" 'NullInterpretation 18 0))
                                                      (leaf (token "*v" 'SpineJoin 19 0)))
                                                (list (leaf (token "*" 'NullInterpretation 6 1))
                                                      (leaf (token "4c" 'SpineData 7 1))
                                                      (leaf (token "4c" 'SpineData 8 1))
                                                      (leaf (token "4c" 'SpineData 9 1))
                                                      (leaf (token "=2" 'Measure 10 1))
                                                      (leaf (token "4c" 'SpineData 11 1))
                                                      (leaf (token "4c" 'SpineData 12 1))
                                                      (leaf (token "4c" 'SpineData 13 1))
                                                      (leaf (token "=3" 'Measure 14 1))
                                                      (leaf (token "4c" 'SpineData 15 1))
                                                      (leaf (token "4c" 'SpineData 16 1))
                                                      (leaf (token "4c" 'SpineData 17 1))
                                                      (leaf (token "*" 'NullInterpretation 18 1))
                                                      (leaf (token "*v" 'SpineJoin 19 1))))
                                        (leaf (token "==" 'Measure 20 0))
                                        (leaf (token "*-" 'SpineTerminator 21 0)))
                                  (list (leaf (token "**kern" 'ExclusiveInterpretation 0 1))
                                        (leaf (token "*clefG2" 'Clef 1 1))
                                        (leaf (token "*k[]" 'KeySignature 2 1))
                                        (leaf (token "*a:" 'KeyLabel 3 1))
                                        (leaf (token "*M3/4" 'TimeSignature 4 1))
                                        (leaf (token "*" 'NullInterpretation 5 1))
                                        (parent (token "*^" 'SpineSplit 6 2)
                                                (list (leaf (token "4c" 'SpineData 7 2))
                                                      (leaf (token "4c" 'SpineData 8 2))
                                                      (leaf (token "4c" 'SpineData 9 2))
                                                      (leaf (token "=2" 'Measure 10 2))
                                                      (leaf (token "4c" 'SpineData 11 2))
                                                      (leaf (token "4c" 'SpineData 12 2))
                                                      (leaf (token "4c" 'SpineData 13 2))
                                                      (leaf (token "=3" 'Measure 14 2))
                                                      (leaf (token "4c" 'SpineData 15 2))
                                                      (leaf (token "4c" 'SpineData 16 2))
                                                      (leaf (token "4c" 'SpineData 17 2))
                                                      (leaf (token "*v" 'SpineJoin 18 2)))
                                                (list (leaf (token "4c" 'SpineData 7 3))
                                                      (leaf (token "4c" 'SpineData 8 3))
                                                      (leaf (token "4c" 'SpineData 9 3))
                                                      (leaf (token "=2" 'Measure 10 3))
                                                      (leaf (token "4c" 'SpineData 11 3))
                                                      (leaf (token "4c" 'SpineData 12 3))
                                                      (leaf (token "4c" 'SpineData 13 3))
                                                      (leaf (token "=3" 'Measure 14 3))
                                                      (leaf (token "4c" 'SpineData 15 3))
                                                      (leaf (token "4c" 'SpineData 16 3))
                                                      (leaf (token "4c" 'SpineData 17 3))
                                                      (leaf (token "*v" 'SpineJoin 18 3))))
                                        (leaf (token "*" 'NullInterpretation 19 2))
                                        (leaf (token "==" 'Measure 20 1))
                                        (leaf (token "*-" 'SpineTerminator 21 1)))))))
|#
(check-expect (gspines->linked-spines (spine-parser (path->hfile "../../data/count/two-spines-one-split.krn"))
                                      (path->hfile "../../data/count/two-spines-one-split.krn"))
              (list (linked-spine KERN-0-0) (linked-spine KERN-0-1)))

(test)
