#lang racket/base

(require "../../../../parser/data-definitions/data-definitions.rkt"
         "../../../../parser/functions/file.rkt"
         "../../../../parser/functions/spine-parser.rkt"
         "../../../../parser/data-structures/humdrum-graph/data-definitions/data-definitions.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hgraph-to-hfile.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hfile-to-hgraph.rkt"
         "../../../../parser/data-structures/linked-spine/data-definitions/data-definitions.rkt"
         "../../../../parser/data-structures/linked-spine/functions/gspines-to-linked-spines.rkt"
         test-engine/racket-tests)

;; Node definitions
(define TERM-25-0 (terminator-node (token "*-" 'SpineTerminator 25 0)))
(define M-24-0 (token-node (token "==" 'Measure 24 0) (box-immutable TERM-25-0)))
(define J-23-0 (token-node (token "*v" 'SpineJoin 23 0) (box-immutable M-24-0)))
(define J-23-1 (token-node (token "*v" 'SpineJoin 23 1) (box-immutable M-24-0)))
(define NULL-22-0 (token-node (token "*" 'NullInterpretation 22 0) (box-immutable J-23-0)))
(define J-22-1 (token-node (token "*v" 'SpineJoin 22 1) (box-immutable J-23-1)))
(define J-22-2 (token-node (token "*v" 'SpineJoin 22 2) (box-immutable J-23-1)))
(define NULL-21-0 (token-node (token "*" 'NullInterpretation 21 0) (box-immutable NULL-22-0)))
(define NULL-21-1 (token-node (token "*" 'NullInterpretation 21 1) (box-immutable J-22-1)))
(define NULL-21-2 (token-node (token "*" 'NullInterpretation 21 2) (box-immutable J-22-2)))
(define NULL-20-0 (token-node (token "*" 'NullInterpretation 20 0) (box-immutable NULL-21-0)))
(define NULL-20-1 (token-node (token "*" 'NullInterpretation 20 1) (box-immutable NULL-21-1)))
(define NULL-20-2 (token-node (token "*" 'NullInterpretation 20 2) (box-immutable NULL-21-2)))
(define 4c-19-0 (token-node (token "4c" 'SpineData 19 0) (box-immutable NULL-20-0)))
(define 4c-19-1 (token-node (token "4c" 'SpineData 19 1) (box-immutable NULL-20-1)))
(define 4c-19-2 (token-node (token "4c" 'SpineData 19 2) (box-immutable NULL-20-2)))
(define 4c-18-0 (token-node (token "4c" 'SpineData 18 0) (box-immutable 4c-19-0)))
(define 4c-18-1 (token-node (token "4c" 'SpineData 18 1) (box-immutable 4c-19-1)))
(define 4c-18-2 (token-node (token "4c" 'SpineData 18 2) (box-immutable 4c-19-2)))
(define 4c-17-0 (token-node (token "4c" 'SpineData 17 0) (box-immutable 4c-18-0)))
(define 4c-17-1 (token-node (token "4c" 'SpineData 17 1) (box-immutable 4c-18-1)))
(define 4c-17-2 (token-node (token "4c" 'SpineData 17 2) (box-immutable 4c-18-2)))
(define M-16-0 (token-node (token "=3" 'Measure 16 0) (box-immutable 4c-17-0)))
(define M-16-1 (token-node (token "=3" 'Measure 16 1) (box-immutable 4c-17-1)))
(define M-16-2 (token-node (token "=3" 'Measure 16 2) (box-immutable 4c-17-2)))
(define 4c-15-0 (token-node (token "4c" 'SpineData 15 0) (box-immutable M-16-0)))
(define 4c-15-1 (token-node (token "4c" 'SpineData 15 1) (box-immutable M-16-1)))
(define 4c-15-2 (token-node (token "4c" 'SpineData 15 2) (box-immutable M-16-2)))
(define 4c-14-0 (token-node (token "4c" 'SpineData 14 0) (box-immutable 4c-15-0)))
(define 4c-14-1 (token-node (token "4c" 'SpineData 14 1) (box-immutable 4c-15-1)))
(define 4c-14-2 (token-node (token "4c" 'SpineData 14 2) (box-immutable 4c-15-2)))
(define 4c-13-0 (token-node (token "4c" 'SpineData 13 0) (box-immutable 4c-14-0)))
(define 4c-13-1 (token-node (token "4c" 'SpineData 13 1) (box-immutable 4c-14-1)))
(define 4c-13-2 (token-node (token "4c" 'SpineData 13 2) (box-immutable 4c-14-2)))
(define M-12-0 (token-node (token "=2" 'Measure 12 0) (box-immutable 4c-13-0)))
(define M-12-1 (token-node (token "=2" 'Measure 12 1) (box-immutable 4c-13-1)))
(define M-12-2 (token-node (token "=2" 'Measure 12 2) (box-immutable 4c-13-2)))
(define 4c-11-0 (token-node (token "4c" 'SpineData 11 0) (box-immutable M-12-0)))
(define 4c-11-1 (token-node (token "4c" 'SpineData 11 1) (box-immutable M-12-1)))
(define 4c-11-2 (token-node (token "4c" 'SpineData 11 2) (box-immutable M-12-2)))
(define 4c-10-0 (token-node (token "4c" 'SpineData 10 0) (box-immutable 4c-11-0)))
(define 4c-10-1 (token-node (token "4c" 'SpineData 10 1) (box-immutable 4c-11-1)))
(define 4c-10-2 (token-node (token "4c" 'SpineData 10 2) (box-immutable 4c-11-2)))
(define 4c-9-0 (token-node (token "4c" 'SpineData 9 0) (box-immutable 4c-10-0)))
(define 4c-9-1 (token-node (token "4c" 'SpineData 9 1) (box-immutable 4c-10-1)))
(define 4c-9-2 (token-node (token "4c" 'SpineData 9 2) (box-immutable 4c-10-2)))
(define NULL-8-0 (token-node (token "*" 'NullInterpretation 8 0) (box-immutable 4c-9-0)))
(define NULL-8-1 (token-node (token "*" 'NullInterpretation 8 1) (box-immutable 4c-9-1)))
(define NULL-8-2 (token-node (token "*" 'NullInterpretation 8 2) (box-immutable 4c-9-2)))
(define NULL-7-0 (token-node (token "*" 'NullInterpretation 7 0) (box-immutable NULL-8-0)))
(define S-7-1 (split-node (token "*^" 'SpineSplit 7 1)
                          (box-immutable NULL-8-1)
                          (box-immutable NULL-8-2)))
(define NULL-6-0 (token-node (token "*" 'NullInterpretation 6 0) (box-immutable NULL-7-0)))
(define NULL-6-1 (token-node (token "*" 'NullInterpretation 6 1) (box-immutable S-7-1)))
(define S-5-0 (split-node (token "*^" 'SpineSplit 5 0)
                          (box-immutable NULL-6-0)
                          (box-immutable NULL-6-1)))
(define TS-4-0 (token-node (token "*M3/4" 'TimeSignature 4 0) (box-immutable S-5-0)))
(define KL-3-0 (token-node (token "*a:" 'KeyLabel 3 0) (box-immutable TS-4-0)))
(define KS-2-0 (token-node (token "*k[]" 'KeySignature 2 0) (box-immutable KL-3-0)))
(define CL-1-0 (token-node (token "*clefG2" 'Clef 1 0) (box-immutable KS-2-0)))
(define KERN-0-0 (token-node (token "**kern" 'ExclusiveInterpretation 0 0) (box-immutable CL-1-0)))

(define TERM-25-1 (terminator-node (token "*-" 'SpineTerminator 25 1)))
(define M-24-1 (token-node (token "==" 'Measure 24 1) (box-immutable TERM-25-1)))
(define NULL-23-2 (token-node (token "*" 'NullInterpretation 23 2) (box-immutable M-24-1)))
(define NULL-22-3 (token-node (token "*" 'NullInterpretation 22 3) (box-immutable NULL-23-2)))
(define J-21-3 (token-node (token "*v" 'SpineJoin 21 3) (box-immutable NULL-22-3)))
(define J-21-4 (token-node (token "*v" 'SpineJoin 21 4) (box-immutable NULL-22-3)))
(define NULL-20-3 (token-node (token "*" 'NullInterpretation 20 3) (box-immutable J-21-3)))
(define J-20-4 (token-node (token "*v" 'SpineJoin 20 4) (box-immutable J-21-4)))
(define J-20-5 (token-node (token "*v" 'SpineJoin 20 5) (box-immutable J-21-4)))
(define 4c-19-3 (token-node (token "4c" 'SpineData 19 3) (box-immutable NULL-20-3)))
(define 4c-19-4 (token-node (token "4c" 'SpineData 19 4) (box-immutable J-20-4)))
(define 4c-19-5 (token-node (token "4c" 'SpineData 19 5) (box-immutable J-20-5)))
(define 4c-18-3 (token-node (token "4c" 'SpineData 18 3) (box-immutable 4c-19-3)))
(define 4c-18-4 (token-node (token "4c" 'SpineData 18 4) (box-immutable 4c-19-4)))
(define 4c-18-5 (token-node (token "4c" 'SpineData 18 5) (box-immutable 4c-19-5)))
(define 4c-17-3 (token-node (token "4c" 'SpineData 17 3) (box-immutable 4c-18-3)))
(define 4c-17-4 (token-node (token "4c" 'SpineData 17 4) (box-immutable 4c-18-4)))
(define 4c-17-5 (token-node (token "4c" 'SpineData 17 5) (box-immutable 4c-18-5)))
(define M-16-3 (token-node (token "=3" 'Measure 16 3) (box-immutable 4c-17-3)))
(define M-16-4 (token-node (token "=3" 'Measure 16 4) (box-immutable 4c-17-4)))
(define M-16-5 (token-node (token "=3" 'Measure 16 5) (box-immutable 4c-17-5)))
(define 4c-15-3 (token-node (token "4c" 'SpineData 15 3) (box-immutable M-16-3)))
(define 4c-15-4 (token-node (token "4c" 'SpineData 15 4) (box-immutable M-16-4)))
(define 4c-15-5 (token-node (token "4c" 'SpineData 15 5) (box-immutable M-16-5)))
(define 4c-14-3 (token-node (token "4c" 'SpineData 14 3) (box-immutable 4c-15-3)))
(define 4c-14-4 (token-node (token "4c" 'SpineData 14 4) (box-immutable 4c-15-4)))
(define 4c-14-5 (token-node (token "4c" 'SpineData 14 5) (box-immutable 4c-15-5)))
(define 4c-13-3 (token-node (token "4c" 'SpineData 13 3) (box-immutable 4c-14-3)))
(define 4c-13-4 (token-node (token "4c" 'SpineData 13 4) (box-immutable 4c-14-4)))
(define 4c-13-5 (token-node (token "4c" 'SpineData 13 5) (box-immutable 4c-14-5)))
(define M-12-3 (token-node (token "=2" 'Measure 12 3) (box-immutable 4c-13-3)))
(define M-12-4 (token-node (token "=2" 'Measure 12 4) (box-immutable 4c-13-4)))
(define M-12-5 (token-node (token "=2" 'Measure 12 5) (box-immutable 4c-13-5)))
(define 4c-11-3 (token-node (token "4c" 'SpineData 11 3) (box-immutable M-12-3)))
(define 4c-11-4 (token-node (token "4c" 'SpineData 11 4) (box-immutable M-12-4)))
(define 4c-11-5 (token-node (token "4c" 'SpineData 11 5) (box-immutable M-12-5)))
(define 4c-10-3 (token-node (token "4c" 'SpineData 10 3) (box-immutable 4c-11-3)))
(define 4c-10-4 (token-node (token "4c" 'SpineData 10 4) (box-immutable 4c-11-4)))
(define 4c-10-5 (token-node (token "4c" 'SpineData 10 5) (box-immutable 4c-11-5)))
(define 4c-9-3 (token-node (token "4c" 'SpineData 9 3) (box-immutable 4c-10-3)))
(define 4c-9-4 (token-node (token "4c" 'SpineData 9 4) (box-immutable 4c-10-4)))
(define 4c-9-5 (token-node (token "4c" 'SpineData 9 5) (box-immutable 4c-10-5)))
(define NULL-8-3 (token-node (token "*" 'NullInterpretation 8 3) (box-immutable 4c-9-3)))
(define S-8-4 (split-node (token "*^" 'SpineSplit 8 4)
                          (box-immutable 4c-9-4)
                          (box-immutable 4c-9-5)))
(define NULL-7-2 (token-node (token "*" 'NullInterpretation 7 2) (box-immutable NULL-8-3)))
(define NULL-7-3 (token-node (token "*" 'NullInterpretation 7 3) (box-immutable S-8-4)))
(define S-6-2 (split-node (token "*^" 'SpineSplit 6 2)
                          (box-immutable NULL-7-2)
                          (box-immutable NULL-7-3)))
(define NULL-5-1 (token-node (token "*" 'NullInterpretation 5 1) (box-immutable S-6-2)))
(define TS-4-1 (token-node (token "*M3/4" 'TimeSignature 4 1) (box-immutable NULL-5-1)))
(define KL-3-1 (token-node (token "*a:" 'KeyLabel 3 1) (box-immutable TS-4-1)))
(define KS-2-1 (token-node (token "*k[]" 'KeySignature 2 1) (box-immutable KL-3-1)))
(define CL-1-1 (token-node (token "*clefG2" 'Clef 1 1) (box-immutable KS-2-1)))
(define KERN-0-1 (token-node (token "**kern" 'ExclusiveInterpretation 0 1) (box-immutable CL-1-1)))

(check-expect (path->hfile "../../data/count/two-spines-two-splits.krn")
              (hfile (list (record "**kern\t**kern" TOKEN
                                   (list (token "**kern" 'ExclusiveInterpretation 0 0)
                                         (token "**kern" 'ExclusiveInterpretation 0 1))
                                   0)
                           (record "*clefG2\t*clefG2" TOKEN (list (token "*clefG2" 'Clef 1 0)
                                                                  (token "*clefG2" 'Clef 1 1))
                                   1)
                           (record "*k[]\t*k[]" TOKEN (list (token "*k[]" 'KeySignature 2 0)
                                                            (token "*k[]" 'KeySignature 2 1))
                                   2)
                           (record "*a:\t*a:" TOKEN (list (token "*a:" 'KeyLabel 3 0)
                                                          (token "*a:" 'KeyLabel 3 1))
                                   3)
                           (record "*M3/4\t*M3/4" TOKEN (list (token "*M3/4" 'TimeSignature 4 0)
                                                              (token "*M3/4" 'TimeSignature 4 1))
                                   4)
                           (record "*^\t*" TOKEN (list (token "*^" 'SpineSplit 5 0)
                                                       (token "*" 'NullInterpretation 5 1))
                                   5)
                           (record "*\t*\t*^" TOKEN (list (token "*" 'NullInterpretation 6 0)
                                                          (token "*" 'NullInterpretation 6 1)
                                                          (token "*^" 'SpineSplit 6 2))
                                   6)
                           (record "*\t*^\t*\t*" TOKEN (list (token "*" 'NullInterpretation 7 0)
                                                             (token "*^" 'SpineSplit 7 1)
                                                             (token "*" 'NullInterpretation 7 2)
                                                             (token "*" 'NullInterpretation 7 3))
                                   7)
                           (record "*\t*\t*\t*\t*^" TOKEN (list (token "*" 'NullInterpretation 8 0)
                                                                (token "*" 'NullInterpretation 8 1)
                                                                (token "*" 'NullInterpretation 8 2)
                                                                (token "*" 'NullInterpretation 8 3)
                                                                (token "*^" 'SpineSplit 8 4))
                                   8)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 9 0)
                                                                        (token "4c" 'SpineData 9 1)
                                                                        (token "4c" 'SpineData 9 2)
                                                                        (token "4c" 'SpineData 9 3)
                                                                        (token "4c" 'SpineData 9 4)
                                                                        (token "4c" 'SpineData 9 5))
                                   9)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 10 0)
                                                                        (token "4c" 'SpineData 10 1)
                                                                        (token "4c" 'SpineData 10 2)
                                                                        (token "4c" 'SpineData 10 3)
                                                                        (token "4c" 'SpineData 10 4)
                                                                        (token "4c" 'SpineData 10 5))
                                   10)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 11 0)
                                                                        (token "4c" 'SpineData 11 1)
                                                                        (token "4c" 'SpineData 11 2)
                                                                        (token "4c" 'SpineData 11 3)
                                                                        (token "4c" 'SpineData 11 4)
                                                                        (token "4c" 'SpineData 11 5))
                                   11)
                           (record "=2\t=2\t=2\t=2\t=2\t=2" TOKEN (list (token "=2" 'Measure 12 0)
                                                                        (token "=2" 'Measure 12 1)
                                                                        (token "=2" 'Measure 12 2)
                                                                        (token "=2" 'Measure 12 3)
                                                                        (token "=2" 'Measure 12 4)
                                                                        (token "=2" 'Measure 12 5))
                                   12)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 13 0)
                                                                        (token "4c" 'SpineData 13 1)
                                                                        (token "4c" 'SpineData 13 2)
                                                                        (token "4c" 'SpineData 13 3)
                                                                        (token "4c" 'SpineData 13 4)
                                                                        (token "4c" 'SpineData 13 5))
                                   13)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 14 0)
                                                                        (token "4c" 'SpineData 14 1)
                                                                        (token "4c" 'SpineData 14 2)
                                                                        (token "4c" 'SpineData 14 3)
                                                                        (token "4c" 'SpineData 14 4)
                                                                        (token "4c" 'SpineData 14 5))
                                   14)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 15 0)
                                                                        (token "4c" 'SpineData 15 1)
                                                                        (token "4c" 'SpineData 15 2)
                                                                        (token "4c" 'SpineData 15 3)
                                                                        (token "4c" 'SpineData 15 4)
                                                                        (token "4c" 'SpineData 15 5))
                                   15)
                           (record "=3\t=3\t=3\t=3\t=3\t=3" TOKEN (list (token "=3" 'Measure 16 0)
                                                                        (token "=3" 'Measure 16 1)
                                                                        (token "=3" 'Measure 16 2)
                                                                        (token "=3" 'Measure 16 3)
                                                                        (token "=3" 'Measure 16 4)
                                                                        (token "=3" 'Measure 16 5))
                                   16)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 17 0)
                                                                        (token "4c" 'SpineData 17 1)
                                                                        (token "4c" 'SpineData 17 2)
                                                                        (token "4c" 'SpineData 17 3)
                                                                        (token "4c" 'SpineData 17 4)
                                                                        (token "4c" 'SpineData 17 5))
                                   17)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 18 0)
                                                                        (token "4c" 'SpineData 18 1)
                                                                        (token "4c" 'SpineData 18 2)
                                                                        (token "4c" 'SpineData 18 3)
                                                                        (token "4c" 'SpineData 18 4)
                                                                        (token "4c" 'SpineData 18 5))
                                   18)
                           (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 19 0)
                                                                        (token "4c" 'SpineData 19 1)
                                                                        (token "4c" 'SpineData 19 2)
                                                                        (token "4c" 'SpineData 19 3)
                                                                        (token "4c" 'SpineData 19 4)
                                                                        (token "4c" 'SpineData 19 5))
                                   19)
                           (record "*\t*\t*\t*\t*v\t*v" TOKEN (list (token "*" 'NullInterpretation 20 0)
                                                                    (token "*" 'NullInterpretation 20 1)
                                                                    (token "*" 'NullInterpretation 20 2)
                                                                    (token "*" 'NullInterpretation 20 3)
                                                                    (token "*v" 'SpineJoin 20 4)
                                                                    (token "*v" 'SpineJoin 20 5))
                                   20)
                           (record "*\t*\t*\t*v\t*v" TOKEN (list (token "*" 'NullInterpretation 21 0)
                                                                 (token "*" 'NullInterpretation 21 1)
                                                                 (token "*" 'NullInterpretation 21 2)
                                                                 (token "*v" 'SpineJoin 21 3)
                                                                 (token "*v" 'SpineJoin 21 4))
                                   21)
                           (record "*\t*v\t*v\t*" TOKEN (list (token "*" 'NullInterpretation 22 0)
                                                              (token "*v" 'SpineJoin 22 1)
                                                              (token "*v" 'SpineJoin 22 2)
                                                              (token "*" 'NullInterpretation 22 3))
                                   22)
                           (record "*v\t*v\t*" TOKEN (list (token "*v" 'SpineJoin 23 0)
                                                           (token "*v" 'SpineJoin 23 1)
                                                           (token "*" 'NullInterpretation 23 2))
                                   23)
                           (record "==\t==" TOKEN (list (token "==" 'Measure 24 0)
                                                        (token "==" 'Measure 24 1))
                                   24)
                           (record "*-\t*-" TOKEN (list (token "*-" 'SpineTerminator 25 0)
                                                        (token "*-" 'SpineTerminator 25 1))
                                   25))))
(check-expect (spine-parser (path->hfile "../../data/count/two-spines-two-splits.krn"))
              (list (global-spine KERN
                                  (list (list (token "**kern" 'ExclusiveInterpretation 0 0))
                                        (list (token "*clefG2" 'Clef 1 0))
                                        (list (token "*k[]" 'KeySignature 2 0))
                                        (list (token "*a:" 'KeyLabel 3 0))
                                        (list (token "*M3/4" 'TimeSignature 4 0))
                                        (list (token "*^" 'SpineSplit 5 0))
                                        (list (token "*" 'NullInterpretation 6 0)
                                              (token "*" 'NullInterpretation 6 1))
                                        (list (token "*" 'NullInterpretation 7 0)
                                              (token "*^" 'SpineSplit 7 1))
                                        (list (token "*" 'NullInterpretation 8 0)
                                              (token "*" 'NullInterpretation 8 1)
                                              (token "*" 'NullInterpretation 8 2))
                                        (list (token "4c" 'SpineData 9 0)
                                              (token "4c" 'SpineData 9 1)
                                              (token "4c" 'SpineData 9 2))
                                        (list (token "4c" 'SpineData 10 0)
                                              (token "4c" 'SpineData 10 1)
                                              (token "4c" 'SpineData 10 2))
                                        (list (token "4c" 'SpineData 11 0)
                                              (token "4c" 'SpineData 11 1)
                                              (token "4c" 'SpineData 11 2))
                                        (list (token "=2" 'Measure 12 0)
                                              (token "=2" 'Measure 12 1)
                                              (token "=2" 'Measure 12 2))
                                        (list (token "4c" 'SpineData 13 0)
                                              (token "4c" 'SpineData 13 1)
                                              (token "4c" 'SpineData 13 2))
                                        (list (token "4c" 'SpineData 14 0)
                                              (token "4c" 'SpineData 14 1)
                                              (token "4c" 'SpineData 14 2))
                                        (list (token "4c" 'SpineData 15 0)
                                              (token "4c" 'SpineData 15 1)
                                              (token "4c" 'SpineData 15 2))
                                        (list (token "=3" 'Measure 16 0)
                                              (token "=3" 'Measure 16 1)
                                              (token "=3" 'Measure 16 2))
                                        (list (token "4c" 'SpineData 17 0)
                                              (token "4c" 'SpineData 17 1)
                                              (token "4c" 'SpineData 17 2))
                                        (list (token "4c" 'SpineData 18 0)
                                              (token "4c" 'SpineData 18 1)
                                              (token "4c" 'SpineData 18 2))
                                        (list (token "4c" 'SpineData 19 0)
                                              (token "4c" 'SpineData 19 1)
                                              (token "4c" 'SpineData 19 2))
                                        (list (token "*" 'NullInterpretation 20 0)
                                              (token "*" 'NullInterpretation 20 1)
                                              (token "*" 'NullInterpretation 20 2))
                                        (list (token "*" 'NullInterpretation 21 0)
                                              (token "*" 'NullInterpretation 21 1)
                                              (token "*" 'NullInterpretation 21 2))
                                        (list (token "*" 'NullInterpretation 22 0)
                                              (token "*v" 'SpineJoin 22 1)
                                              (token "*v" 'SpineJoin 22 2))
                                        (list (token "*v" 'SpineJoin 23 0)
                                              (token "*v" 'SpineJoin 23 1))
                                        (list (token "==" 'Measure 24 0))
                                        (list (token "*-" 'SpineTerminator 25 0)))
                                  0)
                    (global-spine KERN
                                  (list (list (token "**kern" 'ExclusiveInterpretation 0 1))
                                        (list (token "*clefG2" 'Clef 1 1))
                                        (list (token "*k[]" 'KeySignature 2 1))
                                        (list (token "*a:" 'KeyLabel 3 1))
                                        (list (token "*M3/4" 'TimeSignature 4 1))
                                        (list (token "*" 'NullInterpretation 5 1))
                                        (list (token "*^" 'SpineSplit 6 2))
                                        (list (token "*" 'NullInterpretation 7 2)
                                              (token "*" 'NullInterpretation 7 3))
                                        (list (token "*" 'NullInterpretation 8 3)
                                              (token "*^" 'SpineSplit 8 4))
                                        (list (token "4c" 'SpineData 9 3)
                                              (token "4c" 'SpineData 9 4)
                                              (token "4c" 'SpineData 9 5))
                                        (list (token "4c" 'SpineData 10 3)
                                              (token "4c" 'SpineData 10 4)
                                              (token "4c" 'SpineData 10 5))
                                        (list (token "4c" 'SpineData 11 3)
                                              (token "4c" 'SpineData 11 4)
                                              (token "4c" 'SpineData 11 5))
                                        (list (token "=2" 'Measure 12 3)
                                              (token "=2" 'Measure 12 4)
                                              (token "=2" 'Measure 12 5))
                                        (list (token "4c" 'SpineData 13 3)
                                              (token "4c" 'SpineData 13 4)
                                              (token "4c" 'SpineData 13 5))
                                        (list (token "4c" 'SpineData 14 3)
                                              (token "4c" 'SpineData 14 4)
                                              (token "4c" 'SpineData 14 5))
                                        (list (token "4c" 'SpineData 15 3)
                                              (token "4c" 'SpineData 15 4)
                                              (token "4c" 'SpineData 15 5))
                                        (list (token "=3" 'Measure 16 3)
                                              (token "=3" 'Measure 16 4)
                                              (token "=3" 'Measure 16 5))
                                        (list (token "4c" 'SpineData 17 3)
                                              (token "4c" 'SpineData 17 4)
                                              (token "4c" 'SpineData 17 5))
                                        (list (token "4c" 'SpineData 18 3)
                                              (token "4c" 'SpineData 18 4)
                                              (token "4c" 'SpineData 18 5))
                                        (list (token "4c" 'SpineData 19 3)
                                              (token "4c" 'SpineData 19 4)
                                              (token "4c" 'SpineData 19 5))
                                        (list (token "*" 'NullInterpretation 20 3)
                                              (token "*v" 'SpineJoin 20 4)
                                              (token "*v" 'SpineJoin 20 5))
                                        (list (token "*v" 'SpineJoin 21 3)
                                              (token "*v" 'SpineJoin 21 4))
                                        (list (token "*" 'NullInterpretation 22 3))
                                        (list (token "*" 'NullInterpretation 23 2))
                                        (list (token "==" 'Measure 24 1))
                                        (list (token "*-" 'SpineTerminator 25 1)))
                                  1)))
(check-expect (hgraph->hfile
               (hgraph (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                         (leaf (token "*clefG2" 'Clef 1 0))
                                         (leaf (token "*k[]" 'KeySignature 2 0))
                                         (leaf (token "*a:" 'KeyLabel 3 0))
                                         (leaf (token "*M3/4" 'TimeSignature 4 0))
                                         (parent (token "*^" 'SpineSplit 5 0)
                                                 (list (leaf (token "*" 'NullInterpretation 6 0))
                                                       (leaf (token "*" 'NullInterpretation 7 0))
                                                       (leaf (token "*" 'NullInterpretation 8 0))
                                                       (leaf (token "4c" 'SpineData 9 0))
                                                       (leaf (token "4c" 'SpineData 10 0))
                                                       (leaf (token "4c" 'SpineData 11 0))
                                                       (leaf (token "=2" 'Measure 12 0))
                                                       (leaf (token "4c" 'SpineData 13 0))
                                                       (leaf (token "4c" 'SpineData 14 0))
                                                       (leaf (token "4c" 'SpineData 15 0))
                                                       (leaf (token "=3" 'Measure 16 0))
                                                       (leaf (token "4c" 'SpineData 17 0))
                                                       (leaf (token "4c" 'SpineData 18 0))
                                                       (leaf (token "4c" 'SpineData 19 0))
                                                       (leaf (token "*" 'NullInterpretation 20 0))
                                                       (leaf (token "*" 'NullInterpretation 21 0))
                                                       (leaf (token "*" 'NullInterpretation 22 0))
                                                       (leaf (token "*v" 'SpineJoin 23 0)))
                                                 (list (leaf (token "*" 'NullInterpretation 6 1))
                                                       (parent (token "*^" 'SpineSplit 7 1)
                                                               (list (leaf (token "*" 'NullInterpretation 8 1))
                                                                     (leaf (token "4c" 'SpineData 9 1))
                                                                     (leaf (token "4c" 'SpineData 10 1))
                                                                     (leaf (token "4c" 'SpineData 11 1))
                                                                     (leaf (token "=2" 'Measure 12 1))
                                                                     (leaf (token "4c" 'SpineData 13 1))
                                                                     (leaf (token "4c" 'SpineData 14 1))
                                                                     (leaf (token "4c" 'SpineData 15 1))
                                                                     (leaf (token "=3" 'Measure 16 1))
                                                                     (leaf (token "4c" 'SpineData 17 1))
                                                                     (leaf (token "4c" 'SpineData 18 1))
                                                                     (leaf (token "4c" 'SpineData 19 1))
                                                                     (leaf (token "*" 'NullInterpretation 20 1))
                                                                     (leaf (token "*" 'NullInterpretation 21 1))
                                                                     (leaf (token "*v" 'SpineJoin 22 1)))
                                                               (list (leaf (token "*" 'NullInterpretation 8 2))
                                                                     (leaf (token "4c" 'SpineData 9 2))
                                                                     (leaf (token "4c" 'SpineData 10 2))
                                                                     (leaf (token "4c" 'SpineData 11 2))
                                                                     (leaf (token "=2" 'Measure 12 2))
                                                                     (leaf (token "4c" 'SpineData 13 2))
                                                                     (leaf (token "4c" 'SpineData 14 2))
                                                                     (leaf (token "4c" 'SpineData 15 2))
                                                                     (leaf (token "=3" 'Measure 16 2))
                                                                     (leaf (token "4c" 'SpineData 17 2))
                                                                     (leaf (token "4c" 'SpineData 18 2))
                                                                     (leaf (token "4c" 'SpineData 19 2))
                                                                     (leaf (token "*" 'NullInterpretation 20 2))
                                                                     (leaf (token "*" 'NullInterpretation 21 2))
                                                                     (leaf (token "*v" 'SpineJoin 22 2))))
                                                       (leaf (token "*v" 'SpineJoin 23 1))))
                                         (leaf (token "==" 'Measure 24 0))
                                         (leaf (token "*-" 'SpineTerminator 25 0)))
                                   (list (leaf (token "**kern" 'ExclusiveInterpretation 0 1))
                                         (leaf (token "*clefG2" 'Clef 1 1))
                                         (leaf (token "*k[]" 'KeySignature 2 1))
                                         (leaf (token "*a:" 'KeyLabel 3 1))
                                         (leaf (token "*M3/4" 'TimeSignature 4 1))
                                         (leaf (token "*" 'NullInterpretation 5 1))
                                         (parent (token "*^" 'SpineSplit 6 2)
                                                 (list (leaf (token "*" 'NullInterpretation 7 2))
                                                       (leaf (token "*" 'NullInterpretation 8 3))
                                                       (leaf (token "4c" 'SpineData 9 3))
                                                       (leaf (token "4c" 'SpineData 10 3))
                                                       (leaf (token "4c" 'SpineData 11 3))
                                                       (leaf (token "=2" 'Measure 12 3))
                                                       (leaf (token "4c" 'SpineData 13 3))
                                                       (leaf (token "4c" 'SpineData 14 3))
                                                       (leaf (token "4c" 'SpineData 15 3))
                                                       (leaf (token "=3" 'Measure 16 3))
                                                       (leaf (token "4c" 'SpineData 17 3))
                                                       (leaf (token "4c" 'SpineData 18 3))
                                                       (leaf (token "4c" 'SpineData 19 3))
                                                       (leaf (token "*" 'NullInterpretation 20 3))
                                                       (leaf (token "*v" 'SpineJoin 21 3)))
                                                 (list (leaf (token "*" 'NullInterpretation 7 3))
                                                       (parent (token "*^" 'SpineSplit 8 4)
                                                               (list (leaf (token "4c" 'SpineData 9 4))
                                                                     (leaf (token "4c" 'SpineData 10 4))
                                                                     (leaf (token "4c" 'SpineData 11 4))
                                                                     (leaf (token "=2" 'Measure 12 4))
                                                                     (leaf (token "4c" 'SpineData 13 4))
                                                                     (leaf (token "4c" 'SpineData 14 4))
                                                                     (leaf (token "4c" 'SpineData 15 4))
                                                                     (leaf (token "=3" 'Measure 16 4))
                                                                     (leaf (token "4c" 'SpineData 17 4))
                                                                     (leaf (token "4c" 'SpineData 18 4))
                                                                     (leaf (token "4c" 'SpineData 19 4))
                                                                     (leaf (token "*v" 'SpineJoin 20 4)))
                                                               (list (leaf (token "4c" 'SpineData 9 5))
                                                                     (leaf (token "4c" 'SpineData 10 5))
                                                                     (leaf (token "4c" 'SpineData 11 5))
                                                                     (leaf (token "=2" 'Measure 12 5))
                                                                     (leaf (token "4c" 'SpineData 13 5))
                                                                     (leaf (token "4c" 'SpineData 14 5))
                                                                     (leaf (token "4c" 'SpineData 15 5))
                                                                     (leaf (token "=3" 'Measure 16 5))
                                                                     (leaf (token "4c" 'SpineData 17 5))
                                                                     (leaf (token "4c" 'SpineData 18 5))
                                                                     (leaf (token "4c" 'SpineData 19 5))
                                                                     (leaf (token "*v" 'SpineJoin 20 5))))
                                                       (leaf (token "*v" 'SpineJoin 21 4))))
                                         (leaf (token "*" 'NullInterpretation 22 3))
                                         (leaf (token "*" 'NullInterpretation 23 2))
                                         (leaf (token "==" 'Measure 24 1))
                                         (leaf (token "*-" 'SpineTerminator 25 1)))))))
              (path->hfile "../../data/count/two-spines-two-splits.krn"))
(check-expect (tokens->records (list (list (token "**kern" 'ExclusiveInterpretation 0 0)
                                      (token "**kern" 'ExclusiveInterpretation 0 1))
                                (list (token "*clefG2" 'Clef 1 0)
                                      (token "*clefG2" 'Clef 1 1))
                                (list (token "*k[]" 'KeySignature 2 0)
                                      (token "*k[]" 'KeySignature 2 1))
                                (list (token "*a:" 'KeyLabel 3 0)
                                      (token "*a:" 'KeyLabel 3 1))
                                (list (token "*M3/4" 'TimeSignature 4 0)
                                      (token "*M3/4" 'TimeSignature 4 1))
                                (list (token "*^" 'SpineSplit 5 0)
                                      (token "*" 'NullInterpretation 5 1))
                                (list (token "*" 'NullInterpretation 6 0)
                                      (token "*" 'NullInterpretation 6 1)
                                      (token "*^" 'SpineSplit 6 2))
                                (list (token "*" 'NullInterpretation 7 0)
                                      (token "*^" 'SpineSplit 7 1)
                                      (token "*" 'NullInterpretation 7 2)
                                      (token "*" 'NullInterpretation 7 3))
                                (list (token "*" 'NullInterpretation 8 0)
                                      (token "*" 'NullInterpretation 8 1)
                                      (token "*" 'NullInterpretation 8 2)
                                      (token "*" 'NullInterpretation 8 3)
                                      (token "*^" 'SpineSplit 8 4))
                                (list (token "4c" 'SpineData 9 0)
                                      (token "4c" 'SpineData 9 1)
                                      (token "4c" 'SpineData 9 2)
                                      (token "4c" 'SpineData 9 3)
                                      (token "4c" 'SpineData 9 4)
                                      (token "4c" 'SpineData 9 5))
                                (list (token "4c" 'SpineData 10 0)
                                      (token "4c" 'SpineData 10 1)
                                      (token "4c" 'SpineData 10 2)
                                      (token "4c" 'SpineData 10 3)
                                      (token "4c" 'SpineData 10 4)
                                      (token "4c" 'SpineData 10 5))
                                (list (token "4c" 'SpineData 11 0)
                                      (token "4c" 'SpineData 11 1)
                                      (token "4c" 'SpineData 11 2)
                                      (token "4c" 'SpineData 11 3)
                                      (token "4c" 'SpineData 11 4)
                                      (token "4c" 'SpineData 11 5))
                                (list (token "=2" 'Measure 12 0)
                                      (token "=2" 'Measure 12 1)
                                      (token "=2" 'Measure 12 2)
                                      (token "=2" 'Measure 12 3)
                                      (token "=2" 'Measure 12 4)
                                      (token "=2" 'Measure 12 5))
                                (list (token "4c" 'SpineData 13 0)
                                      (token "4c" 'SpineData 13 1)
                                      (token "4c" 'SpineData 13 2)
                                      (token "4c" 'SpineData 13 3)
                                      (token "4c" 'SpineData 13 4)
                                      (token "4c" 'SpineData 13 5))
                                (list (token "4c" 'SpineData 14 0)
                                      (token "4c" 'SpineData 14 1)
                                      (token "4c" 'SpineData 14 2)
                                      (token "4c" 'SpineData 14 3)
                                      (token "4c" 'SpineData 14 4)
                                      (token "4c" 'SpineData 14 5))
                                (list (token "4c" 'SpineData 15 0)
                                      (token "4c" 'SpineData 15 1)
                                      (token "4c" 'SpineData 15 2)
                                      (token "4c" 'SpineData 15 3)
                                      (token "4c" 'SpineData 15 4)
                                      (token "4c" 'SpineData 15 5))
                                (list (token "=3" 'Measure 16 0)
                                      (token "=3" 'Measure 16 1)
                                      (token "=3" 'Measure 16 2)
                                      (token "=3" 'Measure 16 3)
                                      (token "=3" 'Measure 16 4)
                                      (token "=3" 'Measure 16 5))
                                (list (token "4c" 'SpineData 17 0)
                                      (token "4c" 'SpineData 17 1)
                                      (token "4c" 'SpineData 17 2)
                                      (token "4c" 'SpineData 17 3)
                                      (token "4c" 'SpineData 17 4)
                                      (token "4c" 'SpineData 17 5))
                                (list (token "4c" 'SpineData 18 0)
                                      (token "4c" 'SpineData 18 1)
                                      (token "4c" 'SpineData 18 2)
                                      (token "4c" 'SpineData 18 3)
                                      (token "4c" 'SpineData 18 4)
                                      (token "4c" 'SpineData 18 5))
                                (list (token "4c" 'SpineData 19 0)
                                      (token "4c" 'SpineData 19 1)
                                      (token "4c" 'SpineData 19 2)
                                      (token "4c" 'SpineData 19 3)
                                      (token "4c" 'SpineData 19 4)
                                      (token "4c" 'SpineData 19 5))
                                (list (token "*" 'NullInterpretation 20 0)
                                      (token "*" 'NullInterpretation 20 1)
                                      (token "*" 'NullInterpretation 20 2)
                                      (token "*" 'NullInterpretation 20 3)
                                      (token "*v" 'SpineJoin 20 4)
                                      (token "*v" 'SpineJoin 20 5))
                                (list (token "*" 'NullInterpretation 21 0)
                                      (token "*" 'NullInterpretation 21 1)
                                      (token "*" 'NullInterpretation 21 2)
                                      (token "*v" 'SpineJoin 21 3)
                                      (token "*v" 'SpineJoin 21 4))
                                (list (token "*" 'NullInterpretation 22 0)
                                      (token "*v" 'SpineJoin 22 1)
                                      (token "*v" 'SpineJoin 22 2)
                                      (token "*" 'NullInterpretation 22 3))
                                (list (token "*v" 'SpineJoin 23 0)
                                      (token "*v" 'SpineJoin 23 1)
                                      (token "*" 'NullInterpretation 23 2))
                                (list (token "==" 'Measure 24 0)
                                      (token "==" 'Measure 24 1))
                                (list (token "*-" 'SpineTerminator 25 0)
                                      (token "*-" 'SpineTerminator 25 1))))
              (list (record "**kern\t**kern" TOKEN
                            (list (token "**kern" 'ExclusiveInterpretation 0 0)
                                  (token "**kern" 'ExclusiveInterpretation 0 1))
                            0)
                    (record "*clefG2\t*clefG2" TOKEN (list (token "*clefG2" 'Clef 1 0)
                                                           (token "*clefG2" 'Clef 1 1))
                            1)
                    (record "*k[]\t*k[]" TOKEN (list (token "*k[]" 'KeySignature 2 0)
                                                     (token "*k[]" 'KeySignature 2 1))
                            2)
                    (record "*a:\t*a:" TOKEN (list (token "*a:" 'KeyLabel 3 0)
                                                   (token "*a:" 'KeyLabel 3 1))
                            3)
                    (record "*M3/4\t*M3/4" TOKEN (list (token "*M3/4" 'TimeSignature 4 0)
                                                       (token "*M3/4" 'TimeSignature 4 1))
                            4)
                    (record "*^\t*" TOKEN (list (token "*^" 'SpineSplit 5 0)
                                                (token "*" 'NullInterpretation 5 1))
                            5)
                    (record "*\t*\t*^" TOKEN (list (token "*" 'NullInterpretation 6 0)
                                                   (token "*" 'NullInterpretation 6 1)
                                                   (token "*^" 'SpineSplit 6 2))
                            6)
                    (record "*\t*^\t*\t*" TOKEN (list (token "*" 'NullInterpretation 7 0)
                                                      (token "*^" 'SpineSplit 7 1)
                                                      (token "*" 'NullInterpretation 7 2)
                                                      (token "*" 'NullInterpretation 7 3))
                            7)
                    (record "*\t*\t*\t*\t*^" TOKEN (list (token "*" 'NullInterpretation 8 0)
                                                         (token "*" 'NullInterpretation 8 1)
                                                         (token "*" 'NullInterpretation 8 2)
                                                         (token "*" 'NullInterpretation 8 3)
                                                         (token "*^" 'SpineSplit 8 4))
                            8)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 9 0)
                                                                 (token "4c" 'SpineData 9 1)
                                                                 (token "4c" 'SpineData 9 2)
                                                                 (token "4c" 'SpineData 9 3)
                                                                 (token "4c" 'SpineData 9 4)
                                                                 (token "4c" 'SpineData 9 5))
                            9)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 10 0)
                                                                 (token "4c" 'SpineData 10 1)
                                                                 (token "4c" 'SpineData 10 2)
                                                                 (token "4c" 'SpineData 10 3)
                                                                 (token "4c" 'SpineData 10 4)
                                                                 (token "4c" 'SpineData 10 5))
                            10)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 11 0)
                                                                 (token "4c" 'SpineData 11 1)
                                                                 (token "4c" 'SpineData 11 2)
                                                                 (token "4c" 'SpineData 11 3)
                                                                 (token "4c" 'SpineData 11 4)
                                                                 (token "4c" 'SpineData 11 5))
                            11)
                    (record "=2\t=2\t=2\t=2\t=2\t=2" TOKEN (list (token "=2" 'Measure 12 0)
                                                                 (token "=2" 'Measure 12 1)
                                                                 (token "=2" 'Measure 12 2)
                                                                 (token "=2" 'Measure 12 3)
                                                                 (token "=2" 'Measure 12 4)
                                                                 (token "=2" 'Measure 12 5))
                            12)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 13 0)
                                                                 (token "4c" 'SpineData 13 1)
                                                                 (token "4c" 'SpineData 13 2)
                                                                 (token "4c" 'SpineData 13 3)
                                                                 (token "4c" 'SpineData 13 4)
                                                                 (token "4c" 'SpineData 13 5))
                            13)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 14 0)
                                                                 (token "4c" 'SpineData 14 1)
                                                                 (token "4c" 'SpineData 14 2)
                                                                 (token "4c" 'SpineData 14 3)
                                                                 (token "4c" 'SpineData 14 4)
                                                                 (token "4c" 'SpineData 14 5))
                            14)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 15 0)
                                                                 (token "4c" 'SpineData 15 1)
                                                                 (token "4c" 'SpineData 15 2)
                                                                 (token "4c" 'SpineData 15 3)
                                                                 (token "4c" 'SpineData 15 4)
                                                                 (token "4c" 'SpineData 15 5))
                            15)
                    (record "=3\t=3\t=3\t=3\t=3\t=3" TOKEN (list (token "=3" 'Measure 16 0)
                                                                 (token "=3" 'Measure 16 1)
                                                                 (token "=3" 'Measure 16 2)
                                                                 (token "=3" 'Measure 16 3)
                                                                 (token "=3" 'Measure 16 4)
                                                                 (token "=3" 'Measure 16 5))
                            16)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 17 0)
                                                                 (token "4c" 'SpineData 17 1)
                                                                 (token "4c" 'SpineData 17 2)
                                                                 (token "4c" 'SpineData 17 3)
                                                                 (token "4c" 'SpineData 17 4)
                                                                 (token "4c" 'SpineData 17 5))
                            17)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 18 0)
                                                                 (token "4c" 'SpineData 18 1)
                                                                 (token "4c" 'SpineData 18 2)
                                                                 (token "4c" 'SpineData 18 3)
                                                                 (token "4c" 'SpineData 18 4)
                                                                 (token "4c" 'SpineData 18 5))
                            18)
                    (record "4c\t4c\t4c\t4c\t4c\t4c" TOKEN (list (token "4c" 'SpineData 19 0)
                                                                 (token "4c" 'SpineData 19 1)
                                                                 (token "4c" 'SpineData 19 2)
                                                                 (token "4c" 'SpineData 19 3)
                                                                 (token "4c" 'SpineData 19 4)
                                                                 (token "4c" 'SpineData 19 5))
                            19)
                    (record "*\t*\t*\t*\t*v\t*v" TOKEN (list (token "*" 'NullInterpretation 20 0)
                                                             (token "*" 'NullInterpretation 20 1)
                                                             (token "*" 'NullInterpretation 20 2)
                                                             (token "*" 'NullInterpretation 20 3)
                                                             (token "*v" 'SpineJoin 20 4)
                                                             (token "*v" 'SpineJoin 20 5))
                            20)
                    (record "*\t*\t*\t*v\t*v" TOKEN (list (token "*" 'NullInterpretation 21 0)
                                                          (token "*" 'NullInterpretation 21 1)
                                                          (token "*" 'NullInterpretation 21 2)
                                                          (token "*v" 'SpineJoin 21 3)
                                                          (token "*v" 'SpineJoin 21 4))
                            21)
                    (record "*\t*v\t*v\t*" TOKEN (list (token "*" 'NullInterpretation 22 0)
                                                       (token "*v" 'SpineJoin 22 1)
                                                       (token "*v" 'SpineJoin 22 2)
                                                       (token "*" 'NullInterpretation 22 3))
                            22)
                    (record "*v\t*v\t*" TOKEN (list (token "*v" 'SpineJoin 23 0)
                                                    (token "*v" 'SpineJoin 23 1)
                                                    (token "*" 'NullInterpretation 23 2))
                            23)
                    (record "==\t==" TOKEN (list (token "==" 'Measure 24 0)
                                                 (token "==" 'Measure 24 1))
                            24)
                    (record "*-\t*-" TOKEN (list (token "*-" 'SpineTerminator 25 0)
                                                 (token "*-" 'SpineTerminator 25 1))
                            25)))
(check-expect (hgraph->tokens
               (hgraph (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                         (leaf (token "*clefG2" 'Clef 1 0))
                                         (leaf (token "*k[]" 'KeySignature 2 0))
                                         (leaf (token "*a:" 'KeyLabel 3 0))
                                         (leaf (token "*M3/4" 'TimeSignature 4 0))
                                         (parent (token "*^" 'SpineSplit 5 0)
                                                 (list (leaf (token "*" 'NullInterpretation 6 0))
                                                       (leaf (token "*" 'NullInterpretation 7 0))
                                                       (leaf (token "*" 'NullInterpretation 8 0))
                                                       (leaf (token "4c" 'SpineData 9 0))
                                                       (leaf (token "4c" 'SpineData 10 0))
                                                       (leaf (token "4c" 'SpineData 11 0))
                                                       (leaf (token "=2" 'Measure 12 0))
                                                       (leaf (token "4c" 'SpineData 13 0))
                                                       (leaf (token "4c" 'SpineData 14 0))
                                                       (leaf (token "4c" 'SpineData 15 0))
                                                       (leaf (token "=3" 'Measure 16 0))
                                                       (leaf (token "4c" 'SpineData 17 0))
                                                       (leaf (token "4c" 'SpineData 18 0))
                                                       (leaf (token "4c" 'SpineData 19 0))
                                                       (leaf (token "*" 'NullInterpretation 20 0))
                                                       (leaf (token "*" 'NullInterpretation 21 0))
                                                       (leaf (token "*" 'NullInterpretation 22 0))
                                                       (leaf (token "*v" 'SpineJoin 23 0)))
                                                 (list (leaf (token "*" 'NullInterpretation 6 1))
                                                       (parent (token "*^" 'SpineSplit 7 1)
                                                               (list (leaf (token "*" 'NullInterpretation 8 1))
                                                                     (leaf (token "4c" 'SpineData 9 1))
                                                                     (leaf (token "4c" 'SpineData 10 1))
                                                                     (leaf (token "4c" 'SpineData 11 1))
                                                                     (leaf (token "=2" 'Measure 12 1))
                                                                     (leaf (token "4c" 'SpineData 13 1))
                                                                     (leaf (token "4c" 'SpineData 14 1))
                                                                     (leaf (token "4c" 'SpineData 15 1))
                                                                     (leaf (token "=3" 'Measure 16 1))
                                                                     (leaf (token "4c" 'SpineData 17 1))
                                                                     (leaf (token "4c" 'SpineData 18 1))
                                                                     (leaf (token "4c" 'SpineData 19 1))
                                                                     (leaf (token "*" 'NullInterpretation 20 1))
                                                                     (leaf (token "*" 'NullInterpretation 21 1))
                                                                     (leaf (token "*v" 'SpineJoin 22 1)))
                                                               (list (leaf (token "*" 'NullInterpretation 8 2))
                                                                     (leaf (token "4c" 'SpineData 9 2))
                                                                     (leaf (token "4c" 'SpineData 10 2))
                                                                     (leaf (token "4c" 'SpineData 11 2))
                                                                     (leaf (token "=2" 'Measure 12 2))
                                                                     (leaf (token "4c" 'SpineData 13 2))
                                                                     (leaf (token "4c" 'SpineData 14 2))
                                                                     (leaf (token "4c" 'SpineData 15 2))
                                                                     (leaf (token "=3" 'Measure 16 2))
                                                                     (leaf (token "4c" 'SpineData 17 2))
                                                                     (leaf (token "4c" 'SpineData 18 2))
                                                                     (leaf (token "4c" 'SpineData 19 2))
                                                                     (leaf (token "*" 'NullInterpretation 20 2))
                                                                     (leaf (token "*" 'NullInterpretation 21 2))
                                                                     (leaf (token "*v" 'SpineJoin 22 2))))
                                                       (leaf (token "*v" 'SpineJoin 23 1))))
                                         (leaf (token "==" 'Measure 24 0))
                                         (leaf (token "*-" 'SpineTerminator 25 0)))
                                   (list (leaf (token "**kern" 'ExclusiveInterpretation 0 1))
                                         (leaf (token "*clefG2" 'Clef 1 1))
                                         (leaf (token "*k[]" 'KeySignature 2 1))
                                         (leaf (token "*a:" 'KeyLabel 3 1))
                                         (leaf (token "*M3/4" 'TimeSignature 4 1))
                                         (leaf (token "*" 'NullInterpretation 5 1))
                                         (parent (token "*^" 'SpineSplit 6 2)
                                                 (list (leaf (token "*" 'NullInterpretation 7 2))
                                                       (leaf (token "*" 'NullInterpretation 8 3))
                                                       (leaf (token "4c" 'SpineData 9 3))
                                                       (leaf (token "4c" 'SpineData 10 3))
                                                       (leaf (token "4c" 'SpineData 11 3))
                                                       (leaf (token "=2" 'Measure 12 3))
                                                       (leaf (token "4c" 'SpineData 13 3))
                                                       (leaf (token "4c" 'SpineData 14 3))
                                                       (leaf (token "4c" 'SpineData 15 3))
                                                       (leaf (token "=3" 'Measure 16 3))
                                                       (leaf (token "4c" 'SpineData 17 3))
                                                       (leaf (token "4c" 'SpineData 18 3))
                                                       (leaf (token "4c" 'SpineData 19 3))
                                                       (leaf (token "*" 'NullInterpretation 20 3))
                                                       (leaf (token "*v" 'SpineJoin 21 3)))
                                                 (list (leaf (token "*" 'NullInterpretation 7 3))
                                                       (parent (token "*^" 'SpineSplit 8 4)
                                                               (list (leaf (token "4c" 'SpineData 9 4))
                                                                     (leaf (token "4c" 'SpineData 10 4))
                                                                     (leaf (token "4c" 'SpineData 11 4))
                                                                     (leaf (token "=2" 'Measure 12 4))
                                                                     (leaf (token "4c" 'SpineData 13 4))
                                                                     (leaf (token "4c" 'SpineData 14 4))
                                                                     (leaf (token "4c" 'SpineData 15 4))
                                                                     (leaf (token "=3" 'Measure 16 4))
                                                                     (leaf (token "4c" 'SpineData 17 4))
                                                                     (leaf (token "4c" 'SpineData 18 4))
                                                                     (leaf (token "4c" 'SpineData 19 4))
                                                                     (leaf (token "*v" 'SpineJoin 20 4)))
                                                               (list (leaf (token "4c" 'SpineData 9 5))
                                                                     (leaf (token "4c" 'SpineData 10 5))
                                                                     (leaf (token "4c" 'SpineData 11 5))
                                                                     (leaf (token "=2" 'Measure 12 5))
                                                                     (leaf (token "4c" 'SpineData 13 5))
                                                                     (leaf (token "4c" 'SpineData 14 5))
                                                                     (leaf (token "4c" 'SpineData 15 5))
                                                                     (leaf (token "=3" 'Measure 16 5))
                                                                     (leaf (token "4c" 'SpineData 17 5))
                                                                     (leaf (token "4c" 'SpineData 18 5))
                                                                     (leaf (token "4c" 'SpineData 19 5))
                                                                     (leaf (token "*v" 'SpineJoin 20 5))))
                                                       (leaf (token "*v" 'SpineJoin 21 4))))
                                         (leaf (token "*" 'NullInterpretation 22 3))
                                         (leaf (token "*" 'NullInterpretation 23 2))
                                         (leaf (token "==" 'Measure 24 1))
                                         (leaf (token "*-" 'SpineTerminator 25 1)))))))
              (list (list (token "**kern" 'ExclusiveInterpretation 0 0)
                          (token "**kern" 'ExclusiveInterpretation 0 1))
                    (list (token "*clefG2" 'Clef 1 0)
                          (token "*clefG2" 'Clef 1 1))
                    (list (token "*k[]" 'KeySignature 2 0)
                          (token "*k[]" 'KeySignature 2 1))
                    (list (token "*a:" 'KeyLabel 3 0)
                          (token "*a:" 'KeyLabel 3 1))
                    (list (token "*M3/4" 'TimeSignature 4 0)
                          (token "*M3/4" 'TimeSignature 4 1))
                    (list (token "*^" 'SpineSplit 5 0)
                          (token "*" 'NullInterpretation 5 1))
                    (list (token "*" 'NullInterpretation 6 0)
                          (token "*" 'NullInterpretation 6 1)
                          (token "*^" 'SpineSplit 6 2))
                    (list (token "*" 'NullInterpretation 7 0)
                          (token "*^" 'SpineSplit 7 1)
                          (token "*" 'NullInterpretation 7 2)
                          (token "*" 'NullInterpretation 7 3))
                    (list (token "*" 'NullInterpretation 8 0)
                          (token "*" 'NullInterpretation 8 1)
                          (token "*" 'NullInterpretation 8 2)
                          (token "*" 'NullInterpretation 8 3)
                          (token "*^" 'SpineSplit 8 4))
                    (list (token "4c" 'SpineData 9 0)
                          (token "4c" 'SpineData 9 1)
                          (token "4c" 'SpineData 9 2)
                          (token "4c" 'SpineData 9 3)
                          (token "4c" 'SpineData 9 4)
                          (token "4c" 'SpineData 9 5))
                    (list (token "4c" 'SpineData 10 0)
                          (token "4c" 'SpineData 10 1)
                          (token "4c" 'SpineData 10 2)
                          (token "4c" 'SpineData 10 3)
                          (token "4c" 'SpineData 10 4)
                          (token "4c" 'SpineData 10 5))
                    (list (token "4c" 'SpineData 11 0)
                          (token "4c" 'SpineData 11 1)
                          (token "4c" 'SpineData 11 2)
                          (token "4c" 'SpineData 11 3)
                          (token "4c" 'SpineData 11 4)
                          (token "4c" 'SpineData 11 5))
                    (list (token "=2" 'Measure 12 0)
                          (token "=2" 'Measure 12 1)
                          (token "=2" 'Measure 12 2)
                          (token "=2" 'Measure 12 3)
                          (token "=2" 'Measure 12 4)
                          (token "=2" 'Measure 12 5))
                    (list (token "4c" 'SpineData 13 0)
                          (token "4c" 'SpineData 13 1)
                          (token "4c" 'SpineData 13 2)
                          (token "4c" 'SpineData 13 3)
                          (token "4c" 'SpineData 13 4)
                          (token "4c" 'SpineData 13 5))
                    (list (token "4c" 'SpineData 14 0)
                          (token "4c" 'SpineData 14 1)
                          (token "4c" 'SpineData 14 2)
                          (token "4c" 'SpineData 14 3)
                          (token "4c" 'SpineData 14 4)
                          (token "4c" 'SpineData 14 5))
                    (list (token "4c" 'SpineData 15 0)
                          (token "4c" 'SpineData 15 1)
                          (token "4c" 'SpineData 15 2)
                          (token "4c" 'SpineData 15 3)
                          (token "4c" 'SpineData 15 4)
                          (token "4c" 'SpineData 15 5))
                    (list (token "=3" 'Measure 16 0)
                          (token "=3" 'Measure 16 1)
                          (token "=3" 'Measure 16 2)
                          (token "=3" 'Measure 16 3)
                          (token "=3" 'Measure 16 4)
                          (token "=3" 'Measure 16 5))
                    (list (token "4c" 'SpineData 17 0)
                          (token "4c" 'SpineData 17 1)
                          (token "4c" 'SpineData 17 2)
                          (token "4c" 'SpineData 17 3)
                          (token "4c" 'SpineData 17 4)
                          (token "4c" 'SpineData 17 5))
                    (list (token "4c" 'SpineData 18 0)
                          (token "4c" 'SpineData 18 1)
                          (token "4c" 'SpineData 18 2)
                          (token "4c" 'SpineData 18 3)
                          (token "4c" 'SpineData 18 4)
                          (token "4c" 'SpineData 18 5))
                    (list (token "4c" 'SpineData 19 0)
                          (token "4c" 'SpineData 19 1)
                          (token "4c" 'SpineData 19 2)
                          (token "4c" 'SpineData 19 3)
                          (token "4c" 'SpineData 19 4)
                          (token "4c" 'SpineData 19 5))
                    (list (token "*" 'NullInterpretation 20 0)
                          (token "*" 'NullInterpretation 20 1)
                          (token "*" 'NullInterpretation 20 2)
                          (token "*" 'NullInterpretation 20 3)
                          (token "*v" 'SpineJoin 20 4)
                          (token "*v" 'SpineJoin 20 5))
                    (list (token "*" 'NullInterpretation 21 0)
                          (token "*" 'NullInterpretation 21 1)
                          (token "*" 'NullInterpretation 21 2)
                          (token "*v" 'SpineJoin 21 3)
                          (token "*v" 'SpineJoin 21 4))
                    (list (token "*" 'NullInterpretation 22 0)
                          (token "*v" 'SpineJoin 22 1)
                          (token "*v" 'SpineJoin 22 2)
                          (token "*" 'NullInterpretation 22 3))
                    (list (token "*v" 'SpineJoin 23 0)
                          (token "*v" 'SpineJoin 23 1)
                          (token "*" 'NullInterpretation 23 2))
                    (list (token "==" 'Measure 24 0)
                          (token "==" 'Measure 24 1))
                    (list (token "*-" 'SpineTerminator 25 0)
                          (token "*-" 'SpineTerminator 25 1))))
#|
(check-expect (hfile->hgraph (path->hfile "../../data/count/two-spines-two-splits.krn"))
              (hgraph (root (list (list (leaf (token "**kern" 'ExclusiveInterpretation 0 0))
                                        (leaf (token "*clefG2" 'Clef 1 0))
                                        (leaf (token "*k[]" 'KeySignature 2 0))
                                        (leaf (token "*a:" 'KeyLabel 3 0))
                                        (leaf (token "*M3/4" 'TimeSignature 4 0))
                                        (parent (token "*^" 'SpineSplit 5 0)
                                                (list (leaf (token "*" 'NullInterpretation 6 0))
                                                      (leaf (token "*" 'NullInterpretation 7 0))
                                                      (leaf (token "*" 'NullInterpretation 8 0))
                                                      (leaf (token "4c" 'SpineData 9 0))
                                                      (leaf (token "4c" 'SpineData 10 0))
                                                      (leaf (token "4c" 'SpineData 11 0))
                                                      (leaf (token "=2" 'Measure 12 0))
                                                      (leaf (token "4c" 'SpineData 13 0))
                                                      (leaf (token "4c" 'SpineData 14 0))
                                                      (leaf (token "4c" 'SpineData 15 0))
                                                      (leaf (token "=3" 'Measure 16 0))
                                                      (leaf (token "4c" 'SpineData 17 0))
                                                      (leaf (token "4c" 'SpineData 18 0))
                                                      (leaf (token "4c" 'SpineData 19 0))
                                                      (leaf (token "*" 'NullInterpretation 20 0))
                                                      (leaf (token "*" 'NullInterpretation 21 0))
                                                      (leaf (token "*" 'NullInterpretation 22 0))
                                                      (leaf (token "*v" 'SpineJoin 23 0)))
                                                (list (leaf (token "*" 'NullInterpretation 6 1))
                                                      (parent (token "*^" 'SpineSplit 7 1)
                                                              (list (leaf (token "*" 'NullInterpretation 8 1))
                                                                    (leaf (token "4c" 'SpineData 9 1))
                                                                    (leaf (token "4c" 'SpineData 10 1))
                                                                    (leaf (token "4c" 'SpineData 11 1))
                                                                    (leaf (token "=2" 'Measure 12 1))
                                                                    (leaf (token "4c" 'SpineData 13 1))
                                                                    (leaf (token "4c" 'SpineData 14 1))
                                                                    (leaf (token "4c" 'SpineData 15 1))
                                                                    (leaf (token "=3" 'Measure 16 1))
                                                                    (leaf (token "4c" 'SpineData 17 1))
                                                                    (leaf (token "4c" 'SpineData 18 1))
                                                                    (leaf (token "4c" 'SpineData 19 1))
                                                                    (leaf (token "*" 'NullInterpretation 20 1))
                                                                    (leaf (token "*" 'NullInterpretation 21 1))
                                                                    (leaf (token "*v" 'SpineJoin 22 1)))
                                                              (list (leaf (token "*" 'NullInterpretation 8 2))
                                                                    (leaf (token "4c" 'SpineData 9 2))
                                                                    (leaf (token "4c" 'SpineData 10 2))
                                                                    (leaf (token "4c" 'SpineData 11 2))
                                                                    (leaf (token "=2" 'Measure 12 2))
                                                                    (leaf (token "4c" 'SpineData 13 2))
                                                                    (leaf (token "4c" 'SpineData 14 2))
                                                                    (leaf (token "4c" 'SpineData 15 2))
                                                                    (leaf (token "=3" 'Measure 16 2))
                                                                    (leaf (token "4c" 'SpineData 17 2))
                                                                    (leaf (token "4c" 'SpineData 18 2))
                                                                    (leaf (token "4c" 'SpineData 19 2))
                                                                    (leaf (token "*" 'NullInterpretation 20 2))
                                                                    (leaf (token "*" 'NullInterpretation 21 2))
                                                                    (leaf (token "*v" 'SpineJoin 22 2))))
                                                      (leaf (token "*v" 'SpineJoin 23 1))))
                                        (leaf (token "==" 'Measure 24 0))
                                        (leaf (token "*-" 'SpineTerminator 25 0)))
                                  (list (leaf (token "**kern" 'ExclusiveInterpretation 0 1))
                                        (leaf (token "*clefG2" 'Clef 1 1))
                                        (leaf (token "*k[]" 'KeySignature 2 1))
                                        (leaf (token "*a:" 'KeyLabel 3 1))
                                        (leaf (token "*M3/4" 'TimeSignature 4 1))
                                        (leaf (token "*" 'NullInterpretation 5 1))
                                        (parent (token "*^" 'SpineSplit 6 2)
                                                (list (leaf (token "*" 'NullInterpretation 7 2))
                                                      (leaf (token "*" 'NullInterpretation 8 3))
                                                      (leaf (token "4c" 'SpineData 9 3))
                                                      (leaf (token "4c" 'SpineData 10 3))
                                                      (leaf (token "4c" 'SpineData 11 3))
                                                      (leaf (token "=2" 'Measure 12 3))
                                                      (leaf (token "4c" 'SpineData 13 3))
                                                      (leaf (token "4c" 'SpineData 14 3))
                                                      (leaf (token "4c" 'SpineData 15 3))
                                                      (leaf (token "=3" 'Measure 16 3))
                                                      (leaf (token "4c" 'SpineData 17 3))
                                                      (leaf (token "4c" 'SpineData 18 3))
                                                      (leaf (token "4c" 'SpineData 19 3))
                                                      (leaf (token "*" 'NullInterpretation 20 3))
                                                      (leaf (token "*v" 'SpineJoin 21 3)))
                                                (list (leaf (token "*" 'NullInterpretation 7 3))
                                                      (parent (token "*^" 'SpineSplit 8 4)
                                                              (list (leaf (token "4c" 'SpineData 9 4))
                                                                    (leaf (token "4c" 'SpineData 10 4))
                                                                    (leaf (token "4c" 'SpineData 11 4))
                                                                    (leaf (token "=2" 'Measure 12 4))
                                                                    (leaf (token "4c" 'SpineData 13 4))
                                                                    (leaf (token "4c" 'SpineData 14 4))
                                                                    (leaf (token "4c" 'SpineData 15 4))
                                                                    (leaf (token "=3" 'Measure 16 4))
                                                                    (leaf (token "4c" 'SpineData 17 4))
                                                                    (leaf (token "4c" 'SpineData 18 4))
                                                                    (leaf (token "4c" 'SpineData 19 4))
                                                                    (leaf (token "*v" 'SpineJoin 20 4)))
                                                              (list (leaf (token "4c" 'SpineData 9 5))
                                                                    (leaf (token "4c" 'SpineData 10 5))
                                                                    (leaf (token "4c" 'SpineData 11 5))
                                                                    (leaf (token "=2" 'Measure 12 5))
                                                                    (leaf (token "4c" 'SpineData 13 5))
                                                                    (leaf (token "4c" 'SpineData 14 5))
                                                                    (leaf (token "4c" 'SpineData 15 5))
                                                                    (leaf (token "=3" 'Measure 16 5))
                                                                    (leaf (token "4c" 'SpineData 17 5))
                                                                    (leaf (token "4c" 'SpineData 18 5))
                                                                    (leaf (token "4c" 'SpineData 19 5))
                                                                    (leaf (token "*v" 'SpineJoin 20 5))))
                                                      (leaf (token "*v" 'SpineJoin 21 4))))
                                        (leaf (token "*" 'NullInterpretation 22 3))
                                        (leaf (token "*" 'NullInterpretation 23 2))
                                        (leaf (token "==" 'Measure 24 1))
                                        (leaf (token "*-" 'SpineTerminator 25 1)))))))
|#
(check-expect (gspines->linked-spines (spine-parser (path->hfile "../../data/count/two-spines-two-splits.krn"))
                                      (path->hfile "../../data/count/two-spines-two-splits.krn"))
              (list (linked-spine KERN-0-0) (linked-spine KERN-0-1)))

(test)
