#lang racket/base

(require "../../../../parser/data-definitions/data-definitions.rkt"
         "../../../../parser/functions/file.rkt"
         "../../../../parser/functions/spine-parser.rkt"
         "../../../../data-structures/abstract-humdrum-graph/data-definitions/data-definitions.rkt"
         "../../../../data-structures/abstract-humdrum-graph/functions/ab-hgraph-to-hfile.rkt"
         "../../../../data-structures/abstract-humdrum-graph/functions/hfile-to-ab-hgraph.rkt"
         test-engine/racket-tests
         racket/list) ; TODO remove

(check-expect (path->hfile "../../data/order/spine-splits-right-joins-left-c.krn")
              (hfile (list (record "**kern" TOKEN
                                   (list (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                   0)
                           (record "*^" TOKEN
                                   (list (token "*^" SPINE-SPLIT 1))
                                   1)
                           (record "*\t*^" TOKEN
                                   (list (token "*" NULL-INTERPRETATION 2)
                                         (token "*^" SPINE-SPLIT 2))
                                   2)
                           (record "*\t*\t*^" TOKEN
                                   (list (token "*" NULL-INTERPRETATION 3)
                                         (token "*" NULL-INTERPRETATION 3)
                                         (token "*^" SPINE-SPLIT 3))
                                   3)
                           (record "4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 4)
                                         (token "4c" SPINE-DATA 4)
                                         (token "4c" SPINE-DATA 4)
                                         (token "4c" SPINE-DATA 4))
                                   4)
                           (record "4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 5)
                                         (token "4c" SPINE-DATA 5)
                                         (token "4c" SPINE-DATA 5)
                                         (token "4c" SPINE-DATA 5))
                                   5)
                           (record "4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 6)
                                         (token "4c" SPINE-DATA 6)
                                         (token "4c" SPINE-DATA 6)
                                         (token "4c" SPINE-DATA 6))
                                   6)
                           (record "*v\t*v\t*\t*" TOKEN
                                   (list (token "*v" SPINE-JOIN 7)
                                         (token "*v" SPINE-JOIN 7)
                                         (token "*" NULL-INTERPRETATION 7)
                                         (token "*" NULL-INTERPRETATION 7))
                                   7)
                           (record "4a\t4b\t4c" TOKEN
                                   (list (token "4a" SPINE-DATA 8)
                                         (token "4b" SPINE-DATA 8)
                                         (token "4c" SPINE-DATA 8))
                                   8)
                           (record "4c\t4d\t4e" TOKEN
                                   (list (token "4c" SPINE-DATA 9)
                                         (token "4d" SPINE-DATA 9)
                                         (token "4e" SPINE-DATA 9))
                                   9)
                           (record "*v\t*v\t*" TOKEN
                                   (list (token "*v" SPINE-JOIN 10)
                                         (token "*v" SPINE-JOIN 10)
                                         (token "*" NULL-INTERPRETATION 10))
                                   10)
                           (record "4e\t4f" TOKEN
                                   (list (token "4e" SPINE-DATA 11)
                                         (token "4f" SPINE-DATA 11))
                                   11)
                           (record "*v\t*v" TOKEN
                                   (list (token "*v" SPINE-JOIN 12)
                                         (token "*v" SPINE-JOIN 12))
                                   12)
                           (record "*-" TOKEN
                                   (list (token "*-" SPINE-TERMINATOR 13))
                                   13))))
(check-expect (spine-parser (path->hfile "../../data/order/spine-splits-right-joins-left-c.krn"))
              (list (global-spine KERN
                                  (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                        (list (token "*^" SPINE-SPLIT 1))
                                        (list (token "*" NULL-INTERPRETATION 2)
                                              (token "*^" SPINE-SPLIT 2))
                                        (list (token "*" NULL-INTERPRETATION 3)
                                              (token "*" NULL-INTERPRETATION 3)
                                              (token "*^" SPINE-SPLIT 3))
                                        (list (token "4c" SPINE-DATA 4)
                                              (token "4c" SPINE-DATA 4)
                                              (token "4c" SPINE-DATA 4)
                                              (token "4c" SPINE-DATA 4))
                                        (list (token "4c" SPINE-DATA 5)
                                              (token "4c" SPINE-DATA 5)
                                              (token "4c" SPINE-DATA 5)
                                              (token "4c" SPINE-DATA 5))
                                        (list (token "4c" SPINE-DATA 6)
                                              (token "4c" SPINE-DATA 6)
                                              (token "4c" SPINE-DATA 6)
                                              (token "4c" SPINE-DATA 6))
                                        (list (token "*v" SPINE-JOIN 7)
                                              (token "*v" SPINE-JOIN 7)
                                              (token "*" NULL-INTERPRETATION 7)
                                              (token "*" NULL-INTERPRETATION 7))
                                        (list (token "4a" SPINE-DATA 8)
                                              (token "4b" SPINE-DATA 8)
                                              (token "4c" SPINE-DATA 8))
                                        (list (token "4c" SPINE-DATA 9)
                                              (token "4d" SPINE-DATA 9)
                                              (token "4e" SPINE-DATA 9))
                                        (list (token "*v" SPINE-JOIN 10)
                                              (token "*v" SPINE-JOIN 10)
                                              (token "*" NULL-INTERPRETATION 10))
                                        (list (token "4e" SPINE-DATA 11)
                                              (token "4f" SPINE-DATA 11))
                                        (list (token "*v" SPINE-JOIN 12)
                                              (token "*v" SPINE-JOIN 12))
                                        (list (token "*-" SPINE-TERMINATOR 13)))
                                  0)))
(check-expect (ab-hgraph->hfile (ab-hgraph (root empty)))
              (path->hfile "../../data/order/spine-splits-right-joins-left-c.krn"))
(check-expect (lolot->lor (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                (list (token "*^" SPINE-SPLIT 1))
                                (list (token "*" NULL-INTERPRETATION 2)
                                      (token "*^" SPINE-SPLIT 2))
                                (list (token "*" NULL-INTERPRETATION 3)
                                      (token "*" NULL-INTERPRETATION 3)
                                      (token "*^" SPINE-SPLIT 3))
                                (list (token "4c" SPINE-DATA 4)
                                      (token "4c" SPINE-DATA 4)
                                      (token "4c" SPINE-DATA 4)
                                      (token "4c" SPINE-DATA 4))
                                (list (token "4c" SPINE-DATA 5)
                                      (token "4c" SPINE-DATA 5)
                                      (token "4c" SPINE-DATA 5)
                                      (token "4c" SPINE-DATA 5))
                                (list (token "4c" SPINE-DATA 6)
                                      (token "4c" SPINE-DATA 6)
                                      (token "4c" SPINE-DATA 6)
                                      (token "4c" SPINE-DATA 6))
                                (list (token "*v" SPINE-JOIN 7)
                                      (token "*v" SPINE-JOIN 7)
                                      (token "*" NULL-INTERPRETATION 7)
                                      (token "*" NULL-INTERPRETATION 7))
                                (list (token "4a" SPINE-DATA 8)
                                      (token "4b" SPINE-DATA 8)
                                      (token "4c" SPINE-DATA 8))
                                (list (token "4c" SPINE-DATA 9)
                                      (token "4d" SPINE-DATA 9)
                                      (token "4e" SPINE-DATA 9))
                                (list (token "*v" SPINE-JOIN 10)
                                      (token "*v" SPINE-JOIN 10)
                                      (token "*" NULL-INTERPRETATION 10))
                                (list (token "4e" SPINE-DATA 11)
                                      (token "4f" SPINE-DATA 11))
                                (list (token "*v" SPINE-JOIN 12)
                                      (token "*v" SPINE-JOIN 12))
                                (list (token "*-" SPINE-TERMINATOR 13))))
              (list (record "**kern" TOKEN
                            (list (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                            0)
                    (record "*^" TOKEN
                            (list (token "*^" SPINE-SPLIT 1))
                            1)
                    (record "*\t*^" TOKEN
                            (list (token "*" NULL-INTERPRETATION 2)
                                  (token "*^" SPINE-SPLIT 2))
                            2)
                    (record "*\t*\t*^" TOKEN
                            (list (token "*" NULL-INTERPRETATION 3)
                                  (token "*" NULL-INTERPRETATION 3)
                                  (token "*^" SPINE-SPLIT 3))
                            3)
                    (record "4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 4)
                                  (token "4c" SPINE-DATA 4)
                                  (token "4c" SPINE-DATA 4)
                                  (token "4c" SPINE-DATA 4))
                            4)
                    (record "4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 5)
                                  (token "4c" SPINE-DATA 5)
                                  (token "4c" SPINE-DATA 5)
                                  (token "4c" SPINE-DATA 5))
                            5)
                    (record "4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 6)
                                  (token "4c" SPINE-DATA 6)
                                  (token "4c" SPINE-DATA 6)
                                  (token "4c" SPINE-DATA 6))
                            6)
                    (record "*v\t*v\t*\t*" TOKEN
                            (list (token "*v" SPINE-JOIN 7)
                                  (token "*v" SPINE-JOIN 7)
                                  (token "*" NULL-INTERPRETATION 7)
                                  (token "*" NULL-INTERPRETATION 7))
                            7)
                    (record "4a\t4b\t4c" TOKEN
                            (list (token "4a" SPINE-DATA 8)
                                  (token "4b" SPINE-DATA 8)
                                  (token "4c" SPINE-DATA 8))
                            8)
                    (record "4c\t4d\t4e" TOKEN
                            (list (token "4c" SPINE-DATA 9)
                                  (token "4d" SPINE-DATA 9)
                                  (token "4e" SPINE-DATA 9))
                            9)
                    (record "*v\t*v\t*" TOKEN
                            (list (token "*v" SPINE-JOIN 10)
                                  (token "*v" SPINE-JOIN 10)
                                  (token "*" NULL-INTERPRETATION 10))
                            10)
                    (record "4e\t4f" TOKEN
                            (list (token "4e" SPINE-DATA 11)
                                  (token "4f" SPINE-DATA 11))
                            11)
                    (record "*v\t*v" TOKEN
                            (list (token "*v" SPINE-JOIN 12)
                                  (token "*v" SPINE-JOIN 12))
                            12)
                    (record "*-" TOKEN
                            (list (token "*-" SPINE-TERMINATOR 13))
                            13)))
(check-expect (ab-hgraph->lolot (ab-hgraph (root empty))) empty)
(check-expect (hfile->ab-hgraph
               (path->hfile "../../data/order/spine-splits-right-joins-left-c.krn") ab-hgraph)
              (ab-hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                           (parent (token "*^" SPINE-SPLIT 1)
                                                   (list (leaf (token "*" NULL-INTERPRETATION 2))
                                                         (leaf (token "*" NULL-INTERPRETATION 3))
                                                         (leaf (token "4c" SPINE-DATA 4))
                                                         (leaf (token "4c" SPINE-DATA 5))
                                                         (leaf (token "4c" SPINE-DATA 6))
                                                         (leaf (token "*v" SPINE-JOIN 7)))
                                                   (list (parent (token "*^" SPINE-SPLIT 2)
                                                                 (list (leaf (token "*" NULL-INTERPRETATION 3))
                                                                       (leaf (token "4c" SPINE-DATA 4))
                                                                       (leaf (token "4c" SPINE-DATA 5))
                                                                       (leaf (token "4c" SPINE-DATA 6))
                                                                       (leaf (token "*v" SPINE-JOIN 7)))
                                                                 (list (parent (token "*^" SPINE-SPLIT 3)
                                                                               (list (leaf (token "4c" SPINE-DATA 4))
                                                                                     (leaf (token "4c" SPINE-DATA 5))
                                                                                     (leaf (token "4c" SPINE-DATA 6))
                                                                                     (leaf (token "*" NULL-INTERPRETATION 7))
                                                                                     (leaf (token "4a" SPINE-DATA 8))
                                                                                     (leaf (token "4c" SPINE-DATA 9))
                                                                                     (leaf (token "*v" SPINE-JOIN 10)))
                                                                               (list (leaf (token "4c" SPINE-DATA 4))
                                                                                     (leaf (token "4c" SPINE-DATA 5))
                                                                                     (leaf (token "4c" SPINE-DATA 6))
                                                                                     (leaf (token "*" NULL-INTERPRETATION 7))
                                                                                     (leaf (token "4b" SPINE-DATA 8))
                                                                                     (leaf (token "4d" SPINE-DATA 9))
                                                                                     (leaf (token "*v" SPINE-JOIN 10))))
                                                                       (leaf (token "4e" SPINE-DATA 11))
                                                                       (leaf (token "*v" SPINE-JOIN 12))))
                                                         (leaf (token "4c" SPINE-DATA 8))
                                                         (leaf (token "4e" SPINE-DATA 9))
                                                         (leaf (token "*" NULL-INTERPRETATION 10))
                                                         (leaf (token "4f" SPINE-DATA 11))
                                                         (leaf (token "*v" SPINE-JOIN 12))))
                                           (leaf (token "*-" SPINE-TERMINATOR 13)))))))
(check-expect (branch->lot (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                 (parent (token "*^" SPINE-SPLIT 1)
                                         (list (leaf (token "*" NULL-INTERPRETATION 2))
                                               (leaf (token "*" NULL-INTERPRETATION 3))
                                               (leaf (token "4c" SPINE-DATA 4))
                                               (leaf (token "4c" SPINE-DATA 5))
                                               (leaf (token "4c" SPINE-DATA 6))
                                               (leaf (token "*v" SPINE-JOIN 7)))
                                         (list (parent (token "*^" SPINE-SPLIT 2)
                                                       (list (leaf (token "*" NULL-INTERPRETATION 3))
                                                             (leaf (token "4c" SPINE-DATA 4))
                                                             (leaf (token "4c" SPINE-DATA 5))
                                                             (leaf (token "4c" SPINE-DATA 6))
                                                             (leaf (token "*v" SPINE-JOIN 7)))
                                                       (list (parent (token "*^" SPINE-SPLIT 3)
                                                                     (list (leaf (token "4c" SPINE-DATA 4))
                                                                           (leaf (token "4c" SPINE-DATA 5))
                                                                           (leaf (token "4c" SPINE-DATA 6))
                                                                           (leaf (token "*" NULL-INTERPRETATION 7))
                                                                           (leaf (token "4a" SPINE-DATA 8))
                                                                           (leaf (token "4c" SPINE-DATA 9))
                                                                           (leaf (token "*v" SPINE-JOIN 10)))
                                                                     (list (leaf (token "4c" SPINE-DATA 4))
                                                                           (leaf (token "4c" SPINE-DATA 5))
                                                                           (leaf (token "4c" SPINE-DATA 6))
                                                                           (leaf (token "*" NULL-INTERPRETATION 7))
                                                                           (leaf (token "4b" SPINE-DATA 8))
                                                                           (leaf (token "4d" SPINE-DATA 9))
                                                                           (leaf (token "*v" SPINE-JOIN 10))))
                                                             (leaf (token "4e" SPINE-DATA 11))
                                                             (leaf (token "*v" SPINE-JOIN 12))))
                                               (leaf (token "4c" SPINE-DATA 8))
                                               (leaf (token "4e" SPINE-DATA 9))
                                               (leaf (token "*" NULL-INTERPRETATION 10))
                                               (leaf (token "4f" SPINE-DATA 11))
                                               (leaf (token "*v" SPINE-JOIN 12))))
                                 (leaf (token "*-" SPINE-TERMINATOR 13))))
              (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                    (token "*^" SPINE-SPLIT 1)
                    (token "*" NULL-INTERPRETATION 2)
                    (token "*" NULL-INTERPRETATION 3)
                    (token "4c" SPINE-DATA 4)
                    (token "4c" SPINE-DATA 5)
                    (token "4c" SPINE-DATA 6)
                    (token "*v" SPINE-JOIN 7)
                    (token "*^" SPINE-SPLIT 2)
                    (token "*" NULL-INTERPRETATION 3)
                    (token "4c" SPINE-DATA 4)
                    (token "4c" SPINE-DATA 5)
                    (token "4c" SPINE-DATA 6)
                    (token "*v" SPINE-JOIN 7)
                    (token "*^" SPINE-SPLIT 3)
                    (token "4c" SPINE-DATA 4)
                    (token "4c" SPINE-DATA 5)
                    (token "4c" SPINE-DATA 6)
                    (token "*" NULL-INTERPRETATION 7)
                    (token "4a" SPINE-DATA 8)
                    (token "4c" SPINE-DATA 9)
                    (token "*v" SPINE-JOIN 10)
                    (token "4c" SPINE-DATA 4)
                    (token "4c" SPINE-DATA 5)
                    (token "4c" SPINE-DATA 6)
                    (token "*" NULL-INTERPRETATION 7)
                    (token "4b" SPINE-DATA 8)
                    (token "4d" SPINE-DATA 9)
                    (token "*v" SPINE-JOIN 10)
                    (token "4e" SPINE-DATA 11)
                    (token "*v" SPINE-JOIN 12)
                    (token "4c" SPINE-DATA 8)
                    (token "4e" SPINE-DATA 9)
                    (token "*" NULL-INTERPRETATION 10)
                    (token "4f" SPINE-DATA 11)
                    (token "*v" SPINE-JOIN 12)
                    (token "*-" SPINE-TERMINATOR 13)))

(test)
