#lang racket/base

(require "../../../../parser/data-definitions/data-definitions.rkt"
         "../../../../parser/functions/file.rkt"
         "../../../../parser/functions/spine-parser.rkt"
         "../../../../parser/data-structures/humdrum-graph/data-definitions/data-definitions.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hgraph-to-hfile.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hfile-to-hgraph.rkt"
         "../../../../parser/data-structures/linked-spine/data-definitions/data-definitions.rkt"
         "../../../../parser/data-structures/linked-spine/functions/gspines-to-linked-spines.rkt"
         test-engine/racket-tests)

;; Node definitions
(define TERM-8-0 (terminator-node (token "*-" SPINE-TERMINATOR 8 0)))
(define J-7-0 (token-node (token "*v" SPINE-JOIN 7 0) (box-immutable TERM-8-0)))
(define J-7-1 (token-node (token "*v" SPINE-JOIN 7 1) (box-immutable TERM-8-0)))
(define NULL-6-0 (token-node (token "*" NULL-INTERPRETATION 6 0) (box-immutable J-7-0)))
(define J-6-1 (token-node (token "*v" SPINE-JOIN 6 1) (box-immutable J-7-1)))
(define J-6-2 (token-node (token "*v" SPINE-JOIN 6 2) (box-immutable J-7-1)))
(define 4c-5-0 (token-node (token "4c" SPINE-DATA 5 0) (box-immutable NULL-6-0)))
(define 4c-5-1 (token-node (token "4c" SPINE-DATA 5 1) (box-immutable J-6-1)))
(define 4c-5-2 (token-node (token "4c" SPINE-DATA 5 2) (box-immutable J-6-2)))
(define 4c-4-0 (token-node (token "4c" SPINE-DATA 4 0) (box-immutable 4c-5-0)))
(define 4c-4-1 (token-node (token "4c" SPINE-DATA 4 1) (box-immutable 4c-5-1)))
(define 4c-4-2 (token-node (token "4c" SPINE-DATA 4 2) (box-immutable 4c-5-2)))
(define 4c-3-0 (token-node (token "4c" SPINE-DATA 3 0) (box-immutable 4c-4-0)))
(define 4c-3-1 (token-node (token "4c" SPINE-DATA 3 1) (box-immutable 4c-4-1)))
(define 4c-3-2 (token-node (token "4c" SPINE-DATA 3 2) (box-immutable 4c-4-2)))
(define NULL-2-0 (token-node (token "*" NULL-INTERPRETATION 2 0) (box-immutable 4c-3-0)))
(define S-2-1 (split-node (token "*^" SPINE-SPLIT 2 1)
                          (box-immutable 4c-3-1)
                          (box-immutable 4c-3-2)))
(define S-1-0 (split-node (token "*^" SPINE-SPLIT 1 0)
                          (box-immutable NULL-2-0)
                          (box-immutable S-2-1)))
(define KERN-0-0 (token-node (token "**kern" EXCLUSIVE-INTERPRETATION 0 0) (box-immutable S-1-0)))

(check-expect (path->hfile "../../data/order/spine-splits-joins-successively.krn")
              (hfile (list (record "**kern" TOKEN
                                   (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                   0)
                           (record "*^" TOKEN (list (token "*^" SPINE-SPLIT 1 0)) 1)
                           (record "*\t*^" TOKEN (list (token "*" NULL-INTERPRETATION 2 0)
                                                       (token "*^" SPINE-SPLIT 2 1))
                                   2)
                           (record "4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 3 0)
                                                            (token "4c" SPINE-DATA 3 1)
                                                            (token "4c" SPINE-DATA 3 2))
                                   3)
                           (record "4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 4 0)
                                                            (token "4c" SPINE-DATA 4 1)
                                                            (token "4c" SPINE-DATA 4 2))
                                   4)
                           (record "4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 5 0)
                                                            (token "4c" SPINE-DATA 5 1)
                                                            (token "4c" SPINE-DATA 5 2))
                                   5)
                           (record "*\t*v\t*v" TOKEN (list (token "*" NULL-INTERPRETATION 6 0)
                                                           (token "*v" SPINE-JOIN 6 1)
                                                           (token "*v" SPINE-JOIN 6 2))
                                   6)
                           (record "*v\t*v" TOKEN (list (token "*v" SPINE-JOIN 7 0)
                                                        (token "*v" SPINE-JOIN 7 1))
                                   7)
                           (record "*-" TOKEN (list (token "*-" SPINE-TERMINATOR 8 0)) 8))))
(check-expect (spine-parser (path->hfile "../../data/order/spine-splits-joins-successively.krn"))
              (list (global-spine KERN
                                  (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                        (list (token "*^" SPINE-SPLIT 1 0))
                                        (list (token "*" NULL-INTERPRETATION 2 0)
                                              (token "*^" SPINE-SPLIT 2 1))
                                        (list (token "4c" SPINE-DATA 3 0)
                                              (token "4c" SPINE-DATA 3 1)
                                              (token "4c" SPINE-DATA 3 2))
                                        (list (token "4c" SPINE-DATA 4 0)
                                              (token "4c" SPINE-DATA 4 1)
                                              (token "4c" SPINE-DATA 4 2))
                                        (list (token "4c" SPINE-DATA 5 0)
                                              (token "4c" SPINE-DATA 5 1)
                                              (token "4c" SPINE-DATA 5 2))
                                        (list (token "*" NULL-INTERPRETATION 6 0)
                                              (token "*v" SPINE-JOIN 6 1)
                                              (token "*v" SPINE-JOIN 6 2))
                                        (list (token "*v" SPINE-JOIN 7 0)
                                              (token "*v" SPINE-JOIN 7 1))
                                        (list (token "*-" SPINE-TERMINATOR 8 0)))
                                  0)))
(check-expect (hgraph->hfile (hgraph (root
                                            (list
                                             (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                                   (parent (token "*^" SPINE-SPLIT 1 0)
                                                           (list (leaf (token "*" NULL-INTERPRETATION 2 0))
                                                                 (leaf (token "4c" SPINE-DATA 3 0))
                                                                 (leaf (token "4c" SPINE-DATA 4 0))
                                                                 (leaf (token "4c" SPINE-DATA 5 0))
                                                                 (leaf (token "*" NULL-INTERPRETATION 6 0))
                                                                 (leaf (token "*v" SPINE-JOIN 7 0)))
                                                           (list (parent (token "*^" SPINE-SPLIT 2 1)
                                                                         (list (leaf (token "4c" SPINE-DATA 3 1))
                                                                               (leaf (token "4c" SPINE-DATA 4 1))
                                                                               (leaf (token "4c" SPINE-DATA 5 1))
                                                                               (leaf (token "*v" SPINE-JOIN 6 1)))
                                                                         (list (leaf (token "4c" SPINE-DATA 3 2))
                                                                               (leaf (token "4c" SPINE-DATA 4 2))
                                                                               (leaf (token "4c" SPINE-DATA 5 2))
                                                                               (leaf (token "*v" SPINE-JOIN 6 2))))
                                                                 (leaf (token "*v" SPINE-JOIN 7 1))))
                                                   (leaf (token "*-" SPINE-TERMINATOR 8 0)))))))
              (path->hfile "../../data/order/spine-splits-joins-successively.krn"))
(check-expect (lolot->lor (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                (list (token "*^" SPINE-SPLIT 1 0))
                                (list (token "*" NULL-INTERPRETATION 2 0)
                                      (token "*^" SPINE-SPLIT 2 1))
                                (list (token "4c" SPINE-DATA 3 0)
                                      (token "4c" SPINE-DATA 3 1)
                                      (token "4c" SPINE-DATA 3 2))
                                (list (token "4c" SPINE-DATA 4 0)
                                      (token "4c" SPINE-DATA 4 1)
                                      (token "4c" SPINE-DATA 4 2))
                                (list (token "4c" SPINE-DATA 5 0)
                                      (token "4c" SPINE-DATA 5 1)
                                      (token "4c" SPINE-DATA 5 2))
                                (list (token "*" NULL-INTERPRETATION 6 0)
                                      (token "*v" SPINE-JOIN 6 1)
                                      (token "*v" SPINE-JOIN 6 2))
                                (list (token "*v" SPINE-JOIN 7 0)
                                      (token "*v" SPINE-JOIN 7 1))
                                (list (token "*-" SPINE-TERMINATOR 8 0))))
              (list (record "**kern" TOKEN
                            (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                            0)
                    (record "*^" TOKEN (list (token "*^" SPINE-SPLIT 1 0)) 1)
                    (record "*\t*^" TOKEN (list (token "*" NULL-INTERPRETATION 2 0)
                                                (token "*^" SPINE-SPLIT 2 1))
                            2)
                    (record "4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 3 0)
                                                     (token "4c" SPINE-DATA 3 1)
                                                     (token "4c" SPINE-DATA 3 2))
                            3)
                    (record "4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 4 0)
                                                     (token "4c" SPINE-DATA 4 1)
                                                     (token "4c" SPINE-DATA 4 2))
                            4)
                    (record "4c\t4c\t4c" TOKEN (list (token "4c" SPINE-DATA 5 0)
                                                     (token "4c" SPINE-DATA 5 1)
                                                     (token "4c" SPINE-DATA 5 2))
                            5)
                    (record "*\t*v\t*v" TOKEN (list (token "*" NULL-INTERPRETATION 6 0)
                                                    (token "*v" SPINE-JOIN 6 1)
                                                    (token "*v" SPINE-JOIN 6 2))
                            6)
                    (record "*v\t*v" TOKEN (list (token "*v" SPINE-JOIN 7 0)
                                                 (token "*v" SPINE-JOIN 7 1))
                            7)
                    (record "*-" TOKEN (list (token "*-" SPINE-TERMINATOR 8 0)) 8)))
(check-expect (hgraph->lolot
               (hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                            (parent (token "*^" SPINE-SPLIT 1 0)
                                                    (list (leaf (token "*" NULL-INTERPRETATION 2 0))
                                                          (leaf (token "4c" SPINE-DATA 3 0))
                                                          (leaf (token "4c" SPINE-DATA 4 0))
                                                          (leaf (token "4c" SPINE-DATA 5 0))
                                                          (leaf (token "*" NULL-INTERPRETATION 6 0))
                                                          (leaf (token "*v" SPINE-JOIN 7 0)))
                                                    (list (parent (token "*^" SPINE-SPLIT 2 1)
                                                                  (list (leaf (token "4c" SPINE-DATA 3 1))
                                                                        (leaf (token "4c" SPINE-DATA 4 1))
                                                                        (leaf (token "4c" SPINE-DATA 5 1))
                                                                        (leaf (token "*v" SPINE-JOIN 6 1)))
                                                                  (list (leaf (token "4c" SPINE-DATA 3 2))
                                                                        (leaf (token "4c" SPINE-DATA 4 2))
                                                                        (leaf (token "4c" SPINE-DATA 5 2))
                                                                        (leaf (token "*v" SPINE-JOIN 6 2))))
                                                          (leaf (token "*v" SPINE-JOIN 7 1))))
                                            (leaf (token "*-" SPINE-TERMINATOR 8 0)))))))
              (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                    (list (token "*^" SPINE-SPLIT 1 0))
                    (list (token "*" NULL-INTERPRETATION 2 0)
                          (token "*^" SPINE-SPLIT 2 1))
                    (list (token "4c" SPINE-DATA 3 0)
                          (token "4c" SPINE-DATA 3 1)
                          (token "4c" SPINE-DATA 3 2))
                    (list (token "4c" SPINE-DATA 4 0)
                          (token "4c" SPINE-DATA 4 1)
                          (token "4c" SPINE-DATA 4 2))
                    (list (token "4c" SPINE-DATA 5 0)
                          (token "4c" SPINE-DATA 5 1)
                          (token "4c" SPINE-DATA 5 2))
                    (list (token "*" NULL-INTERPRETATION 6 0)
                          (token "*v" SPINE-JOIN 6 1)
                          (token "*v" SPINE-JOIN 6 2))
                    (list (token "*v" SPINE-JOIN 7 0)
                          (token "*v" SPINE-JOIN 7 1))
                    (list (token "*-" SPINE-TERMINATOR 8 0))))
(check-expect (hfile->hgraph (path->hfile "../../data/order/spine-splits-joins-successively.krn"))
              (hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                           (parent (token "*^" SPINE-SPLIT 1 0)
                                                   (list (leaf (token "*" NULL-INTERPRETATION 2 0))
                                                         (leaf (token "4c" SPINE-DATA 3 0))
                                                         (leaf (token "4c" SPINE-DATA 4 0))
                                                         (leaf (token "4c" SPINE-DATA 5 0))
                                                         (leaf (token "*" NULL-INTERPRETATION 6 0))
                                                         (leaf (token "*v" SPINE-JOIN 7 0)))
                                                   (list (parent (token "*^" SPINE-SPLIT 2 1)
                                                                 (list (leaf (token "4c" SPINE-DATA 3 1))
                                                                       (leaf (token "4c" SPINE-DATA 4 1))
                                                                       (leaf (token "4c" SPINE-DATA 5 1))
                                                                       (leaf (token "*v" SPINE-JOIN 6 1)))
                                                                 (list (leaf (token "4c" SPINE-DATA 3 2))
                                                                       (leaf (token "4c" SPINE-DATA 4 2))
                                                                       (leaf (token "4c" SPINE-DATA 5 2))
                                                                       (leaf (token "*v" SPINE-JOIN 6 2))))
                                                         (leaf (token "*v" SPINE-JOIN 7 1))))
                                           (leaf (token "*-" SPINE-TERMINATOR 8 0)))))))
(check-expect (branch->lot (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                 (parent (token "*^" SPINE-SPLIT 1 0)
                                         (list (leaf (token "*" NULL-INTERPRETATION 2 0))
                                               (leaf (token "4c" SPINE-DATA 3 0))
                                               (leaf (token "4c" SPINE-DATA 4 0))
                                               (leaf (token "4c" SPINE-DATA 5 0))
                                               (leaf (token "*" NULL-INTERPRETATION 6 0))
                                               (leaf (token "*v" SPINE-JOIN 7 0)))
                                         (list (parent (token "*^" SPINE-SPLIT 2 1)
                                                       (list (leaf (token "4c" SPINE-DATA 3 1))
                                                             (leaf (token "4c" SPINE-DATA 4 1))
                                                             (leaf (token "4c" SPINE-DATA 5 1))
                                                             (leaf (token "*v" SPINE-JOIN 6 1)))
                                                       (list (leaf (token "4c" SPINE-DATA 3 2))
                                                             (leaf (token "4c" SPINE-DATA 4 2))
                                                             (leaf (token "4c" SPINE-DATA 5 2))
                                                             (leaf (token "*v" SPINE-JOIN 6 2))))
                                               (leaf (token "*v" SPINE-JOIN 7 1))))
                                 (leaf (token "*-" SPINE-TERMINATOR 8 0))))
              (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0)
                    (token "*^" SPINE-SPLIT 1 0)
                    (token "*" NULL-INTERPRETATION 2 0)
                    (token "4c" SPINE-DATA 3 0)
                    (token "4c" SPINE-DATA 4 0)
                    (token "4c" SPINE-DATA 5 0)
                    (token "*" NULL-INTERPRETATION 6 0)
                    (token "*v" SPINE-JOIN 7 0)
                    (token "*^" SPINE-SPLIT 2 1)
                    (token "4c" SPINE-DATA 3 1)
                    (token "4c" SPINE-DATA 4 1)
                    (token "4c" SPINE-DATA 5 1)
                    (token "*v" SPINE-JOIN 6 1)
                    (token "4c" SPINE-DATA 3 2)
                    (token "4c" SPINE-DATA 4 2)
                    (token "4c" SPINE-DATA 5 2)
                    (token "*v" SPINE-JOIN 6 2)
                    (token "*v" SPINE-JOIN 7 1)
                    (token "*-" SPINE-TERMINATOR 8 0)))
(check-expect (gspines->linked-spines (spine-parser (path->hfile "../../data/order/spine-splits-joins-successively.krn"))
                                      (path->hfile "../../data/order/spine-splits-joins-successively.krn"))
              (list (linked-spine KERN-0-0)))

(test)
