#lang racket/base

(require "../../../../parser/data-definitions/data-definitions.rkt"
         "../../../../parser/functions/file.rkt"
         "../../../../parser/functions/spine-parser.rkt"
         "../../../../parser/data-structures/humdrum-graph/data-definitions/data-definitions.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hgraph-to-hfile.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hfile-to-hgraph.rkt"
         test-engine/racket-tests)

(check-expect (path->hfile "../../data/order/spine-splits-simultaneous.krn")
              (hfile (list (record "**kern" TOKEN
                                   (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                   0)
                           (record "*^" TOKEN
                                   (list (token "*^" SPINE-SPLIT 1 0))
                                   1)
                           (record "*^\t*^" TOKEN
                                   (list (token "*^" SPINE-SPLIT 2 0)
                                         (token "*^" SPINE-SPLIT 2 1))
                                   2)
                           (record "4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 3 0)
                                         (token "4c" SPINE-DATA 3 1)
                                         (token "4c" SPINE-DATA 3 2)
                                         (token "4c" SPINE-DATA 3 3))
                                   3)
                           (record "4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 4 0)
                                         (token "4c" SPINE-DATA 4 1)
                                         (token "4c" SPINE-DATA 4 2)
                                         (token "4c" SPINE-DATA 4 3))
                                   4)
                           (record "4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 5 0)
                                         (token "4c" SPINE-DATA 5 1)
                                         (token "4c" SPINE-DATA 5 2)
                                         (token "4c" SPINE-DATA 5 3))
                                   5)
                           (record "*\t*\t*v\t*v" TOKEN
                                   (list (token "*" NULL-INTERPRETATION 6 0)
                                         (token "*" NULL-INTERPRETATION 6 1)
                                         (token "*v" SPINE-JOIN 6 2)
                                         (token "*v" SPINE-JOIN 6 3))
                                   6)
                           (record "*\t*v\t*v" TOKEN
                                   (list (token "*" NULL-INTERPRETATION 7 0)
                                         (token "*v" SPINE-JOIN 7 1)
                                         (token "*v" SPINE-JOIN 7 2))
                                   7)
                           (record "*v\t*v" TOKEN
                                   (list (token "*v" SPINE-JOIN 8 0)
                                         (token "*v" SPINE-JOIN 8 1))
                                   8)
                           (record "*-" TOKEN
                                   (list (token "*-" SPINE-TERMINATOR 9 0))
                                   9))))
(check-expect (spine-parser (path->hfile "../../data/order/spine-splits-simultaneous.krn"))
              (list (global-spine KERN
                                  (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                        (list (token "*^" SPINE-SPLIT 1 0))
                                        (list (token "*^" SPINE-SPLIT 2 0)
                                              (token "*^" SPINE-SPLIT 2 1))
                                        (list (token "4c" SPINE-DATA 3 0)
                                              (token "4c" SPINE-DATA 3 1)
                                              (token "4c" SPINE-DATA 3 2)
                                              (token "4c" SPINE-DATA 3 3))
                                        (list (token "4c" SPINE-DATA 4 0)
                                              (token "4c" SPINE-DATA 4 1)
                                              (token "4c" SPINE-DATA 4 2)
                                              (token "4c" SPINE-DATA 4 3))
                                        (list (token "4c" SPINE-DATA 5 0)
                                              (token "4c" SPINE-DATA 5 1)
                                              (token "4c" SPINE-DATA 5 2)
                                              (token "4c" SPINE-DATA 5 3))
                                        (list (token "*" NULL-INTERPRETATION 6 0)
                                              (token "*" NULL-INTERPRETATION 6 1)
                                              (token "*v" SPINE-JOIN 6 2)
                                              (token "*v" SPINE-JOIN 6 3))
                                        (list (token "*" NULL-INTERPRETATION 7 0)
                                              (token "*v" SPINE-JOIN 7 1)
                                              (token "*v" SPINE-JOIN 7 2))
                                        (list (token "*v" SPINE-JOIN 8 0)
                                              (token "*v" SPINE-JOIN 8 1))
                                        (list (token "*-" SPINE-TERMINATOR 9 0)))
                                  0)))
(check-expect (hgraph->hfile
               (hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                         (parent (token "*^" SPINE-SPLIT 1 0)
                                                 (list (parent (token "*^" SPINE-SPLIT 2 0)
                                                               (list (leaf (token "4c" SPINE-DATA 3 0))
                                                                     (leaf (token "4c" SPINE-DATA 4 0))
                                                                     (leaf (token "4c" SPINE-DATA 5 0))
                                                                     (leaf (token "*" NULL-INTERPRETATION 6 0))
                                                                     (leaf (token "*" NULL-INTERPRETATION 7 0))
                                                                     (leaf (token "*v" SPINE-JOIN 8 0)))
                                                               (list (leaf (token "4c" SPINE-DATA 3 1))
                                                                     (leaf (token "4c" SPINE-DATA 4 1))
                                                                     (leaf (token "4c" SPINE-DATA 5 1))
                                                                     (leaf (token "*" NULL-INTERPRETATION 6 1))
                                                                     (leaf (token "*v" SPINE-JOIN 7 0))))
                                                       (leaf (token "*v" SPINE-JOIN 8 0)))
                                                 (list (parent (token "*^" SPINE-SPLIT 2 1)
                                                               (list (leaf (token "4c" SPINE-DATA 3 2))
                                                                     (leaf (token "4c" SPINE-DATA 4 2))
                                                                     (leaf (token "4c" SPINE-DATA 5 2))
                                                                     (leaf (token "*v" SPINE-JOIN 6 2)))
                                                               (list (leaf (token "4c" SPINE-DATA 3 3))
                                                                     (leaf (token "4c" SPINE-DATA 4 3))
                                                                     (leaf (token "4c" SPINE-DATA 5 3))
                                                                     (leaf (token "*v" SPINE-JOIN 6 3))))
                                                       (leaf (token "*v" SPINE-JOIN 7 1))))
                                         (leaf (token "*-" SPINE-TERMINATOR 9 0)))))))
              (path->hfile "../../data/order/spine-splits-simultaneous.krn"))
(check-expect (lolot->lor (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                (list (token "*^" SPINE-SPLIT 1 0))
                                (list (token "*^" SPINE-SPLIT 2 0)
                                      (token "*^" SPINE-SPLIT 2 1))
                                (list (token "4c" SPINE-DATA 3 0)
                                      (token "4c" SPINE-DATA 3 1)
                                      (token "4c" SPINE-DATA 3 2)
                                      (token "4c" SPINE-DATA 3 3))
                                (list (token "4c" SPINE-DATA 4 0)
                                      (token "4c" SPINE-DATA 4 1)
                                      (token "4c" SPINE-DATA 4 2)
                                      (token "4c" SPINE-DATA 4 3))
                                (list (token "4c" SPINE-DATA 5 0)
                                      (token "4c" SPINE-DATA 5 1)
                                      (token "4c" SPINE-DATA 5 2)
                                      (token "4c" SPINE-DATA 5 3))
                                (list (token "*" NULL-INTERPRETATION 6 0)
                                      (token "*" NULL-INTERPRETATION 6 1)
                                      (token "*v" SPINE-JOIN 6 2)
                                      (token "*v" SPINE-JOIN 6 3))
                                (list (token "*" NULL-INTERPRETATION 7 0)
                                      (token "*v" SPINE-JOIN 7 1)
                                      (token "*v" SPINE-JOIN 7 2))
                                (list (token "*v" SPINE-JOIN 8 0)
                                      (token "*v" SPINE-JOIN 8 1))
                                (list (token "*-" SPINE-TERMINATOR 9 0))))
              (list (record "**kern" TOKEN
                            (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                            0)
                    (record "*^" TOKEN
                            (list (token "*^" SPINE-SPLIT 1 0))
                            1)
                    (record "*^\t*^" TOKEN
                            (list (token "*^" SPINE-SPLIT 2 0)
                                  (token "*^" SPINE-SPLIT 2 1))
                            2)
                    (record "4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 3 0)
                                  (token "4c" SPINE-DATA 3 1)
                                  (token "4c" SPINE-DATA 3 2)
                                  (token "4c" SPINE-DATA 3 3))
                            3)
                    (record "4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 4 0)
                                  (token "4c" SPINE-DATA 4 1)
                                  (token "4c" SPINE-DATA 4 2)
                                  (token "4c" SPINE-DATA 4 3))
                            4)
                    (record "4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 5 0)
                                  (token "4c" SPINE-DATA 5 1)
                                  (token "4c" SPINE-DATA 5 2)
                                  (token "4c" SPINE-DATA 5 3))
                            5)
                    (record "*\t*\t*v\t*v" TOKEN
                            (list (token "*" NULL-INTERPRETATION 6 0)
                                  (token "*" NULL-INTERPRETATION 6 1)
                                  (token "*v" SPINE-JOIN 6 2)
                                  (token "*v" SPINE-JOIN 6 3))
                            6)
                    (record "*\t*v\t*v" TOKEN
                            (list (token "*" NULL-INTERPRETATION 7 0)
                                  (token "*v" SPINE-JOIN 7 1)
                                  (token "*v" SPINE-JOIN 7 2))
                            7)
                    (record "*v\t*v" TOKEN
                            (list (token "*v" SPINE-JOIN 8 0)
                                  (token "*v" SPINE-JOIN 8 1))
                            8)
                    (record "*-" TOKEN
                            (list (token "*-" SPINE-TERMINATOR 9 0))
                            9)))
(check-expect (hgraph->lolot
               (hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                         (parent (token "*^" SPINE-SPLIT 1 0)
                                                 (list (parent (token "*^" SPINE-SPLIT 2 0)
                                                               (list (leaf (token "4c" SPINE-DATA 3 0))
                                                                     (leaf (token "4c" SPINE-DATA 4 0))
                                                                     (leaf (token "4c" SPINE-DATA 5 0))
                                                                     (leaf (token "*" NULL-INTERPRETATION 6 0))
                                                                     (leaf (token "*" NULL-INTERPRETATION 7 0))
                                                                     (leaf (token "*v" SPINE-JOIN 8 0)))
                                                               (list (leaf (token "4c" SPINE-DATA 3 1))
                                                                     (leaf (token "4c" SPINE-DATA 4 1))
                                                                     (leaf (token "4c" SPINE-DATA 5 1))
                                                                     (leaf (token "*" NULL-INTERPRETATION 6 1))
                                                                     (leaf (token "*v" SPINE-JOIN 7 1))))
                                                       (leaf (token "*v" SPINE-JOIN 8 0)))
                                                 (list (parent (token "*^" SPINE-SPLIT 2 1)
                                                               (list (leaf (token "4c" SPINE-DATA 3 2))
                                                                     (leaf (token "4c" SPINE-DATA 4 2))
                                                                     (leaf (token "4c" SPINE-DATA 5 2))
                                                                     (leaf (token "*v" SPINE-JOIN 6 2)))
                                                               (list (leaf (token "4c" SPINE-DATA 3 3))
                                                                     (leaf (token "4c" SPINE-DATA 4 3))
                                                                     (leaf (token "4c" SPINE-DATA 5 3))
                                                                     (leaf (token "*v" SPINE-JOIN 6 3))))
                                                       (leaf (token "*v" SPINE-JOIN 7 1))))
                                         (leaf (token "*-" SPINE-TERMINATOR 9 0)))))))
              (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                    (list (token "*^" SPINE-SPLIT 1 0))
                    (list (token "*^" SPINE-SPLIT 2 0)
                          (token "*^" SPINE-SPLIT 2 1))
                    (list (token "4c" SPINE-DATA 3 0)
                          (token "4c" SPINE-DATA 3 1)
                          (token "4c" SPINE-DATA 3 2)
                          (token "4c" SPINE-DATA 3 3))
                    (list (token "4c" SPINE-DATA 4 0)
                          (token "4c" SPINE-DATA 4 1)
                          (token "4c" SPINE-DATA 4 2)
                          (token "4c" SPINE-DATA 4 3))
                    (list (token "4c" SPINE-DATA 5 0)
                          (token "4c" SPINE-DATA 5 1)
                          (token "4c" SPINE-DATA 5 2)
                          (token "4c" SPINE-DATA 5 3))
                    (list (token "*" NULL-INTERPRETATION 6 0)
                          (token "*" NULL-INTERPRETATION 6 1)
                          (token "*v" SPINE-JOIN 6 2)
                          (token "*v" SPINE-JOIN 6 3))
                    (list (token "*" NULL-INTERPRETATION 7 0)
                          (token "*v" SPINE-JOIN 7 1)
                          (token "*v" SPINE-JOIN 7 2))
                    (list (token "*v" SPINE-JOIN 8 0)
                          (token "*v" SPINE-JOIN 8 1))
                    (list (token "*-" SPINE-TERMINATOR 9 0))))
(check-expect (hfile->hgraph (path->hfile "../../data/order/spine-splits-simultaneous.krn"))
                             (hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                                       (parent (token "*^" SPINE-SPLIT 1 0)
                                                               (list (parent (token "*^" SPINE-SPLIT 2 0)
                                                                             (list (leaf (token "4c" SPINE-DATA 3 0))
                                                                                   (leaf (token "4c" SPINE-DATA 4 0))
                                                                                   (leaf (token "4c" SPINE-DATA 5 0))
                                                                                   (leaf (token "*" NULL-INTERPRETATION 6 0))
                                                                                   (leaf (token "*" NULL-INTERPRETATION 7 0))
                                                                                   (leaf (token "*v" SPINE-JOIN 8 0)))
                                                                             (list (leaf (token "4c" SPINE-DATA 3 1))
                                                                                   (leaf (token "4c" SPINE-DATA 4 1))
                                                                                   (leaf (token "4c" SPINE-DATA 5 1))
                                                                                   (leaf (token "*" NULL-INTERPRETATION 6 1))
                                                                                   (leaf (token "*v" SPINE-JOIN 7 1))))
                                                                     (leaf (token "*v" SPINE-JOIN 8 0)))
                                                               (list (parent (token "*^" SPINE-SPLIT 2 1)
                                                                             (list (leaf (token "4c" SPINE-DATA 3 2))
                                                                                   (leaf (token "4c" SPINE-DATA 4 2))
                                                                                   (leaf (token "4c" SPINE-DATA 5 2))
                                                                                   (leaf (token "*v" SPINE-JOIN 6 2)))
                                                                             (list (leaf (token "4c" SPINE-DATA 3 3))
                                                                                   (leaf (token "4c" SPINE-DATA 4 3))
                                                                                   (leaf (token "4c" SPINE-DATA 5 3))
                                                                                   (leaf (token "*v" SPINE-JOIN 6 3))))
                                                                     (leaf (token "*v" SPINE-JOIN 7 1))))
                                                       (leaf (token "*-" SPINE-TERMINATOR 9 0)))))))
(check-expect (branch->lot (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                 (parent (token "*^" SPINE-SPLIT 1 0)
                                         (list (parent (token "*^" SPINE-SPLIT 2 0)
                                                       (list (leaf (token "4c" SPINE-DATA 3 0))
                                                             (leaf (token "4c" SPINE-DATA 4 0))
                                                             (leaf (token "4c" SPINE-DATA 5 0))
                                                             (leaf (token "*" NULL-INTERPRETATION 6 0))
                                                             (leaf (token "*" NULL-INTERPRETATION 7 0))
                                                             (leaf (token "*v" SPINE-JOIN 8 0)))
                                                       (list (leaf (token "4c" SPINE-DATA 3 1))
                                                             (leaf (token "4c" SPINE-DATA 4 1))
                                                             (leaf (token "4c" SPINE-DATA 5 1))
                                                             (leaf (token "*" NULL-INTERPRETATION 6 1))
                                                             (leaf (token "*v" SPINE-JOIN 7 1))))
                                               (leaf (token "*v" SPINE-JOIN 8 0)))
                                         (list (parent (token "*^" SPINE-SPLIT 2 1)
                                                       (list (leaf (token "4c" SPINE-DATA 3 2))
                                                             (leaf (token "4c" SPINE-DATA 4 2))
                                                             (leaf (token "4c" SPINE-DATA 5 2))
                                                             (leaf (token "*v" SPINE-JOIN 6 2)))
                                                       (list (leaf (token "4c" SPINE-DATA 3 3))
                                                             (leaf (token "4c" SPINE-DATA 4 3))
                                                             (leaf (token "4c" SPINE-DATA 5 3))
                                                             (leaf (token "*v" SPINE-JOIN 6 3))))
                                               (leaf (token "*v" SPINE-JOIN 7 1))))
                                 (leaf (token "*-" SPINE-TERMINATOR 9 0))))
              (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0)
                    (token "*^" SPINE-SPLIT 1 0)
                    (token "*^" SPINE-SPLIT 2 0)
                    (token "4c" SPINE-DATA 3 0)
                    (token "4c" SPINE-DATA 4 0)
                    (token "4c" SPINE-DATA 5 0)
                    (token "*" NULL-INTERPRETATION 6 0)
                    (token "*" NULL-INTERPRETATION 7 0)
                    (token "*v" SPINE-JOIN 8 0)
                    (token "4c" SPINE-DATA 3 1)
                    (token "4c" SPINE-DATA 4 1)
                    (token "4c" SPINE-DATA 5 1)
                    (token "*" NULL-INTERPRETATION 6 1)
                    (token "*v" SPINE-JOIN 7 1)
                    (token "*v" SPINE-JOIN 8 0)
                    (token "*^" SPINE-SPLIT 2 1)
                    (token "4c" SPINE-DATA 3 2)
                    (token "4c" SPINE-DATA 4 2)
                    (token "4c" SPINE-DATA 5 2)
                    (token "*v" SPINE-JOIN 6 2)
                    (token "4c" SPINE-DATA 3 3)
                    (token "4c" SPINE-DATA 4 3)
                    (token "4c" SPINE-DATA 5 3)
                    (token "*v" SPINE-JOIN 6 3)
                    (token "*v" SPINE-JOIN 7 1)
                    (token "*-" SPINE-TERMINATOR 9 0)))

(test)
