#lang racket/base

(require "../../../../parser/data-definitions/data-definitions.rkt"
         "../../../../parser/functions/file.rkt"
         "../../../../parser/functions/spine-parser.rkt"
         "../../../../parser/data-structures/humdrum-graph/data-definitions/data-definitions.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hgraph-to-hfile.rkt"
         "../../../../parser/data-structures/humdrum-graph/functions/hfile-to-hgraph.rkt"
         "../../../../parser/data-structures/linked-spine/functions/gspines-to-linked-spines.rkt"
         test-engine/racket-tests)

(check-expect (path->hfile "../../data/order/spine-splits-right-joins-left-c.krn")
              (hfile (list (record "**kern" TOKEN
                                   (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                   0)
                           (record "*^" TOKEN
                                   (list (token "*^" SPINE-SPLIT 1 0))
                                   1)
                           (record "*\t*^" TOKEN
                                   (list (token "*" NULL-INTERPRETATION 2 0)
                                         (token "*^" SPINE-SPLIT 2 1))
                                   2)
                           (record "*\t*\t*^" TOKEN
                                   (list (token "*" NULL-INTERPRETATION 3 0)
                                         (token "*" NULL-INTERPRETATION 3 1)
                                         (token "*^" SPINE-SPLIT 3 2))
                                   3)
                           (record "4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 4 0)
                                         (token "4c" SPINE-DATA 4 1)
                                         (token "4c" SPINE-DATA 4 2)
                                         (token "4c" SPINE-DATA 4 3))
                                   4)
                           (record "4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 5 0)
                                         (token "4c" SPINE-DATA 5 1)
                                         (token "4c" SPINE-DATA 5 2)
                                         (token "4c" SPINE-DATA 5 3))
                                   5)
                           (record "4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 6 0)
                                         (token "4c" SPINE-DATA 6 1)
                                         (token "4c" SPINE-DATA 6 2)
                                         (token "4c" SPINE-DATA 6 3))
                                   6)
                           (record "*v\t*v\t*\t*" TOKEN
                                   (list (token "*v" SPINE-JOIN 7 0)
                                         (token "*v" SPINE-JOIN 7 1)
                                         (token "*" NULL-INTERPRETATION 7 2)
                                         (token "*" NULL-INTERPRETATION 7 3))
                                   7)
                           (record "4a\t4b\t4c" TOKEN
                                   (list (token "4a" SPINE-DATA 8 0)
                                         (token "4b" SPINE-DATA 8 1)
                                         (token "4c" SPINE-DATA 8 2))
                                   8)
                           (record "4c\t4d\t4e" TOKEN
                                   (list (token "4c" SPINE-DATA 9 0)
                                         (token "4d" SPINE-DATA 9 1)
                                         (token "4e" SPINE-DATA 9 2))
                                   9)
                           (record "*v\t*v\t*" TOKEN
                                   (list (token "*v" SPINE-JOIN 10 0)
                                         (token "*v" SPINE-JOIN 10 1)
                                         (token "*" NULL-INTERPRETATION 10 2))
                                   10)
                           (record "4e\t4f" TOKEN
                                   (list (token "4e" SPINE-DATA 11 0)
                                         (token "4f" SPINE-DATA 11 1))
                                   11)
                           (record "*v\t*v" TOKEN
                                   (list (token "*v" SPINE-JOIN 12 0)
                                         (token "*v" SPINE-JOIN 12 1))
                                   12)
                           (record "*-" TOKEN
                                   (list (token "*-" SPINE-TERMINATOR 13 0))
                                   13))))
(check-expect (spine-parser (path->hfile "../../data/order/spine-splits-right-joins-left-c.krn"))
              (list (global-spine KERN
                                  (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                        (list (token "*^" SPINE-SPLIT 1 0))
                                        (list (token "*" NULL-INTERPRETATION 2 0)
                                              (token "*^" SPINE-SPLIT 2 1))
                                        (list (token "*" NULL-INTERPRETATION 3 0)
                                              (token "*" NULL-INTERPRETATION 3 1)
                                              (token "*^" SPINE-SPLIT 3 2))
                                        (list (token "4c" SPINE-DATA 4 0)
                                              (token "4c" SPINE-DATA 4 1)
                                              (token "4c" SPINE-DATA 4 2)
                                              (token "4c" SPINE-DATA 4 3))
                                        (list (token "4c" SPINE-DATA 5 0)
                                              (token "4c" SPINE-DATA 5 1)
                                              (token "4c" SPINE-DATA 5 2)
                                              (token "4c" SPINE-DATA 5 3))
                                        (list (token "4c" SPINE-DATA 6 0)
                                              (token "4c" SPINE-DATA 6 1)
                                              (token "4c" SPINE-DATA 6 2)
                                              (token "4c" SPINE-DATA 6 3))
                                        (list (token "*v" SPINE-JOIN 7 0)
                                              (token "*v" SPINE-JOIN 7 1)
                                              (token "*" NULL-INTERPRETATION 7 2)
                                              (token "*" NULL-INTERPRETATION 7 3))
                                        (list (token "4a" SPINE-DATA 8 0)
                                              (token "4b" SPINE-DATA 8 1)
                                              (token "4c" SPINE-DATA 8 2))
                                        (list (token "4c" SPINE-DATA 9 0)
                                              (token "4d" SPINE-DATA 9 1)
                                              (token "4e" SPINE-DATA 9 2))
                                        (list (token "*v" SPINE-JOIN 10 0)
                                              (token "*v" SPINE-JOIN 10 1)
                                              (token "*" NULL-INTERPRETATION 10 2))
                                        (list (token "4e" SPINE-DATA 11 0)
                                              (token "4f" SPINE-DATA 11 1))
                                        (list (token "*v" SPINE-JOIN 12 0)
                                              (token "*v" SPINE-JOIN 12 1))
                                        (list (token "*-" SPINE-TERMINATOR 13 0)))
                                  0)))
(check-expect (hgraph->hfile (hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                                       (parent (token "*^" SPINE-SPLIT 1 0)
                                                               (list (leaf (token "*" NULL-INTERPRETATION 2 0))
                                                                     (leaf (token "*" NULL-INTERPRETATION 3 0))
                                                                     (leaf (token "4c" SPINE-DATA 4 0))
                                                                     (leaf (token "4c" SPINE-DATA 5 0))
                                                                     (leaf (token "4c" SPINE-DATA 6 0))
                                                                     (leaf (token "*v" SPINE-JOIN 7 0)))
                                                               (list (parent (token "*^" SPINE-SPLIT 2 1)
                                                                             (list (leaf (token "*" NULL-INTERPRETATION 3 1))
                                                                                   (leaf (token "4c" SPINE-DATA 4 1))
                                                                                   (leaf (token "4c" SPINE-DATA 5 1))
                                                                                   (leaf (token "4c" SPINE-DATA 6 1))
                                                                                   (leaf (token "*v" SPINE-JOIN 7 1)))
                                                                             (list (parent (token "*^" SPINE-SPLIT 3 2)
                                                                                           (list (leaf (token "4c" SPINE-DATA 4 2))
                                                                                                 (leaf (token "4c" SPINE-DATA 5 2))
                                                                                                 (leaf (token "4c" SPINE-DATA 6 2))
                                                                                                 (leaf (token "*" NULL-INTERPRETATION 7 2))
                                                                                                 (leaf (token "4a" SPINE-DATA 8 2))
                                                                                                 (leaf (token "4c" SPINE-DATA 9 2))
                                                                                                 (leaf (token "*v" SPINE-JOIN 1 20)))
                                                                                           (list (leaf (token "4c" SPINE-DATA 4 3))
                                                                                                 (leaf (token "4c" SPINE-DATA 5 3))
                                                                                                 (leaf (token "4c" SPINE-DATA 6 3))
                                                                                                 (leaf (token "*" NULL-INTERPRETATION 7 3))
                                                                                                 (leaf (token "4b" SPINE-DATA 8 3))
                                                                                                 (leaf (token "4d" SPINE-DATA 9 3))
                                                                                                 (leaf (token "*v" SPINE-JOIN 10 3))))
                                                                                   (leaf (token "4e" SPINE-DATA 11 2))
                                                                                   (leaf (token "*v" SPINE-JOIN 12 2))))
                                                                     (leaf (token "4c" SPINE-DATA 8 1))
                                                                     (leaf (token "4e" SPINE-DATA 9 1))
                                                                     (leaf (token "*" NULL-INTERPRETATION 10 1))
                                                                     (leaf (token "4f" SPINE-DATA 11 1))
                                                                     (leaf (token "*v" SPINE-JOIN 12 1))))
                                                       (leaf (token "*-" SPINE-TERMINATOR 13 0)))))))
              (path->hfile "../../data/order/spine-splits-right-joins-left-c.krn"))
(check-expect (lolot->lor (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                (list (token "*^" SPINE-SPLIT 1 0))
                                (list (token "*" NULL-INTERPRETATION 2 0)
                                      (token "*^" SPINE-SPLIT 2 1))
                                (list (token "*" NULL-INTERPRETATION 3 0)
                                      (token "*" NULL-INTERPRETATION 3 1)
                                      (token "*^" SPINE-SPLIT 3 2))
                                (list (token "4c" SPINE-DATA 4 0)
                                      (token "4c" SPINE-DATA 4 1)
                                      (token "4c" SPINE-DATA 4 2)
                                      (token "4c" SPINE-DATA 4 3))
                                (list (token "4c" SPINE-DATA 5 0)
                                      (token "4c" SPINE-DATA 5 1)
                                      (token "4c" SPINE-DATA 5 2)
                                      (token "4c" SPINE-DATA 5 3))
                                (list (token "4c" SPINE-DATA 6 0)
                                      (token "4c" SPINE-DATA 6 1)
                                      (token "4c" SPINE-DATA 6 2)
                                      (token "4c" SPINE-DATA 6 3))
                                (list (token "*v" SPINE-JOIN 7 0)
                                      (token "*v" SPINE-JOIN 7 1)
                                      (token "*" NULL-INTERPRETATION 7 2)
                                      (token "*" NULL-INTERPRETATION 7 3))
                                (list (token "4a" SPINE-DATA 8 0)
                                      (token "4b" SPINE-DATA 8 1)
                                      (token "4c" SPINE-DATA 8 2))
                                (list (token "4c" SPINE-DATA 9 0)
                                      (token "4d" SPINE-DATA 9 1)
                                      (token "4e" SPINE-DATA 9 2))
                                (list (token "*v" SPINE-JOIN 10 0)
                                      (token "*v" SPINE-JOIN 10 1)
                                      (token "*" NULL-INTERPRETATION 10 2))
                                (list (token "4e" SPINE-DATA 11 0)
                                      (token "4f" SPINE-DATA 11 1))
                                (list (token "*v" SPINE-JOIN 12 0)
                                      (token "*v" SPINE-JOIN 12 1))
                                (list (token "*-" SPINE-TERMINATOR 13 0))))
              (list (record "**kern" TOKEN
                            (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                            0)
                    (record "*^" TOKEN
                            (list (token "*^" SPINE-SPLIT 1 0))
                            1)
                    (record "*\t*^" TOKEN
                            (list (token "*" NULL-INTERPRETATION 2 0)
                                  (token "*^" SPINE-SPLIT 2 1))
                            2)
                    (record "*\t*\t*^" TOKEN
                            (list (token "*" NULL-INTERPRETATION 3 0)
                                  (token "*" NULL-INTERPRETATION 3 1)
                                  (token "*^" SPINE-SPLIT 3 2))
                            3)
                    (record "4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 4 0)
                                  (token "4c" SPINE-DATA 4 1)
                                  (token "4c" SPINE-DATA 4 2)
                                  (token "4c" SPINE-DATA 4 3))
                            4)
                    (record "4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 5 0)
                                  (token "4c" SPINE-DATA 5 1)
                                  (token "4c" SPINE-DATA 5 2)
                                  (token "4c" SPINE-DATA 5 3))
                            5)
                    (record "4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 6 0)
                                  (token "4c" SPINE-DATA 6 1)
                                  (token "4c" SPINE-DATA 6 2)
                                  (token "4c" SPINE-DATA 6 3))
                            6)
                    (record "*v\t*v\t*\t*" TOKEN
                            (list (token "*v" SPINE-JOIN 7 0)
                                  (token "*v" SPINE-JOIN 7 1)
                                  (token "*" NULL-INTERPRETATION 7 2)
                                  (token "*" NULL-INTERPRETATION 7 3))
                            7)
                    (record "4a\t4b\t4c" TOKEN
                            (list (token "4a" SPINE-DATA 8 0)
                                  (token "4b" SPINE-DATA 8 1)
                                  (token "4c" SPINE-DATA 8 2))
                            8)
                    (record "4c\t4d\t4e" TOKEN
                            (list (token "4c" SPINE-DATA 9 0)
                                  (token "4d" SPINE-DATA 9 1)
                                  (token "4e" SPINE-DATA 9 2))
                            9)
                    (record "*v\t*v\t*" TOKEN
                            (list (token "*v" SPINE-JOIN 10 0)
                                  (token "*v" SPINE-JOIN 10 1)
                                  (token "*" NULL-INTERPRETATION 10 2))
                            10)
                    (record "4e\t4f" TOKEN
                            (list (token "4e" SPINE-DATA 11 0)
                                  (token "4f" SPINE-DATA 11 1))
                            11)
                    (record "*v\t*v" TOKEN
                            (list (token "*v" SPINE-JOIN 12 0)
                                  (token "*v" SPINE-JOIN 12 1))
                            12)
                    (record "*-" TOKEN
                            (list (token "*-" SPINE-TERMINATOR 13 0))
                            13)))
(check-expect (hgraph->lolot (hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                                       (parent (token "*^" SPINE-SPLIT 1 0)
                                                               (list (leaf (token "*" NULL-INTERPRETATION 2 0))
                                                                     (leaf (token "*" NULL-INTERPRETATION 3 0))
                                                                     (leaf (token "4c" SPINE-DATA 4 0))
                                                                     (leaf (token "4c" SPINE-DATA 5 0))
                                                                     (leaf (token "4c" SPINE-DATA 6 0))
                                                                     (leaf (token "*v" SPINE-JOIN 7 0)))
                                                               (list (parent (token "*^" SPINE-SPLIT 2 1)
                                                                             (list (leaf (token "*" NULL-INTERPRETATION 3 1))
                                                                                   (leaf (token "4c" SPINE-DATA 4 1))
                                                                                   (leaf (token "4c" SPINE-DATA 5 1))
                                                                                   (leaf (token "4c" SPINE-DATA 6 1))
                                                                                   (leaf (token "*v" SPINE-JOIN 7 1)))
                                                                             (list (parent (token "*^" SPINE-SPLIT 3 2)
                                                                                           (list (leaf (token "4c" SPINE-DATA 4 2))
                                                                                                 (leaf (token "4c" SPINE-DATA 5 2))
                                                                                                 (leaf (token "4c" SPINE-DATA 6 2))
                                                                                                 (leaf (token "*" NULL-INTERPRETATION 7 2))
                                                                                                 (leaf (token "4a" SPINE-DATA 8 2))
                                                                                                 (leaf (token "4c" SPINE-DATA 9 2))
                                                                                                 (leaf (token "*v" SPINE-JOIN 1 20)))
                                                                                           (list (leaf (token "4c" SPINE-DATA 4 3))
                                                                                                 (leaf (token "4c" SPINE-DATA 5 3))
                                                                                                 (leaf (token "4c" SPINE-DATA 6 3))
                                                                                                 (leaf (token "*" NULL-INTERPRETATION 7 3))
                                                                                                 (leaf (token "4b" SPINE-DATA 8 3))
                                                                                                 (leaf (token "4d" SPINE-DATA 9 3))
                                                                                                 (leaf (token "*v" SPINE-JOIN 10 3))))
                                                                                   (leaf (token "4e" SPINE-DATA 11 2))
                                                                                   (leaf (token "*v" SPINE-JOIN 12 2))))
                                                                     (leaf (token "4c" SPINE-DATA 8 1))
                                                                     (leaf (token "4e" SPINE-DATA 9 1))
                                                                     (leaf (token "*" NULL-INTERPRETATION 10 1))
                                                                     (leaf (token "4f" SPINE-DATA 11 1))
                                                                     (leaf (token "*v" SPINE-JOIN 12 1))))
                                                       (leaf (token "*-" SPINE-TERMINATOR 13 0)))))))
              (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                    (list (token "*^" SPINE-SPLIT 1 0))
                    (list (token "*" NULL-INTERPRETATION 2 0)
                          (token "*^" SPINE-SPLIT 2 1))
                    (list (token "*" NULL-INTERPRETATION 3 0)
                          (token "*" NULL-INTERPRETATION 3 1)
                          (token "*^" SPINE-SPLIT 3 2))
                    (list (token "4c" SPINE-DATA 4 0)
                          (token "4c" SPINE-DATA 4 1)
                          (token "4c" SPINE-DATA 4 2)
                          (token "4c" SPINE-DATA 4 3))
                    (list (token "4c" SPINE-DATA 5 0)
                          (token "4c" SPINE-DATA 5 1)
                          (token "4c" SPINE-DATA 5 2)
                          (token "4c" SPINE-DATA 5 3))
                    (list (token "4c" SPINE-DATA 6 0)
                          (token "4c" SPINE-DATA 6 1)
                          (token "4c" SPINE-DATA 6 2)
                          (token "4c" SPINE-DATA 6 3))
                    (list (token "*v" SPINE-JOIN 7 0)
                          (token "*v" SPINE-JOIN 7 1)
                          (token "*" NULL-INTERPRETATION 7 2)
                          (token "*" NULL-INTERPRETATION 7 3))
                    (list (token "4a" SPINE-DATA 8 0)
                          (token "4b" SPINE-DATA 8 1)
                          (token "4c" SPINE-DATA 8 2))
                    (list (token "4c" SPINE-DATA 9 0)
                          (token "4d" SPINE-DATA 9 1)
                          (token "4e" SPINE-DATA 9 2))
                    (list (token "*v" SPINE-JOIN 10 0)
                          (token "*v" SPINE-JOIN 10 1)
                          (token "*" NULL-INTERPRETATION 10 2))
                    (list (token "4e" SPINE-DATA 11 0)
                          (token "4f" SPINE-DATA 11 1))
                    (list (token "*v" SPINE-JOIN 12 0)
                          (token "*v" SPINE-JOIN 12 1))
                    (list (token "*-" SPINE-TERMINATOR 13 0))))
(check-expect (hfile->hgraph (path->hfile "../../data/order/spine-splits-right-joins-left-c.krn"))
              (hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                        (parent (token "*^" SPINE-SPLIT 1 0)
                                                (list (leaf (token "*" NULL-INTERPRETATION 2 0))
                                                      (leaf (token "*" NULL-INTERPRETATION 3 0))
                                                      (leaf (token "4c" SPINE-DATA 4 0))
                                                      (leaf (token "4c" SPINE-DATA 5 0))
                                                      (leaf (token "4c" SPINE-DATA 6 0))
                                                      (leaf (token "*v" SPINE-JOIN 7 0)))
                                                (list (parent (token "*^" SPINE-SPLIT 2 1)
                                                              (list (leaf (token "*" NULL-INTERPRETATION 3 1))
                                                                    (leaf (token "4c" SPINE-DATA 4 1))
                                                                    (leaf (token "4c" SPINE-DATA 5 1))
                                                                    (leaf (token "4c" SPINE-DATA 6 1))
                                                                    (leaf (token "*v" SPINE-JOIN 7 1)))
                                                              (list (parent (token "*^" SPINE-SPLIT 3 2)
                                                                            (list (leaf (token "4c" SPINE-DATA 4 2))
                                                                                  (leaf (token "4c" SPINE-DATA 5 2))
                                                                                  (leaf (token "4c" SPINE-DATA 6 2))
                                                                                  (leaf (token "*" NULL-INTERPRETATION 7 2))
                                                                                  (leaf (token "4a" SPINE-DATA 8 2))
                                                                                  (leaf (token "4c" SPINE-DATA 9 2))
                                                                                  (leaf (token "*v" SPINE-JOIN 1 20)))
                                                                            (list (leaf (token "4c" SPINE-DATA 4 3))
                                                                                  (leaf (token "4c" SPINE-DATA 5 3))
                                                                                  (leaf (token "4c" SPINE-DATA 6 3))
                                                                                  (leaf (token "*" NULL-INTERPRETATION 7 3))
                                                                                  (leaf (token "4b" SPINE-DATA 8 3))
                                                                                  (leaf (token "4d" SPINE-DATA 9 3))
                                                                                  (leaf (token "*v" SPINE-JOIN 10 3))))
                                                                    (leaf (token "4e" SPINE-DATA 11 2))
                                                                    (leaf (token "*v" SPINE-JOIN 12 2))))
                                                      (leaf (token "4c" SPINE-DATA 8 1))
                                                      (leaf (token "4e" SPINE-DATA 9 1))
                                                      (leaf (token "*" NULL-INTERPRETATION 10 1))
                                                      (leaf (token "4f" SPINE-DATA 11 1))
                                                      (leaf (token "*v" SPINE-JOIN 12 1))))
                                        (leaf (token "*-" SPINE-TERMINATOR 13 0)))))))
(check-expect (branch->lot (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0 0))
                                 (parent (token "*^" SPINE-SPLIT 1 0)
                                         (list (leaf (token "*" NULL-INTERPRETATION 2 0))
                                               (leaf (token "*" NULL-INTERPRETATION 3 0))
                                               (leaf (token "4c" SPINE-DATA 4 0))
                                               (leaf (token "4c" SPINE-DATA 5 0))
                                               (leaf (token "4c" SPINE-DATA 6 0))
                                               (leaf (token "*v" SPINE-JOIN 7 0)))
                                         (list (parent (token "*^" SPINE-SPLIT 2 1)
                                                       (list (leaf (token "*" NULL-INTERPRETATION 3 1))
                                                             (leaf (token "4c" SPINE-DATA 4 1))
                                                             (leaf (token "4c" SPINE-DATA 5 1))
                                                             (leaf (token "4c" SPINE-DATA 6 1))
                                                             (leaf (token "*v" SPINE-JOIN 7 1)))
                                                       (list (parent (token "*^" SPINE-SPLIT 3 2)
                                                                     (list (leaf (token "4c" SPINE-DATA 4 2))
                                                                           (leaf (token "4c" SPINE-DATA 5 2))
                                                                           (leaf (token "4c" SPINE-DATA 6 2))
                                                                           (leaf (token "*" NULL-INTERPRETATION 7 2))
                                                                           (leaf (token "4a" SPINE-DATA 8 2))
                                                                           (leaf (token "4c" SPINE-DATA 9 2))
                                                                           (leaf (token "*v" SPINE-JOIN 10 2)))
                                                                     (list (leaf (token "4c" SPINE-DATA 4 3))
                                                                           (leaf (token "4c" SPINE-DATA 5 3))
                                                                           (leaf (token "4c" SPINE-DATA 6 3))
                                                                           (leaf (token "*" NULL-INTERPRETATION 7 3))
                                                                           (leaf (token "4b" SPINE-DATA 8 3))
                                                                           (leaf (token "4d" SPINE-DATA 9 3))
                                                                           (leaf (token "*v" SPINE-JOIN 10 3))))
                                                             (leaf (token "4e" SPINE-DATA 11 2))
                                                             (leaf (token "*v" SPINE-JOIN 12 2))))
                                               (leaf (token "4c" SPINE-DATA 8 1))
                                               (leaf (token "4e" SPINE-DATA 9 1))
                                               (leaf (token "*" NULL-INTERPRETATION 10 1))
                                               (leaf (token "4f" SPINE-DATA 11 1))
                                               (leaf (token "*v" SPINE-JOIN 12 1))))
                                 (leaf (token "*-" SPINE-TERMINATOR 13 0))))
              (list (token"**kern" EXCLUSIVE-INTERPRETATION 0 0)
                    (token "*^" SPINE-SPLIT 1 0)
                    (token "*" NULL-INTERPRETATION 2 0)
                    (token "*" NULL-INTERPRETATION 3 0)
                    (token "4c" SPINE-DATA 4 0)
                    (token "4c" SPINE-DATA 5 0)
                    (token "4c" SPINE-DATA 6 0)
                    (token "*v" SPINE-JOIN 7 0)
                    (token "*^" SPINE-SPLIT 2 1)
                    (token "*" NULL-INTERPRETATION 3 1)
                    (token "4c" SPINE-DATA 4 1)
                    (token "4c" SPINE-DATA 5 1)
                    (token "4c" SPINE-DATA 6 1)
                    (token "*v" SPINE-JOIN 7 1)
                    (token "*^" SPINE-SPLIT 3 2)
                    (token "4c" SPINE-DATA 4 2)
                    (token "4c" SPINE-DATA 5 2)
                    (token "4c" SPINE-DATA 6 2)
                    (token "*" NULL-INTERPRETATION 7 2)
                    (token "4a" SPINE-DATA 8 2)
                    (token "4c" SPINE-DATA 9 2)
                    (token "*v" SPINE-JOIN 10 2)
                    (token "4c" SPINE-DATA 4 3)
                    (token "4c" SPINE-DATA 5 3)
                    (token "4c" SPINE-DATA 6 3)
                    (token "*" NULL-INTERPRETATION 7 3)
                    (token "4b" SPINE-DATA 8 3)
                    (token "4d" SPINE-DATA 9 3)
                    (token "*v" SPINE-JOIN 10 3)
                    (token "4e" SPINE-DATA 11 2)
                    (token "*v" SPINE-JOIN 12 2)
                    (token "4c" SPINE-DATA 8 1)
                    (token "4e" SPINE-DATA 9 1)
                    (token "*" NULL-INTERPRETATION 10 1)
                    (token "4f" SPINE-DATA 11 1)
                    (token "*v" SPINE-JOIN 12 1)
                    (token "*-" SPINE-TERMINATOR 13 0)))
(check-expect (gspines->linked-spines empty) empty)

(test)
