#lang racket/base

(require "../../../../parser/data-definitions/data-definitions.rkt"
         "../../../../parser/functions/file.rkt"
         "../../../../parser/functions/spine-parser.rkt"
         "../../../../data-structures/abstract-humdrum-graph/data-definitions/data-definitions.rkt"
         "../../../../data-structures/abstract-humdrum-graph/functions/ab-hgraph-to-hfile.rkt"
         "../../../../data-structures/abstract-humdrum-graph/functions/hfile-to-ab-hgraph.rkt"
         test-engine/racket-tests
         racket/list) ; TODO remove

(check-expect (path->hfile "../../data/order/two-spines-split-simultaneously.krn")
              (hfile (list (record "**kern\t**kern" TOKEN
                                   (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                                         (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                   0)
                           (record "*^\t*^" TOKEN
                                   (list (token "*^" SPINE-SPLIT 1)
                                         (token "*^" SPINE-SPLIT 1))
                                   1)
                           (record "4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 2)
                                         (token "4c" SPINE-DATA 2)
                                         (token "4c" SPINE-DATA 2)
                                         (token "4c" SPINE-DATA 2))
                                   2)
                           (record "4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 3)
                                         (token "4c" SPINE-DATA 3)
                                         (token "4c" SPINE-DATA 3)
                                         (token "4c" SPINE-DATA 3))
                                   3)
                           (record "4c\t4c\t4c\t4c" TOKEN
                                   (list (token "4c" SPINE-DATA 4)
                                         (token "4c" SPINE-DATA 4)
                                         (token "4c" SPINE-DATA 4)
                                         (token "4c" SPINE-DATA 4))
                                   4)
                           (record "*\t*\t*v\t*v" TOKEN
                                   (list (token "*" NULL-INTERPRETATION 5)
                                         (token "*" NULL-INTERPRETATION 5)
                                         (token "*v" SPINE-JOIN 5)
                                         (token "*v" SPINE-JOIN 5))
                                   5)
                           (record "*v\t*v\t*" TOKEN
                                   (list (token "*v" SPINE-JOIN 6)
                                         (token "*v" SPINE-JOIN 6)
                                         (token "*" NULL-INTERPRETATION 6))
                                   6)
                           (record "*-\t*-" TOKEN
                                   (list (token "*-" SPINE-TERMINATOR 7)
                                         (token "*-" SPINE-TERMINATOR 7))
                                   7))))
(check-expect (spine-parser (path->hfile "../../data/order/two-spines-split-simultaneously.krn"))
              (list (global-spine KERN
                                  (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                        (list (token "*^" SPINE-SPLIT 1))
                                        (list (token "4c" SPINE-DATA 2)
                                              (token "4c" SPINE-DATA 2))
                                        (list (token "4c" SPINE-DATA 3)
                                              (token "4c" SPINE-DATA 3))
                                        (list (token "4c" SPINE-DATA 4)
                                              (token "4c" SPINE-DATA 4))
                                        (list (token "*" NULL-INTERPRETATION 5)
                                              (token "*" NULL-INTERPRETATION 5))
                                        (list (token "*v" SPINE-JOIN 6)
                                              (token "*v" SPINE-JOIN 6))
                                        (list (token "*-" SPINE-TERMINATOR 7)))
                                  0)
                    (global-spine KERN
                                  (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                        (list (token "*^" SPINE-SPLIT 1))
                                        (list (token "4c" SPINE-DATA 2)
                                              (token "4c" SPINE-DATA 2))
                                        (list (token "4c" SPINE-DATA 3)
                                              (token "4c" SPINE-DATA 3))
                                        (list (token "4c" SPINE-DATA 4)
                                              (token "4c" SPINE-DATA 4))
                                        (list (token "*v" SPINE-JOIN 5)
                                              (token "*v" SPINE-JOIN 5))
                                        (list (token "*" NULL-INTERPRETATION 6))
                                        (list (token "*-" SPINE-TERMINATOR 7)))
                                  1)))
(check-expect (ab-hgraph->hfile
               (ab-hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                            (parent (token "*^" SPINE-SPLIT 1)
                                                    (list (leaf (token "4c" SPINE-DATA 2))
                                                          (leaf (token "4c" SPINE-DATA 3))
                                                          (leaf (token "4c" SPINE-DATA 4))
                                                          (leaf (token "*" NULL-INTERPRETATION 5))
                                                          (leaf (token "*v" SPINE-JOIN 6)))
                                                    (list (leaf (token "4c" SPINE-DATA 2))
                                                          (leaf (token "4c" SPINE-DATA 3))
                                                          (leaf (token "4c" SPINE-DATA 4))
                                                          (leaf (token "*" NULL-INTERPRETATION 5))
                                                          (leaf (token "*v" SPINE-JOIN 6))))
                                            (leaf (token "*-" SPINE-TERMINATOR 7)))
                                      (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                            (parent (token "*^" SPINE-SPLIT 1)
                                                    (list (leaf (token "4c" SPINE-DATA 2))
                                                          (leaf (token "4c" SPINE-DATA 3))
                                                          (leaf (token "4c" SPINE-DATA 4))
                                                          (leaf (token "*v" SPINE-JOIN 5)))
                                                    (list (leaf (token "4c" SPINE-DATA 2))
                                                          (leaf (token "4c" SPINE-DATA 3))
                                                          (leaf (token "4c" SPINE-DATA 4))
                                                          (leaf (token "*v" SPINE-JOIN 5))))
                                            (leaf (token "*" NULL-INTERPRETATION 6))
                                            (leaf (token "*-" SPINE-TERMINATOR 7)))))))
              (path->hfile "../../data/order/two-spines-split-simultaneously.krn"))
(check-expect (lolot->lor (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                                      (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                (list (token "*^" SPINE-SPLIT 1)
                                      (token "*^" SPINE-SPLIT 1))
                                (list (token "4c" SPINE-DATA 2)
                                      (token "4c" SPINE-DATA 2)
                                      (token "4c" SPINE-DATA 2)
                                      (token "4c" SPINE-DATA 2))
                                (list (token "4c" SPINE-DATA 3)
                                      (token "4c" SPINE-DATA 3)
                                      (token "4c" SPINE-DATA 3)
                                      (token "4c" SPINE-DATA 3))
                                (list (token "4c" SPINE-DATA 4)
                                      (token "4c" SPINE-DATA 4)
                                      (token "4c" SPINE-DATA 4)
                                      (token "4c" SPINE-DATA 4))
                                (list (token "*" NULL-INTERPRETATION 5)
                                      (token "*" NULL-INTERPRETATION 5)
                                      (token "*v" SPINE-JOIN 5)
                                      (token "*v" SPINE-JOIN 5))
                                (list (token "*v" SPINE-JOIN 6)
                                      (token "*v" SPINE-JOIN 6)
                                      (token "*" NULL-INTERPRETATION 6))
                                (list (token "*-" SPINE-TERMINATOR 7)
                                      (token "*-" SPINE-TERMINATOR 7))))
              (list (record "**kern\t**kern" TOKEN
                            (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                                  (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                            0)
                    (record "*^\t*^" TOKEN
                            (list (token "*^" SPINE-SPLIT 1)
                                  (token "*^" SPINE-SPLIT 1))
                            1)
                    (record "4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 2)
                                  (token "4c" SPINE-DATA 2)
                                  (token "4c" SPINE-DATA 2)
                                  (token "4c" SPINE-DATA 2))
                            2)
                    (record "4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 3)
                                  (token "4c" SPINE-DATA 3)
                                  (token "4c" SPINE-DATA 3)
                                  (token "4c" SPINE-DATA 3))
                            3)
                    (record "4c\t4c\t4c\t4c" TOKEN
                            (list (token "4c" SPINE-DATA 4)
                                  (token "4c" SPINE-DATA 4)
                                  (token "4c" SPINE-DATA 4)
                                  (token "4c" SPINE-DATA 4))
                            4)
                    (record "*\t*\t*v\t*v" TOKEN
                            (list (token "*" NULL-INTERPRETATION 5)
                                  (token "*" NULL-INTERPRETATION 5)
                                  (token "*v" SPINE-JOIN 5)
                                  (token "*v" SPINE-JOIN 5))
                            5)
                    (record "*v\t*v\t*" TOKEN
                            (list (token "*v" SPINE-JOIN 6)
                                  (token "*v" SPINE-JOIN 6)
                                  (token "*" NULL-INTERPRETATION 6))
                            6)
                    (record "*-\t*-" TOKEN
                            (list (token "*-" SPINE-TERMINATOR 7)
                                  (token "*-" SPINE-TERMINATOR 7))
                            7)))
(check-expect (ab-hgraph->lolot
               (ab-hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                            (parent (token "*^" SPINE-SPLIT 1)
                                                    (list (leaf (token "4c" SPINE-DATA 2))
                                                          (leaf (token "4c" SPINE-DATA 3))
                                                          (leaf (token "4c" SPINE-DATA 4))
                                                          (leaf (token "*" NULL-INTERPRETATION 5))
                                                          (leaf (token "*v" SPINE-JOIN 6)))
                                                    (list (leaf (token "4c" SPINE-DATA 2))
                                                          (leaf (token "4c" SPINE-DATA 3))
                                                          (leaf (token "4c" SPINE-DATA 4))
                                                          (leaf (token "*" NULL-INTERPRETATION 5))
                                                          (leaf (token "*v" SPINE-JOIN 6))))
                                            (leaf (token "*-" SPINE-TERMINATOR 7)))
                                      (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                            (parent (token "*^" SPINE-SPLIT 1)
                                                    (list (leaf (token "4c" SPINE-DATA 2))
                                                          (leaf (token "4c" SPINE-DATA 3))
                                                          (leaf (token "4c" SPINE-DATA 4))
                                                          (leaf (token "*v" SPINE-JOIN 5)))
                                                    (list (leaf (token "4c" SPINE-DATA 2))
                                                          (leaf (token "4c" SPINE-DATA 3))
                                                          (leaf (token "4c" SPINE-DATA 4))
                                                          (leaf (token "*v" SPINE-JOIN 5))))
                                            (leaf (token "*" NULL-INTERPRETATION 6))
                                            (leaf (token "*-" SPINE-TERMINATOR 7)))))))
              (list (list (token "**kern" EXCLUSIVE-INTERPRETATION 0)
                          (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                    (list (token "*^" SPINE-SPLIT 1)
                          (token "*^" SPINE-SPLIT 1))
                    (list (token "4c" SPINE-DATA 2)
                          (token "4c" SPINE-DATA 2)
                          (token "4c" SPINE-DATA 2)
                          (token "4c" SPINE-DATA 2))
                    (list (token "4c" SPINE-DATA 3)
                          (token "4c" SPINE-DATA 3)
                          (token "4c" SPINE-DATA 3)
                          (token "4c" SPINE-DATA 3))
                    (list (token "4c" SPINE-DATA 4)
                          (token "4c" SPINE-DATA 4)
                          (token "4c" SPINE-DATA 4)
                          (token "4c" SPINE-DATA 4))
                    (list (token "*" NULL-INTERPRETATION 5)
                          (token "*" NULL-INTERPRETATION 5)
                          (token "*v" SPINE-JOIN 5)
                          (token "*v" SPINE-JOIN 5))
                    (list (token "*v" SPINE-JOIN 6)
                          (token "*v" SPINE-JOIN 6)
                          (token "*" NULL-INTERPRETATION 6))
                    (list (token "*-" SPINE-TERMINATOR 7)
                          (token "*-" SPINE-TERMINATOR 7))))
(check-expect (hfile->ab-hgraph
               (path->hfile "../../data/order/two-spines-split-simultaneously.krn")
               ab-hgraph)
              (ab-hgraph (root (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                           (parent (token "*^" SPINE-SPLIT 1)
                                                   (list (leaf (token "4c" SPINE-DATA 2))
                                                         (leaf (token "4c" SPINE-DATA 3))
                                                         (leaf (token "4c" SPINE-DATA 4))
                                                         (leaf (token "*" NULL-INTERPRETATION 5))
                                                         (leaf (token "*v" SPINE-JOIN 6)))
                                                   (list (leaf (token "4c" SPINE-DATA 2))
                                                         (leaf (token "4c" SPINE-DATA 3))
                                                         (leaf (token "4c" SPINE-DATA 4))
                                                         (leaf (token "*" NULL-INTERPRETATION 5))
                                                         (leaf (token "*v" SPINE-JOIN 6))))
                                           (leaf (token "*-" SPINE-TERMINATOR 7)))
                                     (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                           (parent (token "*^" SPINE-SPLIT 1)
                                                   (list (leaf (token "4c" SPINE-DATA 2))
                                                         (leaf (token "4c" SPINE-DATA 3))
                                                         (leaf (token "4c" SPINE-DATA 4))
                                                         (leaf (token "*v" SPINE-JOIN 5)))
                                                   (list (leaf (token "4c" SPINE-DATA 2))
                                                         (leaf (token "4c" SPINE-DATA 3))
                                                         (leaf (token "4c" SPINE-DATA 4))
                                                         (leaf (token "*v" SPINE-JOIN 5))))
                                           (leaf (token "*" NULL-INTERPRETATION 6))
                                           (leaf (token "*-" SPINE-TERMINATOR 7)))))))
; branch->lot for spine 0
(check-expect (branch->lot (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                 (parent (token "*^" SPINE-SPLIT 1)
                                         (list (leaf (token "4c" SPINE-DATA 2))
                                               (leaf (token "4c" SPINE-DATA 3))
                                               (leaf (token "4c" SPINE-DATA 4))
                                               (leaf (token "*" NULL-INTERPRETATION 5))
                                               (leaf (token "*v" SPINE-JOIN 6)))
                                         (list (leaf (token "4c" SPINE-DATA 2))
                                               (leaf (token "4c" SPINE-DATA 3))
                                               (leaf (token "4c" SPINE-DATA 4))
                                               (leaf (token "*" NULL-INTERPRETATION 5))
                                               (leaf (token "*v" SPINE-JOIN 6))))
                                 (leaf (token "*-" SPINE-TERMINATOR 7))))
              (list (token"**kern" EXCLUSIVE-INTERPRETATION 0)
                    (token "*^" SPINE-SPLIT 1)
                    (token "4c" SPINE-DATA 2)
                    (token "4c" SPINE-DATA 3)
                    (token "4c" SPINE-DATA 4)
                    (token "*" NULL-INTERPRETATION 5)
                    (token "*v" SPINE-JOIN 6)
                    (token "4c" SPINE-DATA 2)
                    (token "4c" SPINE-DATA 3)
                    (token "4c" SPINE-DATA 4)
                    (token "*" NULL-INTERPRETATION 5)
                    (token "*v" SPINE-JOIN 6)
                    (token "*-" SPINE-TERMINATOR 7)))
; branch->lot for spine 1
(check-expect (branch->lot (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                                 (parent (token "*^" SPINE-SPLIT 1)
                                         (list (leaf (token "4c" SPINE-DATA 2))
                                               (leaf (token "4c" SPINE-DATA 3))
                                               (leaf (token "4c" SPINE-DATA 4))
                                               (leaf (token "*v" SPINE-JOIN 5)))
                                         (list (leaf (token "4c" SPINE-DATA 2))
                                               (leaf (token "4c" SPINE-DATA 3))
                                               (leaf (token "4c" SPINE-DATA 4))
                                               (leaf (token "*v" SPINE-JOIN 5))))
                                 (leaf (token "*" NULL-INTERPRETATION 6))
                                 (leaf (token "*-" SPINE-TERMINATOR 7))))
              (list (token"**kern" EXCLUSIVE-INTERPRETATION 0)
                    (token "*^" SPINE-SPLIT 1)
                    (token "4c" SPINE-DATA 2)
                    (token "4c" SPINE-DATA 3)
                    (token "4c" SPINE-DATA 4)
                    (token "*v" SPINE-JOIN 5)
                    (token "4c" SPINE-DATA 2)
                    (token "4c" SPINE-DATA 3)
                    (token "4c" SPINE-DATA 4)
                    (token "*v" SPINE-JOIN 5)
                    (token "*" NULL-INTERPRETATION 6)
                    (token "*-" SPINE-TERMINATOR 7)))

(test)
