#lang racket

#|
	Tests for TandemInterpretation.
|#

(require "../../parser/TandemInterpretation.rkt"
         test-engine/racket-tests)

; tandem-interpretation?
(check-expect (tandem-interpretation? "*above") #t)
(check-expect (tandem-interpretation? "*8va") #t)
(check-expect (tandem-interpretation? "*below") #t)
(check-expect (tandem-interpretation? "*brackettup") #t)
(check-expect (tandem-interpretation? "*tupbreak") #t)
(check-expect (tandem-interpretation? "*kcancel") #t)
(check-expect (tandem-interpretation? "*center") #t)
(check-expect (tandem-interpretation? "*clefF4") #t)
(check-expect (tandem-interpretation? "*clefG2") #t)
(check-expect (tandem-interpretation? "*clefC1") #t)
(check-expect (tandem-interpretation? "*cue") #t)
(check-expect (tandem-interpretation? "*X8va") #t)
(check-expect (tandem-interpretation? "*Xbrackettup") #t)
(check-expect (tandem-interpretation? "*Xflip") #t)
(check-expect (tandem-interpretation? "*Xlig") #t)
(check-expect (tandem-interpretation? "*Xtuplet") #t)
(check-expect (tandem-interpretation? "*X8ba") #t)
(check-expect (tandem-interpretation? "*Xped") #t)
(check-expect (tandem-interpretation? "*Xtremolo") #t)
(check-expect (tandem-interpretation? "*>[A,A,B]") #t)
(check-expect (tandem-interpretation? "*flip") #t)
(check-expect (tandem-interpretation? "*grp:A") #t)
(check-expect (tandem-interpretation? "*group1") #t)
(check-expect (tandem-interpretation? "*mI") #t)
(check-expect (tandem-interpretation? "*oI") #t)
(check-expect (tandem-interpretation? "*A-:") #t)
(check-expect (tandem-interpretation? "*F#:") #t)
(check-expect (tandem-interpretation? "*c:") #t)
(check-expect (tandem-interpretation? "*k[f#c#g#]") #t)
(check-expect (tandem-interpretation? "*k[b-e-]") #t)
(check-expect (tandem-interpretation? "*k[]") #t)
(check-expect (tandem-interpretation? "*lig") #t)
(check-expect (tandem-interpretation? "*MM100") #t)
(check-expect (tandem-interpretation? "*") #t)
(check-expect (tandem-interpretation? "*tuplet") #t)
(check-expect (tandem-interpretation? "*8ba") #t)
(check-expect (tandem-interpretation? "*part1") #t)
(check-expect (tandem-interpretation? "*ped") #t)
(check-expect (tandem-interpretation? "*rscale:1/4") #t)
(check-expect (tandem-interpretation? "*v") #t)
(check-expect (tandem-interpretation? "*^") #t)
(check-expect (tandem-interpretation? "*-") #t)
(check-expect (tandem-interpretation? "*staff1") #t)
(check-expect (tandem-interpretation? "*M4/4") #t)
(check-expect (tandem-interpretation? "*M12/8") #t)
(check-expect (tandem-interpretation? "*tremolo") #t)
(check-expect (tandem-interpretation? "**kern") #f)
(check-expect (tandem-interpretation? "!!!REF: Reference record") #f)
(check-expect (tandem-interpretation? "!! Global comment") #f)
(check-expect (tandem-interpretation? "!\t! Local comment\t!") #f)

; tandem-interpretation-match?
(check-expect (tandem-interpretation-match? 'AboveStaff "*above") #t)
(check-expect (tandem-interpretation-match? 'AllaOttava "*8va") #t)
(check-expect (tandem-interpretation-match? 'BelowStaff "*below") #t)
(check-expect (tandem-interpretation-match? 'BracketTuplet "*brackettup") #t)
(check-expect (tandem-interpretation-match? 'BreakTuplet "*tupbreak") #t)
(check-expect (tandem-interpretation-match? 'CancelKeySignature "*kcancel") #t)
(check-expect (tandem-interpretation-match? 'CenterStaff "*center") #t)
(check-expect (tandem-interpretation-match? 'Clef "*clefF4") #t)
(check-expect (tandem-interpretation-match? 'Clef "*clefG2") #t)
(check-expect (tandem-interpretation-match? 'Clef "*clefC1") #t)
(check-expect (tandem-interpretation-match? 'CueSizedNotes "*cue") #t)
(check-expect (tandem-interpretation-match? 'EndAllaOttava "*X8va") #t)
(check-expect (tandem-interpretation-match? 'EndBracketTuplet "*Xbrackettup") #t)
(check-expect (tandem-interpretation-match? 'EndFlipSubspines "*Xflip") #t)
(check-expect (tandem-interpretation-match? 'EndLigatureBracket "*Xlig") #t)
(check-expect (tandem-interpretation-match? 'EndNumberTuplet "*Xtuplet") #t)
(check-expect (tandem-interpretation-match? 'EndOttavaBassa "*X8ba") #t)
(check-expect (tandem-interpretation-match? 'EndPedalMarking "*Xped") #t)
(check-expect (tandem-interpretation-match? 'EndTremolo "*Xtremolo") #t)
(check-expect (tandem-interpretation-match? 'ExpansionList "*>[A,A,B]") #t)
(check-expect (tandem-interpretation-match? 'FlipSubspines "*flip") #t)
(check-expect (tandem-interpretation-match? 'GroupAttribution "*grp:A") #t)
(check-expect (tandem-interpretation-match? 'GroupNumber "*group1") #t)
(check-expect (tandem-interpretation-match? 'InstrumentClass "*mI") #t)
(check-expect (tandem-interpretation-match? 'InstrumentClass "*oI") #t)
(check-expect (tandem-interpretation-match? 'KeyLabel "*A-:") #t)
(check-expect (tandem-interpretation-match? 'KeyLabel "*F#:") #t)
(check-expect (tandem-interpretation-match? 'KeyLabel "*c:") #t)
(check-expect (tandem-interpretation-match? 'KeySignature "*k[f#c#g#]") #t)
(check-expect (tandem-interpretation-match? 'KeySignature "*k[b-e-]") #t)
(check-expect (tandem-interpretation-match? 'KeySignature "*k[]") #t)
(check-expect (tandem-interpretation-match? 'LigatureBracket "*lig") #t)
(check-expect (tandem-interpretation-match? 'MetronomeMarking "*MM100") #t)
(check-expect (tandem-interpretation-match? 'NullInterpretation "*") #t)
(check-expect (tandem-interpretation-match? 'NumberTuplet "*tuplet") #t)
(check-expect (tandem-interpretation-match? 'OttavaBassa "*8ba") #t)
(check-expect (tandem-interpretation-match? 'PartNumber "*part1") #t)
(check-expect (tandem-interpretation-match? 'PedalMarking "*ped") #t)
(check-expect (tandem-interpretation-match? 'RhythmicScalingFactor "*rscale:1/4") #t)
(check-expect (tandem-interpretation-match? 'SpineJoin "*v") #t)
(check-expect (tandem-interpretation-match? 'SpineSplit "*^") #t)
(check-expect (tandem-interpretation-match? 'SpineTerminator "*-") #t)
(check-expect (tandem-interpretation-match? 'StaffNumber "*staff1") #t)
(check-expect (tandem-interpretation-match? 'TimeSignature "*M4/4") #t)
(check-expect (tandem-interpretation-match? 'TimeSignature "*M12/8") #t)
(check-expect (tandem-interpretation-match? 'Tremolo "*tremolo") #t)
(check-expect (tandem-interpretation-match? 'SpineJoin "*^") #f)
(check-expect (tandem-interpretation-match? 'SpineSplit "*") #f)

; type-tandem
(check-expect (type-tandem "*above") 'AboveStaff)
(check-expect (type-tandem "*8va") 'AllaOttava)
(check-expect (type-tandem "*below") 'BelowStaff)
(check-expect (type-tandem "*brackettup") 'BracketTuplet)
(check-expect (type-tandem "*tupbreak") 'BreakTuplet)
(check-expect (type-tandem "*kcancel") 'CancelKeySignature)
(check-expect (type-tandem "*center") 'CenterStaff)
(check-expect (type-tandem "*clefF4") 'Clef)
(check-expect (type-tandem "*clefG2") 'Clef)
(check-expect (type-tandem "*clefC1") 'Clef)
(check-expect (type-tandem "*cue") 'CueSizedNotes)
(check-expect (type-tandem "*X8va") 'EndAllaOttava)
(check-expect (type-tandem "*Xbrackettup") 'EndBracketTuplet)
(check-expect (type-tandem "*Xflip") 'EndFlipSubspines)
(check-expect (type-tandem "*Xlig") 'EndLigatureBracket)
(check-expect (type-tandem "*Xtuplet") 'EndNumberTuplet)
(check-expect (type-tandem "*X8ba") 'EndOttavaBassa)
(check-expect (type-tandem "*Xped") 'EndPedalMarking)
(check-expect (type-tandem "*Xtremolo") 'EndTremolo)
(check-expect (type-tandem "*>[A,A,B]") 'ExpansionList)
(check-expect (type-tandem "*flip") 'FlipSubspines)
(check-expect (type-tandem "*grp:A") 'GroupAttribution)
(check-expect (type-tandem "*group1") 'GroupNumber)
(check-expect (type-tandem "*mI") 'InstrumentClass)
(check-expect (type-tandem "*oI") 'InstrumentClass)
(check-expect (type-tandem "*A-:") 'KeyLabel)
(check-expect (type-tandem "*F#:") 'KeyLabel)
(check-expect (type-tandem "*c:") 'KeyLabel)
(check-expect (type-tandem "*k[f#c#g#]") 'KeySignature)
(check-expect (type-tandem "*k[b-e-]") 'KeySignature)
(check-expect (type-tandem "*k[]") 'KeySignature)
(check-expect (type-tandem "*lig") 'LigatureBracket)
(check-expect (type-tandem "*MM100") 'MetronomeMarking)
(check-expect (type-tandem "*") 'NullInterpretation)
(check-expect (type-tandem "*tuplet") 'NumberTuplet)
(check-expect (type-tandem "*8ba") 'OttavaBassa)
(check-expect (type-tandem "*part1") 'PartNumber)
(check-expect (type-tandem "*ped") 'PedalMarking)
(check-expect (type-tandem "*rscale:1/4") 'RhythmicScalingFactor)
(check-expect (type-tandem "*v") 'SpineJoin)
(check-expect (type-tandem "*^") 'SpineSplit)
(check-expect (type-tandem "*-") 'SpineTerminator)
(check-expect (type-tandem "*staff1") 'StaffNumber)
(check-expect (type-tandem "*M4/4") 'TimeSignature)
(check-expect (type-tandem "*M12/8") 'TimeSignature)
(check-expect (type-tandem "*tremolo") 'Tremolo)
(check-expect (type-tandem "*tandem") 'Unknown)

(test)
