#lang racket

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; hum-parser: data-structures: AbstractHumdrumGraph
;;   tests for hfile->ab-hgraph
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(require
  "../../../parser/data-definitions/data-definitions.rkt"
  (only-in "../../../parser/functions/file.rkt" path->hfile)
  "../../../data-structures/abstract-humdrum-graph/data-definitions/data-definitions.rkt"
  "../../../data-structures/abstract-humdrum-graph/functions/hfile-to-ab-hgraph.rkt"
  test-engine/racket-tests)

(define one-spine-no-splits    "../data/one-spine-no-splits.krn")
(define one-spine-one-split    "../data/one-spine-one-split.krn")
(define one-spine-two-splits   "../data/one-spine-two-splits.krn")
(define two-spines-no-splits   "../data/two-spines-no-splits.krn")
(define two-spines-one-splits  "../data/two-spines-one-splits.krn")
(define two-spines-both-split  "../data/two-spines-both-split.krn")
(define three-spines-two-splits-not-consecutive
  "../data/three-spines-two-splits-not-consecutive.krn")
(define three-spines-two-splits-not-consecutive-2
  "../data/three-spines-two-splits-not-consecutive-2.krn")
(define four-cases             "../data/four-cases.krn")
(define parent-scriabin        "../data/parent-scriabin-op11_no02.krn")

(define one-spine-no-splits-hfile    (path->hfile one-spine-no-splits))
(define one-spine-one-split-hfile    (path->hfile one-spine-one-split))
(define one-spine-two-splits-hfile   (path->hfile one-spine-two-splits))
(define two-spines-no-splits-hfile   (path->hfile two-spines-no-splits))
(define two-spines-one-splits-hfile  (path->hfile two-spines-one-splits))
(define two-spines-both-split-hfile  (path->hfile two-spines-both-split))
(define three-spines-two-splits-not-consecutive-hfile
  (path->hfile three-spines-two-splits-not-consecutive))
(define three-spines-two-splits-not-consecutive-2-hfile
  (path->hfile three-spines-two-splits-not-consecutive-2))
(define four-cases-hfile             (path->hfile four-cases))
(define parent-scriabin-hfile        (path->hfile parent-scriabin))

; hfile->ab-hgraph
(check-expect (hfile->ab-hgraph one-spine-no-splits-hfile ab-hgraph)
              (ab-hgraph
               (root
                (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                            (leaf (token "*clefG2" CLEF 1))
                            (leaf (token "*k[]" KEY-SIG 2))
                            (leaf (token "*a:" KEY-LABEL 3))
                            (leaf (token "*M1/4" TIME-SIG 4))
                            (leaf (token "4a" SPINE-DATA 5))
                            (leaf (token "=2" MEASURE 6))
                            (leaf (token "4b" SPINE-DATA 7))
                            (leaf (token "=3" MEASURE 8))
                            (leaf (token "4a" SPINE-DATA 9))
                            (leaf (token "==" MEASURE 10))
                            (leaf (token "*-" SPINE-TERMINATOR 11)))))))
(check-expect (hfile->ab-hgraph one-spine-one-split-hfile ab-hgraph)
              (ab-hgraph
               (root
                (list (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                            (leaf (token "*clefG2" CLEF 1))
                            (leaf (token "*k[]" KEY-SIG 2))
                            (leaf (token "*a:" KEY-LABEL 3))
                            (leaf (token "*M1/4" TIME-SIG 4))
                            (leaf (token "4a" SPINE-DATA 5))
                            (leaf (token "=2" MEASURE 6))
                            (parent (token "*^" SPINE-SPLIT 7)
                                    (list (leaf (token "4b" SPINE-DATA 8))
                                          (leaf (token "=3" MEASURE 9))
                                          (leaf (token "4a" SPINE-DATA 10))
                                          (leaf (token "*v" SPINE-JOIN 11)))
                                    (list (leaf (token "4bb" SPINE-DATA 8))
                                          (leaf (token "=3" MEASURE 9))
                                          (leaf (token "4aa" SPINE-DATA 10))
                                          (leaf (token "*v" SPINE-JOIN 11))))
                            (leaf (token "==" MEASURE 12))
                            (leaf (token "*-" SPINE-TERMINATOR 13)))))))
(check-expect
  (hfile->ab-hgraph one-spine-two-splits-hfile ab-hgraph)
  (ab-hgraph
    (root
      (list
        (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
              (leaf (token "*clefG2" CLEF 1))
              (leaf (token "*k[]" KEY-SIG 2))
              (leaf (token "*a:" KEY-LABEL 3))
              (leaf (token "*M1/4" TIME-SIG 4))
              (parent (token "*^" SPINE-SPLIT 5)
                      (list (leaf (token "4a" SPINE-DATA 6))
                            (leaf (token "=2" MEASURE 7))
                            (leaf (token "*" NULL-INTERPRETATION 8))
                            (leaf (token "4b" SPINE-DATA 9))
                            (leaf (token "=3" MEASURE 10))
                            (leaf (token "4a" SPINE-DATA 11))
                            (leaf (token "*" NULL-INTERPRETATION 12))
                            (leaf (token "*v" SPINE-JOIN 13)))
                      (list (leaf (token "4aa" SPINE-DATA 6))
                            (leaf (token "=2" MEASURE 7))
                            (parent (token "*^" SPINE-SPLIT 8)
                                    (list (leaf (token "4bb" SPINE-DATA 9))
                                          (leaf (token "=3" MEASURE 10))
                                          (leaf (token "4aa" SPINE-DATA 11))
                                          (leaf (token "*v" SPINE-JOIN 12)))
                                    (list (leaf (token "4bbb" SPINE-DATA 9))
                                          (leaf (token "=3" MEASURE 10))
                                          (leaf (token "4aaa" SPINE-DATA 11))
                                          (leaf (token "*v" SPINE-JOIN 12))))
                            (leaf (token "*v" SPINE-JOIN 13))))
              (leaf (token "==" MEASURE 14))
              (leaf (token "*-" SPINE-TERMINATOR 15)))))))
(check-expect (hfile->ab-hgraph two-spines-no-splits-hfile ab-hgraph)
              (ab-hgraph
                (root
                  (list
                    (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                          (leaf (token "*clefG2" CLEF 1))
                          (leaf (token "*k[]" KEY-SIG 2))
                          (leaf (token "*a:" KEY-LABEL 3))
                          (leaf (token "*M1/4" TIME-SIG 4))
                          (leaf (token "4a" SPINE-DATA 5))
                          (leaf (token "=2" MEASURE 6))
                          (leaf (token "4b" SPINE-DATA 7))
                          (leaf (token "=3" MEASURE 8))
                          (leaf (token "4a" SPINE-DATA 9))
                          (leaf (token "==" MEASURE 10))
                          (leaf (token "*-" SPINE-TERMINATOR 11)))
                    (list (leaf (token "**dynam" EXCLUSIVE-INTERPRETATION 0))
                          (leaf (token "*" NULL-INTERPRETATION 1))
                          (leaf (token "*" NULL-INTERPRETATION 2))
                          (leaf (token "*" NULL-INTERPRETATION 3))
                          (leaf (token "*" NULL-INTERPRETATION 4))
                          (leaf (token "p" SPINE-DATA 5))
                          (leaf (token "=2" MEASURE 6))
                          (leaf (token "f" SPINE-DATA 7))
                          (leaf (token "=3" MEASURE 8))
                          (leaf (token "." NULL-SPINE-DATA 9))
                          (leaf (token "==" MEASURE 10))
                          (leaf (token "*-" SPINE-TERMINATOR 11)))))))
(check-expect (hfile->ab-hgraph two-spines-one-splits-hfile ab-hgraph)
              (ab-hgraph
                (root
                  (list
                    (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
                          (leaf (token "*clefG2" CLEF 1))
                          (leaf (token "*k[]" KEY-SIG 2))
                          (leaf (token "*a:" KEY-LABEL 3))
                          (leaf (token "*M1/4" TIME-SIG 4))
                          (leaf (token "4a" SPINE-DATA 5))
                          (leaf (token "=2" MEASURE 6))
                          (parent (token "*^" SPINE-SPLIT 7)
                                  (list (leaf (token "4b" SPINE-DATA 8))
                                        (leaf (token "=3" MEASURE 9))
                                        (leaf (token "4a" SPINE-DATA 10))
                                        (leaf (token "*v" SPINE-JOIN 11)))
                                  (list (leaf (token "4bb" SPINE-DATA 8))
                                        (leaf (token "=3" MEASURE 9))
                                        (leaf (token "4aa" SPINE-DATA 10))
                                        (leaf (token "*v" SPINE-JOIN 11))))
                          (leaf (token "==" MEASURE 12))
                          (leaf (token "*-" SPINE-TERMINATOR 13)))
                    (list (leaf (token "**dynam" EXCLUSIVE-INTERPRETATION 0))
                          (leaf (token "*" NULL-INTERPRETATION 1))
                          (leaf (token "*" NULL-INTERPRETATION 2))
                          (leaf (token "*" NULL-INTERPRETATION 3))
                          (leaf (token "*" NULL-INTERPRETATION 4))
                          (leaf (token "p" SPINE-DATA 5))
                          (leaf (token "=2" MEASURE 6))
                          (leaf (token "*" NULL-INTERPRETATION 7))
                          (leaf (token "f" SPINE-DATA 8))
                          (leaf (token "=3" MEASURE 9))
                          (leaf (token "." NULL-SPINE-DATA 10))
                          (leaf (token "*" NULL-INTERPRETATION 11))
                          (leaf (token "==" MEASURE 12))
                          (leaf (token "*-" SPINE-TERMINATOR 13)))))))
(check-expect
  (hfile->ab-hgraph two-spines-both-split-hfile ab-hgraph)
  (ab-hgraph
    (root
      (list
        (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
              (leaf (token "*clefG2" CLEF 1))
              (leaf (token "*k[]" KEY-SIG 2))
              (leaf (token "*a:" KEY-LABEL 3))
              (leaf (token "*M1/4" TIME-SIG 4))
              (leaf (token "*" NULL-INTERPRETATION 5))
              (leaf (token "4a" SPINE-DATA 6))
              (leaf (token "=2" MEASURE 7))
              (parent (token "*^" SPINE-SPLIT 8)
                      (list (leaf (token "4b" SPINE-DATA 9))
                            (leaf (token "=3" MEASURE 10))
                            (leaf (token "4a" SPINE-DATA 11))
                            (leaf (token "*" NULL-INTERPRETATION 12))
                            (leaf (token "*v" SPINE-JOIN 13)))
                      (list (leaf (token "4bb" SPINE-DATA 9))
                            (leaf (token "=3" MEASURE 10))
                            (leaf (token "4aa" SPINE-DATA 11))
                            (leaf (token "*" NULL-INTERPRETATION 12))
                            (leaf (token "*v" SPINE-JOIN 13))))
              (leaf (token "==" MEASURE 14))
              (leaf (token "*-" SPINE-TERMINATOR 15)))
        (list (leaf (token "**dynam" EXCLUSIVE-INTERPRETATION 0))
              (leaf (token "*" NULL-INTERPRETATION 1))
              (leaf (token "*" NULL-INTERPRETATION 2))
              (leaf (token "*" NULL-INTERPRETATION 3))
              (leaf (token "*" NULL-INTERPRETATION 4))
              (parent (token "*^" SPINE-SPLIT 5)
                      (list (leaf (token "p" SPINE-DATA 6))
                            (leaf (token "=2" MEASURE 7))
                            (leaf (token "*" NULL-INTERPRETATION 8))
                            (leaf (token "f" SPINE-DATA 9))
                            (leaf (token "=3" MEASURE 10))
                            (leaf (token "." NULL-SPINE-DATA 11))
                            (leaf (token "*v" SPINE-JOIN 12)))
                      (list (leaf (token "pp" SPINE-DATA 6))
                            (leaf (token "=2" MEASURE 7))
                            (leaf (token "*" NULL-INTERPRETATION 8))
                            (leaf (token "ff" SPINE-DATA 9))
                            (leaf (token "=3" MEASURE 10))
                            (leaf (token "ff" SPINE-DATA 11))
                            (leaf (token "*v" SPINE-JOIN 12))))
              (leaf (token "*" NULL-INTERPRETATION 13))
              (leaf (token "==" MEASURE 14))
              (leaf (token "*-" SPINE-TERMINATOR 15)))))))
(check-expect
  (hfile->ab-hgraph three-spines-two-splits-not-consecutive-hfile
                    ab-hgraph)
  (ab-hgraph
    (root
      (list
        (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
              (leaf (token "*staff2" STAFF-NUMBER 1))
              (leaf (token "*Ipiano" INSTRUMENT-CLASS 2))
              (leaf (token "*clefF4" CLEF 3))
              (leaf (token "*k[]" KEY-SIG 4))
              (leaf (token "*a:" KEY-LABEL 5))
              (leaf (token "*M3/4" TIME-SIG 6))
              (leaf (token "=33" MEASURE 7))
              (parent (token "*^" SPINE-SPLIT 8)
                      (list (leaf (token "4E" SPINE-DATA 9))
                            (leaf (token "." NULL-SPINE-DATA 10))
                            (leaf (token "4D" SPINE-DATA 11))
                            (leaf (token "." NULL-SPINE-DATA 12))
                            (leaf (token "[4C#X" SPINE-DATA 13))
                            (leaf (token "." NULL-SPINE-DATA 14))
                            (leaf (token "=34" MEASURE 15))
                            (leaf (token "2.C#] 2.B]" SPINE-DATA 16))
                            (leaf (token "." NULL-SPINE-DATA 17))
                            (leaf (token "." NULL-SPINE-DATA 18))
                            (leaf (token "." NULL-SPINE-DATA 19))
                            (leaf (token "." NULL-SPINE-DATA 20))
                            (leaf (token "." NULL-SPINE-DATA 21))
                            (leaf (token "=35" MEASURE 22))
                            (leaf (token "*" NULL-INTERPRETATION 23))
                            (leaf (token "4E" SPINE-DATA 24))
                            (leaf (token "4D" SPINE-DATA 25))
                            (leaf (token "." NULL-SPINE-DATA 26))
                            (leaf (token "[4C#X" SPINE-DATA 27))
                            (leaf (token "." NULL-SPINE-DATA 28))
                            (leaf (token "=36" MEASURE 29))
                            (leaf (token "2.C#] 2.B]" SPINE-DATA 30))
                            (leaf (token "." NULL-SPINE-DATA 31))
                            (leaf (token "." NULL-SPINE-DATA 32))
                            (leaf (token "." NULL-SPINE-DATA 33))
                            (leaf (token "." NULL-SPINE-DATA 34))
                            (leaf (token "*" NULL-INTERPRETATION 35))
                            (leaf (token "=37" MEASURE 36))
                            (parent (token "*^" SPINE-SPLIT 37)
                                    (list
                                      (leaf (token "2.D\\" SPINE-DATA 38))
                                      (leaf (token "." NULL-SPINE-DATA 39))
                                      (leaf (token "." NULL-SPINE-DATA 40))
                                      (leaf (token "." NULL-SPINE-DATA 41))
                                      (leaf (token "." NULL-SPINE-DATA 42))
                                      (leaf (token "=38" MEASURE 43))
                                      (leaf (token "2.D\\" SPINE-DATA 44))
                                      (leaf (token "." NULL-SPINE-DATA 45))
                                      (leaf (token "." NULL-SPINE-DATA 46))
                                      (leaf (token "." NULL-SPINE-DATA 47))
                                      (leaf (token "." NULL-SPINE-DATA 48))
                                      (leaf (token "*" NULL-INTERPRETATION 49))
                                      (leaf (token "*v" SPINE-JOIN 50)))
                                    (list
                                      (leaf (token "2B" SPINE-DATA 38))
                                      (leaf (token "." NULL-SPINE-DATA 39))
                                      (leaf (token "." NULL-SPINE-DATA 40))
                                      (leaf (token "." NULL-SPINE-DATA 41))
                                      (leaf (token "4B-X" SPINE-DATA 42))
                                      (leaf (token "=38" MEASURE 43))
                                      (leaf (token "4A" SPINE-DATA 44))
                                      (leaf (token "." NULL-SPINE-DATA 45))
                                      (leaf (token "2c" SPINE-DATA 46))
                                      (leaf (token "." NULL-SPINE-DATA 47))
                                      (leaf (token "." NULL-SPINE-DATA 48))
                                      (leaf (token "*v" SPINE-JOIN 49))))
                            (leaf (token "*v" SPINE-JOIN 50)))
                      (list (leaf (token "[2.B" SPINE-DATA 9))
                            (leaf (token "." NULL-SPINE-DATA 10))
                            (leaf (token "." NULL-SPINE-DATA 11))
                            (leaf (token "." NULL-SPINE-DATA 12))
                            (leaf (token "." NULL-SPINE-DATA 13))
                            (leaf (token "." NULL-SPINE-DATA 14))
                            (leaf (token "=34" MEASURE 15))
                            (leaf (token "4g" SPINE-DATA 16))
                            (leaf (token "." NULL-SPINE-DATA 17))
                            (leaf (token "4e" SPINE-DATA 18))
                            (leaf (token "." NULL-SPINE-DATA 19))
                            (leaf (token "4r" SPINE-DATA 20))
                            (leaf (token "." NULL-SPINE-DATA 21))
                            (leaf (token "=35" MEASURE 22))
                            (leaf (token "*" NULL-INTERPRETATION 23))
                            (leaf (token "4r" SPINE-DATA 24))
                            (leaf (token "8r" SPINE-DATA 25))
                            (leaf (token "8G" SPINE-DATA 26))
                            (leaf (token "8A#XL" SPINE-DATA 27))
                            (leaf (token "[8BJ" SPINE-DATA 28))
                            (leaf (token "=36" MEASURE 29))
                            (leaf (token "4.g" SPINE-DATA 30))
                            (leaf (token "." NULL-SPINE-DATA 31))
                            (leaf (token "8f#X" SPINE-DATA 32))
                            (leaf (token "8f#L" SPINE-DATA 33))
                            (leaf (token "8eJ" SPINE-DATA 34))
                            (leaf (token "*" NULL-INTERPRETATION 35))
                            (leaf (token "=37" MEASURE 36))
                            (leaf (token "*" NULL-INTERPRETATION 37))
                            (leaf (token "4d" SPINE-DATA 38))
                            (leaf (token "." NULL-SPINE-DATA 39))
                            (leaf (token "[2g" SPINE-DATA 40))
                            (leaf (token "." NULL-SPINE-DATA 41))
                            (leaf (token "." NULL-SPINE-DATA 42))
                            (leaf (token "=38" MEASURE 43))
                            (leaf (token "4g]" SPINE-DATA 44))
                            (leaf (token "." NULL-SPINE-DATA 45))
                            (leaf (token "4g" SPINE-DATA 46))
                            (leaf (token "." NULL-SPINE-DATA 47))
                            (leaf (token "4f#X" SPINE-DATA 48))
                            (leaf (token "*v" SPINE-JOIN 49))))
              (leaf (token "==" MEASURE 51))
              (leaf (token "*-" SPINE-TERMINATOR 52)))
        (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
              (leaf (token "*staff1" STAFF-NUMBER 1))
              (leaf (token "*Ipiano" INSTRUMENT-CLASS 2))
              (leaf (token "*clefG2" CLEF 3))
              (leaf (token "*k[]" KEY-SIG 4))
              (leaf (token "*a:" KEY-LABEL 5))
              (leaf (token "*M3/4" TIME-SIG 6))
              (leaf (token "=33" MEASURE 7))
              (leaf (token "*" NULL-INTERPRETATION 8))
              (leaf (token "8r" SPINE-DATA 9))
              (leaf (token "8f#XL" SPINE-DATA 10))
              (leaf (token "8a" SPINE-DATA 11))
              (leaf (token "8g" SPINE-DATA 12))
              (leaf (token "8b" SPINE-DATA 13))
              (leaf (token "8eeJ" SPINE-DATA 14))
              (leaf (token "=34" MEASURE 15))
              (leaf (token "8ccc#XL" SPINE-DATA 16))
              (leaf (token "8bbJ" SPINE-DATA 17))
              (leaf (token "8r" SPINE-DATA 18))
              (leaf (token "8ff#X" SPINE-DATA 19))
              (leaf (token "8aaL" SPINE-DATA 20))
              (leaf (token "8ggJ" SPINE-DATA 21))
              (leaf (token "=35" MEASURE 22))
              (parent (token "*^" SPINE-SPLIT 23)
                      (list (leaf (token "2.g" SPINE-DATA 24))
                            (leaf (token "." NULL-SPINE-DATA 25))
                            (leaf (token "." NULL-SPINE-DATA 26))
                            (leaf (token "." NULL-SPINE-DATA 27))
                            (leaf (token "." NULL-SPINE-DATA 28))
                            (leaf (token "=36" MEASURE 29))
                            (leaf (token "2.b" SPINE-DATA 30))
                            (leaf (token "." NULL-SPINE-DATA 31))
                            (leaf (token "." NULL-SPINE-DATA 32))
                            (leaf (token "." NULL-SPINE-DATA 33))
                            (leaf (token "." NULL-SPINE-DATA 34))
                            (leaf (token "*v" SPINE-JOIN 35)))
                      (list (leaf (token "2ff#X" SPINE-DATA 24))
                            (leaf (token "." NULL-SPINE-DATA 25))
                            (leaf (token "." NULL-SPINE-DATA 26))
                            (leaf (token "4ee" SPINE-DATA 27))
                            (leaf (token "." NULL-SPINE-DATA 28))
                            (leaf (token "=36" MEASURE 29))
                            (leaf (token "4dd#X" SPINE-DATA 30))
                            (leaf (token "4ee" SPINE-DATA 31))
                            (leaf (token "." NULL-SPINE-DATA 32))
                            (leaf (token "4gg" SPINE-DATA 33))
                            (leaf (token "." NULL-SPINE-DATA 34))
                            (leaf (token "*v" SPINE-JOIN 35))))
              (leaf (token "=37" MEASURE 36))
              (leaf (token "*" NULL-INTERPRETATION 37))
              (leaf (token "8ff#XL" SPINE-DATA 38))
              (leaf (token "8aa" SPINE-DATA 39))
              (leaf (token "8gg" SPINE-DATA 40))
              (leaf (token "8ddJ" SPINE-DATA 41))
              (leaf (token "[4dd#X" SPINE-DATA 42))
              (leaf (token "=38" MEASURE 43))
              (leaf (token "8dd#L]" SPINE-DATA 44))
              (leaf (token "8ff#X" SPINE-DATA 45))
              (leaf (token "8ee" SPINE-DATA 46))
              (leaf (token "8aJ" SPINE-DATA 47))
              (leaf (token "[4b" SPINE-DATA 48))
              (leaf (token "*" NULL-INTERPRETATION 49))
              (leaf (token "*" NULL-INTERPRETATION 50))
              (leaf (token "==" MEASURE 51))
              (leaf (token "*-" SPINE-TERMINATOR 52)))
        (list (leaf (token "**dynam" EXCLUSIVE-INTERPRETATION 0))
              (leaf (token "*staff1/2" STAFF-NUMBER 1))
              (leaf (token "*" NULL-INTERPRETATION 2))
              (leaf (token "*" NULL-INTERPRETATION 3))
              (leaf (token "*" NULL-INTERPRETATION 4))
              (leaf (token "*" NULL-INTERPRETATION 5))
              (leaf (token "*" NULL-INTERPRETATION 6))
              (leaf (token "=33" MEASURE 7))
              (leaf (token "*" NULL-INTERPRETATION 8))
              (leaf (token "." NULL-SPINE-DATA 9))
              (leaf (token "." NULL-SPINE-DATA 10))
              (leaf (token "<" SPINE-DATA 11))
              (leaf (token "(" SPINE-DATA 12))
              (leaf (token "(" SPINE-DATA 13))
              (leaf (token "[" SPINE-DATA 14))
              (leaf (token "=34" MEASURE 15))
              (leaf (token ">" SPINE-DATA 16))
              (leaf (token ")" SPINE-DATA 17))
              (leaf (token "]" SPINE-DATA 18))
              (leaf (token "<" SPINE-DATA 19))
              (leaf (token "(" SPINE-DATA 20))
              (leaf (token "[" SPINE-DATA 21))
              (leaf (token "=35" MEASURE 22))
              (leaf (token "*" NULL-INTERPRETATION 23))
              (leaf (token ">" SPINE-DATA 24))
              (leaf (token ")" SPINE-DATA 25))
              (leaf (token ")" SPINE-DATA 26))
              (leaf (token ")" SPINE-DATA 27))
              (leaf (token "]" SPINE-DATA 28))
              (leaf (token "=36" MEASURE 29))
              (leaf (token "." NULL-SPINE-DATA 30))
              (leaf (token "." NULL-SPINE-DATA 31))
              (leaf (token "." NULL-SPINE-DATA 32))
              (leaf (token "." NULL-SPINE-DATA 33))
              (leaf (token "." NULL-SPINE-DATA 34))
              (leaf (token "*" NULL-INTERPRETATION 35))
              (leaf (token "=37" MEASURE 36))
              (leaf (token "*" NULL-INTERPRETATION 37))
              (leaf (token "." NULL-SPINE-DATA 38))
              (leaf (token "." NULL-SPINE-DATA 39))
              (leaf (token "." NULL-SPINE-DATA 40))
              (leaf (token "." NULL-SPINE-DATA 41))
              (leaf (token "." NULL-SPINE-DATA 42))
              (leaf (token "=38" MEASURE 43))
              (leaf (token "." NULL-SPINE-DATA 44))
              (leaf (token "." NULL-SPINE-DATA 45))
              (leaf (token "." NULL-SPINE-DATA 46))
              (leaf (token "." NULL-SPINE-DATA 47))
              (leaf (token "." NULL-SPINE-DATA 48))
              (leaf (token "*" NULL-INTERPRETATION 49))
              (leaf (token "*" NULL-INTERPRETATION 50))
              (leaf (token "==" MEASURE 51))
              (leaf (token "*-" SPINE-TERMINATOR 52)))))))
(check-expect
  (hfile->ab-hgraph three-spines-two-splits-not-consecutive-2-hfile
                    ab-hgraph)
  (ab-hgraph
    (root
      (list
        (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
              (leaf (token "*staff2" STAFF-NUMBER 1))
              (leaf (token "*Ipiano" INSTRUMENT-CLASS 2))
              (leaf (token "*clefF4" CLEF 3))
              (leaf (token "*k[]" KEY-SIG 4))
              (leaf (token "*a:" KEY-LABEL 5))
              (leaf (token "*M3/4" TIME-SIG 6))
              (leaf (token "=33" MEASURE 7))
              (parent (token "*^" SPINE-SPLIT 8)
                      (list (leaf (token "4E" SPINE-DATA 9))
                            (leaf (token "." NULL-SPINE-DATA 10))
                            (leaf (token "4D" SPINE-DATA 11))
                            (leaf (token "." NULL-SPINE-DATA 12))
                            (leaf (token "[4C#X" SPINE-DATA 13))
                            (leaf (token "." NULL-SPINE-DATA 14))
                            (leaf (token "=34" MEASURE 15))
                            (leaf (token "2.C#] 2.B]" SPINE-DATA 16))
                            (leaf (token "." NULL-SPINE-DATA 17))
                            (leaf (token "." NULL-SPINE-DATA 18))
                            (leaf (token "." NULL-SPINE-DATA 19))
                            (leaf (token "." NULL-SPINE-DATA 20))
                            (leaf (token "." NULL-SPINE-DATA 21))
                            (leaf (token "=35" MEASURE 22))
                            (leaf (token "*" NULL-INTERPRETATION 23))
                            (leaf (token "4E" SPINE-DATA 24))
                            (leaf (token "4D" SPINE-DATA 25))
                            (leaf (token "." NULL-SPINE-DATA 26))
                            (leaf (token "[4C#X" SPINE-DATA 27))
                            (leaf (token "." NULL-SPINE-DATA 28))
                            (leaf (token "=36" MEASURE 29))
                            (leaf (token "2.C#] 2.B]" SPINE-DATA 30))
                            (leaf (token "." NULL-SPINE-DATA 31))
                            (leaf (token "." NULL-SPINE-DATA 32))
                            (leaf (token "." NULL-SPINE-DATA 33))
                            (leaf (token "." NULL-SPINE-DATA 34))
                            (leaf (token "*" NULL-INTERPRETATION 35))
                            (leaf (token "=37" MEASURE 36))
                            (leaf (token "*" NULL-INTERPRETATION 37))
                            (leaf (token "2.D\\" SPINE-DATA 38))
                            (leaf (token "." NULL-SPINE-DATA 39))
                            (leaf (token "." NULL-SPINE-DATA 40))
                            (leaf (token "." NULL-SPINE-DATA 41))
                            (leaf (token "." NULL-SPINE-DATA 42))
                            (leaf (token "=38" MEASURE 43))
                            (leaf (token "2.D\\" SPINE-DATA 44))
                            (leaf (token "." NULL-SPINE-DATA 45))
                            (leaf (token "." NULL-SPINE-DATA 46))
                            (leaf (token "." NULL-SPINE-DATA 47))
                            (leaf (token "." NULL-SPINE-DATA 48))
                            (leaf (token "*" NULL-INTERPRETATION 49))
                            (leaf (token "*v" SPINE-JOIN 50)))
                      (list (leaf (token "[2.B" SPINE-DATA 9))
                            (leaf (token "." NULL-SPINE-DATA 10))
                            (leaf (token "." NULL-SPINE-DATA 11))
                            (leaf (token "." NULL-SPINE-DATA 12))
                            (leaf (token "." NULL-SPINE-DATA 13))
                            (leaf (token "." NULL-SPINE-DATA 14))
                            (leaf (token "=34" MEASURE 15))
                            (leaf (token "4g" SPINE-DATA 16))
                            (leaf (token "." NULL-SPINE-DATA 17))
                            (leaf (token "4e" SPINE-DATA 18))
                            (leaf (token "." NULL-SPINE-DATA 19))
                            (leaf (token "4r" SPINE-DATA 20))
                            (leaf (token "." NULL-SPINE-DATA 21))
                            (leaf (token "=35" MEASURE 22))
                            (leaf (token "*" NULL-INTERPRETATION 23))
                            (leaf (token "4r" SPINE-DATA 24))
                            (leaf (token "8r" SPINE-DATA 25))
                            (leaf (token "8G" SPINE-DATA 26))
                            (leaf (token "8A#XL" SPINE-DATA 27))
                            (leaf (token "[8BJ" SPINE-DATA 28))
                            (leaf (token "=36" MEASURE 29))
                            (leaf (token "4.g" SPINE-DATA 30))
                            (leaf (token "." NULL-SPINE-DATA 31))
                            (leaf (token "8f#X" SPINE-DATA 32))
                            (leaf (token "8f#L" SPINE-DATA 33))
                            (leaf (token "8eJ" SPINE-DATA 34))
                            (leaf (token "*" NULL-INTERPRETATION 35))
                            (leaf (token "=37" MEASURE 36))
                            (parent (token "*^" SPINE-SPLIT 37)
                                    (list (leaf (token "2B" SPINE-DATA 38))
                                          (leaf (token "." NULL-SPINE-DATA 39))
                                          (leaf (token "." NULL-SPINE-DATA 40))
                                          (leaf (token "." NULL-SPINE-DATA 41))
                                          (leaf (token "4B-X" SPINE-DATA 42))
                                          (leaf (token "=38" MEASURE 43))
                                          (leaf (token "4A" SPINE-DATA 44))
                                          (leaf (token "." NULL-SPINE-DATA 45))
                                          (leaf (token "2c" SPINE-DATA 46))
                                          (leaf (token "." NULL-SPINE-DATA 47))
                                          (leaf (token "." NULL-SPINE-DATA 48))
                                          (leaf (token "*v" SPINE-JOIN 49)))
                                    (list (leaf (token "4d" SPINE-DATA 38))
                                          (leaf (token "." NULL-SPINE-DATA 39))
                                          (leaf (token "[2g" SPINE-DATA 40))
                                          (leaf (token "." NULL-SPINE-DATA 41))
                                          (leaf (token "." NULL-SPINE-DATA 42))
                                          (leaf (token "=38" MEASURE 43))
                                          (leaf (token "4g]" SPINE-DATA 44))
                                          (leaf (token "." NULL-SPINE-DATA 45))
                                          (leaf (token "4g" SPINE-DATA 46))
                                          (leaf (token "." NULL-SPINE-DATA 47))
                                          (leaf (token "4f#X" SPINE-DATA 48))
                                          (leaf (token "*v" SPINE-JOIN 49))))
                            (leaf (token "*v" SPINE-JOIN 50))))
              (leaf (token "==" MEASURE 51))
              (leaf (token "*-" SPINE-TERMINATOR 52)))
        (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
              (leaf (token "*staff1" STAFF-NUMBER 1))
              (leaf (token "*Ipiano" INSTRUMENT-CLASS 2))
              (leaf (token "*clefG2" CLEF 3))
              (leaf (token "*k[]" KEY-SIG 4))
              (leaf (token "*a:" KEY-LABEL 5))
              (leaf (token "*M3/4" TIME-SIG 6))
              (leaf (token "=33" MEASURE 7))
              (leaf (token "*" NULL-INTERPRETATION 8))
              (leaf (token "8r" SPINE-DATA 9))
              (leaf (token "8f#XL" SPINE-DATA 10))
              (leaf (token "8a" SPINE-DATA 11))
              (leaf (token "8g" SPINE-DATA 12))
              (leaf (token "8b" SPINE-DATA 13))
              (leaf (token "8eeJ" SPINE-DATA 14))
              (leaf (token "=34" MEASURE 15))
              (leaf (token "8ccc#XL" SPINE-DATA 16))
              (leaf (token "8bbJ" SPINE-DATA 17))
              (leaf (token "8r" SPINE-DATA 18))
              (leaf (token "8ff#X" SPINE-DATA 19))
              (leaf (token "8aaL" SPINE-DATA 20))
              (leaf (token "8ggJ" SPINE-DATA 21))
              (leaf (token "=35" MEASURE 22))
              (parent (token "*^" SPINE-SPLIT 23)
                      (list (leaf (token "2.g" SPINE-DATA 24))
                            (leaf (token "." NULL-SPINE-DATA 25))
                            (leaf (token "." NULL-SPINE-DATA 26))
                            (leaf (token "." NULL-SPINE-DATA 27))
                            (leaf (token "." NULL-SPINE-DATA 28))
                            (leaf (token "=36" MEASURE 29))
                            (leaf (token "2.b" SPINE-DATA 30))
                            (leaf (token "." NULL-SPINE-DATA 31))
                            (leaf (token "." NULL-SPINE-DATA 32))
                            (leaf (token "." NULL-SPINE-DATA 33))
                            (leaf (token "." NULL-SPINE-DATA 34))
                            (leaf (token "*v" SPINE-JOIN 35)))
                      (list (leaf (token "2ff#X" SPINE-DATA 24))
                            (leaf (token "." NULL-SPINE-DATA 25))
                            (leaf (token "." NULL-SPINE-DATA 26))
                            (leaf (token "4ee" SPINE-DATA 27))
                            (leaf (token "." NULL-SPINE-DATA 28))
                            (leaf (token "=36" MEASURE 29))
                            (leaf (token "4dd#X" SPINE-DATA 30))
                            (leaf (token "4ee" SPINE-DATA 31))
                            (leaf (token "." NULL-SPINE-DATA 32))
                            (leaf (token "4gg" SPINE-DATA 33))
                            (leaf (token "." NULL-SPINE-DATA 34))
                            (leaf (token "*v" SPINE-JOIN 35))))
              (leaf (token "=37" MEASURE 36))
              (leaf (token "*" NULL-INTERPRETATION 37))
              (leaf (token "8ff#XL" SPINE-DATA 38))
              (leaf (token "8aa" SPINE-DATA 39))
              (leaf (token "8gg" SPINE-DATA 40))
              (leaf (token "8ddJ" SPINE-DATA 41))
              (leaf (token "[4dd#X" SPINE-DATA 42))
              (leaf (token "=38" MEASURE 43))
              (leaf (token "8dd#L]" SPINE-DATA 44))
              (leaf (token "8ff#X" SPINE-DATA 45))
              (leaf (token "8ee" SPINE-DATA 46))
              (leaf (token "8aJ" SPINE-DATA 47))
              (leaf (token "[4b" SPINE-DATA 48))
              (leaf (token "*" NULL-INTERPRETATION 49))
              (leaf (token "*" NULL-INTERPRETATION 50))
              (leaf (token "==" MEASURE 51))
              (leaf (token "*-" SPINE-TERMINATOR 52)))
        (list (leaf (token "**dynam" EXCLUSIVE-INTERPRETATION 0))
              (leaf (token "*staff1/2" STAFF-NUMBER 1))
              (leaf (token "*" NULL-INTERPRETATION 2))
              (leaf (token "*" NULL-INTERPRETATION 3))
              (leaf (token "*" NULL-INTERPRETATION 4))
              (leaf (token "*" NULL-INTERPRETATION 5))
              (leaf (token "*" NULL-INTERPRETATION 6))
              (leaf (token "=33" MEASURE 7))
              (leaf (token "*" NULL-INTERPRETATION 8))
              (leaf (token "." NULL-SPINE-DATA 9))
              (leaf (token "." NULL-SPINE-DATA 10))
              (leaf (token "<" SPINE-DATA 11))
              (leaf (token "(" SPINE-DATA 12))
              (leaf (token "(" SPINE-DATA 13))
              (leaf (token "[" SPINE-DATA 14))
              (leaf (token "=34" MEASURE 15))
              (leaf (token ">" SPINE-DATA 16))
              (leaf (token ")" SPINE-DATA 17))
              (leaf (token "]" SPINE-DATA 18))
              (leaf (token "<" SPINE-DATA 19))
              (leaf (token "(" SPINE-DATA 20))
              (leaf (token "[" SPINE-DATA 21))
              (leaf (token "=35" MEASURE 22))
              (leaf (token "*" NULL-INTERPRETATION 23))
              (leaf (token ">" SPINE-DATA 24))
              (leaf (token ")" SPINE-DATA 25))
              (leaf (token ")" SPINE-DATA 26))
              (leaf (token ")" SPINE-DATA 27))
              (leaf (token "]" SPINE-DATA 28))
              (leaf (token "=36" MEASURE 29))
              (leaf (token "." NULL-SPINE-DATA 30))
              (leaf (token "." NULL-SPINE-DATA 31))
              (leaf (token "." NULL-SPINE-DATA 32))
              (leaf (token "." NULL-SPINE-DATA 33))
              (leaf (token "." NULL-SPINE-DATA 34))
              (leaf (token "*" NULL-INTERPRETATION 35))
              (leaf (token "=37" MEASURE 36))
              (leaf (token "*" NULL-INTERPRETATION 37))
              (leaf (token "." NULL-SPINE-DATA 38))
              (leaf (token "." NULL-SPINE-DATA 39))
              (leaf (token "." NULL-SPINE-DATA 40))
              (leaf (token "." NULL-SPINE-DATA 41))
              (leaf (token "." NULL-SPINE-DATA 42))
              (leaf (token "=38" MEASURE 43))
              (leaf (token "." NULL-SPINE-DATA 44))
              (leaf (token "." NULL-SPINE-DATA 45))
              (leaf (token "." NULL-SPINE-DATA 46))
              (leaf (token "." NULL-SPINE-DATA 47))
              (leaf (token "." NULL-SPINE-DATA 48))
              (leaf (token "*" NULL-INTERPRETATION 49))
              (leaf (token "*" NULL-INTERPRETATION 50))
              (leaf (token "==" MEASURE 51))
              (leaf (token "*-" SPINE-TERMINATOR 52)))))))
(check-expect
  (hfile->ab-hgraph four-cases-hfile ab-hgraph)
  (ab-hgraph
    (root
      (list
        (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
              (parent (token "*^" SPINE-SPLIT 1)
                      (list (leaf (token "*" NULL-INTERPRETATION 2))
                            (leaf (token "4a" SPINE-DATA 3))
                            (leaf (token "*" NULL-INTERPRETATION 4))
                            (leaf (token "*v" SPINE-JOIN 5)))
                      (list (parent (token "*^" SPINE-SPLIT 2)
                                    (list (leaf (token "4aa" SPINE-DATA 3))
                                          (leaf (token "*v" SPINE-JOIN 4)))
                                    (list (leaf (token "4aaa" SPINE-DATA 3))
                                          (leaf (token "*v" SPINE-JOIN 4))))
                            (leaf (token "*v" SPINE-JOIN 5))))
              (leaf (token "4a" SPINE-DATA 6))
              (parent (token "*^" SPINE-SPLIT 7)
                      (list (leaf (token "*" NULL-INTERPRETATION 8))
                            (leaf (token "4a" SPINE-DATA 9))
                            (leaf (token "*" NULL-INTERPRETATION 10))
                            (leaf (token "4a" SPINE-DATA 11))
                            (leaf (token "*v" SPINE-JOIN 12)))
                      (list (parent (token "*^" SPINE-SPLIT 8)
                                    (list (leaf (token "4aa" SPINE-DATA 9))
                                          (leaf (token "*v" SPINE-JOIN 10)))
                                    (list (leaf (token "4aaa" SPINE-DATA 9))
                                          (leaf (token "*v" SPINE-JOIN 10))))
                            (leaf (token "4aa" SPINE-DATA 11))
                            (leaf (token "*v" SPINE-JOIN 12))))
              (leaf (token "4a" SPINE-DATA 13))
              (parent (token "*^" SPINE-SPLIT 14)
                      (list (leaf (token "4a" SPINE-DATA 15))
                            (leaf (token "*" NULL-INTERPRETATION 16))
                            (leaf (token "4a" SPINE-DATA 17))
                            (leaf (token "*" NULL-INTERPRETATION 18))
                            (leaf (token "4a" SPINE-DATA 19))
                            (leaf (token "*v" SPINE-JOIN 20)))
                      (list (leaf (token "4aa" SPINE-DATA 15))
                            (parent (token "*^" SPINE-SPLIT 16)
                                    (list (leaf (token "4aa" SPINE-DATA 17))
                                          (leaf (token "*v" SPINE-JOIN 18)))
                                    (list (leaf (token "4aaa" SPINE-DATA 17))
                                          (leaf (token "*v" SPINE-JOIN 18))))
                            (leaf (token "4aa" SPINE-DATA 19))
                            (leaf (token "*v" SPINE-JOIN 20))))
              (leaf (token "4a" SPINE-DATA 21))
              (parent (token "*^" SPINE-SPLIT 22)
                      (list (leaf (token "4a" SPINE-DATA 23))
                            (leaf (token "*" NULL-INTERPRETATION 24))
                            (leaf (token "4a" SPINE-DATA 25))
                            (leaf (token "*" NULL-INTERPRETATION 26))
                            (leaf (token "*v" SPINE-JOIN 27)))
                      (list (leaf (token "4aa" SPINE-DATA 23))
                            (parent (token "*^" SPINE-SPLIT 24)
                                    (list (leaf (token "4aa" SPINE-DATA 25))
                                          (leaf (token "*v" SPINE-JOIN 26)))
                                    (list (leaf (token "4aaa" SPINE-DATA 25))
                                          (leaf (token "*v" SPINE-JOIN 26))))
                            (leaf (token "*v" SPINE-JOIN 27))))
              (leaf (token "4a" SPINE-DATA 28))
              (leaf (token "==" MEASURE 29))
              (leaf (token "*-" SPINE-TERMINATOR 30)))))))
(check-expect
  (hfile->ab-hgraph parent-scriabin-hfile
                    ab-hgraph)
  (ab-hgraph
    (root
      (list
        (list (leaf (token "**kern" EXCLUSIVE-INTERPRETATION 0))
              (parent (token "*^" SPINE-SPLIT 1)
                      (list (leaf (token "4E" SPINE-DATA 2))
                            (leaf (token "." NULL-SPINE-DATA 3))
                            (leaf (token "4D" SPINE-DATA 4))
                            (leaf (token "." NULL-SPINE-DATA 5))
                            (leaf (token "[4C#X" SPINE-DATA 6))
                            (leaf (token "." NULL-SPINE-DATA 7))
                            (leaf (token "=34" MEASURE 8))
                            (leaf (token "2.C#] 2.B]" SPINE-DATA 9))
                            (leaf (token "." NULL-SPINE-DATA 10))
                            (leaf (token "." NULL-SPINE-DATA 11))
                            (leaf (token "." NULL-SPINE-DATA 12))
                            (leaf (token "." NULL-SPINE-DATA 13))
                            (leaf (token "." NULL-SPINE-DATA 14))
                            (leaf (token "=35" MEASURE 15))
                            (leaf (token "*" NULL-INTERPRETATION 16))
                            (leaf (token "4E" SPINE-DATA 17))
                            (leaf (token "4D" SPINE-DATA 18))
                            (leaf (token "." NULL-SPINE-DATA 19))
                            (leaf (token "[4C#X" SPINE-DATA 20))
                            (leaf (token "." NULL-SPINE-DATA 21))
                            (leaf (token "=36" MEASURE 22))
                            (leaf (token "2.C#] 2.B]" SPINE-DATA 23))
                            (leaf (token "." NULL-SPINE-DATA 24))
                            (leaf (token "." NULL-SPINE-DATA 25))
                            (leaf (token "." NULL-SPINE-DATA 26))
                            (leaf (token "." NULL-SPINE-DATA 27))
                            (leaf (token "=37" MEASURE 28))
                            (parent (token "*^" SPINE-SPLIT 29)
                                    (list
                                      (leaf (token "2.D\\" SPINE-DATA 30))
                                      (leaf (token "." NULL-SPINE-DATA 31))
                                      (leaf (token "." NULL-SPINE-DATA 32))
                                      (leaf (token "." NULL-SPINE-DATA 33))
                                      (leaf (token "." NULL-SPINE-DATA 34))
                                      (leaf (token "=38" MEASURE 35))
                                      (leaf (token "2.D\\" SPINE-DATA 36))
                                      (leaf (token "." NULL-SPINE-DATA 37))
                                      (leaf (token "." NULL-SPINE-DATA 38))
                                      (leaf (token "." NULL-SPINE-DATA 39))
                                      (leaf (token "." NULL-SPINE-DATA 40))
                                      (leaf (token "*" NULL-INTERPRETATION 41))
                                      (leaf (token "*v" SPINE-JOIN 42)))
                                    (list
                                      (leaf (token "2B" SPINE-DATA 30))
                                      (leaf (token "." NULL-SPINE-DATA 31))
                                      (leaf (token "." NULL-SPINE-DATA 32))
                                      (leaf (token "." NULL-SPINE-DATA 33))
                                      (leaf (token "4B-X" SPINE-DATA 34))
                                      (leaf (token "=38" MEASURE 35))
                                      (leaf (token "4A" SPINE-DATA 36))
                                      (leaf (token "." NULL-SPINE-DATA 37))
                                      (leaf (token "2c" SPINE-DATA 38))
                                      (leaf (token "." NULL-SPINE-DATA 39))
                                      (leaf (token "." NULL-SPINE-DATA 40))
                                      (leaf (token "*v" SPINE-JOIN 41))))
                            (leaf (token "*v" SPINE-JOIN 42)))
                      (list (leaf (token "[2.B" SPINE-DATA 2))
                            (leaf (token "." NULL-SPINE-DATA 3))
                            (leaf (token "." NULL-SPINE-DATA 4))
                            (leaf (token "." NULL-SPINE-DATA 5))
                            (leaf (token "." NULL-SPINE-DATA 6))
                            (leaf (token "." NULL-SPINE-DATA 7))
                            (leaf (token "=34" MEASURE 8))
                            (leaf (token "4g" SPINE-DATA 9))
                            (leaf (token "." NULL-SPINE-DATA 10))
                            (leaf (token "4e" SPINE-DATA 11))
                            (leaf (token "." NULL-SPINE-DATA 12))
                            (leaf (token "4r" SPINE-DATA 13))
                            (leaf (token "." NULL-SPINE-DATA 14))
                            (leaf (token "=35" MEASURE 15))
                            (leaf (token "*" NULL-INTERPRETATION 16))
                            (leaf (token "4r" SPINE-DATA 17))
                            (leaf (token "8r" SPINE-DATA 18))
                            (leaf (token "8G" SPINE-DATA 19))
                            (leaf (token "8A#XL" SPINE-DATA 20))
                            (leaf (token "[8BJ" SPINE-DATA 21))
                            (leaf (token "=36" MEASURE 22))
                            (leaf (token "4.g" SPINE-DATA 23))
                            (leaf (token "." NULL-SPINE-DATA 24))
                            (leaf (token "8f#X" SPINE-DATA 25))
                            (leaf (token "8f#L" SPINE-DATA 26))
                            (leaf (token "8eJ" SPINE-DATA 27))
                            (leaf (token "=37" MEASURE 28))
                            (leaf (token "*" NULL-INTERPRETATION 29))
                            (leaf (token "4d" SPINE-DATA 30))
                            (leaf (token "." NULL-SPINE-DATA 31))
                            (leaf (token "[2g" SPINE-DATA 32))
                            (leaf (token "." NULL-SPINE-DATA 33))
                            (leaf (token "." NULL-SPINE-DATA 34))
                            (leaf (token "=38" MEASURE 35))
                            (leaf (token "4g]" SPINE-DATA 36))
                            (leaf (token "." NULL-SPINE-DATA 37))
                            (leaf (token "4g" SPINE-DATA 38))
                            (leaf (token "." NULL-SPINE-DATA 39))
                            (leaf (token "4f#X" SPINE-DATA 40))
                            (leaf (token "*v" SPINE-JOIN 41))))
              (leaf (token "==" MEASURE 43))
              (leaf (token "*-" SPINE-TERMINATOR 44)))))))

; get-token
(check-error (get-token empty 1))

; splits-to-left?
(check-error (splits-to-left? "*"
                              (list (token "*" NULL-INTERPRETATION 10)
                                    (token "*" NULL-INTERPRETATION 10)
                                    (token "*clefG2" CLEF 10))
                              4))

; trim-original
(check-error (trim-original empty
                            (list (leaf (token "*-" SPINE-TERMINATOR 50)))
                            (list (leaf (token "*-" SPINE-TERMINATOR 50)))))

(test)
